STM32F107xC HAL User Manual: PLL2
PLL2
RCC Exported Functions
Functions
__STATIC_INLINE void LL_RCC_PLL2_Enable (void)
Enable PLL2.
__STATIC_INLINE void LL_RCC_PLL2_Disable (void)
Disable PLL2.
__STATIC_INLINE uint32_t LL_RCC_PLL2_IsReady (void)
Check if PLL2 Ready.
__STATIC_INLINE void LL_RCC_PLL_ConfigDomain_PLL2 (uint32_t Divider, uint32_t Multiplicator)
Configure PLL2 used for PLL2 Domain.
__STATIC_INLINE uint32_t LL_RCC_PLL2_GetMultiplicator (void)
Get PLL2 Multiplication Factor.
Function Documentation
__STATIC_INLINE void LL_RCC_PLL2_Disable (void)
Disable PLL2.
Reference Manual to LL API cross reference:
CR PLL2ON LL_RCC_PLL2_Disable
Return values:
None
Definition at line 1714 of file stm32f1xx_ll_rcc.h.
__STATIC_INLINE void LL_RCC_PLL2_Enable (void)
Enable PLL2.
Reference Manual to LL API cross reference:
CR PLL2ON LL_RCC_PLL2_Enable
Return values:
None
Definition at line 1704 of file stm32f1xx_ll_rcc.h.
Referenced by UTILS_EnablePLLAndSwitchSystem().
__STATIC_INLINE uint32_t LL_RCC_PLL2_GetMultiplicator (void)
Get PLL2 Multiplication Factor.
Reference Manual to LL API cross reference:
CFGR2 PLL2MUL LL_RCC_PLL2_GetMultiplicator
Return values:
Returned value can be one of the following values:
LL_RCC_PLL2_MUL_8
LL_RCC_PLL2_MUL_9
LL_RCC_PLL2_MUL_10
LL_RCC_PLL2_MUL_11
LL_RCC_PLL2_MUL_12
LL_RCC_PLL2_MUL_13
LL_RCC_PLL2_MUL_14
LL_RCC_PLL2_MUL_16
LL_RCC_PLL2_MUL_20
Definition at line 1781 of file stm32f1xx_ll_rcc.h.
Referenced by RCC_PLL2_GetFreqClockFreq().
__STATIC_INLINE uint32_t LL_RCC_PLL2_IsReady (void)
Check if PLL2 Ready.
Reference Manual to LL API cross reference:
CR PLL2RDY LL_RCC_PLL2_IsReady
Return values:
State of bit (1 or 0).
Definition at line 1724 of file stm32f1xx_ll_rcc.h.
Referenced by UTILS_EnablePLLAndSwitchSystem(), and UTILS_PLL_IsBusy().
__STATIC_INLINE void LL_RCC_PLL_ConfigDomain_PLL2 (uint32_t Divider, uint32_t Multiplicator)
Configure PLL2 used for PLL2 Domain.
Reference Manual to LL API cross reference:
CFGR2 PREDIV2 LL_RCC_PLL_ConfigDomain_PLL2
CFGR2 PLL2MUL LL_RCC_PLL_ConfigDomain_PLL2
Parameters:
Divider This parameter can be one of the following values:
LL_RCC_HSE_PREDIV2_DIV_1
LL_RCC_HSE_PREDIV2_DIV_2
LL_RCC_HSE_PREDIV2_DIV_3
LL_RCC_HSE_PREDIV2_DIV_4
LL_RCC_HSE_PREDIV2_DIV_5
LL_RCC_HSE_PREDIV2_DIV_6
LL_RCC_HSE_PREDIV2_DIV_7
LL_RCC_HSE_PREDIV2_DIV_8
LL_RCC_HSE_PREDIV2_DIV_9
LL_RCC_HSE_PREDIV2_DIV_10
LL_RCC_HSE_PREDIV2_DIV_11
LL_RCC_HSE_PREDIV2_DIV_12
LL_RCC_HSE_PREDIV2_DIV_13
LL_RCC_HSE_PREDIV2_DIV_14
LL_RCC_HSE_PREDIV2_DIV_15
LL_RCC_HSE_PREDIV2_DIV_16
Multiplicator This parameter can be one of the following values:
LL_RCC_PLL2_MUL_8
LL_RCC_PLL2_MUL_9
LL_RCC_PLL2_MUL_10
LL_RCC_PLL2_MUL_11
LL_RCC_PLL2_MUL_12
LL_RCC_PLL2_MUL_13
LL_RCC_PLL2_MUL_14
LL_RCC_PLL2_MUL_16
LL_RCC_PLL2_MUL_20
Return values:
None
Definition at line 1762 of file stm32f1xx_ll_rcc.h.