STM32F107xC HAL User Manual: HSE
HSE
RCC Exported Functions
Functions
__STATIC_INLINE void LL_RCC_HSE_EnableCSS (void)
Enable the Clock Security System.
__STATIC_INLINE void LL_RCC_HSE_EnableBypass (void)
Enable HSE external oscillator (HSE Bypass)
__STATIC_INLINE void LL_RCC_HSE_DisableBypass (void)
Disable HSE external oscillator (HSE Bypass)
__STATIC_INLINE void LL_RCC_HSE_Enable (void)
Enable HSE crystal oscillator (HSE ON)
__STATIC_INLINE void LL_RCC_HSE_Disable (void)
Disable HSE crystal oscillator (HSE ON)
__STATIC_INLINE uint32_t LL_RCC_HSE_IsReady (void)
Check if HSE oscillator Ready.
__STATIC_INLINE uint32_t LL_RCC_HSE_GetPrediv2 (void)
Get PREDIV2 division factor.
Function Documentation
__STATIC_INLINE void LL_RCC_HSE_Disable (void)
Disable HSE crystal oscillator (HSE ON)
Reference Manual to LL API cross reference:
CR HSEON LL_RCC_HSE_Disable
Return values:
None
Definition at line 784 of file stm32f1xx_ll_rcc.h.
__STATIC_INLINE void LL_RCC_HSE_DisableBypass (void)
Disable HSE external oscillator (HSE Bypass)
Reference Manual to LL API cross reference:
CR HSEBYP LL_RCC_HSE_DisableBypass
Return values:
None
Definition at line 764 of file stm32f1xx_ll_rcc.h.
Referenced by LL_PLL_ConfigSystemClock_HSE().
__STATIC_INLINE void LL_RCC_HSE_Enable (void)
Enable HSE crystal oscillator (HSE ON)
Reference Manual to LL API cross reference:
CR HSEON LL_RCC_HSE_Enable
Return values:
None
Definition at line 774 of file stm32f1xx_ll_rcc.h.
Referenced by LL_PLL_ConfigSystemClock_HSE().
__STATIC_INLINE void LL_RCC_HSE_EnableBypass (void)
Enable HSE external oscillator (HSE Bypass)
Reference Manual to LL API cross reference:
CR HSEBYP LL_RCC_HSE_EnableBypass
Return values:
None
Definition at line 754 of file stm32f1xx_ll_rcc.h.
Referenced by LL_PLL_ConfigSystemClock_HSE().
__STATIC_INLINE void LL_RCC_HSE_EnableCSS (void)
Enable the Clock Security System.
Reference Manual to LL API cross reference:
CR CSSON LL_RCC_HSE_EnableCSS
Return values:
None
Definition at line 744 of file stm32f1xx_ll_rcc.h.
__STATIC_INLINE uint32_t LL_RCC_HSE_GetPrediv2 (void)
Get PREDIV2 division factor.
Reference Manual to LL API cross reference:
CFGR2 PREDIV2 LL_RCC_HSE_GetPrediv2
Return values:
Returned value can be one of the following values:
LL_RCC_HSE_PREDIV2_DIV_1
LL_RCC_HSE_PREDIV2_DIV_2
LL_RCC_HSE_PREDIV2_DIV_3
LL_RCC_HSE_PREDIV2_DIV_4
LL_RCC_HSE_PREDIV2_DIV_5
LL_RCC_HSE_PREDIV2_DIV_6
LL_RCC_HSE_PREDIV2_DIV_7
LL_RCC_HSE_PREDIV2_DIV_8
LL_RCC_HSE_PREDIV2_DIV_9
LL_RCC_HSE_PREDIV2_DIV_10
LL_RCC_HSE_PREDIV2_DIV_11
LL_RCC_HSE_PREDIV2_DIV_12
LL_RCC_HSE_PREDIV2_DIV_13
LL_RCC_HSE_PREDIV2_DIV_14
LL_RCC_HSE_PREDIV2_DIV_15
LL_RCC_HSE_PREDIV2_DIV_16
Definition at line 821 of file stm32f1xx_ll_rcc.h.
Referenced by RCC_PLL2_GetFreqClockFreq(), and RCC_PLLI2S_GetFreqDomain_I2S().
__STATIC_INLINE uint32_t LL_RCC_HSE_IsReady (void)
Check if HSE oscillator Ready.
Reference Manual to LL API cross reference:
CR HSERDY LL_RCC_HSE_IsReady
Return values:
State of bit (1 or 0).
Definition at line 794 of file stm32f1xx_ll_rcc.h.
Referenced by LL_PLL_ConfigSystemClock_HSE().