STM32F107xC HAL User Manual: Peripheral Clock Source
Peripheral Clock Source
RCC Exported Functions
Functions
__STATIC_INLINE void LL_RCC_SetI2SClockSource (uint32_t I2SxSource)
Configure I2Sx clock source.
__STATIC_INLINE void LL_RCC_SetUSBClockSource (uint32_t USBxSource)
Configure USB clock source.
__STATIC_INLINE void LL_RCC_SetADCClockSource (uint32_t ADCxSource)
Configure ADC clock source.
__STATIC_INLINE uint32_t LL_RCC_GetI2SClockSource (uint32_t I2Sx)
Get I2Sx clock source.
__STATIC_INLINE uint32_t LL_RCC_GetUSBClockSource (uint32_t USBx)
Get USBx clock source.
__STATIC_INLINE uint32_t LL_RCC_GetADCClockSource (uint32_t ADCx)
Get ADCx clock source.
Function Documentation
__STATIC_INLINE uint32_t LL_RCC_GetADCClockSource (uint32_t ADCx)
Get ADCx clock source.
Reference Manual to LL API cross reference:
CFGR ADCPRE LL_RCC_GetADCClockSource
Parameters:
ADCx This parameter can be one of the following values:
LL_RCC_ADC_CLKSOURCE
Return values:
Returned value can be one of the following values:
LL_RCC_ADC_CLKSRC_PCLK2_DIV_2
LL_RCC_ADC_CLKSRC_PCLK2_DIV_4
LL_RCC_ADC_CLKSRC_PCLK2_DIV_6
LL_RCC_ADC_CLKSRC_PCLK2_DIV_8
Definition at line 1280 of file stm32f1xx_ll_rcc.h.
Referenced by LL_RCC_GetADCClockFreq().
__STATIC_INLINE uint32_t LL_RCC_GetI2SClockSource (uint32_t I2Sx)
Get I2Sx clock source.
Reference Manual to LL API cross reference:
CFGR2 I2S2SRC LL_RCC_GetI2SClockSource
CFGR2 I2S3SRC LL_RCC_GetI2SClockSource
Parameters:
I2Sx This parameter can be one of the following values:
LL_RCC_I2S2_CLKSOURCE
LL_RCC_I2S3_CLKSOURCE
Return values:
Returned value can be one of the following values:
LL_RCC_I2S2_CLKSOURCE_SYSCLK
LL_RCC_I2S2_CLKSOURCE_PLLI2S_VCO
LL_RCC_I2S3_CLKSOURCE_SYSCLK
LL_RCC_I2S3_CLKSOURCE_PLLI2S_VCO
Definition at line 1242 of file stm32f1xx_ll_rcc.h.
Referenced by LL_RCC_GetI2SClockFreq().
__STATIC_INLINE uint32_t LL_RCC_GetUSBClockSource (uint32_t USBx)
Get USBx clock source.
Reference Manual to LL API cross reference:
CFGR OTGFSPRE LL_RCC_GetUSBClockSource
CFGR USBPRE LL_RCC_GetUSBClockSource
Parameters:
USBx This parameter can be one of the following values:
LL_RCC_USB_CLKSOURCE
Return values:
Returned value can be one of the following values:
LL_RCC_USB_CLKSOURCE_PLL (*)
LL_RCC_USB_CLKSOURCE_PLL_DIV_1_5 (*)
LL_RCC_USB_CLKSOURCE_PLL_DIV_2 (*)
LL_RCC_USB_CLKSOURCE_PLL_DIV_3 (*)
(*) value not defined in all devices
Definition at line 1263 of file stm32f1xx_ll_rcc.h.
Referenced by LL_RCC_GetUSBClockFreq().
__STATIC_INLINE void LL_RCC_SetADCClockSource (uint32_t ADCxSource)
Configure ADC clock source.
Reference Manual to LL API cross reference:
CFGR ADCPRE LL_RCC_SetADCClockSource
Parameters:
ADCxSource This parameter can be one of the following values:
LL_RCC_ADC_CLKSRC_PCLK2_DIV_2
LL_RCC_ADC_CLKSRC_PCLK2_DIV_4
LL_RCC_ADC_CLKSRC_PCLK2_DIV_6
LL_RCC_ADC_CLKSRC_PCLK2_DIV_8
Return values:
None
Definition at line 1223 of file stm32f1xx_ll_rcc.h.
__STATIC_INLINE void LL_RCC_SetI2SClockSource (uint32_t I2SxSource)
Configure I2Sx clock source.
Reference Manual to LL API cross reference:
CFGR2 I2S2SRC LL_RCC_SetI2SClockSource
CFGR2 I2S3SRC LL_RCC_SetI2SClockSource
Parameters:
I2SxSource This parameter can be one of the following values:
LL_RCC_I2S2_CLKSOURCE_SYSCLK
LL_RCC_I2S2_CLKSOURCE_PLLI2S_VCO
LL_RCC_I2S3_CLKSOURCE_SYSCLK
LL_RCC_I2S3_CLKSOURCE_PLLI2S_VCO
Return values:
None
Definition at line 1183 of file stm32f1xx_ll_rcc.h.
__STATIC_INLINE void LL_RCC_SetUSBClockSource (uint32_t USBxSource)
Configure USB clock source.
Reference Manual to LL API cross reference:
CFGR OTGFSPRE LL_RCC_SetUSBClockSource
CFGR USBPRE LL_RCC_SetUSBClockSource
Parameters:
USBxSource This parameter can be one of the following values:
LL_RCC_USB_CLKSOURCE_PLL (*)
LL_RCC_USB_CLKSOURCE_PLL_DIV_1_5 (*)
LL_RCC_USB_CLKSOURCE_PLL_DIV_2 (*)
LL_RCC_USB_CLKSOURCE_PLL_DIV_3 (*)
(*) value not defined in all devices
Return values:
None
Definition at line 1203 of file stm32f1xx_ll_rcc.h.