STM32F103xG HAL User Manual: System
System
RCC Exported Functions
Functions
__STATIC_INLINE void LL_RCC_SetSysClkSource (uint32_t Source)
Configure the system clock source.
__STATIC_INLINE uint32_t LL_RCC_GetSysClkSource (void)
Get the system clock source.
__STATIC_INLINE void LL_RCC_SetAHBPrescaler (uint32_t Prescaler)
Set AHB prescaler.
__STATIC_INLINE void LL_RCC_SetAPB1Prescaler (uint32_t Prescaler)
Set APB1 prescaler.
__STATIC_INLINE void LL_RCC_SetAPB2Prescaler (uint32_t Prescaler)
Set APB2 prescaler.
__STATIC_INLINE uint32_t LL_RCC_GetAHBPrescaler (void)
Get AHB prescaler.
__STATIC_INLINE uint32_t LL_RCC_GetAPB1Prescaler (void)
Get APB1 prescaler.
__STATIC_INLINE uint32_t LL_RCC_GetAPB2Prescaler (void)
Get APB2 prescaler.
Function Documentation
__STATIC_INLINE uint32_t LL_RCC_GetAHBPrescaler (void)
Get AHB prescaler.
Reference Manual to LL API cross reference:
CFGR HPRE LL_RCC_GetAHBPrescaler
Return values:
Returned value can be one of the following values:
LL_RCC_SYSCLK_DIV_1
LL_RCC_SYSCLK_DIV_2
LL_RCC_SYSCLK_DIV_4
LL_RCC_SYSCLK_DIV_8
LL_RCC_SYSCLK_DIV_16
LL_RCC_SYSCLK_DIV_64
LL_RCC_SYSCLK_DIV_128
LL_RCC_SYSCLK_DIV_256
LL_RCC_SYSCLK_DIV_512
Definition at line 1098 of file stm32f1xx_ll_rcc.h.
Referenced by RCC_GetHCLKClockFreq().
__STATIC_INLINE uint32_t LL_RCC_GetAPB1Prescaler (void)
Get APB1 prescaler.
Reference Manual to LL API cross reference:
CFGR PPRE1 LL_RCC_GetAPB1Prescaler
Return values:
Returned value can be one of the following values:
LL_RCC_APB1_DIV_1
LL_RCC_APB1_DIV_2
LL_RCC_APB1_DIV_4
LL_RCC_APB1_DIV_8
LL_RCC_APB1_DIV_16
Definition at line 1113 of file stm32f1xx_ll_rcc.h.
Referenced by RCC_GetPCLK1ClockFreq().
__STATIC_INLINE uint32_t LL_RCC_GetAPB2Prescaler (void)
Get APB2 prescaler.
Reference Manual to LL API cross reference:
CFGR PPRE2 LL_RCC_GetAPB2Prescaler
Return values:
Returned value can be one of the following values:
LL_RCC_APB2_DIV_1
LL_RCC_APB2_DIV_2
LL_RCC_APB2_DIV_4
LL_RCC_APB2_DIV_8
LL_RCC_APB2_DIV_16
Definition at line 1128 of file stm32f1xx_ll_rcc.h.
Referenced by RCC_GetPCLK2ClockFreq().
__STATIC_INLINE uint32_t LL_RCC_GetSysClkSource (void)
Get the system clock source.
Reference Manual to LL API cross reference:
CFGR SWS LL_RCC_GetSysClkSource
Return values:
Returned value can be one of the following values:
LL_RCC_SYS_CLKSOURCE_STATUS_HSI
LL_RCC_SYS_CLKSOURCE_STATUS_HSE
LL_RCC_SYS_CLKSOURCE_STATUS_PLL
Definition at line 1027 of file stm32f1xx_ll_rcc.h.
Referenced by LL_RCC_DeInit(), RCC_GetSystemClockFreq(), and UTILS_EnablePLLAndSwitchSystem().
__STATIC_INLINE void LL_RCC_SetAHBPrescaler (uint32_t Prescaler)
Set AHB prescaler.
Reference Manual to LL API cross reference:
CFGR HPRE LL_RCC_SetAHBPrescaler
Parameters:
Prescaler This parameter can be one of the following values:
LL_RCC_SYSCLK_DIV_1
LL_RCC_SYSCLK_DIV_2
LL_RCC_SYSCLK_DIV_4
LL_RCC_SYSCLK_DIV_8
LL_RCC_SYSCLK_DIV_16
LL_RCC_SYSCLK_DIV_64
LL_RCC_SYSCLK_DIV_128
LL_RCC_SYSCLK_DIV_256
LL_RCC_SYSCLK_DIV_512
Return values:
None
Definition at line 1047 of file stm32f1xx_ll_rcc.h.
Referenced by UTILS_EnablePLLAndSwitchSystem().
__STATIC_INLINE void LL_RCC_SetAPB1Prescaler (uint32_t Prescaler)
Set APB1 prescaler.
Reference Manual to LL API cross reference:
CFGR PPRE1 LL_RCC_SetAPB1Prescaler
Parameters:
Prescaler This parameter can be one of the following values:
LL_RCC_APB1_DIV_1
LL_RCC_APB1_DIV_2
LL_RCC_APB1_DIV_4
LL_RCC_APB1_DIV_8
LL_RCC_APB1_DIV_16
Return values:
None
Definition at line 1063 of file stm32f1xx_ll_rcc.h.
Referenced by UTILS_EnablePLLAndSwitchSystem().
__STATIC_INLINE void LL_RCC_SetAPB2Prescaler (uint32_t Prescaler)
Set APB2 prescaler.
Reference Manual to LL API cross reference:
CFGR PPRE2 LL_RCC_SetAPB2Prescaler
Parameters:
Prescaler This parameter can be one of the following values:
LL_RCC_APB2_DIV_1
LL_RCC_APB2_DIV_2
LL_RCC_APB2_DIV_4
LL_RCC_APB2_DIV_8
LL_RCC_APB2_DIV_16
Return values:
None
Definition at line 1079 of file stm32f1xx_ll_rcc.h.
Referenced by UTILS_EnablePLLAndSwitchSystem().
__STATIC_INLINE void LL_RCC_SetSysClkSource (uint32_t Source)
Configure the system clock source.
Reference Manual to LL API cross reference:
CFGR SW LL_RCC_SetSysClkSource
Parameters:
Source This parameter can be one of the following values:
LL_RCC_SYS_CLKSOURCE_HSI
LL_RCC_SYS_CLKSOURCE_HSE
LL_RCC_SYS_CLKSOURCE_PLL
Return values:
None
Definition at line 1014 of file stm32f1xx_ll_rcc.h.
Referenced by LL_RCC_DeInit(), and UTILS_EnablePLLAndSwitchSystem().