STM32F107xC HAL User Manual: Configuration functions
Configuration functions
USART Exported Functions
Functions
__STATIC_INLINE void LL_USART_Enable (USART_TypeDef *USARTx)
USART Enable.
__STATIC_INLINE void LL_USART_Disable (USART_TypeDef *USARTx)
USART Disable (all USART prescalers and outputs are disabled)
__STATIC_INLINE uint32_t LL_USART_IsEnabled (USART_TypeDef *USARTx)
Indicate if USART is enabled.
__STATIC_INLINE void LL_USART_EnableDirectionRx (USART_TypeDef *USARTx)
Receiver Enable (Receiver is enabled and begins searching for a start bit)
__STATIC_INLINE void LL_USART_DisableDirectionRx (USART_TypeDef *USARTx)
Receiver Disable.
__STATIC_INLINE void LL_USART_EnableDirectionTx (USART_TypeDef *USARTx)
Transmitter Enable.
__STATIC_INLINE void LL_USART_DisableDirectionTx (USART_TypeDef *USARTx)
Transmitter Disable.
__STATIC_INLINE void LL_USART_SetTransferDirection (USART_TypeDef *USARTx, uint32_t TransferDirection)
Configure simultaneously enabled/disabled states of Transmitter and Receiver.
__STATIC_INLINE uint32_t LL_USART_GetTransferDirection (USART_TypeDef *USARTx)
Return enabled/disabled states of Transmitter and Receiver.
__STATIC_INLINE void LL_USART_SetParity (USART_TypeDef *USARTx, uint32_t Parity)
Configure Parity (enabled/disabled and parity mode if enabled).
__STATIC_INLINE uint32_t LL_USART_GetParity (USART_TypeDef *USARTx)
Return Parity configuration (enabled/disabled and parity mode if enabled)
__STATIC_INLINE void LL_USART_SetWakeUpMethod (USART_TypeDef *USARTx, uint32_t Method)
Set Receiver Wake Up method from Mute mode.
__STATIC_INLINE uint32_t LL_USART_GetWakeUpMethod (USART_TypeDef *USARTx)
Return Receiver Wake Up method from Mute mode.
__STATIC_INLINE void LL_USART_SetDataWidth (USART_TypeDef *USARTx, uint32_t DataWidth)
Set Word length (i.e.
__STATIC_INLINE uint32_t LL_USART_GetDataWidth (USART_TypeDef *USARTx)
Return Word length (i.e.
__STATIC_INLINE void LL_USART_SetLastClkPulseOutput (USART_TypeDef *USARTx, uint32_t LastBitClockPulse)
Configure if Clock pulse of the last data bit is output to the SCLK pin or not.
__STATIC_INLINE uint32_t LL_USART_GetLastClkPulseOutput (USART_TypeDef *USARTx)
Retrieve Clock pulse of the last data bit output configuration (Last bit Clock pulse output to the SCLK pin or not)
__STATIC_INLINE void LL_USART_SetClockPhase (USART_TypeDef *USARTx, uint32_t ClockPhase)
Select the phase of the clock output on the SCLK pin in synchronous mode.
__STATIC_INLINE uint32_t LL_USART_GetClockPhase (USART_TypeDef *USARTx)
Return phase of the clock output on the SCLK pin in synchronous mode.
__STATIC_INLINE void LL_USART_SetClockPolarity (USART_TypeDef *USARTx, uint32_t ClockPolarity)
Select the polarity of the clock output on the SCLK pin in synchronous mode.
__STATIC_INLINE uint32_t LL_USART_GetClockPolarity (USART_TypeDef *USARTx)
Return polarity of the clock output on the SCLK pin in synchronous mode.
__STATIC_INLINE void LL_USART_ConfigClock (USART_TypeDef *USARTx, uint32_t Phase, uint32_t Polarity, uint32_t LBCPOutput)
Configure Clock signal format (Phase Polarity and choice about output of last bit clock pulse)
__STATIC_INLINE void LL_USART_EnableSCLKOutput (USART_TypeDef *USARTx)
Enable Clock output on SCLK pin.
__STATIC_INLINE void LL_USART_DisableSCLKOutput (USART_TypeDef *USARTx)
Disable Clock output on SCLK pin.
__STATIC_INLINE uint32_t LL_USART_IsEnabledSCLKOutput (USART_TypeDef *USARTx)
Indicate if Clock output on SCLK pin is enabled.
__STATIC_INLINE void LL_USART_SetStopBitsLength (USART_TypeDef *USARTx, uint32_t StopBits)
Set the length of the stop bits.
__STATIC_INLINE uint32_t LL_USART_GetStopBitsLength (USART_TypeDef *USARTx)
Retrieve the length of the stop bits.
__STATIC_INLINE void LL_USART_ConfigCharacter (USART_TypeDef *USARTx, uint32_t DataWidth, uint32_t Parity, uint32_t StopBits)
Configure Character frame format (Datawidth, Parity control, Stop Bits)
__STATIC_INLINE void LL_USART_SetNodeAddress (USART_TypeDef *USARTx, uint32_t NodeAddress)
Set Address of the USART node.
__STATIC_INLINE uint32_t LL_USART_GetNodeAddress (USART_TypeDef *USARTx)
Return 4 bit Address of the USART node as set in ADD field of CR2.
__STATIC_INLINE void LL_USART_EnableRTSHWFlowCtrl (USART_TypeDef *USARTx)
Enable RTS HW Flow Control.
__STATIC_INLINE void LL_USART_DisableRTSHWFlowCtrl (USART_TypeDef *USARTx)
Disable RTS HW Flow Control.
__STATIC_INLINE void LL_USART_EnableCTSHWFlowCtrl (USART_TypeDef *USARTx)
Enable CTS HW Flow Control.
__STATIC_INLINE void LL_USART_DisableCTSHWFlowCtrl (USART_TypeDef *USARTx)
Disable CTS HW Flow Control.
__STATIC_INLINE void LL_USART_SetHWFlowCtrl (USART_TypeDef *USARTx, uint32_t HardwareFlowControl)
Configure HW Flow Control mode (both CTS and RTS)
__STATIC_INLINE uint32_t LL_USART_GetHWFlowCtrl (USART_TypeDef *USARTx)
Return HW Flow Control configuration (both CTS and RTS)
__STATIC_INLINE void LL_USART_SetBaudRate (USART_TypeDef *USARTx, uint32_t PeriphClk, uint32_t BaudRate)
Configure USART BRR register for achieving expected Baud Rate value.
__STATIC_INLINE uint32_t LL_USART_GetBaudRate (USART_TypeDef *USARTx, uint32_t PeriphClk)
Return current Baud Rate value, according to USARTDIV present in BRR register (full BRR content), and to used Peripheral Clock and Oversampling mode values.
Function Documentation
__STATIC_INLINE void LL_USART_ConfigCharacter (USART_TypeDef * USARTx, uint32_t DataWidth, uint32_t Parity, uint32_t StopBits)
Configure Character frame format (Datawidth, Parity control, Stop Bits)
Note:
Call of this function is equivalent to following function call sequence :
Data Width configuration using LL_USART_SetDataWidth() function
Parity Control and mode configuration using LL_USART_SetParity() function
Stop bits configuration using LL_USART_SetStopBitsLength() function
Reference Manual to LL API cross reference:
CR1 PS LL_USART_ConfigCharacter
CR1 PCE LL_USART_ConfigCharacter
CR1 M LL_USART_ConfigCharacter
CR2 STOP LL_USART_ConfigCharacter
Parameters:
USARTx USART Instance
DataWidth This parameter can be one of the following values:
LL_USART_DATAWIDTH_8B
LL_USART_DATAWIDTH_9B
Parity This parameter can be one of the following values:
LL_USART_PARITY_NONE
LL_USART_PARITY_EVEN
LL_USART_PARITY_ODD
StopBits This parameter can be one of the following values:
LL_USART_STOPBITS_0_5
LL_USART_STOPBITS_1
LL_USART_STOPBITS_1_5
LL_USART_STOPBITS_2
Return values:
None
Definition at line 853 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE void LL_USART_ConfigClock (USART_TypeDef * USARTx, uint32_t Phase, uint32_t Polarity, uint32_t LBCPOutput)
Configure Clock signal format (Phase Polarity and choice about output of last bit clock pulse)
Note:
Macro IS_USART_INSTANCE(USARTx) can be used to check whether or not Synchronous mode is supported by the USARTx instance.
Call of this function is equivalent to following function call sequence :
Clock Phase configuration using LL_USART_SetClockPhase() function
Clock Polarity configuration using LL_USART_SetClockPolarity() function
Output of Last bit Clock pulse configuration using LL_USART_SetLastClkPulseOutput() function
Reference Manual to LL API cross reference:
CR2 CPHA LL_USART_ConfigClock
CR2 CPOL LL_USART_ConfigClock
CR2 LBCL LL_USART_ConfigClock
Parameters:
USARTx USART Instance
Phase This parameter can be one of the following values:
LL_USART_PHASE_1EDGE
LL_USART_PHASE_2EDGE
Polarity This parameter can be one of the following values:
LL_USART_POLARITY_LOW
LL_USART_POLARITY_HIGH
LBCPOutput This parameter can be one of the following values:
LL_USART_LASTCLKPULSE_NO_OUTPUT
LL_USART_LASTCLKPULSE_OUTPUT
Return values:
None
Definition at line 753 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE void LL_USART_Disable (USART_TypeDef * USARTx)
USART Disable (all USART prescalers and outputs are disabled)
Note:
When USART is disabled, USART prescalers and outputs are stopped immediately, and current operations are discarded. The configuration of the USART is kept, but all the status flags, in the USARTx_SR are set to their default values.
Reference Manual to LL API cross reference:
CR1 UE LL_USART_Disable
Parameters:
USARTx USART Instance
Return values:
None
Definition at line 425 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE void LL_USART_DisableCTSHWFlowCtrl (USART_TypeDef * USARTx)
Disable CTS HW Flow Control.
Note:
Macro IS_UART_HWFLOW_INSTANCE(USARTx) can be used to check whether or not Hardware Flow control feature is supported by the USARTx instance.
Reference Manual to LL API cross reference:
CR3 CTSE LL_USART_DisableCTSHWFlowCtrl
Parameters:
USARTx USART Instance
Return values:
None
Definition at line 933 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE void LL_USART_DisableDirectionRx (USART_TypeDef * USARTx)
Receiver Disable.
Reference Manual to LL API cross reference:
CR1 RE LL_USART_DisableDirectionRx
Parameters:
USARTx USART Instance
Return values:
None
Definition at line 458 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE void LL_USART_DisableDirectionTx (USART_TypeDef * USARTx)
Transmitter Disable.
Reference Manual to LL API cross reference:
CR1 TE LL_USART_DisableDirectionTx
Parameters:
USARTx USART Instance
Return values:
None
Definition at line 480 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE void LL_USART_DisableRTSHWFlowCtrl (USART_TypeDef * USARTx)
Disable RTS HW Flow Control.
Note:
Macro IS_UART_HWFLOW_INSTANCE(USARTx) can be used to check whether or not Hardware Flow control feature is supported by the USARTx instance.
Reference Manual to LL API cross reference:
CR3 RTSE LL_USART_DisableRTSHWFlowCtrl
Parameters:
USARTx USART Instance
Return values:
None
Definition at line 907 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE void LL_USART_DisableSCLKOutput (USART_TypeDef * USARTx)
Disable Clock output on SCLK pin.
Note:
Macro IS_USART_INSTANCE(USARTx) can be used to check whether or not Synchronous mode is supported by the USARTx instance.
Reference Manual to LL API cross reference:
CR2 CLKEN LL_USART_DisableSCLKOutput
Parameters:
USARTx USART Instance
Return values:
None
Definition at line 779 of file stm32f1xx_ll_usart.h.
Referenced by LL_USART_ClockInit().
__STATIC_INLINE void LL_USART_Enable (USART_TypeDef * USARTx)
USART Enable.
Reference Manual to LL API cross reference:
CR1 UE LL_USART_Enable
Parameters:
USARTx USART Instance
Return values:
None
Definition at line 411 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE void LL_USART_EnableCTSHWFlowCtrl (USART_TypeDef * USARTx)
Enable CTS HW Flow Control.
Note:
Macro IS_UART_HWFLOW_INSTANCE(USARTx) can be used to check whether or not Hardware Flow control feature is supported by the USARTx instance.
Reference Manual to LL API cross reference:
CR3 CTSE LL_USART_EnableCTSHWFlowCtrl
Parameters:
USARTx USART Instance
Return values:
None
Definition at line 920 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE void LL_USART_EnableDirectionRx (USART_TypeDef * USARTx)
Receiver Enable (Receiver is enabled and begins searching for a start bit)
Reference Manual to LL API cross reference:
CR1 RE LL_USART_EnableDirectionRx
Parameters:
USARTx USART Instance
Return values:
None
Definition at line 447 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE void LL_USART_EnableDirectionTx (USART_TypeDef * USARTx)
Transmitter Enable.
Reference Manual to LL API cross reference:
CR1 TE LL_USART_EnableDirectionTx
Parameters:
USARTx USART Instance
Return values:
None
Definition at line 469 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE void LL_USART_EnableRTSHWFlowCtrl (USART_TypeDef * USARTx)
Enable RTS HW Flow Control.
Note:
Macro IS_UART_HWFLOW_INSTANCE(USARTx) can be used to check whether or not Hardware Flow control feature is supported by the USARTx instance.
Reference Manual to LL API cross reference:
CR3 RTSE LL_USART_EnableRTSHWFlowCtrl
Parameters:
USARTx USART Instance
Return values:
None
Definition at line 894 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE void LL_USART_EnableSCLKOutput (USART_TypeDef * USARTx)
Enable Clock output on SCLK pin.
Note:
Macro IS_USART_INSTANCE(USARTx) can be used to check whether or not Synchronous mode is supported by the USARTx instance.
Reference Manual to LL API cross reference:
CR2 CLKEN LL_USART_EnableSCLKOutput
Parameters:
USARTx USART Instance
Return values:
None
Definition at line 766 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE uint32_t LL_USART_GetBaudRate (USART_TypeDef * USARTx, uint32_t PeriphClk)
Return current Baud Rate value, according to USARTDIV present in BRR register (full BRR content), and to used Peripheral Clock and Oversampling mode values.
Note:
In case of non-initialized or invalid value stored in BRR register, value 0 will be returned.
Reference Manual to LL API cross reference:
BRR BRR LL_USART_GetBaudRate
Parameters:
USARTx USART Instance
PeriphClk Peripheral Clock
Return values:
Baud Rate
Definition at line 1102 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE uint32_t LL_USART_GetClockPhase (USART_TypeDef * USARTx)
Return phase of the clock output on the SCLK pin in synchronous mode.
Note:
Macro IS_USART_INSTANCE(USARTx) can be used to check whether or not Synchronous mode is supported by the USARTx instance.
Reference Manual to LL API cross reference:
CR2 CPHA LL_USART_GetClockPhase
Parameters:
USARTx USART Instance
Return values:
Returned value can be one of the following values:
LL_USART_PHASE_1EDGE
LL_USART_PHASE_2EDGE
Definition at line 694 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE uint32_t LL_USART_GetClockPolarity (USART_TypeDef * USARTx)
Return polarity of the clock output on the SCLK pin in synchronous mode.
Note:
Macro IS_USART_INSTANCE(USARTx) can be used to check whether or not Synchronous mode is supported by the USARTx instance.
Reference Manual to LL API cross reference:
CR2 CPOL LL_USART_GetClockPolarity
Parameters:
USARTx USART Instance
Return values:
Returned value can be one of the following values:
LL_USART_POLARITY_LOW
LL_USART_POLARITY_HIGH
Definition at line 725 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE uint32_t LL_USART_GetDataWidth (USART_TypeDef * USARTx)
Return Word length (i.e.
nb of data bits, excluding start and stop bits)
Reference Manual to LL API cross reference:
CR1 M LL_USART_GetDataWidth
Parameters:
USARTx USART Instance
Return values:
Returned value can be one of the following values:
LL_USART_DATAWIDTH_8B
LL_USART_DATAWIDTH_9B
Definition at line 602 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE uint32_t LL_USART_GetHWFlowCtrl (USART_TypeDef * USARTx)
Return HW Flow Control configuration (both CTS and RTS)
Note:
Macro IS_UART_HWFLOW_INSTANCE(USARTx) can be used to check whether or not Hardware Flow control feature is supported by the USARTx instance.
Reference Manual to LL API cross reference:
CR3 RTSE LL_USART_GetHWFlowCtrl
CR3 CTSE LL_USART_GetHWFlowCtrl
Parameters:
USARTx USART Instance
Return values:
Returned value can be one of the following values:
LL_USART_HWCONTROL_NONE
LL_USART_HWCONTROL_RTS
LL_USART_HWCONTROL_CTS
LL_USART_HWCONTROL_RTS_CTS
Definition at line 970 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE uint32_t LL_USART_GetLastClkPulseOutput (USART_TypeDef * USARTx)
Retrieve Clock pulse of the last data bit output configuration (Last bit Clock pulse output to the SCLK pin or not)
Note:
Macro IS_USART_INSTANCE(USARTx) can be used to check whether or not Synchronous mode is supported by the USARTx instance.
Reference Manual to LL API cross reference:
CR2 LBCL LL_USART_GetLastClkPulseOutput
Parameters:
USARTx USART Instance
Return values:
Returned value can be one of the following values:
LL_USART_LASTCLKPULSE_NO_OUTPUT
LL_USART_LASTCLKPULSE_OUTPUT
Definition at line 663 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE uint32_t LL_USART_GetNodeAddress (USART_TypeDef * USARTx)
Return 4 bit Address of the USART node as set in ADD field of CR2.
Note:
only 4bits (b3-b0) of returned value are relevant (b31-b4 are not relevant)
Reference Manual to LL API cross reference:
CR2 ADD LL_USART_GetNodeAddress
Parameters:
USARTx USART Instance
Return values:
Address of the USART node (Value between Min_Data=0 and Max_Data=255)
Definition at line 881 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE uint32_t LL_USART_GetParity (USART_TypeDef * USARTx)
Return Parity configuration (enabled/disabled and parity mode if enabled)
Reference Manual to LL API cross reference:
CR1 PS LL_USART_GetParity
CR1 PCE LL_USART_GetParity
Parameters:
USARTx USART Instance
Return values:
Returned value can be one of the following values:
LL_USART_PARITY_NONE
LL_USART_PARITY_EVEN
LL_USART_PARITY_ODD
Definition at line 548 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE uint32_t LL_USART_GetStopBitsLength (USART_TypeDef * USARTx)
Retrieve the length of the stop bits.
Reference Manual to LL API cross reference:
CR2 STOP LL_USART_GetStopBitsLength
Parameters:
USARTx USART Instance
Return values:
Returned value can be one of the following values:
LL_USART_STOPBITS_0_5
LL_USART_STOPBITS_1
LL_USART_STOPBITS_1_5
LL_USART_STOPBITS_2
Definition at line 823 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE uint32_t LL_USART_GetTransferDirection (USART_TypeDef * USARTx)
Return enabled/disabled states of Transmitter and Receiver.
Reference Manual to LL API cross reference:
CR1 RE LL_USART_GetTransferDirection
CR1 TE LL_USART_GetTransferDirection
Parameters:
USARTx USART Instance
Return values:
Returned value can be one of the following values:
LL_USART_DIRECTION_NONE
LL_USART_DIRECTION_RX
LL_USART_DIRECTION_TX
LL_USART_DIRECTION_TX_RX
Definition at line 514 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE uint32_t LL_USART_GetWakeUpMethod (USART_TypeDef * USARTx)
Return Receiver Wake Up method from Mute mode.
Reference Manual to LL API cross reference:
CR1 WAKE LL_USART_GetWakeUpMethod
Parameters:
USARTx USART Instance
Return values:
Returned value can be one of the following values:
LL_USART_WAKEUP_IDLELINE
LL_USART_WAKEUP_ADDRESSMARK
Definition at line 575 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE uint32_t LL_USART_IsEnabled (USART_TypeDef * USARTx)
Indicate if USART is enabled.
Reference Manual to LL API cross reference:
CR1 UE LL_USART_IsEnabled
Parameters:
USARTx USART Instance
Return values:
State of bit (1 or 0).
Definition at line 436 of file stm32f1xx_ll_usart.h.
Referenced by LL_USART_ClockInit(), and LL_USART_Init().
__STATIC_INLINE uint32_t LL_USART_IsEnabledSCLKOutput (USART_TypeDef * USARTx)
Indicate if Clock output on SCLK pin is enabled.
Note:
Macro IS_USART_INSTANCE(USARTx) can be used to check whether or not Synchronous mode is supported by the USARTx instance.
Reference Manual to LL API cross reference:
CR2 CLKEN LL_USART_IsEnabledSCLKOutput
Parameters:
USARTx USART Instance
Return values:
State of bit (1 or 0).
Definition at line 792 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE void LL_USART_SetBaudRate (USART_TypeDef * USARTx, uint32_t PeriphClk, uint32_t BaudRate)
Configure USART BRR register for achieving expected Baud Rate value.
Note:
Compute and set USARTDIV value in BRR Register (full BRR content) according to used Peripheral Clock, Oversampling mode, and expected Baud Rate values
Peripheral clock and Baud rate values provided as function parameters should be valid (Baud rate value != 0)
Reference Manual to LL API cross reference:
BRR BRR LL_USART_SetBaudRate
Parameters:
USARTx USART Instance
PeriphClk Peripheral Clock
BaudRate Baud Rate
Return values:
None
Definition at line 1088 of file stm32f1xx_ll_usart.h.
References __LL_USART_DIV_SAMPLING16.
Referenced by LL_USART_Init().
__STATIC_INLINE void LL_USART_SetClockPhase (USART_TypeDef * USARTx, uint32_t ClockPhase)
Select the phase of the clock output on the SCLK pin in synchronous mode.
Note:
Macro IS_USART_INSTANCE(USARTx) can be used to check whether or not Synchronous mode is supported by the USARTx instance.
Reference Manual to LL API cross reference:
CR2 CPHA LL_USART_SetClockPhase
Parameters:
USARTx USART Instance
ClockPhase This parameter can be one of the following values:
LL_USART_PHASE_1EDGE
LL_USART_PHASE_2EDGE
Return values:
None
Definition at line 679 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE void LL_USART_SetClockPolarity (USART_TypeDef * USARTx, uint32_t ClockPolarity)
Select the polarity of the clock output on the SCLK pin in synchronous mode.
Note:
Macro IS_USART_INSTANCE(USARTx) can be used to check whether or not Synchronous mode is supported by the USARTx instance.
Reference Manual to LL API cross reference:
CR2 CPOL LL_USART_SetClockPolarity
Parameters:
USARTx USART Instance
ClockPolarity This parameter can be one of the following values:
LL_USART_POLARITY_LOW
LL_USART_POLARITY_HIGH
Return values:
None
Definition at line 710 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE void LL_USART_SetDataWidth (USART_TypeDef * USARTx, uint32_t DataWidth)
Set Word length (i.e.
nb of data bits, excluding start and stop bits)
Reference Manual to LL API cross reference:
CR1 M LL_USART_SetDataWidth
Parameters:
USARTx USART Instance
DataWidth This parameter can be one of the following values:
LL_USART_DATAWIDTH_8B
LL_USART_DATAWIDTH_9B
Return values:
None
Definition at line 589 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE void LL_USART_SetHWFlowCtrl (USART_TypeDef * USARTx, uint32_t HardwareFlowControl)
Configure HW Flow Control mode (both CTS and RTS)
Note:
Macro IS_UART_HWFLOW_INSTANCE(USARTx) can be used to check whether or not Hardware Flow control feature is supported by the USARTx instance.
Reference Manual to LL API cross reference:
CR3 RTSE LL_USART_SetHWFlowCtrl
CR3 CTSE LL_USART_SetHWFlowCtrl
Parameters:
USARTx USART Instance
HardwareFlowControl This parameter can be one of the following values:
LL_USART_HWCONTROL_NONE
LL_USART_HWCONTROL_RTS
LL_USART_HWCONTROL_CTS
LL_USART_HWCONTROL_RTS_CTS
Return values:
None
Definition at line 952 of file stm32f1xx_ll_usart.h.
Referenced by LL_USART_Init().
__STATIC_INLINE void LL_USART_SetLastClkPulseOutput (USART_TypeDef * USARTx, uint32_t LastBitClockPulse)
Configure if Clock pulse of the last data bit is output to the SCLK pin or not.
Note:
Macro IS_USART_INSTANCE(USARTx) can be used to check whether or not Synchronous mode is supported by the USARTx instance.
Reference Manual to LL API cross reference:
CR2 LBCL LL_USART_SetLastClkPulseOutput
Parameters:
USARTx USART Instance
LastBitClockPulse This parameter can be one of the following values:
LL_USART_LASTCLKPULSE_NO_OUTPUT
LL_USART_LASTCLKPULSE_OUTPUT
Return values:
None
Definition at line 647 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE void LL_USART_SetNodeAddress (USART_TypeDef * USARTx, uint32_t NodeAddress)
Set Address of the USART node.
Note:
This is used in multiprocessor communication during Mute mode or Stop mode, for wake up with address mark detection.
Reference Manual to LL API cross reference:
CR2 ADD LL_USART_SetNodeAddress
Parameters:
USARTx USART Instance
NodeAddress 4 bit Address of the USART node.
Return values:
None
Definition at line 869 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE void LL_USART_SetParity (USART_TypeDef * USARTx, uint32_t Parity)
Configure Parity (enabled/disabled and parity mode if enabled).
Note:
This function selects if hardware parity control (generation and detection) is enabled or disabled. When the parity control is enabled (Odd or Even), computed parity bit is inserted at the MSB position (9th or 8th bit depending on data width) and parity is checked on the received data.
Reference Manual to LL API cross reference:
CR1 PS LL_USART_SetParity
CR1 PCE LL_USART_SetParity
Parameters:
USARTx USART Instance
Parity This parameter can be one of the following values:
LL_USART_PARITY_NONE
LL_USART_PARITY_EVEN
LL_USART_PARITY_ODD
Return values:
None
Definition at line 533 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE void LL_USART_SetStopBitsLength (USART_TypeDef * USARTx, uint32_t StopBits)
Set the length of the stop bits.
Reference Manual to LL API cross reference:
CR2 STOP LL_USART_SetStopBitsLength
Parameters:
USARTx USART Instance
StopBits This parameter can be one of the following values:
LL_USART_STOPBITS_0_5
LL_USART_STOPBITS_1
LL_USART_STOPBITS_1_5
LL_USART_STOPBITS_2
Return values:
None
Definition at line 808 of file stm32f1xx_ll_usart.h.
Referenced by LL_USART_Init().
__STATIC_INLINE void LL_USART_SetTransferDirection (USART_TypeDef * USARTx, uint32_t TransferDirection)
Configure simultaneously enabled/disabled states of Transmitter and Receiver.
Reference Manual to LL API cross reference:
CR1 RE LL_USART_SetTransferDirection
CR1 TE LL_USART_SetTransferDirection
Parameters:
USARTx USART Instance
TransferDirection This parameter can be one of the following values:
LL_USART_DIRECTION_NONE
LL_USART_DIRECTION_RX
LL_USART_DIRECTION_TX
LL_USART_DIRECTION_TX_RX
Return values:
None
Definition at line 498 of file stm32f1xx_ll_usart.h.
__STATIC_INLINE void LL_USART_SetWakeUpMethod (USART_TypeDef * USARTx, uint32_t Method)
Set Receiver Wake Up method from Mute mode.
Reference Manual to LL API cross reference:
CR1 WAKE LL_USART_SetWakeUpMethod
Parameters:
USARTx USART Instance
Method This parameter can be one of the following values:
LL_USART_WAKEUP_IDLELINE
LL_USART_WAKEUP_ADDRESSMARK
Return values:
None
Definition at line 562 of file stm32f1xx_ll_usart.h.