STM32F107xC HAL User Manual: Initialization and de-initialization functions
Initialization and de-initialization functions
PCD Exported Functions
Initialization and Configuration functions.
Functions
HAL_StatusTypeDef HAL_PCD_Init (PCD_HandleTypeDef *hpcd)
Initializes the PCD according to the specified parameters in the PCD_InitTypeDef and initialize the associated handle.
HAL_StatusTypeDef HAL_PCD_DeInit (PCD_HandleTypeDef *hpcd)
DeInitializes the PCD peripheral.
__weak void HAL_PCD_MspInit (PCD_HandleTypeDef *hpcd)
Initializes the PCD MSP.
__weak void HAL_PCD_MspDeInit (PCD_HandleTypeDef *hpcd)
DeInitializes PCD MSP.
Detailed Description
Initialization and Configuration functions.
 ===============================================================================
            ##### Initialization and de-initialization functions #####
 ===============================================================================
    [..]  This section provides functions allowing to:
Function Documentation
HAL_StatusTypeDef HAL_PCD_DeInit (PCD_HandleTypeDef * hpcd)
DeInitializes the PCD peripheral.
Parameters:
hpcd PCD handle
Return values:
HAL status
Definition at line 244 of file stm32f1xx_hal_pcd.c.
References HAL_PCD_MspDeInit(), HAL_PCD_STATE_BUSY, HAL_PCD_STATE_RESET, HAL_PCD_Stop(), and PCD_HandleTypeDef::State.
HAL_StatusTypeDef HAL_PCD_Init (PCD_HandleTypeDef * hpcd)
Initializes the PCD according to the specified parameters in the PCD_InitTypeDef and initialize the associated handle.
Parameters:
hpcd PCD handle
Return values:
HAL status
Definition at line 126 of file stm32f1xx_hal_pcd.c.
References __HAL_PCD_DISABLE, assert_param, HAL_PCD_ConnectCallback(), HAL_PCD_DataInStageCallback(), HAL_PCD_DataOutStageCallback(), HAL_PCD_DisconnectCallback(), HAL_PCD_ISOINIncompleteCallback(), HAL_PCD_ISOOUTIncompleteCallback(), HAL_PCD_MspInit(), HAL_PCD_ResetCallback(), HAL_PCD_ResumeCallback(), HAL_PCD_SetupStageCallback(), HAL_PCD_SOFCallback(), HAL_PCD_STATE_BUSY, HAL_PCD_STATE_ERROR, HAL_PCD_STATE_READY, HAL_PCD_STATE_RESET, HAL_PCD_SuspendCallback(), PCD_HandleTypeDef::IN_ep, PCD_HandleTypeDef::Init, PCD_HandleTypeDef::Instance, PCD_HandleTypeDef::Lock, PCD_HandleTypeDef::OUT_ep, PCD_HandleTypeDef::State, and PCD_HandleTypeDef::USB_Address.
void HAL_PCD_MspDeInit (PCD_HandleTypeDef * hpcd)
DeInitializes PCD MSP.
Parameters:
hpcd PCD handle
Return values:
None
Definition at line 295 of file stm32f1xx_hal_pcd.c.
Referenced by HAL_PCD_DeInit().
void HAL_PCD_MspInit (PCD_HandleTypeDef * hpcd)
Initializes the PCD MSP.
Parameters:
hpcd PCD handle
Return values:
None
Definition at line 280 of file stm32f1xx_hal_pcd.c.
Referenced by HAL_PCD_Init().