STM32F107xC HAL User Manual: ETH Private Functions
ETH Private Functions
ETH
Functions
static void ETH_MACDMAConfig (ETH_HandleTypeDef *heth, uint32_t err)
Configures Ethernet MAC and DMA with default parameters.
static void ETH_MACAddressConfig (ETH_HandleTypeDef *heth, uint32_t MacAddr, uint8_t *Addr)
Configures the selected MAC address.
static void ETH_MACReceptionEnable (ETH_HandleTypeDef *heth)
Enables the MAC reception.
static void ETH_MACReceptionDisable (ETH_HandleTypeDef *heth)
Disables the MAC reception.
static void ETH_MACTransmissionEnable (ETH_HandleTypeDef *heth)
Enables the MAC transmission.
static void ETH_MACTransmissionDisable (ETH_HandleTypeDef *heth)
Disables the MAC transmission.
static void ETH_DMATransmissionEnable (ETH_HandleTypeDef *heth)
Enables the DMA transmission.
static void ETH_DMATransmissionDisable (ETH_HandleTypeDef *heth)
Disables the DMA transmission.
static void ETH_DMAReceptionEnable (ETH_HandleTypeDef *heth)
Enables the DMA reception.
static void ETH_DMAReceptionDisable (ETH_HandleTypeDef *heth)
Disables the DMA reception.
static void ETH_FlushTransmitFIFO (ETH_HandleTypeDef *heth)
Clears the ETHERNET transmit FIFO.
static void ETH_Delay (uint32_t mdelay)
This function provides delay (in milliseconds) based on CPU cycles method.
Function Documentation
static void ETH_Delay (uint32_t mdelay) [static]
This function provides delay (in milliseconds) based on CPU cycles method.
Parameters:
mdelay,: specifies the delay time length, in milliseconds.
Return values:
None
Definition at line 2257 of file stm32f1xx_hal_eth.c.
Referenced by ETH_FlushTransmitFIFO(), ETH_MACReceptionDisable(), ETH_MACReceptionEnable(), ETH_MACTransmissionDisable(), and ETH_MACTransmissionEnable().
static void ETH_DMAReceptionDisable (ETH_HandleTypeDef * heth) [static]
Disables the DMA reception.
Parameters:
heth,: pointer to a ETH_HandleTypeDef structure that contains the configuration information for ETHERNET module
Return values:
None
Definition at line 2226 of file stm32f1xx_hal_eth.c.
References ETH_HandleTypeDef::Instance.
Referenced by HAL_ETH_Stop().
static void ETH_DMAReceptionEnable (ETH_HandleTypeDef * heth) [static]
Enables the DMA reception.
Parameters:
heth,: pointer to a ETH_HandleTypeDef structure that contains the configuration information for ETHERNET module
Return values:
None
Definition at line 2214 of file stm32f1xx_hal_eth.c.
References ETH_HandleTypeDef::Instance.
Referenced by HAL_ETH_Start().
static void ETH_DMATransmissionDisable (ETH_HandleTypeDef * heth) [static]
Disables the DMA transmission.
Parameters:
heth,: pointer to a ETH_HandleTypeDef structure that contains the configuration information for ETHERNET module
Return values:
None
Definition at line 2202 of file stm32f1xx_hal_eth.c.
References ETH_HandleTypeDef::Instance.
Referenced by HAL_ETH_Stop().
static void ETH_DMATransmissionEnable (ETH_HandleTypeDef * heth) [static]
Enables the DMA transmission.
Parameters:
heth,: pointer to a ETH_HandleTypeDef structure that contains the configuration information for ETHERNET module
Return values:
None
Definition at line 2190 of file stm32f1xx_hal_eth.c.
References ETH_HandleTypeDef::Instance.
Referenced by HAL_ETH_Start().
static void ETH_FlushTransmitFIFO (ETH_HandleTypeDef * heth) [static]
Clears the ETHERNET transmit FIFO.
Parameters:
heth,: pointer to a ETH_HandleTypeDef structure that contains the configuration information for ETHERNET module
Return values:
None
Definition at line 2238 of file stm32f1xx_hal_eth.c.
References ETH_Delay(), ETH_REG_WRITE_DELAY, and ETH_HandleTypeDef::Instance.
Referenced by HAL_ETH_Start(), and HAL_ETH_Stop().
static void ETH_MACAddressConfig (ETH_HandleTypeDef * heth, uint32_t MacAddr, uint8_t * Addr) [static]
Configures the selected MAC address.
Parameters:
heth,: pointer to a ETH_HandleTypeDef structure that contains the configuration information for ETHERNET module
MacAddr,: The MAC address to configure This parameter can be one of the following values:
ETH_MAC_Address0: MAC Address0
ETH_MAC_Address1: MAC Address1
ETH_MAC_Address2: MAC Address2
ETH_MAC_Address3: MAC Address3
Addr,: Pointer to MAC address buffer data (6 bytes)
Return values:
HAL status
Definition at line 2083 of file stm32f1xx_hal_eth.c.
References assert_param, ETH_MAC_ADDR_HBASE, ETH_MAC_ADDR_LBASE, and IS_ETH_MAC_ADDRESS0123.
Referenced by ETH_MACDMAConfig().
static void ETH_MACDMAConfig (ETH_HandleTypeDef * heth, uint32_t err) [static]
Configures Ethernet MAC and DMA with default parameters.
Parameters:
heth,: pointer to a ETH_HandleTypeDef structure that contains the configuration information for ETHERNET module
err,: Ethernet Init error
Return values:
HAL status
Definition at line 1823 of file stm32f1xx_hal_eth.c.
References __HAL_ETH_DMA_ENABLE_IT, ETH_DMAInitTypeDef::AddressAlignedBeats, ETH_MACInitTypeDef::AutomaticPadCRCStrip, ETH_MACInitTypeDef::BackOffLimit, ETH_MACInitTypeDef::BroadcastFramesReception, ETH_MACInitTypeDef::CarrierSense, ETH_InitTypeDef::ChecksumMode, ETH_MACInitTypeDef::ChecksumOffload, ETH_MACInitTypeDef::DeferralCheck, ETH_DMAInitTypeDef::DescriptorSkipLength, ETH_MACInitTypeDef::DestinationAddrFilter, ETH_DMAInitTypeDef::DMAArbitration, ETH_DMAInitTypeDef::DropTCPIPChecksumErrorFrame, ETH_ADDRESSALIGNEDBEATS_ENABLE, ETH_AUTOMATICPADCRCSTRIP_DISABLE, ETH_BACKOFFLIMIT_10, ETH_BROADCASTFRAMESRECEPTION_ENABLE, ETH_CARRIERSENCE_ENABLE, ETH_CHECKSUM_BY_HARDWARE, ETH_CHECKSUMOFFLAOD_DISABLE, ETH_CHECKSUMOFFLAOD_ENABLE, ETH_DEFFERRALCHECK_DISABLE, ETH_DESTINATIONADDRFILTER_NORMAL, ETH_DMA_IT_NIS, ETH_DMA_IT_R, ETH_DMAARBITRATION_ROUNDROBIN_RXTX_1_1, ETH_DMAOMR_CLEAR_MASK, ETH_DROPTCPIPCHECKSUMERRORFRAME_ENABLE, ETH_FIXEDBURST_ENABLE, ETH_FLUSHRECEIVEDFRAME_ENABLE, ETH_FORWARDERRORFRAMES_DISABLE, ETH_FORWARDUNDERSIZEDGOODFRAMES_DISABLE, ETH_INTERFRAMEGAP_96BIT, ETH_JABBER_ENABLE, ETH_LOOPBACKMODE_DISABLE, ETH_MAC_ADDRESS0, ETH_MACAddressConfig(), ETH_MACCR_CLEAR_MASK, ETH_MACFCR_CLEAR_MASK, ETH_MODE_FULLDUPLEX, ETH_MULTICASTFRAMESFILTER_PERFECT, ETH_PASSCONTROLFRAMES_BLOCKALL, ETH_PAUSELOWTHRESHOLD_MINUS4, ETH_PROMISCUOUS_MODE_DISABLE, ETH_RECEIVEAll_DISABLE, ETH_RECEIVEDTHRESHOLDCONTROL_64BYTES, ETH_RECEIVEFLOWCONTROL_DISABLE, ETH_RECEIVEOWN_ENABLE, ETH_RECEIVESTOREFORWARD_ENABLE, ETH_REG_WRITE_DELAY, ETH_RETRYTRANSMISSION_DISABLE, ETH_RXDMABURSTLENGTH_32BEAT, ETH_RXINTERRUPT_MODE, ETH_SECONDFRAMEOPERARTE_ENABLE, ETH_SOURCEADDRFILTER_DISABLE, ETH_SPEED_100M, ETH_SUCCESS, ETH_TRANSMITFLOWCONTROL_DISABLE, ETH_TRANSMITSTOREFORWARD_ENABLE, ETH_TRANSMITTHRESHOLDCONTROL_64BYTES, ETH_TXDMABURSTLENGTH_32BEAT, ETH_UNICASTFRAMESFILTER_PERFECT, ETH_UNICASTPAUSEFRAMEDETECT_DISABLE, ETH_VLANTAGCOMPARISON_16BIT, ETH_WATCHDOG_ENABLE, ETH_ZEROQUANTAPAUSE_DISABLE, ETH_DMAInitTypeDef::FixedBurst, ETH_DMAInitTypeDef::FlushReceivedFrame, ETH_DMAInitTypeDef::ForwardErrorFrames, ETH_DMAInitTypeDef::ForwardUndersizedGoodFrames, HAL_Delay(), ETH_MACInitTypeDef::HashTableHigh, ETH_MACInitTypeDef::HashTableLow, ETH_HandleTypeDef::Init, ETH_HandleTypeDef::Instance, ETH_MACInitTypeDef::InterFrameGap, ETH_MACInitTypeDef::Jabber, ETH_MACInitTypeDef::LoopbackMode, ETH_InitTypeDef::MACAddr, ETH_MACInitTypeDef::MulticastFramesFilter, ETH_MACInitTypeDef::PassControlFrames, ETH_MACInitTypeDef::PauseLowThreshold, ETH_MACInitTypeDef::PauseTime, ETH_MACInitTypeDef::PromiscuousMode, ETH_MACInitTypeDef::ReceiveAll, ETH_MACInitTypeDef::ReceiveFlowControl, ETH_MACInitTypeDef::ReceiveOwn, ETH_DMAInitTypeDef::ReceiveStoreForward, ETH_DMAInitTypeDef::ReceiveThresholdControl, ETH_MACInitTypeDef::RetryTransmission, ETH_DMAInitTypeDef::RxDMABurstLength, ETH_DMAInitTypeDef::SecondFrameOperate, ETH_MACInitTypeDef::SourceAddrFilter, ETH_MACInitTypeDef::TransmitFlowControl, ETH_DMAInitTypeDef::TransmitStoreForward, ETH_DMAInitTypeDef::TransmitThresholdControl, ETH_DMAInitTypeDef::TxDMABurstLength, ETH_MACInitTypeDef::UnicastFramesFilter, ETH_MACInitTypeDef::UnicastPauseFrameDetect, ETH_MACInitTypeDef::VLANTagComparison, ETH_MACInitTypeDef::VLANTagIdentifier, ETH_MACInitTypeDef::Watchdog, and ETH_MACInitTypeDef::ZeroQuantaPause.
Referenced by HAL_ETH_Init().
static void ETH_MACReceptionDisable (ETH_HandleTypeDef * heth) [static]
Disables the MAC reception.
Parameters:
heth,: pointer to a ETH_HandleTypeDef structure that contains the configuration information for ETHERNET module
Return values:
None
Definition at line 2170 of file stm32f1xx_hal_eth.c.
References ETH_Delay(), ETH_REG_WRITE_DELAY, and ETH_HandleTypeDef::Instance.
Referenced by HAL_ETH_Stop().
static void ETH_MACReceptionEnable (ETH_HandleTypeDef * heth) [static]
Enables the MAC reception.
Parameters:
heth,: pointer to a ETH_HandleTypeDef structure that contains the configuration information for ETHERNET module
Return values:
None
Definition at line 2150 of file stm32f1xx_hal_eth.c.
References ETH_Delay(), ETH_REG_WRITE_DELAY, and ETH_HandleTypeDef::Instance.
Referenced by HAL_ETH_Start().
static void ETH_MACTransmissionDisable (ETH_HandleTypeDef * heth) [static]
Disables the MAC transmission.
Parameters:
heth,: pointer to a ETH_HandleTypeDef structure that contains the configuration information for ETHERNET module
Return values:
None
Definition at line 2130 of file stm32f1xx_hal_eth.c.
References ETH_Delay(), ETH_REG_WRITE_DELAY, and ETH_HandleTypeDef::Instance.
Referenced by HAL_ETH_Stop().
static void ETH_MACTransmissionEnable (ETH_HandleTypeDef * heth) [static]
Enables the MAC transmission.
Parameters:
heth,: pointer to a ETH_HandleTypeDef structure that contains the configuration information for ETHERNET module
Return values:
None
Definition at line 2110 of file stm32f1xx_hal_eth.c.
References ETH_Delay(), ETH_REG_WRITE_DELAY, and ETH_HandleTypeDef::Instance.
Referenced by HAL_ETH_Start().