STM32F107xC HAL User Manual: Initialization and de-initialization functions
Initialization and de-initialization functions
ETH Exported Functions
Initialization and Configuration functions.
Functions
HAL_StatusTypeDef HAL_ETH_Init (ETH_HandleTypeDef *heth)
Initializes the Ethernet MAC and DMA according to default parameters.
HAL_StatusTypeDef HAL_ETH_DeInit (ETH_HandleTypeDef *heth)
De-Initializes the ETH peripheral.
HAL_StatusTypeDef HAL_ETH_DMATxDescListInit (ETH_HandleTypeDef *heth, ETH_DMADescTypeDef *DMATxDescTab, uint8_t *TxBuff, uint32_t TxBuffCount)
Initializes the DMA Tx descriptors in chain mode.
HAL_StatusTypeDef HAL_ETH_DMARxDescListInit (ETH_HandleTypeDef *heth, ETH_DMADescTypeDef *DMARxDescTab, uint8_t *RxBuff, uint32_t RxBuffCount)
Initializes the DMA Rx descriptors in chain mode.
__weak void HAL_ETH_MspInit (ETH_HandleTypeDef *heth)
Initializes the ETH MSP.
__weak void HAL_ETH_MspDeInit (ETH_HandleTypeDef *heth)
DeInitializes ETH MSP.
Detailed Description
Initialization and Configuration functions.
  ===============================================================================
            ##### Initialization and de-initialization functions #####
  ===============================================================================
  [..]  This section provides functions allowing to:
      (+) Initialize and configure the Ethernet peripheral
      (+) De-initialize the Ethernet peripheral
Function Documentation
HAL_StatusTypeDef HAL_ETH_DeInit (ETH_HandleTypeDef * heth)
De-Initializes the ETH peripheral.
Parameters:
heth,: pointer to a ETH_HandleTypeDef structure that contains the configuration information for ETHERNET module
Return values:
HAL status
Definition at line 485 of file stm32f1xx_hal_eth.c.
References HAL_ETH_MspDeInit(), HAL_ETH_STATE_BUSY, HAL_ETH_STATE_RESET, and ETH_HandleTypeDef::State.
HAL_StatusTypeDef HAL_ETH_DMARxDescListInit (ETH_HandleTypeDef * heth, ETH_DMADescTypeDef * DMARxDescTab, uint8_t * RxBuff, uint32_t RxBuffCount)
Initializes the DMA Rx descriptors in chain mode.
Parameters:
heth,: pointer to a ETH_HandleTypeDef structure that contains the configuration information for ETHERNET module
DMARxDescTab,: Pointer to the first Rx desc list
RxBuff,: Pointer to the first RxBuffer list
RxBuffCount,: Number of the used Rx desc in the list
Return values:
HAL status
Definition at line 588 of file stm32f1xx_hal_eth.c.
References ETH_DMADescTypeDef::Buffer1Addr, ETH_DMADescTypeDef::Buffer2NextDescAddr, ETH_DMADescTypeDef::ControlBufferSize, ETH_DMARXDESC_DIC, ETH_DMARXDESC_OWN, ETH_DMARXDESC_RCH, ETH_RX_BUF_SIZE, ETH_RXINTERRUPT_MODE, HAL_ETH_STATE_BUSY, HAL_ETH_STATE_READY, ETH_HandleTypeDef::Init, ETH_HandleTypeDef::Instance, ETH_HandleTypeDef::RxDesc, ETH_HandleTypeDef::State, and ETH_DMADescTypeDef::Status.
HAL_StatusTypeDef HAL_ETH_DMATxDescListInit (ETH_HandleTypeDef * heth, ETH_DMADescTypeDef * DMATxDescTab, uint8_t * TxBuff, uint32_t TxBuffCount)
Initializes the DMA Tx descriptors in chain mode.
Parameters:
heth,: pointer to a ETH_HandleTypeDef structure that contains the configuration information for ETHERNET module
DMATxDescTab,: Pointer to the first Tx desc list
TxBuff,: Pointer to the first TxBuffer list
TxBuffCount,: Number of the used Tx desc in the list
Return values:
HAL status
Definition at line 521 of file stm32f1xx_hal_eth.c.
References ETH_DMADescTypeDef::Buffer1Addr, ETH_DMADescTypeDef::Buffer2NextDescAddr, ETH_CHECKSUM_BY_HARDWARE, ETH_DMATXDESC_CHECKSUMTCPUDPICMPFULL, ETH_DMATXDESC_TCH, ETH_TX_BUF_SIZE, HAL_ETH_STATE_BUSY, HAL_ETH_STATE_READY, ETH_HandleTypeDef::Init, ETH_HandleTypeDef::Instance, ETH_HandleTypeDef::State, ETH_DMADescTypeDef::Status, and ETH_HandleTypeDef::TxDesc.
HAL_StatusTypeDef HAL_ETH_Init (ETH_HandleTypeDef * heth)
Initializes the Ethernet MAC and DMA according to default parameters.
Parameters:
heth,: pointer to a ETH_HandleTypeDef structure that contains the configuration information for ETHERNET module
Return values:
HAL status
Definition at line 212 of file stm32f1xx_hal_eth.c.
References assert_param, ETH_InitTypeDef::AutoNegotiation, ETH_InitTypeDef::ChecksumMode, ETH_InitTypeDef::DuplexMode, ETH_AUTONEGOTIATION_DISABLE, ETH_ERROR, ETH_MACDMAConfig(), ETH_MACMIIAR_CR_MASK, ETH_MODE_FULLDUPLEX, ETH_MODE_HALFDUPLEX, ETH_SPEED_100M, ETH_SPEED_10M, ETH_SUCCESS, ETH_TIMEOUT_AUTONEGO_COMPLETED, ETH_TIMEOUT_LINKED_STATE, ETH_TIMEOUT_SWRESET, HAL_Delay(), HAL_ETH_MspInit(), HAL_ETH_ReadPHYRegister(), HAL_ETH_STATE_READY, HAL_ETH_STATE_RESET, HAL_ETH_STATE_TIMEOUT, HAL_ETH_WritePHYRegister(), HAL_GetTick(), HAL_RCC_GetHCLKFreq(), ETH_HandleTypeDef::Init, ETH_HandleTypeDef::Instance, IS_ETH_AUTONEGOTIATION, IS_ETH_CHECKSUM_MODE, IS_ETH_DUPLEX_MODE, IS_ETH_MEDIA_INTERFACE, IS_ETH_RX_MODE, IS_ETH_SPEED, ETH_HandleTypeDef::Lock, ETH_InitTypeDef::MediaInterface, PHY_AUTONEGO_COMPLETE, PHY_AUTONEGOTIATION, PHY_BCR, PHY_BSR, PHY_CONFIG_DELAY, PHY_DUPLEX_STATUS, PHY_LINKED_STATUS, PHY_RESET, PHY_RESET_DELAY, PHY_SPEED_STATUS, PHY_SR, ETH_InitTypeDef::RxMode, ETH_InitTypeDef::Speed, and ETH_HandleTypeDef::State.
void HAL_ETH_MspDeInit (ETH_HandleTypeDef * heth)
DeInitializes ETH MSP.
Parameters:
heth,: pointer to a ETH_HandleTypeDef structure that contains the configuration information for ETHERNET module
Return values:
None
Definition at line 670 of file stm32f1xx_hal_eth.c.
Referenced by HAL_ETH_DeInit().
void HAL_ETH_MspInit (ETH_HandleTypeDef * heth)
Initializes the ETH MSP.
Parameters:
heth,: pointer to a ETH_HandleTypeDef structure that contains the configuration information for ETHERNET module
Return values:
None
Definition at line 655 of file stm32f1xx_hal_eth.c.
Referenced by HAL_ETH_Init().