STM32F107xC HAL User Manual: Input and Output operation functions
Input and Output operation functions
HCD Exported Functions
HCD IO operation functions.
Functions
HAL_StatusTypeDef HAL_HCD_HC_SubmitRequest (HCD_HandleTypeDef *hhcd, uint8_t ch_num, uint8_t direction, uint8_t ep_type, uint8_t token, uint8_t *pbuff, uint16_t length, uint8_t do_ping)
Submit a new URB for processing.
void HAL_HCD_IRQHandler (HCD_HandleTypeDef *hhcd)
Handle HCD interrupt request.
__weak void HAL_HCD_SOF_Callback (HCD_HandleTypeDef *hhcd)
SOF callback.
__weak void HAL_HCD_Connect_Callback (HCD_HandleTypeDef *hhcd)
Connection Event callback.
__weak void HAL_HCD_Disconnect_Callback (HCD_HandleTypeDef *hhcd)
Disconnection Event callback.
__weak void HAL_HCD_PortEnabled_Callback (HCD_HandleTypeDef *hhcd)
Port Enabled Event callback.
__weak void HAL_HCD_PortDisabled_Callback (HCD_HandleTypeDef *hhcd)
Port Disabled Event callback.
__weak void HAL_HCD_HC_NotifyURBChange_Callback (HCD_HandleTypeDef *hhcd, uint8_t chnum, HCD_URBStateTypeDef urb_state)
Notify URB state change callback.
Detailed Description
HCD IO operation functions.
 ===============================================================================
                      ##### IO operation functions #####
 ===============================================================================
 [..] This subsection provides a set of functions allowing to manage the USB Host Data
    Transfer
Function Documentation
void HAL_HCD_Connect_Callback (HCD_HandleTypeDef * hhcd)
Connection Event callback.
Parameters:
hhcd HCD handle
Return values:
None
Definition at line 618 of file stm32f1xx_hal_hcd.c.
Referenced by HAL_HCD_Init(), and HCD_Port_IRQHandler().
void HAL_HCD_Disconnect_Callback (HCD_HandleTypeDef * hhcd)
Disconnection Event callback.
Parameters:
hhcd HCD handle
Return values:
None
Definition at line 633 of file stm32f1xx_hal_hcd.c.
Referenced by HAL_HCD_Init(), and HAL_HCD_IRQHandler().
void HAL_HCD_HC_NotifyURBChange_Callback (HCD_HandleTypeDef * hhcd, uint8_t chnum, HCD_URBStateTypeDef urb_state)
Notify URB state change callback.
Parameters:
hhcd HCD handle
chnum Channel number. This parameter can be a value from 1 to 15
urb_state,: This parameter can be one of these values: URB_IDLE/ URB_DONE/ URB_NOTREADY/ URB_NYET/ URB_ERROR/ URB_STALL/
Return values:
None
Definition at line 688 of file stm32f1xx_hal_hcd.c.
Referenced by HAL_HCD_Init(), HCD_HC_IN_IRQHandler(), and HCD_HC_OUT_IRQHandler().
HAL_StatusTypeDef HAL_HCD_HC_SubmitRequest (HCD_HandleTypeDef * hhcd, uint8_t ch_num, uint8_t direction, uint8_t ep_type, uint8_t token, uint8_t * pbuff, uint16_t length, uint8_t do_ping)
Submit a new URB for processing.
Parameters:
hhcd HCD handle
ch_num Channel number. This parameter can be a value from 1 to 15
direction Channel number. This parameter can be one of these values: 0 : Output / 1 : Input
ep_type Endpoint Type. This parameter can be one of these values: EP_TYPE_CTRL: Control type/ EP_TYPE_ISOC: Isochronous type/ EP_TYPE_BULK: Bulk type/ EP_TYPE_INTR: Interrupt type/
token Endpoint Type. This parameter can be one of these values: 0: HC_PID_SETUP / 1: HC_PID_DATA1
pbuff pointer to URB data
length Length of URB data
do_ping activate do ping protocol (for high speed only). This parameter can be one of these values: 0 : do ping inactive / 1 : do ping active
Return values:
HAL status
Definition at line 363 of file stm32f1xx_hal_hcd.c.
References HCD_HandleTypeDef::hc, and HCD_HandleTypeDef::Instance.
void HAL_HCD_IRQHandler (HCD_HandleTypeDef * hhcd)
Handle HCD interrupt request.
Parameters:
hhcd HCD handle
Return values:
None
Definition at line 490 of file stm32f1xx_hal_hcd.c.
References __HAL_HCD_CLEAR_FLAG, __HAL_HCD_GET_FLAG, __HAL_HCD_IS_INVALID_INTERRUPT, HAL_HCD_Disconnect_Callback(), HAL_HCD_SOF_Callback(), HCD_HC_IN_IRQHandler(), HCD_HC_OUT_IRQHandler(), HCD_Port_IRQHandler(), HCD_RXQLVL_IRQHandler(), HCD_HandleTypeDef::Init, and HCD_HandleTypeDef::Instance.
void HAL_HCD_PortDisabled_Callback (HCD_HandleTypeDef * hhcd)
Port Disabled Event callback.
Parameters:
hhcd HCD handle
Return values:
None
Definition at line 663 of file stm32f1xx_hal_hcd.c.
Referenced by HAL_HCD_Init(), and HCD_Port_IRQHandler().
void HAL_HCD_PortEnabled_Callback (HCD_HandleTypeDef * hhcd)
Port Enabled Event callback.
Parameters:
hhcd HCD handle
Return values:
None
Definition at line 648 of file stm32f1xx_hal_hcd.c.
Referenced by HAL_HCD_Init(), and HCD_Port_IRQHandler().
void HAL_HCD_SOF_Callback (HCD_HandleTypeDef * hhcd)
SOF callback.
Parameters:
hhcd HCD handle
Return values:
None
Definition at line 603 of file stm32f1xx_hal_hcd.c.
Referenced by HAL_HCD_Init(), and HAL_HCD_IRQHandler().