STM32F107xC HAL User Manual: Configuration
Configuration
RTC Exported Functions
Functions
__STATIC_INLINE void LL_RTC_SetAsynchPrescaler (RTC_TypeDef *RTCx, uint32_t AsynchPrescaler)
Set Asynchronous prescaler factor.
__STATIC_INLINE uint32_t LL_RTC_GetDivider (RTC_TypeDef *RTCx)
Get Asynchronous prescaler factor.
__STATIC_INLINE void LL_RTC_SetOutputSource (BKP_TypeDef *BKPx, uint32_t OutputSource)
Set Output Source.
__STATIC_INLINE uint32_t LL_RTC_GetOutPutSource (BKP_TypeDef *BKPx)
Get Output Source.
__STATIC_INLINE void LL_RTC_EnableWriteProtection (RTC_TypeDef *RTCx)
Enable the write protection for RTC registers.
__STATIC_INLINE void LL_RTC_DisableWriteProtection (RTC_TypeDef *RTCx)
Disable the write protection for RTC registers.
Function Documentation
__STATIC_INLINE void LL_RTC_DisableWriteProtection (RTC_TypeDef * RTCx)
Disable the write protection for RTC registers.
Reference Manual to LL API cross reference:
CRL RTC_CRL_CNF LL_RTC_DisableWriteProtection
Parameters:
RTCx RTC Instance
Return values:
None
Definition at line 351 of file stm32f1xx_ll_rtc.h.
Referenced by LL_RTC_DeInit(), and LL_RTC_EnterInitMode().
__STATIC_INLINE void LL_RTC_EnableWriteProtection (RTC_TypeDef * RTCx)
Enable the write protection for RTC registers.
Reference Manual to LL API cross reference:
CRL CNF LL_RTC_EnableWriteProtection
Parameters:
RTCx RTC Instance
Return values:
None
Definition at line 340 of file stm32f1xx_ll_rtc.h.
Referenced by LL_RTC_DeInit(), and LL_RTC_ExitInitMode().
__STATIC_INLINE uint32_t LL_RTC_GetDivider (RTC_TypeDef * RTCx)
Get Asynchronous prescaler factor.
Reference Manual to LL API cross reference:
DIVH DIV LL_RTC_GetDivider
Reference Manual to LL API cross reference:
DIVL DIV LL_RTC_GetDivider
Parameters:
RTCx RTC Instance
Return values:
Value between Min_Data = 0 and Max_Data = 0xFFFFF
Definition at line 290 of file stm32f1xx_ll_rtc.h.
__STATIC_INLINE uint32_t LL_RTC_GetOutPutSource (BKP_TypeDef * BKPx)
Get Output Source.
Reference Manual to LL API cross reference:
RTCCR CCO LL_RTC_GetOutPutSource
Reference Manual to LL API cross reference:
RTCCR ASOE LL_RTC_GetOutPutSource
Reference Manual to LL API cross reference:
RTCCR ASOS LL_RTC_GetOutPutSource
Parameters:
BKPx BKP Instance
Return values:
Returned value can be one of the following values:
LL_RTC_CALIB_OUTPUT_NONE
LL_RTC_CALIB_OUTPUT_RTCCLOCK
LL_RTC_CALIB_OUTPUT_ALARM
LL_RTC_CALIB_OUTPUT_SECOND
Definition at line 329 of file stm32f1xx_ll_rtc.h.
__STATIC_INLINE void LL_RTC_SetAsynchPrescaler (RTC_TypeDef * RTCx, uint32_t AsynchPrescaler)
Set Asynchronous prescaler factor.
Reference Manual to LL API cross reference:
PRLH PRL LL_RTC_SetAsynchPrescaler
Reference Manual to LL API cross reference:
PRLL PRL LL_RTC_SetAsynchPrescaler
Parameters:
RTCx RTC Instance
AsynchPrescaler Value between Min_Data = 0 and Max_Data = 0xFFFFF
Return values:
None
Definition at line 277 of file stm32f1xx_ll_rtc.h.
Referenced by LL_RTC_Init().
__STATIC_INLINE void LL_RTC_SetOutputSource (BKP_TypeDef * BKPx, uint32_t OutputSource)
Set Output Source.
Reference Manual to LL API cross reference:
RTCCR CCO LL_RTC_SetOutputSource
Reference Manual to LL API cross reference:
RTCCR ASOE LL_RTC_SetOutputSource
Reference Manual to LL API cross reference:
RTCCR ASOS LL_RTC_SetOutputSource
Parameters:
BKPx BKP Instance
OutputSource This parameter can be one of the following values:
LL_RTC_CALIB_OUTPUT_NONE
LL_RTC_CALIB_OUTPUT_RTCCLOCK
LL_RTC_CALIB_OUTPUT_ALARM
LL_RTC_CALIB_OUTPUT_SECOND
Return values:
None
Definition at line 312 of file stm32f1xx_ll_rtc.h.
Referenced by LL_RTC_Init().