STM32F107xC HAL User Manual: Initialization and de-initialization functions
Initialization and de-initialization functions
RTC Exported Functions
Initialization and Configuration functions.
Functions
HAL_StatusTypeDef HAL_RTC_Init (RTC_HandleTypeDef *hrtc)
Initializes the RTC peripheral.
HAL_StatusTypeDef HAL_RTC_DeInit (RTC_HandleTypeDef *hrtc)
DeInitializes the RTC peripheral.
__weak void HAL_RTC_MspInit (RTC_HandleTypeDef *hrtc)
Initializes the RTC MSP.
__weak void HAL_RTC_MspDeInit (RTC_HandleTypeDef *hrtc)
DeInitializes the RTC MSP.
Detailed Description
Initialization and Configuration functions.
 ===============================================================================
              ##### Initialization and de-initialization functions #####
 ===============================================================================
   [..] This section provides functions allowing to initialize and configure the
         RTC Prescaler (Asynchronous), disable RTC registers Write protection,
         enter and exit the RTC initialization mode,
         RTC registers synchronization check and reference clock detection enable.
         (#) The RTC Prescaler should be programmed to generate the RTC 1Hz time base.
         (#) All RTC registers are Write protected. Writing to the RTC registers
             is enabled by setting the CNF bit in the RTC_CRL register.
         (#) To read the calendar after wakeup from low power modes (Standby or Stop)
             the software must first wait for the RSF bit (Register Synchronized Flag)
             in the RTC_CRL register to be set by hardware.
             The HAL_RTC_WaitForSynchro() function implements the above software
             sequence (RSF clear and RSF check).
Function Documentation
HAL_StatusTypeDef HAL_RTC_DeInit (RTC_HandleTypeDef * hrtc)
DeInitializes the RTC peripheral.
Parameters:
hrtc pointer to a RTC_HandleTypeDef structure that contains the configuration information for RTC.
Note:
This function does not reset the RTC Backup Data registers.
Return values:
HAL status
Definition at line 408 of file stm32f1xx_hal_rtc.c.
References assert_param, HAL_RTC_MspDeInit(), HAL_RTC_STATE_BUSY, HAL_RTC_STATE_ERROR, HAL_RTC_STATE_RESET, HAL_RTC_WaitForSynchro(), RTC_HandleTypeDef::Instance, RTC_EnterInitMode(), RTC_ExitInitMode(), RTC_FLAG_RSF, and RTC_HandleTypeDef::State.
HAL_StatusTypeDef HAL_RTC_Init (RTC_HandleTypeDef * hrtc)
Initializes the RTC peripheral.
Parameters:
hrtc pointer to a RTC_HandleTypeDef structure that contains the configuration information for RTC.
Return values:
HAL status
Definition at line 272 of file stm32f1xx_hal_rtc.c.
References assert_param, RTC_InitTypeDef::AsynchPrediv, RTC_DateTypeDef::Date, RTC_HandleTypeDef::DateToUpdate, HAL_RCCEx_GetPeriphCLKFreq(), HAL_RTC_AlarmAEventCallback(), HAL_RTC_MspDeInit(), HAL_RTC_MspInit(), HAL_RTC_STATE_BUSY, HAL_RTC_STATE_ERROR, HAL_RTC_STATE_READY, HAL_RTC_STATE_RESET, HAL_RTC_WaitForSynchro(), HAL_RTCEx_Tamper1EventCallback(), RTC_HandleTypeDef::Init, RTC_HandleTypeDef::Instance, IS_RTC_ASYNCH_PREDIV, IS_RTC_CALIB_OUTPUT, RTC_HandleTypeDef::Lock, RTC_DateTypeDef::Month, RTC_InitTypeDef::OutPut, RCC_PERIPHCLK_RTC, RTC_AUTO_1_SECOND, RTC_EnterInitMode(), RTC_ExitInitMode(), RTC_FLAG_ALRAF, RTC_FLAG_OW, RTC_FLAG_SEC, RTC_MONTH_JANUARY, RTC_OUTPUTSOURCE_NONE, RTC_HandleTypeDef::State, and RTC_DateTypeDef::Year.
void HAL_RTC_MspDeInit (RTC_HandleTypeDef * hrtc)
DeInitializes the RTC MSP.
Parameters:
hrtc pointer to a RTC_HandleTypeDef structure that contains the configuration information for RTC.
Return values:
None
Definition at line 662 of file stm32f1xx_hal_rtc.c.
Referenced by HAL_RTC_DeInit(), and HAL_RTC_Init().
void HAL_RTC_MspInit (RTC_HandleTypeDef * hrtc)
Initializes the RTC MSP.
Parameters:
hrtc pointer to a RTC_HandleTypeDef structure that contains the configuration information for RTC.
Return values:
None
Definition at line 647 of file stm32f1xx_hal_rtc.c.
Referenced by HAL_RTC_Init().