STM32F107xC HAL User Manual: FLAG Management
FLAG Management
I2S Exported Functions
Functions
__STATIC_INLINE uint32_t LL_I2S_IsActiveFlag_RXNE (SPI_TypeDef *SPIx)
Check if Rx buffer is not empty.
__STATIC_INLINE uint32_t LL_I2S_IsActiveFlag_TXE (SPI_TypeDef *SPIx)
Check if Tx buffer is empty.
__STATIC_INLINE uint32_t LL_I2S_IsActiveFlag_BSY (SPI_TypeDef *SPIx)
Get busy flag.
__STATIC_INLINE uint32_t LL_I2S_IsActiveFlag_OVR (SPI_TypeDef *SPIx)
Get overrun error flag.
__STATIC_INLINE uint32_t LL_I2S_IsActiveFlag_UDR (SPI_TypeDef *SPIx)
Get underrun error flag.
__STATIC_INLINE uint32_t LL_I2S_IsActiveFlag_CHSIDE (SPI_TypeDef *SPIx)
Get channel side flag.
__STATIC_INLINE void LL_I2S_ClearFlag_OVR (SPI_TypeDef *SPIx)
Clear overrun error flag.
__STATIC_INLINE void LL_I2S_ClearFlag_UDR (SPI_TypeDef *SPIx)
Clear underrun error flag.
__STATIC_INLINE void LL_I2S_ClearFlag_FRE (SPI_TypeDef *SPIx)
Clear frame format error flag.
Function Documentation
__STATIC_INLINE void LL_I2S_ClearFlag_FRE (SPI_TypeDef * SPIx)
Clear frame format error flag.
Reference Manual to LL API cross reference:
SR FRE LL_I2S_ClearFlag_FRE
Parameters:
SPIx SPI Instance
Return values:
None
Definition at line 1679 of file stm32f1xx_ll_spi.h.
References LL_SPI_ClearFlag_FRE().
__STATIC_INLINE void LL_I2S_ClearFlag_OVR (SPI_TypeDef * SPIx)
Clear overrun error flag.
Reference Manual to LL API cross reference:
SR OVR LL_I2S_ClearFlag_OVR
Parameters:
SPIx SPI Instance
Return values:
None
Definition at line 1655 of file stm32f1xx_ll_spi.h.
References LL_SPI_ClearFlag_OVR().
__STATIC_INLINE void LL_I2S_ClearFlag_UDR (SPI_TypeDef * SPIx)
Clear underrun error flag.
Reference Manual to LL API cross reference:
SR UDR LL_I2S_ClearFlag_UDR
Parameters:
SPIx SPI Instance
Return values:
None
Definition at line 1666 of file stm32f1xx_ll_spi.h.
__STATIC_INLINE uint32_t LL_I2S_IsActiveFlag_BSY (SPI_TypeDef * SPIx)
Get busy flag.
Reference Manual to LL API cross reference:
SR BSY LL_I2S_IsActiveFlag_BSY
Parameters:
SPIx SPI Instance
Return values:
State of bit (1 or 0).
Definition at line 1607 of file stm32f1xx_ll_spi.h.
References LL_SPI_IsActiveFlag_BSY().
__STATIC_INLINE uint32_t LL_I2S_IsActiveFlag_CHSIDE (SPI_TypeDef * SPIx)
Get channel side flag.
Note:
0: Channel Left has to be transmitted or has been received
1: Channel Right has to be transmitted or has been received
It has no significance in PCM mode.
Reference Manual to LL API cross reference:
SR CHSIDE LL_I2S_IsActiveFlag_CHSIDE
Parameters:
SPIx SPI Instance
Return values:
State of bit (1 or 0).
Definition at line 1644 of file stm32f1xx_ll_spi.h.
__STATIC_INLINE uint32_t LL_I2S_IsActiveFlag_OVR (SPI_TypeDef * SPIx)
Get overrun error flag.
Reference Manual to LL API cross reference:
SR OVR LL_I2S_IsActiveFlag_OVR
Parameters:
SPIx SPI Instance
Return values:
State of bit (1 or 0).
Definition at line 1618 of file stm32f1xx_ll_spi.h.
References LL_SPI_IsActiveFlag_OVR().
__STATIC_INLINE uint32_t LL_I2S_IsActiveFlag_RXNE (SPI_TypeDef * SPIx)
Check if Rx buffer is not empty.
Reference Manual to LL API cross reference:
SR RXNE LL_I2S_IsActiveFlag_RXNE
Parameters:
SPIx SPI Instance
Return values:
State of bit (1 or 0).
Definition at line 1585 of file stm32f1xx_ll_spi.h.
References LL_SPI_IsActiveFlag_RXNE().
__STATIC_INLINE uint32_t LL_I2S_IsActiveFlag_TXE (SPI_TypeDef * SPIx)
Check if Tx buffer is empty.
Reference Manual to LL API cross reference:
SR TXE LL_I2S_IsActiveFlag_TXE
Parameters:
SPIx SPI Instance
Return values:
State of bit (1 or 0).
Definition at line 1596 of file stm32f1xx_ll_spi.h.
References LL_SPI_IsActiveFlag_TXE().
__STATIC_INLINE uint32_t LL_I2S_IsActiveFlag_UDR (SPI_TypeDef * SPIx)
Get underrun error flag.
Reference Manual to LL API cross reference:
SR UDR LL_I2S_IsActiveFlag_UDR
Parameters:
SPIx SPI Instance
Return values:
State of bit (1 or 0).
Definition at line 1629 of file stm32f1xx_ll_spi.h.