STM32F107xC HAL User Manual: HCD Private Functions
HCD Private Functions
HCD
Functions
static void HCD_HC_IN_IRQHandler (HCD_HandleTypeDef *hhcd, uint8_t chnum)
Handle Host Channel IN interrupt requests.
static void HCD_HC_OUT_IRQHandler (HCD_HandleTypeDef *hhcd, uint8_t chnum)
Handle Host Channel OUT interrupt requests.
static void HCD_RXQLVL_IRQHandler (HCD_HandleTypeDef *hhcd)
Handle Rx Queue Level interrupt requests.
static void HCD_Port_IRQHandler (HCD_HandleTypeDef *hhcd)
Handle Host Port interrupt requests.
Function Documentation
static void HCD_HC_IN_IRQHandler (HCD_HandleTypeDef * hhcd, uint8_t chnum) [static]
Handle Host Channel IN interrupt requests.
Parameters:
hhcd HCD handle
chnum Channel number. This parameter can be a value from 1 to 15
Return values:
none
Definition at line 1156 of file stm32f1xx_hal_hcd.c.
References __HAL_HCD_CLEAR_HC_INT, __HAL_HCD_MASK_HALT_HC_INT, __HAL_HCD_UNMASK_HALT_HC_INT, HAL_HCD_HC_NotifyURBChange_Callback(), HCD_HandleTypeDef::hc, and HCD_HandleTypeDef::Instance.
Referenced by HAL_HCD_IRQHandler().
static void HCD_HC_OUT_IRQHandler (HCD_HandleTypeDef * hhcd, uint8_t chnum) [static]
Handle Host Channel OUT interrupt requests.
Parameters:
hhcd HCD handle
chnum Channel number. This parameter can be a value from 1 to 15
Return values:
none
Definition at line 1322 of file stm32f1xx_hal_hcd.c.
References __HAL_HCD_CLEAR_HC_INT, __HAL_HCD_MASK_HALT_HC_INT, __HAL_HCD_UNMASK_HALT_HC_INT, HAL_HCD_HC_NotifyURBChange_Callback(), HCD_HandleTypeDef::hc, and HCD_HandleTypeDef::Instance.
Referenced by HAL_HCD_IRQHandler().
static void HCD_Port_IRQHandler (HCD_HandleTypeDef * hhcd) [static]
Handle Host Port interrupt requests.
Parameters:
hhcd HCD handle
Return values:
None
Definition at line 1518 of file stm32f1xx_hal_hcd.c.
References HAL_HCD_Connect_Callback(), HAL_HCD_PortDisabled_Callback(), HAL_HCD_PortEnabled_Callback(), HCD_SPEED_FULL, HCD_HandleTypeDef::Init, and HCD_HandleTypeDef::Instance.
Referenced by HAL_HCD_IRQHandler().
static void HCD_RXQLVL_IRQHandler (HCD_HandleTypeDef * hhcd) [static]
Handle Rx Queue Level interrupt requests.
Parameters:
hhcd HCD handle
Return values:
none
Definition at line 1464 of file stm32f1xx_hal_hcd.c.
References HCD_HandleTypeDef::hc, and HCD_HandleTypeDef::Instance.
Referenced by HAL_HCD_IRQHandler().