STM32F107xC HAL User Manual: FLAG_Management
FLAG_Management
RTC Exported Functions
Functions
__STATIC_INLINE uint32_t LL_RTC_IsActiveFlag_TAMPI (BKP_TypeDef *BKPx)
Get RTC_TAMPI Interruption detection flag.
__STATIC_INLINE void LL_RTC_ClearFlag_TAMPI (BKP_TypeDef *BKPx)
Clear RTC_TAMP Interruption detection flag.
__STATIC_INLINE uint32_t LL_RTC_IsActiveFlag_TAMPE (BKP_TypeDef *BKPx)
Get RTC_TAMPE Event detection flag.
__STATIC_INLINE void LL_RTC_ClearFlag_TAMPE (BKP_TypeDef *BKPx)
Clear RTC_TAMPE Even detection flag.
__STATIC_INLINE uint32_t LL_RTC_IsActiveFlag_ALR (RTC_TypeDef *RTCx)
Get Alarm flag.
__STATIC_INLINE void LL_RTC_ClearFlag_ALR (RTC_TypeDef *RTCx)
Clear Alarm flag.
__STATIC_INLINE uint32_t LL_RTC_IsActiveFlag_RS (RTC_TypeDef *RTCx)
Get Registers synchronization flag.
__STATIC_INLINE void LL_RTC_ClearFlag_RS (RTC_TypeDef *RTCx)
Clear Registers synchronization flag.
__STATIC_INLINE uint32_t LL_RTC_IsActiveFlag_OW (RTC_TypeDef *RTCx)
Get Registers OverFlow flag.
__STATIC_INLINE void LL_RTC_ClearFlag_OW (RTC_TypeDef *RTCx)
Clear Registers OverFlow flag.
__STATIC_INLINE uint32_t LL_RTC_IsActiveFlag_SEC (RTC_TypeDef *RTCx)
Get Registers synchronization flag.
__STATIC_INLINE void LL_RTC_ClearFlag_SEC (RTC_TypeDef *RTCx)
Clear Registers synchronization flag.
__STATIC_INLINE uint32_t LL_RTC_IsActiveFlag_RTOF (RTC_TypeDef *RTCx)
Get RTC Operation OFF status flag.
Function Documentation
__STATIC_INLINE void LL_RTC_ClearFlag_ALR (RTC_TypeDef * RTCx)
Clear Alarm flag.
Reference Manual to LL API cross reference:
CRL ALRF LL_RTC_ClearFlag_ALR
Parameters:
RTCx RTC Instance
Return values:
None
Definition at line 725 of file stm32f1xx_ll_rtc.h.
Referenced by LL_RTC_Init().
__STATIC_INLINE void LL_RTC_ClearFlag_OW (RTC_TypeDef * RTCx)
Clear Registers OverFlow flag.
Reference Manual to LL API cross reference:
CRL OWF LL_RTC_ClearFlag_OW
Parameters:
RTCx RTC Instance
Return values:
None
Definition at line 769 of file stm32f1xx_ll_rtc.h.
Referenced by LL_RTC_Init().
__STATIC_INLINE void LL_RTC_ClearFlag_RS (RTC_TypeDef * RTCx)
Clear Registers synchronization flag.
Reference Manual to LL API cross reference:
CRL RSF LL_RTC_ClearFlag_RS
Parameters:
RTCx RTC Instance
Return values:
None
Definition at line 747 of file stm32f1xx_ll_rtc.h.
Referenced by LL_RTC_DeInit(), and LL_RTC_WaitForSynchro().
__STATIC_INLINE void LL_RTC_ClearFlag_SEC (RTC_TypeDef * RTCx)
Clear Registers synchronization flag.
Reference Manual to LL API cross reference:
CRL SECF LL_RTC_ClearFlag_SEC
Parameters:
RTCx RTC Instance
Return values:
None
Definition at line 791 of file stm32f1xx_ll_rtc.h.
Referenced by LL_RTC_Init().
__STATIC_INLINE void LL_RTC_ClearFlag_TAMPE (BKP_TypeDef * BKPx)
Clear RTC_TAMPE Even detection flag.
Reference Manual to LL API cross reference:
CSR CTE LL_RTC_ClearFlag_TAMPE
Parameters:
BKPx BKP Instance
Return values:
None
Definition at line 703 of file stm32f1xx_ll_rtc.h.
__STATIC_INLINE void LL_RTC_ClearFlag_TAMPI (BKP_TypeDef * BKPx)
Clear RTC_TAMP Interruption detection flag.
Reference Manual to LL API cross reference:
CSR CTI LL_RTC_ClearFlag_TAMPI
Parameters:
BKPx BKP Instance
Return values:
None
Definition at line 681 of file stm32f1xx_ll_rtc.h.
__STATIC_INLINE uint32_t LL_RTC_IsActiveFlag_ALR (RTC_TypeDef * RTCx)
Get Alarm flag.
Reference Manual to LL API cross reference:
CRL ALRF LL_RTC_IsActiveFlag_ALR
Parameters:
RTCx RTC Instance
Return values:
State of bit (1 or 0).
Definition at line 714 of file stm32f1xx_ll_rtc.h.
__STATIC_INLINE uint32_t LL_RTC_IsActiveFlag_OW (RTC_TypeDef * RTCx)
Get Registers OverFlow flag.
Reference Manual to LL API cross reference:
CRL OWF LL_RTC_IsActiveFlag_OW
Parameters:
RTCx RTC Instance
Return values:
State of bit (1 or 0).
Definition at line 758 of file stm32f1xx_ll_rtc.h.
__STATIC_INLINE uint32_t LL_RTC_IsActiveFlag_RS (RTC_TypeDef * RTCx)
Get Registers synchronization flag.
Reference Manual to LL API cross reference:
CRL RSF LL_RTC_IsActiveFlag_RS
Parameters:
RTCx RTC Instance
Return values:
State of bit (1 or 0).
Definition at line 736 of file stm32f1xx_ll_rtc.h.
Referenced by LL_RTC_WaitForSynchro().
__STATIC_INLINE uint32_t LL_RTC_IsActiveFlag_RTOF (RTC_TypeDef * RTCx)
Get RTC Operation OFF status flag.
Reference Manual to LL API cross reference:
CRL RTOFF LL_RTC_IsActiveFlag_RTOF
Parameters:
RTCx RTC Instance
Return values:
State of bit (1 or 0).
Definition at line 802 of file stm32f1xx_ll_rtc.h.
Referenced by LL_RTC_EnterInitMode(), and LL_RTC_ExitInitMode().
__STATIC_INLINE uint32_t LL_RTC_IsActiveFlag_SEC (RTC_TypeDef * RTCx)
Get Registers synchronization flag.
Reference Manual to LL API cross reference:
CRL SECF LL_RTC_IsActiveFlag_SEC
Parameters:
RTCx RTC Instance
Return values:
State of bit (1 or 0).
Definition at line 780 of file stm32f1xx_ll_rtc.h.
__STATIC_INLINE uint32_t LL_RTC_IsActiveFlag_TAMPE (BKP_TypeDef * BKPx)
Get RTC_TAMPE Event detection flag.
Reference Manual to LL API cross reference:
CSR TEF LL_RTC_IsActiveFlag_TAMPE
Parameters:
BKPx BKP Instance
Return values:
State of bit (1 or 0).
Definition at line 692 of file stm32f1xx_ll_rtc.h.
__STATIC_INLINE uint32_t LL_RTC_IsActiveFlag_TAMPI (BKP_TypeDef * BKPx)
Get RTC_TAMPI Interruption detection flag.
Reference Manual to LL API cross reference:
CSR TIF LL_RTC_IsActiveFlag_TAMPI
Parameters:
BKPx BKP Instance
Return values:
State of bit (1 or 0).
Definition at line 670 of file stm32f1xx_ll_rtc.h.