STM32F107xC HAL User Manual: PCD Private Functions
PCD Private Functions
PCD
Functions
static HAL_StatusTypeDef PCD_WriteEmptyTxFifo (PCD_HandleTypeDef *hpcd, uint32_t epnum)
Check FIFO for the next packet to be loaded.
static HAL_StatusTypeDef PCD_EP_OutXfrComplete_int (PCD_HandleTypeDef *hpcd, uint32_t epnum)
process EP OUT transfer complete interrupt.
static HAL_StatusTypeDef PCD_EP_OutSetupPacket_int (PCD_HandleTypeDef *hpcd, uint32_t epnum)
process EP OUT setup packet received interrupt.
Function Documentation
static HAL_StatusTypeDef PCD_EP_OutSetupPacket_int (PCD_HandleTypeDef * hpcd, uint32_t epnum) [static]
process EP OUT setup packet received interrupt.
Parameters:
hpcd PCD handle
epnum endpoint number
Return values:
HAL status
Definition at line 1963 of file stm32f1xx_hal_pcd.c.
References HAL_PCD_SetupStageCallback(), and PCD_HandleTypeDef::Instance.
Referenced by HAL_PCD_IRQHandler().
static HAL_StatusTypeDef PCD_EP_OutXfrComplete_int (PCD_HandleTypeDef * hpcd, uint32_t epnum) [static]
process EP OUT transfer complete interrupt.
Parameters:
hpcd PCD handle
epnum endpoint number
Return values:
HAL status
Definition at line 1916 of file stm32f1xx_hal_pcd.c.
References HAL_PCD_DataOutStageCallback(), and PCD_HandleTypeDef::Instance.
Referenced by HAL_PCD_IRQHandler().
static HAL_StatusTypeDef PCD_WriteEmptyTxFifo (PCD_HandleTypeDef * hpcd, uint32_t epnum) [static]
Check FIFO for the next packet to be loaded.
Parameters:
hpcd PCD handle
epnum endpoint number
Return values:
HAL status
Definition at line 1857 of file stm32f1xx_hal_pcd.c.
References PCD_HandleTypeDef::IN_ep, and PCD_HandleTypeDef::Instance.
Referenced by HAL_PCD_IRQHandler().