STM32F107xC HAL User Manual: Initialization and de-initialization functions
Initialization and de-initialization functions
I2S Exported Functions
Initialization and Configuration functions.
Functions
HAL_StatusTypeDef HAL_I2S_Init (I2S_HandleTypeDef *hi2s)
Initializes the I2S according to the specified parameters in the I2S_InitTypeDef and create the associated handle.
HAL_StatusTypeDef HAL_I2S_DeInit (I2S_HandleTypeDef *hi2s)
DeInitializes the I2S peripheral.
__weak void HAL_I2S_MspInit (I2S_HandleTypeDef *hi2s)
I2S MSP Init.
__weak void HAL_I2S_MspDeInit (I2S_HandleTypeDef *hi2s)
I2S MSP DeInit.
Detailed Description
Initialization and Configuration functions.
 ===============================================================================
              ##### Initialization and de-initialization functions #####
 ===============================================================================
    [..]  This subsection provides a set of functions allowing to initialize and
          de-initialize the I2Sx peripheral in simplex mode:
      (+) User must Implement HAL_I2S_MspInit() function in which he configures
          all related peripherals resources (CLOCK, GPIO, DMA, IT and NVIC ).
      (+) Call the function HAL_I2S_Init() to configure the selected device with
          the selected configuration:
        (++) Mode
        (++) Standard
        (++) Data Format
        (++) MCLK Output
        (++) Audio frequency
        (++) Polarity
     (+) Call the function HAL_I2S_DeInit() to restore the default configuration
          of the selected I2Sx peripheral.
Function Documentation
HAL_StatusTypeDef HAL_I2S_DeInit (I2S_HandleTypeDef * hi2s)
DeInitializes the I2S peripheral.
Parameters:
hi2s pointer to a I2S_HandleTypeDef structure that contains the configuration information for I2S module
Return values:
HAL status
Definition at line 442 of file stm32f1xx_hal_i2s.c.
References __HAL_I2S_DISABLE, assert_param, I2S_HandleTypeDef::ErrorCode, HAL_I2S_ERROR_NONE, HAL_I2S_MspDeInit(), HAL_I2S_STATE_BUSY, HAL_I2S_STATE_RESET, I2S_HandleTypeDef::Instance, and I2S_HandleTypeDef::State.
HAL_StatusTypeDef HAL_I2S_Init (I2S_HandleTypeDef * hi2s)
Initializes the I2S according to the specified parameters in the I2S_InitTypeDef and create the associated handle.
Parameters:
hi2s pointer to a I2S_HandleTypeDef structure that contains the configuration information for I2S module
Return values:
HAL status
Definition at line 264 of file stm32f1xx_hal_i2s.c.
References assert_param, I2S_InitTypeDef::AudioFreq, I2S_InitTypeDef::CPOL, I2S_InitTypeDef::DataFormat, I2S_HandleTypeDef::ErrorCode, HAL_I2S_ERROR_NONE, HAL_I2S_ERROR_PRESCALER, HAL_I2S_ErrorCallback(), HAL_I2S_MspInit(), HAL_I2S_RxCpltCallback(), HAL_I2S_RxHalfCpltCallback(), HAL_I2S_STATE_BUSY, HAL_I2S_STATE_READY, HAL_I2S_STATE_RESET, HAL_I2S_TxCpltCallback(), HAL_I2S_TxHalfCpltCallback(), HAL_RCC_GetSysClockFreq(), HAL_RCCEx_GetPeriphCLKFreq(), I2S_AUDIOFREQ_DEFAULT, I2S_DATAFORMAT_16B, I2S_MCLKOUTPUT_ENABLE, I2S_STANDARD_LSB, I2S_STANDARD_PCM_LONG, I2S_STANDARD_PCM_SHORT, I2S_HandleTypeDef::Init, I2S_HandleTypeDef::Instance, IS_I2S_AUDIO_FREQ, IS_I2S_CPOL, IS_I2S_DATA_FORMAT, IS_I2S_MCLK_OUTPUT, IS_I2S_MODE, IS_I2S_STANDARD, I2S_HandleTypeDef::Lock, I2S_InitTypeDef::MCLKOutput, I2S_InitTypeDef::Mode, RCC_PERIPHCLK_I2S2, RCC_PERIPHCLK_I2S3, I2S_InitTypeDef::Standard, and I2S_HandleTypeDef::State.
void HAL_I2S_MspDeInit (I2S_HandleTypeDef * hi2s)
I2S MSP DeInit.
Parameters:
hi2s pointer to a I2S_HandleTypeDef structure that contains the configuration information for I2S module
Return values:
None
Definition at line 502 of file stm32f1xx_hal_i2s.c.
Referenced by HAL_I2S_DeInit().
void HAL_I2S_MspInit (I2S_HandleTypeDef * hi2s)
I2S MSP Init.
Parameters:
hi2s pointer to a I2S_HandleTypeDef structure that contains the configuration information for I2S module
Return values:
None
Definition at line 486 of file stm32f1xx_hal_i2s.c.
Referenced by HAL_I2S_Init().