STM32F107xC HAL User Manual: Initialization and de-initialization functions
Initialization and de-initialization functions
CAN Exported Functions
Initialization and Configuration functions.
Functions
HAL_StatusTypeDef HAL_CAN_Init (CAN_HandleTypeDef *hcan)
Initializes the CAN peripheral according to the specified parameters in the CAN_InitStruct.
HAL_StatusTypeDef HAL_CAN_DeInit (CAN_HandleTypeDef *hcan)
Deinitializes the CAN peripheral registers to their default reset values.
__weak void HAL_CAN_MspInit (CAN_HandleTypeDef *hcan)
Initializes the CAN MSP.
__weak void HAL_CAN_MspDeInit (CAN_HandleTypeDef *hcan)
DeInitializes the CAN MSP.
Detailed Description
Initialization and Configuration functions.
  ==============================================================================
              ##### Initialization and de-initialization functions #####
  ==============================================================================
    [..]  This section provides functions allowing to:
      (+) HAL_CAN_Init                       : Initialize and configure the CAN.
      (+) HAL_CAN_DeInit                     : De-initialize the CAN.
      (+) HAL_CAN_MspInit                    : Initialize the CAN MSP.
      (+) HAL_CAN_MspDeInit                  : DeInitialize the CAN MSP.
Function Documentation
HAL_StatusTypeDef HAL_CAN_DeInit (CAN_HandleTypeDef * hcan)
Deinitializes the CAN peripheral registers to their default reset values.
Parameters:
hcan pointer to a CAN_HandleTypeDef structure that contains the configuration information for the specified CAN.
Return values:
HAL status
Definition at line 459 of file stm32f1xx_hal_can.c.
References assert_param, __CAN_HandleTypeDef::ErrorCode, HAL_CAN_ERROR_NONE, HAL_CAN_MspDeInit(), HAL_CAN_STATE_RESET, HAL_CAN_Stop(), __CAN_HandleTypeDef::Instance, and __CAN_HandleTypeDef::State.
HAL_StatusTypeDef HAL_CAN_Init (CAN_HandleTypeDef * hcan)
Initializes the CAN peripheral according to the specified parameters in the CAN_InitStruct.
Parameters:
hcan pointer to a CAN_HandleTypeDef structure that contains the configuration information for the specified CAN.
Return values:
HAL status
Definition at line 274 of file stm32f1xx_hal_can.c.
References assert_param, CAN_InitTypeDef::AutoBusOff, CAN_InitTypeDef::AutoRetransmission, CAN_InitTypeDef::AutoWakeUp, CAN_TIMEOUT_VALUE, __CAN_HandleTypeDef::ErrorCode, HAL_CAN_ERROR_NONE, HAL_CAN_ERROR_TIMEOUT, HAL_CAN_ErrorCallback(), HAL_CAN_MspInit(), HAL_CAN_RxFifo0FullCallback(), HAL_CAN_RxFifo0MsgPendingCallback(), HAL_CAN_RxFifo1FullCallback(), HAL_CAN_RxFifo1MsgPendingCallback(), HAL_CAN_SleepCallback(), HAL_CAN_STATE_ERROR, HAL_CAN_STATE_READY, HAL_CAN_STATE_RESET, HAL_CAN_TxMailbox0AbortCallback(), HAL_CAN_TxMailbox0CompleteCallback(), HAL_CAN_TxMailbox1AbortCallback(), HAL_CAN_TxMailbox1CompleteCallback(), HAL_CAN_TxMailbox2AbortCallback(), HAL_CAN_TxMailbox2CompleteCallback(), HAL_CAN_WakeUpFromRxMsgCallback(), HAL_GetTick(), __CAN_HandleTypeDef::Init, __CAN_HandleTypeDef::Instance, IS_CAN_BS1, IS_CAN_BS2, IS_CAN_MODE, IS_CAN_PRESCALER, IS_CAN_SJW, CAN_InitTypeDef::Mode, CAN_InitTypeDef::Prescaler, CAN_InitTypeDef::ReceiveFifoLocked, __CAN_HandleTypeDef::State, CAN_InitTypeDef::SyncJumpWidth, CAN_InitTypeDef::TimeSeg1, CAN_InitTypeDef::TimeSeg2, CAN_InitTypeDef::TimeTriggeredMode, and CAN_InitTypeDef::TransmitFifoPriority.
void HAL_CAN_MspDeInit (CAN_HandleTypeDef * hcan)
DeInitializes the CAN MSP.
Parameters:
hcan pointer to a CAN_HandleTypeDef structure that contains the configuration information for the specified CAN.
Return values:
None
Definition at line 522 of file stm32f1xx_hal_can.c.
Referenced by HAL_CAN_DeInit().
void HAL_CAN_MspInit (CAN_HandleTypeDef * hcan)
Initializes the CAN MSP.
Parameters:
hcan pointer to a CAN_HandleTypeDef structure that contains the configuration information for the specified CAN.
Return values:
None
Definition at line 506 of file stm32f1xx_hal_can.c.
Referenced by HAL_CAN_Init().