STM32F107xC HAL User Manual: TIM Callbacks functions
TIM Callbacks functions
TIM Exported Functions
TIM Callbacks functions.
Functions
__weak void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef *htim)
Period elapsed callback in non-blocking mode.
__weak void HAL_TIM_PeriodElapsedHalfCpltCallback (TIM_HandleTypeDef *htim)
Period elapsed half complete callback in non-blocking mode.
__weak void HAL_TIM_OC_DelayElapsedCallback (TIM_HandleTypeDef *htim)
Output Compare callback in non-blocking mode.
__weak void HAL_TIM_IC_CaptureCallback (TIM_HandleTypeDef *htim)
Input Capture callback in non-blocking mode.
__weak void HAL_TIM_IC_CaptureHalfCpltCallback (TIM_HandleTypeDef *htim)
Input Capture half complete callback in non-blocking mode.
__weak void HAL_TIM_PWM_PulseFinishedCallback (TIM_HandleTypeDef *htim)
PWM Pulse finished callback in non-blocking mode.
__weak void HAL_TIM_PWM_PulseFinishedHalfCpltCallback (TIM_HandleTypeDef *htim)
PWM Pulse finished half complete callback in non-blocking mode.
__weak void HAL_TIM_TriggerCallback (TIM_HandleTypeDef *htim)
Hall Trigger detection callback in non-blocking mode.
__weak void HAL_TIM_TriggerHalfCpltCallback (TIM_HandleTypeDef *htim)
Hall Trigger detection half complete callback in non-blocking mode.
__weak void HAL_TIM_ErrorCallback (TIM_HandleTypeDef *htim)
Timer error callback in non-blocking mode.
Detailed Description
TIM Callbacks functions.
  ==============================================================================
                        ##### TIM Callbacks functions #####
  ==============================================================================
 [..]
   This section provides TIM callback functions:
   (+) TIM Period elapsed callback
   (+) TIM Output Compare callback
   (+) TIM Input capture callback
   (+) TIM Trigger callback
   (+) TIM Error callback
Function Documentation
void HAL_TIM_ErrorCallback (TIM_HandleTypeDef * htim)
Timer error callback in non-blocking mode.
Parameters:
htim TIM handle
Return values:
None
Definition at line 4966 of file stm32f1xx_hal_tim.c.
Referenced by TIM_DMAError().
void HAL_TIM_IC_CaptureCallback (TIM_HandleTypeDef * htim)
Input Capture callback in non-blocking mode.
Parameters:
htim TIM IC handle
Return values:
None
Definition at line 4876 of file stm32f1xx_hal_tim.c.
Referenced by HAL_TIM_IRQHandler(), and TIM_DMACaptureCplt().
void HAL_TIM_IC_CaptureHalfCpltCallback (TIM_HandleTypeDef * htim)
Input Capture half complete callback in non-blocking mode.
Parameters:
htim TIM IC handle
Return values:
None
Definition at line 4891 of file stm32f1xx_hal_tim.c.
Referenced by TIM_DMACaptureHalfCplt().
void HAL_TIM_OC_DelayElapsedCallback (TIM_HandleTypeDef * htim)
Output Compare callback in non-blocking mode.
Parameters:
htim TIM OC handle
Return values:
None
Definition at line 4861 of file stm32f1xx_hal_tim.c.
Referenced by HAL_TIM_IRQHandler().
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef * htim)
Period elapsed callback in non-blocking mode.
Parameters:
htim TIM handle
Return values:
None
Definition at line 4831 of file stm32f1xx_hal_tim.c.
Referenced by HAL_TIM_IRQHandler(), and TIM_DMAPeriodElapsedCplt().
void HAL_TIM_PeriodElapsedHalfCpltCallback (TIM_HandleTypeDef * htim)
Period elapsed half complete callback in non-blocking mode.
Parameters:
htim TIM handle
Return values:
None
Definition at line 4846 of file stm32f1xx_hal_tim.c.
Referenced by TIM_DMAPeriodElapsedHalfCplt().
void HAL_TIM_PWM_PulseFinishedCallback (TIM_HandleTypeDef * htim)
PWM Pulse finished callback in non-blocking mode.
Parameters:
htim TIM handle
Return values:
None
Definition at line 4906 of file stm32f1xx_hal_tim.c.
Referenced by HAL_TIM_IRQHandler(), and TIM_DMADelayPulseCplt().
void HAL_TIM_PWM_PulseFinishedHalfCpltCallback (TIM_HandleTypeDef * htim)
PWM Pulse finished half complete callback in non-blocking mode.
Parameters:
htim TIM handle
Return values:
None
Definition at line 4921 of file stm32f1xx_hal_tim.c.
Referenced by TIM_DMADelayPulseHalfCplt().
void HAL_TIM_TriggerCallback (TIM_HandleTypeDef * htim)
Hall Trigger detection callback in non-blocking mode.
Parameters:
htim TIM handle
Return values:
None
Definition at line 4936 of file stm32f1xx_hal_tim.c.
Referenced by HAL_TIM_IRQHandler(), and TIM_DMATriggerCplt().
void HAL_TIM_TriggerHalfCpltCallback (TIM_HandleTypeDef * htim)
Hall Trigger detection half complete callback in non-blocking mode.
Parameters:
htim TIM handle
Return values:
None
Definition at line 4951 of file stm32f1xx_hal_tim.c.
Referenced by TIM_DMATriggerHalfCplt().