STM32F107xC HAL User Manual: Peripheral Control functions
Peripheral Control functions
ETH Exported Functions
Peripheral Control functions.
Functions
HAL_StatusTypeDef HAL_ETH_Start (ETH_HandleTypeDef *heth)
Enables Ethernet MAC and DMA reception/transmission.
HAL_StatusTypeDef HAL_ETH_Stop (ETH_HandleTypeDef *heth)
Stop Ethernet MAC and DMA reception/transmission.
HAL_StatusTypeDef HAL_ETH_ConfigMAC (ETH_HandleTypeDef *heth, ETH_MACInitTypeDef *macconf)
Set ETH MAC Configuration.
HAL_StatusTypeDef HAL_ETH_ConfigDMA (ETH_HandleTypeDef *heth, ETH_DMAInitTypeDef *dmaconf)
Sets ETH DMA Configuration.
Detailed Description
Peripheral Control functions.
 ===============================================================================
                  ##### Peripheral Control functions #####
 ===============================================================================
    [..]  This section provides functions allowing to:
      (+) Enable MAC and DMA transmission and reception.
          HAL_ETH_Start();
      (+) Disable MAC and DMA transmission and reception.
          HAL_ETH_Stop();
      (+) Set the MAC configuration in runtime mode
          HAL_ETH_ConfigMAC();
      (+) Set the DMA configuration in runtime mode
          HAL_ETH_ConfigDMA();
Function Documentation
HAL_StatusTypeDef HAL_ETH_ConfigDMA (ETH_HandleTypeDef * heth, ETH_DMAInitTypeDef * dmaconf)
Sets ETH DMA Configuration.
Parameters:
heth,: pointer to a ETH_HandleTypeDef structure that contains the configuration information for ETHERNET module
dmaconf,: DMA Configuration structure
Return values:
HAL status
Definition at line 1693 of file stm32f1xx_hal_eth.c.
References ETH_DMAInitTypeDef::AddressAlignedBeats, assert_param, ETH_DMAInitTypeDef::DescriptorSkipLength, ETH_DMAInitTypeDef::DMAArbitration, ETH_DMAInitTypeDef::DropTCPIPChecksumErrorFrame, ETH_DMAOMR_CLEAR_MASK, ETH_REG_WRITE_DELAY, ETH_DMAInitTypeDef::FixedBurst, ETH_DMAInitTypeDef::FlushReceivedFrame, ETH_DMAInitTypeDef::ForwardErrorFrames, ETH_DMAInitTypeDef::ForwardUndersizedGoodFrames, HAL_Delay(), HAL_ETH_STATE_BUSY, HAL_ETH_STATE_READY, ETH_HandleTypeDef::Instance, IS_ETH_ADDRESS_ALIGNED_BEATS, IS_ETH_DMA_ARBITRATION_ROUNDROBIN_RXTX, IS_ETH_DMA_DESC_SKIP_LENGTH, IS_ETH_DROP_TCPIP_CHECKSUM_FRAME, IS_ETH_FIXED_BURST, IS_ETH_FLUSH_RECEIVE_FRAME, IS_ETH_FORWARD_ERROR_FRAMES, IS_ETH_FORWARD_UNDERSIZED_GOOD_FRAMES, IS_ETH_RECEIVE_STORE_FORWARD, IS_ETH_RECEIVE_THRESHOLD_CONTROL, IS_ETH_RXDMA_BURST_LENGTH, IS_ETH_SECOND_FRAME_OPERATE, IS_ETH_TRANSMIT_STORE_FORWARD, IS_ETH_TRANSMIT_THRESHOLD_CONTROL, IS_ETH_TXDMA_BURST_LENGTH, ETH_DMAInitTypeDef::ReceiveStoreForward, ETH_DMAInitTypeDef::ReceiveThresholdControl, ETH_DMAInitTypeDef::RxDMABurstLength, ETH_DMAInitTypeDef::SecondFrameOperate, ETH_HandleTypeDef::State, ETH_DMAInitTypeDef::TransmitStoreForward, ETH_DMAInitTypeDef::TransmitThresholdControl, and ETH_DMAInitTypeDef::TxDMABurstLength.
HAL_StatusTypeDef HAL_ETH_ConfigMAC (ETH_HandleTypeDef * heth, ETH_MACInitTypeDef * macconf)
Set ETH MAC Configuration.
Parameters:
heth,: pointer to a ETH_HandleTypeDef structure that contains the configuration information for ETHERNET module
macconf,: MAC Configuration structure
Return values:
HAL status
Definition at line 1526 of file stm32f1xx_hal_eth.c.
References assert_param, ETH_MACInitTypeDef::AutomaticPadCRCStrip, ETH_MACInitTypeDef::BackOffLimit, ETH_MACInitTypeDef::BroadcastFramesReception, ETH_MACInitTypeDef::CarrierSense, ETH_MACInitTypeDef::ChecksumOffload, ETH_MACInitTypeDef::DeferralCheck, ETH_MACInitTypeDef::DestinationAddrFilter, ETH_InitTypeDef::DuplexMode, ETH_MACCR_CLEAR_MASK, ETH_MACFCR_CLEAR_MASK, ETH_REG_WRITE_DELAY, HAL_Delay(), HAL_ETH_STATE_BUSY, HAL_ETH_STATE_READY, ETH_MACInitTypeDef::HashTableHigh, ETH_MACInitTypeDef::HashTableLow, ETH_HandleTypeDef::Init, ETH_HandleTypeDef::Instance, ETH_MACInitTypeDef::InterFrameGap, IS_ETH_AUTOMATIC_PADCRC_STRIP, IS_ETH_BACKOFF_LIMIT, IS_ETH_BROADCAST_FRAMES_RECEPTION, IS_ETH_CARRIER_SENSE, IS_ETH_CHECKSUM_OFFLOAD, IS_ETH_CONTROL_FRAMES, IS_ETH_DEFERRAL_CHECK, IS_ETH_DESTINATION_ADDR_FILTER, IS_ETH_DUPLEX_MODE, IS_ETH_INTER_FRAME_GAP, IS_ETH_JABBER, IS_ETH_LOOPBACK_MODE, IS_ETH_MULTICAST_FRAMES_FILTER, IS_ETH_PAUSE_LOW_THRESHOLD, IS_ETH_PAUSE_TIME, IS_ETH_PROMISCUOUS_MODE, IS_ETH_RECEIVE_ALL, IS_ETH_RECEIVE_FLOWCONTROL, IS_ETH_RECEIVE_OWN, IS_ETH_RETRY_TRANSMISSION, IS_ETH_SOURCE_ADDR_FILTER, IS_ETH_SPEED, IS_ETH_TRANSMIT_FLOWCONTROL, IS_ETH_UNICAST_FRAMES_FILTER, IS_ETH_UNICAST_PAUSE_FRAME_DETECT, IS_ETH_VLAN_TAG_COMPARISON, IS_ETH_VLAN_TAG_IDENTIFIER, IS_ETH_WATCHDOG, IS_ETH_ZEROQUANTA_PAUSE, ETH_MACInitTypeDef::Jabber, ETH_MACInitTypeDef::LoopbackMode, ETH_MACInitTypeDef::MulticastFramesFilter, ETH_MACInitTypeDef::PassControlFrames, ETH_MACInitTypeDef::PauseLowThreshold, ETH_MACInitTypeDef::PauseTime, ETH_MACInitTypeDef::PromiscuousMode, ETH_MACInitTypeDef::ReceiveAll, ETH_MACInitTypeDef::ReceiveFlowControl, ETH_MACInitTypeDef::ReceiveOwn, ETH_MACInitTypeDef::RetryTransmission, ETH_MACInitTypeDef::SourceAddrFilter, ETH_InitTypeDef::Speed, ETH_HandleTypeDef::State, ETH_MACInitTypeDef::TransmitFlowControl, ETH_MACInitTypeDef::UnicastFramesFilter, ETH_MACInitTypeDef::UnicastPauseFrameDetect, ETH_MACInitTypeDef::VLANTagComparison, ETH_MACInitTypeDef::VLANTagIdentifier, ETH_MACInitTypeDef::Watchdog, and ETH_MACInitTypeDef::ZeroQuantaPause.
HAL_StatusTypeDef HAL_ETH_Start (ETH_HandleTypeDef * heth)
Enables Ethernet MAC and DMA reception/transmission.
Parameters:
heth,: pointer to a ETH_HandleTypeDef structure that contains the configuration information for ETHERNET module
Return values:
HAL status
Definition at line 1447 of file stm32f1xx_hal_eth.c.
References ETH_DMAReceptionEnable(), ETH_DMATransmissionEnable(), ETH_FlushTransmitFIFO(), ETH_MACReceptionEnable(), ETH_MACTransmissionEnable(), HAL_ETH_STATE_BUSY, HAL_ETH_STATE_READY, and ETH_HandleTypeDef::State.
HAL_StatusTypeDef HAL_ETH_Stop (ETH_HandleTypeDef * heth)
Stop Ethernet MAC and DMA reception/transmission.
Parameters:
heth,: pointer to a ETH_HandleTypeDef structure that contains the configuration information for ETHERNET module
Return values:
HAL status
Definition at line 1486 of file stm32f1xx_hal_eth.c.
References ETH_DMAReceptionDisable(), ETH_DMATransmissionDisable(), ETH_FlushTransmitFIFO(), ETH_MACReceptionDisable(), ETH_MACTransmissionDisable(), HAL_ETH_STATE_BUSY, HAL_ETH_STATE_READY, and ETH_HandleTypeDef::State.