STM32F107xC HAL User Manual: Initialization and de-initialization functions
Initialization and de-initialization functions
HCD Exported Functions
Initialization and Configuration functions.
Functions
HAL_StatusTypeDef HAL_HCD_Init (HCD_HandleTypeDef *hhcd)
Initialize the host driver.
HAL_StatusTypeDef HAL_HCD_HC_Init (HCD_HandleTypeDef *hhcd, uint8_t ch_num, uint8_t epnum, uint8_t dev_address, uint8_t speed, uint8_t ep_type, uint16_t mps)
Initialize a host channel.
HAL_StatusTypeDef HAL_HCD_HC_Halt (HCD_HandleTypeDef *hhcd, uint8_t ch_num)
Halt a host channel.
HAL_StatusTypeDef HAL_HCD_DeInit (HCD_HandleTypeDef *hhcd)
DeInitialize the host driver.
__weak void HAL_HCD_MspInit (HCD_HandleTypeDef *hhcd)
Initialize the HCD MSP.
__weak void HAL_HCD_MspDeInit (HCD_HandleTypeDef *hhcd)
DeInitialize the HCD MSP.
Detailed Description
Initialization and Configuration functions.
 ===============================================================================
          ##### Initialization and de-initialization functions #####
 ===============================================================================
    [..]  This section provides functions allowing to:
Function Documentation
HAL_StatusTypeDef HAL_HCD_DeInit (HCD_HandleTypeDef * hhcd)
DeInitialize the host driver.
Parameters:
hhcd HCD handle
Return values:
HAL status
Definition at line 261 of file stm32f1xx_hal_hcd.c.
References __HAL_HCD_DISABLE, HAL_HCD_MspDeInit(), HAL_HCD_STATE_BUSY, HAL_HCD_STATE_RESET, and HCD_HandleTypeDef::State.
HAL_StatusTypeDef HAL_HCD_HC_Halt (HCD_HandleTypeDef * hhcd, uint8_t ch_num)
Halt a host channel.
Parameters:
hhcd HCD handle
ch_num Channel number. This parameter can be a value from 1 to 15
Return values:
HAL status
Definition at line 245 of file stm32f1xx_hal_hcd.c.
References HCD_HandleTypeDef::Instance.
HAL_StatusTypeDef HAL_HCD_HC_Init (HCD_HandleTypeDef * hhcd, uint8_t ch_num, uint8_t epnum, uint8_t dev_address, uint8_t speed, uint8_t ep_type, uint16_t mps)
Initialize a host channel.
Parameters:
hhcd HCD handle
ch_num Channel number. This parameter can be a value from 1 to 15
epnum Endpoint number. This parameter can be a value from 1 to 15
dev_address Current device address This parameter can be a value from 0 to 255
speed Current device speed. This parameter can be one of these values: HCD_SPEED_FULL: Full speed mode, HCD_SPEED_LOW: Low speed mode
ep_type Endpoint Type. This parameter can be one of these values: EP_TYPE_CTRL: Control type, EP_TYPE_ISOC: Isochronous type, EP_TYPE_BULK: Bulk type, EP_TYPE_INTR: Interrupt type
mps Max Packet Size. This parameter can be a value from 0 to32K
Return values:
HAL status
Definition at line 197 of file stm32f1xx_hal_hcd.c.
References HCD_HandleTypeDef::hc, and HCD_HandleTypeDef::Instance.
HAL_StatusTypeDef HAL_HCD_Init (HCD_HandleTypeDef * hhcd)
Initialize the host driver.
Parameters:
hhcd HCD handle
Return values:
HAL status
Definition at line 108 of file stm32f1xx_hal_hcd.c.
References __HAL_HCD_DISABLE, assert_param, HAL_HCD_Connect_Callback(), HAL_HCD_Disconnect_Callback(), HAL_HCD_HC_NotifyURBChange_Callback(), HAL_HCD_MspInit(), HAL_HCD_PortDisabled_Callback(), HAL_HCD_PortEnabled_Callback(), HAL_HCD_SOF_Callback(), HAL_HCD_STATE_BUSY, HAL_HCD_STATE_READY, HAL_HCD_STATE_RESET, HCD_HandleTypeDef::Init, HCD_HandleTypeDef::Instance, HCD_HandleTypeDef::Lock, and HCD_HandleTypeDef::State.
void HAL_HCD_MspDeInit (HCD_HandleTypeDef * hhcd)
DeInitialize the HCD MSP.
Parameters:
hhcd HCD handle
Return values:
None
Definition at line 311 of file stm32f1xx_hal_hcd.c.
Referenced by HAL_HCD_DeInit().
void HAL_HCD_MspInit (HCD_HandleTypeDef * hhcd)
Initialize the HCD MSP.
Parameters:
hhcd HCD handle
Return values:
None
Definition at line 296 of file stm32f1xx_hal_hcd.c.
Referenced by HAL_HCD_Init().