STM32F100xE HAL User Manual: TIM Private Functions
TIM Private Functions
TIM
Private functions.
Functions
static ErrorStatus OC1Config (TIM_TypeDef *TIMx, LL_TIM_OC_InitTypeDef *TIM_OCInitStruct)
Configure the TIMx output channel 1.
static ErrorStatus OC2Config (TIM_TypeDef *TIMx, LL_TIM_OC_InitTypeDef *TIM_OCInitStruct)
Configure the TIMx output channel 2.
static ErrorStatus OC3Config (TIM_TypeDef *TIMx, LL_TIM_OC_InitTypeDef *TIM_OCInitStruct)
Configure the TIMx output channel 3.
static ErrorStatus OC4Config (TIM_TypeDef *TIMx, LL_TIM_OC_InitTypeDef *TIM_OCInitStruct)
Configure the TIMx output channel 4.
static ErrorStatus IC1Config (TIM_TypeDef *TIMx, LL_TIM_IC_InitTypeDef *TIM_ICInitStruct)
Configure the TIMx input channel 1.
static ErrorStatus IC2Config (TIM_TypeDef *TIMx, LL_TIM_IC_InitTypeDef *TIM_ICInitStruct)
Configure the TIMx input channel 2.
static ErrorStatus IC3Config (TIM_TypeDef *TIMx, LL_TIM_IC_InitTypeDef *TIM_ICInitStruct)
Configure the TIMx input channel 3.
static ErrorStatus IC4Config (TIM_TypeDef *TIMx, LL_TIM_IC_InitTypeDef *TIM_ICInitStruct)
Configure the TIMx input channel 4.
Detailed Description
Private functions.
Function Documentation
static ErrorStatus IC1Config (TIM_TypeDef * TIMx, LL_TIM_IC_InitTypeDef * TIM_ICInitStruct) [static]
Configure the TIMx input channel 1.
Parameters:
TIMx Timer Instance
TIM_ICInitStruct pointer to the the TIMx input channel 1 configuration data structure
Return values:
An ErrorStatus enumeration value:
SUCCESS: TIMx registers are de-initialized
ERROR: not applicable
Definition at line 1057 of file stm32f1xx_ll_tim.c.
References assert_param, LL_TIM_IC_InitTypeDef::ICActiveInput, LL_TIM_IC_InitTypeDef::ICFilter, LL_TIM_IC_InitTypeDef::ICPolarity, LL_TIM_IC_InitTypeDef::ICPrescaler, IS_LL_TIM_ACTIVEINPUT, IS_LL_TIM_IC_FILTER, IS_LL_TIM_IC_POLARITY, and IS_LL_TIM_ICPSC.
Referenced by LL_TIM_IC_Init().
static ErrorStatus IC2Config (TIM_TypeDef * TIMx, LL_TIM_IC_InitTypeDef * TIM_ICInitStruct) [static]
Configure the TIMx input channel 2.
Parameters:
TIMx Timer Instance
TIM_ICInitStruct pointer to the the TIMx input channel 2 configuration data structure
Return values:
An ErrorStatus enumeration value:
SUCCESS: TIMx registers are de-initialized
ERROR: not applicable
Definition at line 1090 of file stm32f1xx_ll_tim.c.
References assert_param, LL_TIM_IC_InitTypeDef::ICActiveInput, LL_TIM_IC_InitTypeDef::ICFilter, LL_TIM_IC_InitTypeDef::ICPolarity, LL_TIM_IC_InitTypeDef::ICPrescaler, IS_LL_TIM_ACTIVEINPUT, IS_LL_TIM_IC_FILTER, IS_LL_TIM_IC_POLARITY, and IS_LL_TIM_ICPSC.
Referenced by LL_TIM_IC_Init().
static ErrorStatus IC3Config (TIM_TypeDef * TIMx, LL_TIM_IC_InitTypeDef * TIM_ICInitStruct) [static]
Configure the TIMx input channel 3.
Parameters:
TIMx Timer Instance
TIM_ICInitStruct pointer to the the TIMx input channel 3 configuration data structure
Return values:
An ErrorStatus enumeration value:
SUCCESS: TIMx registers are de-initialized
ERROR: not applicable
Definition at line 1123 of file stm32f1xx_ll_tim.c.
References assert_param, LL_TIM_IC_InitTypeDef::ICActiveInput, LL_TIM_IC_InitTypeDef::ICFilter, LL_TIM_IC_InitTypeDef::ICPolarity, LL_TIM_IC_InitTypeDef::ICPrescaler, IS_LL_TIM_ACTIVEINPUT, IS_LL_TIM_IC_FILTER, IS_LL_TIM_IC_POLARITY, and IS_LL_TIM_ICPSC.
Referenced by LL_TIM_IC_Init().
static ErrorStatus IC4Config (TIM_TypeDef * TIMx, LL_TIM_IC_InitTypeDef * TIM_ICInitStruct) [static]
Configure the TIMx input channel 4.
Parameters:
TIMx Timer Instance
TIM_ICInitStruct pointer to the the TIMx input channel 4 configuration data structure
Return values:
An ErrorStatus enumeration value:
SUCCESS: TIMx registers are de-initialized
ERROR: not applicable
Definition at line 1156 of file stm32f1xx_ll_tim.c.
References assert_param, LL_TIM_IC_InitTypeDef::ICActiveInput, LL_TIM_IC_InitTypeDef::ICFilter, LL_TIM_IC_InitTypeDef::ICPolarity, LL_TIM_IC_InitTypeDef::ICPrescaler, IS_LL_TIM_ACTIVEINPUT, IS_LL_TIM_IC_FILTER, IS_LL_TIM_IC_POLARITY, and IS_LL_TIM_ICPSC.
Referenced by LL_TIM_IC_Init().
static ErrorStatus OC1Config (TIM_TypeDef * TIMx, LL_TIM_OC_InitTypeDef * TIM_OCInitStruct) [static]
Configure the TIMx output channel 1.
Parameters:
TIMx Timer Instance
TIM_OCInitStruct pointer to the the TIMx output channel 1 configuration data structure
Return values:
An ErrorStatus enumeration value:
SUCCESS: TIMx registers are de-initialized
ERROR: not applicable
Definition at line 749 of file stm32f1xx_ll_tim.c.
References assert_param, LL_TIM_OC_InitTypeDef::CompareValue, IS_LL_TIM_OCIDLESTATE, IS_LL_TIM_OCMODE, IS_LL_TIM_OCPOLARITY, IS_LL_TIM_OCSTATE, LL_TIM_OC_SetCompareCH1(), LL_TIM_ReadReg, LL_TIM_WriteReg, LL_TIM_OC_InitTypeDef::OCIdleState, LL_TIM_OC_InitTypeDef::OCMode, LL_TIM_OC_InitTypeDef::OCNIdleState, LL_TIM_OC_InitTypeDef::OCNPolarity, LL_TIM_OC_InitTypeDef::OCNState, LL_TIM_OC_InitTypeDef::OCPolarity, and LL_TIM_OC_InitTypeDef::OCState.
Referenced by LL_TIM_OC_Init().
static ErrorStatus OC2Config (TIM_TypeDef * TIMx, LL_TIM_OC_InitTypeDef * TIM_OCInitStruct) [static]
Configure the TIMx output channel 2.
Parameters:
TIMx Timer Instance
TIM_OCInitStruct pointer to the the TIMx output channel 2 configuration data structure
Return values:
An ErrorStatus enumeration value:
SUCCESS: TIMx registers are de-initialized
ERROR: not applicable
Definition at line 828 of file stm32f1xx_ll_tim.c.
References assert_param, LL_TIM_OC_InitTypeDef::CompareValue, IS_LL_TIM_OCIDLESTATE, IS_LL_TIM_OCMODE, IS_LL_TIM_OCPOLARITY, IS_LL_TIM_OCSTATE, LL_TIM_OC_SetCompareCH2(), LL_TIM_ReadReg, LL_TIM_WriteReg, LL_TIM_OC_InitTypeDef::OCIdleState, LL_TIM_OC_InitTypeDef::OCMode, LL_TIM_OC_InitTypeDef::OCNIdleState, LL_TIM_OC_InitTypeDef::OCNPolarity, LL_TIM_OC_InitTypeDef::OCNState, LL_TIM_OC_InitTypeDef::OCPolarity, and LL_TIM_OC_InitTypeDef::OCState.
Referenced by LL_TIM_OC_Init().
static ErrorStatus OC3Config (TIM_TypeDef * TIMx, LL_TIM_OC_InitTypeDef * TIM_OCInitStruct) [static]
Configure the TIMx output channel 3.
Parameters:
TIMx Timer Instance
TIM_OCInitStruct pointer to the the TIMx output channel 3 configuration data structure
Return values:
An ErrorStatus enumeration value:
SUCCESS: TIMx registers are de-initialized
ERROR: not applicable
Definition at line 907 of file stm32f1xx_ll_tim.c.
References assert_param, LL_TIM_OC_InitTypeDef::CompareValue, IS_LL_TIM_OCIDLESTATE, IS_LL_TIM_OCMODE, IS_LL_TIM_OCPOLARITY, IS_LL_TIM_OCSTATE, LL_TIM_OC_SetCompareCH3(), LL_TIM_ReadReg, LL_TIM_WriteReg, LL_TIM_OC_InitTypeDef::OCIdleState, LL_TIM_OC_InitTypeDef::OCMode, LL_TIM_OC_InitTypeDef::OCNIdleState, LL_TIM_OC_InitTypeDef::OCNPolarity, LL_TIM_OC_InitTypeDef::OCNState, LL_TIM_OC_InitTypeDef::OCPolarity, and LL_TIM_OC_InitTypeDef::OCState.
Referenced by LL_TIM_OC_Init().
static ErrorStatus OC4Config (TIM_TypeDef * TIMx, LL_TIM_OC_InitTypeDef * TIM_OCInitStruct) [static]
Configure the TIMx output channel 4.
Parameters:
TIMx Timer Instance
TIM_OCInitStruct pointer to the the TIMx output channel 4 configuration data structure
Return values:
An ErrorStatus enumeration value:
SUCCESS: TIMx registers are de-initialized
ERROR: not applicable
Definition at line 986 of file stm32f1xx_ll_tim.c.
References assert_param, LL_TIM_OC_InitTypeDef::CompareValue, IS_LL_TIM_OCIDLESTATE, IS_LL_TIM_OCMODE, IS_LL_TIM_OCPOLARITY, IS_LL_TIM_OCSTATE, LL_TIM_OC_SetCompareCH4(), LL_TIM_ReadReg, LL_TIM_WriteReg, LL_TIM_OC_InitTypeDef::OCIdleState, LL_TIM_OC_InitTypeDef::OCMode, LL_TIM_OC_InitTypeDef::OCNIdleState, LL_TIM_OC_InitTypeDef::OCNPolarity, LL_TIM_OC_InitTypeDef::OCNState, LL_TIM_OC_InitTypeDef::OCPolarity, and LL_TIM_OC_InitTypeDef::OCState.
Referenced by LL_TIM_OC_Init().