STM32F100xE HAL User Manual: HSI
HSI
RCC Exported Functions
Functions
__STATIC_INLINE void LL_RCC_HSI_Enable (void)
Enable HSI oscillator.
__STATIC_INLINE void LL_RCC_HSI_Disable (void)
Disable HSI oscillator.
__STATIC_INLINE uint32_t LL_RCC_HSI_IsReady (void)
Check if HSI clock is ready.
__STATIC_INLINE uint32_t LL_RCC_HSI_GetCalibration (void)
Get HSI Calibration value.
__STATIC_INLINE void LL_RCC_HSI_SetCalibTrimming (uint32_t Value)
Set HSI Calibration trimming.
__STATIC_INLINE uint32_t LL_RCC_HSI_GetCalibTrimming (void)
Get HSI Calibration trimming.
Function Documentation
__STATIC_INLINE void LL_RCC_HSI_Disable (void)
Disable HSI oscillator.
Reference Manual to LL API cross reference:
CR HSION LL_RCC_HSI_Disable
Return values:
None
Definition at line 850 of file stm32f1xx_ll_rcc.h.
__STATIC_INLINE void LL_RCC_HSI_Enable (void)
Enable HSI oscillator.
Reference Manual to LL API cross reference:
CR HSION LL_RCC_HSI_Enable
Return values:
None
Definition at line 840 of file stm32f1xx_ll_rcc.h.
Referenced by LL_PLL_ConfigSystemClock_HSI(), and LL_RCC_DeInit().
__STATIC_INLINE uint32_t LL_RCC_HSI_GetCalibration (void)
Get HSI Calibration value.
Note:
When HSITRIM is written, HSICAL is updated with the sum of HSITRIM and the factory trim value
Reference Manual to LL API cross reference:
CR HSICAL LL_RCC_HSI_GetCalibration
Return values:
Between Min_Data = 0x00 and Max_Data = 0xFF
Definition at line 872 of file stm32f1xx_ll_rcc.h.
__STATIC_INLINE uint32_t LL_RCC_HSI_GetCalibTrimming (void)
Get HSI Calibration trimming.
Reference Manual to LL API cross reference:
CR HSITRIM LL_RCC_HSI_GetCalibTrimming
Return values:
Between Min_Data = 0x00 and Max_Data = 0x1F
Definition at line 896 of file stm32f1xx_ll_rcc.h.
__STATIC_INLINE uint32_t LL_RCC_HSI_IsReady (void)
Check if HSI clock is ready.
Reference Manual to LL API cross reference:
CR HSIRDY LL_RCC_HSI_IsReady
Return values:
State of bit (1 or 0).
Definition at line 860 of file stm32f1xx_ll_rcc.h.
Referenced by LL_PLL_ConfigSystemClock_HSI(), and LL_RCC_DeInit().
__STATIC_INLINE void LL_RCC_HSI_SetCalibTrimming (uint32_t Value)
Set HSI Calibration trimming.
Note:
user-programmable trimming value that is added to the HSICAL
Default value is 16, which, when added to the HSICAL value, should trim the HSI to 16 MHz +/- 1 %
Reference Manual to LL API cross reference:
CR HSITRIM LL_RCC_HSI_SetCalibTrimming
Parameters:
Value between Min_Data = 0x00 and Max_Data = 0x1F
Return values:
None
Definition at line 886 of file stm32f1xx_ll_rcc.h.
Referenced by LL_RCC_DeInit().