STM32F100xE HAL User Manual: Input and Output operation functions
Input and Output operation functions
CEC Exported Functions
CEC Transmit/Receive functions.
Functions
HAL_StatusTypeDef HAL_CEC_Transmit_IT (CEC_HandleTypeDef *hcec, uint8_t InitiatorAddress, uint8_t DestinationAddress, uint8_t *pData, uint32_t Size)
Send data in interrupt mode.
uint32_t HAL_CEC_GetLastReceivedFrameSize (CEC_HandleTypeDef *hcec)
Get size of the received frame.
void HAL_CEC_ChangeRxBuffer (CEC_HandleTypeDef *hcec, uint8_t *Rxbuffer)
Change Rx Buffer.
void HAL_CEC_IRQHandler (CEC_HandleTypeDef *hcec)
This function handles CEC interrupt requests.
__weak void HAL_CEC_TxCpltCallback (CEC_HandleTypeDef *hcec)
Tx Transfer completed callback.
__weak void HAL_CEC_RxCpltCallback (CEC_HandleTypeDef *hcec, uint32_t RxFrameSize)
Rx Transfer completed callback.
__weak void HAL_CEC_ErrorCallback (CEC_HandleTypeDef *hcec)
CEC error callbacks.
Detailed Description
CEC Transmit/Receive functions.
 ===============================================================================
                      ##### IO operation functions #####
 ===============================================================================
    [..]
    This subsection provides a set of functions allowing to manage the CEC data transfers.
    (#) The CEC handle must contain the initiator (TX side) and the destination (RX side)
        logical addresses (4-bit long addresses, 0xF for broadcast messages destination)
    (#) The communication is performed using Interrupts.
           These API's return the HAL status.
           The end of the data processing will be indicated through the
           dedicated CEC IRQ when using Interrupt mode.
           The HAL_CEC_TxCpltCallback(), HAL_CEC_RxCpltCallback() user callbacks
           will be executed respectively at the end of the transmit or Receive process
           The HAL_CEC_ErrorCallback() user callback will be executed when a communication
           error is detected
    (#) API's with Interrupt are :
         (+) HAL_CEC_Transmit_IT()
         (+) HAL_CEC_IRQHandler()
    (#) A set of User Callbacks are provided:
         (+) HAL_CEC_TxCpltCallback()
         (+) HAL_CEC_RxCpltCallback()
         (+) HAL_CEC_ErrorCallback()
Function Documentation
void HAL_CEC_ChangeRxBuffer (CEC_HandleTypeDef * hcec, uint8_t * Rxbuffer)
Change Rx Buffer.
Parameters:
hcec,: CEC handle
Rxbuffer,: Rx Buffer
Note:
This function can be called only inside the HAL_CEC_RxCpltCallback()
Return values:
Frame size
Definition at line 725 of file stm32f1xx_hal_cec.c.
References __CEC_HandleTypeDef::Init, and CEC_InitTypeDef::RxBuffer.
void HAL_CEC_ErrorCallback (CEC_HandleTypeDef * hcec)
CEC error callbacks.
Parameters:
hcec,: CEC handle
Return values:
None
Definition at line 823 of file stm32f1xx_hal_cec.c.
Referenced by HAL_CEC_Init(), and HAL_CEC_IRQHandler().
uint32_t HAL_CEC_GetLastReceivedFrameSize (CEC_HandleTypeDef * hcec)
Get size of the received frame.
Parameters:
hcec,: CEC handle
Return values:
Frame size
Definition at line 713 of file stm32f1xx_hal_cec.c.
References __CEC_HandleTypeDef::RxXferSize.
void HAL_CEC_IRQHandler (CEC_HandleTypeDef * hcec)
This function handles CEC interrupt requests.
Parameters:
hcec,: CEC handle
Return values:
None
Definition at line 735 of file stm32f1xx_hal_cec.c.
References __HAL_CEC_CLEAR_FLAG, __HAL_CEC_GET_FLAG, CEC_ESR_ALL_ERROR, CEC_FLAG_RBTF, CEC_FLAG_RERR, CEC_FLAG_TBTRF, CEC_FLAG_TERR, CEC_Receive_IT(), CEC_Transmit_IT(), __CEC_HandleTypeDef::ErrorCode, __CEC_HandleTypeDef::gState, HAL_CEC_ErrorCallback(), HAL_CEC_STATE_BUSY_RX, HAL_CEC_STATE_READY, __CEC_HandleTypeDef::Init, __CEC_HandleTypeDef::Instance, CEC_InitTypeDef::RxBuffer, __CEC_HandleTypeDef::RxState, and __CEC_HandleTypeDef::RxXferSize.
void HAL_CEC_RxCpltCallback (CEC_HandleTypeDef * hcec, uint32_t RxFrameSize)
Rx Transfer completed callback.
Parameters:
hcec,: CEC handle
RxFrameSize,: Size of frame
Return values:
None
Definition at line 808 of file stm32f1xx_hal_cec.c.
Referenced by CEC_Receive_IT(), and HAL_CEC_Init().
HAL_StatusTypeDef HAL_CEC_Transmit_IT (CEC_HandleTypeDef * hcec, uint8_t InitiatorAddress, uint8_t DestinationAddress, uint8_t * pData, uint32_t Size)
Send data in interrupt mode.
Parameters:
hcec,: CEC handle
InitiatorAddress,: Initiator address
DestinationAddress,: destination logical address
pData,: pointer to input byte data buffer
Size,: amount of data to be sent in bytes (without counting the header). 0 means only the header is sent (ping operation). Maximum TX size is 15 bytes (1 opcode and up to 14 operands).
Return values:
HAL status
Definition at line 657 of file stm32f1xx_hal_cec.c.
References assert_param, CEC_FLAG_TEOM, CEC_FLAG_TRANSMIT_MASK, CEC_FLAG_TSOM, CEC_INITIATOR_LSB_POS, __CEC_HandleTypeDef::ErrorCode, __CEC_HandleTypeDef::gState, HAL_CEC_ERROR_NONE, HAL_CEC_STATE_BUSY_TX, HAL_CEC_STATE_READY, __CEC_HandleTypeDef::Instance, IS_CEC_ADDRESS, IS_CEC_MSGSIZE, __CEC_HandleTypeDef::pTxBuffPtr, and __CEC_HandleTypeDef::TxXferCount.
void HAL_CEC_TxCpltCallback (CEC_HandleTypeDef * hcec)
Tx Transfer completed callback.
Parameters:
hcec,: CEC handle
Return values:
None
Definition at line 793 of file stm32f1xx_hal_cec.c.
Referenced by CEC_Transmit_IT(), and HAL_CEC_Init().