STM32F100xE HAL User Manual: CEC Private Functions
CEC Private Functions
CEC
Functions
static HAL_StatusTypeDef CEC_Transmit_IT (CEC_HandleTypeDef *hcec)
Send data in interrupt mode.
static HAL_StatusTypeDef CEC_Receive_IT (CEC_HandleTypeDef *hcec)
Receive data in interrupt mode.
Function Documentation
static HAL_StatusTypeDef CEC_Receive_IT (CEC_HandleTypeDef * hcec) [static]
Receive data in interrupt mode.
Parameters:
hcec,: CEC handle. Function called under interruption only, once interruptions have been enabled by HAL_CEC_Receive_IT()
Return values:
HAL status
Definition at line 951 of file stm32f1xx_hal_cec.c.
References CEC_FLAG_RECEIVE_MASK, CEC_FLAG_REOM, HAL_CEC_RxCpltCallback(), HAL_CEC_STATE_BUSY_RX, HAL_CEC_STATE_READY, __CEC_HandleTypeDef::Init, __CEC_HandleTypeDef::Instance, CEC_InitTypeDef::RxBuffer, __CEC_HandleTypeDef::RxState, and __CEC_HandleTypeDef::RxXferSize.
Referenced by HAL_CEC_IRQHandler().
static HAL_StatusTypeDef CEC_Transmit_IT (CEC_HandleTypeDef * hcec) [static]
Send data in interrupt mode.
Parameters:
hcec,: CEC handle. Function called under interruption only, once interruptions have been enabled by HAL_CEC_Transmit_IT()
Return values:
HAL status
Definition at line 894 of file stm32f1xx_hal_cec.c.
References __HAL_CEC_GET_TRANSMISSION_START_FLAG, CEC_FLAG_TEOM, CEC_FLAG_TRANSMIT_MASK, __CEC_HandleTypeDef::gState, HAL_CEC_STATE_BUSY_TX, HAL_CEC_STATE_READY, HAL_CEC_TxCpltCallback(), __CEC_HandleTypeDef::Instance, __CEC_HandleTypeDef::pTxBuffPtr, and __CEC_HandleTypeDef::TxXferCount.
Referenced by HAL_CEC_IRQHandler().