STM32F100xE HAL User Manual: IO operation functions
IO operation functions
USART Exported Functions
USART Transmit and Receive functions.
Functions
HAL_StatusTypeDef HAL_USART_Transmit (USART_HandleTypeDef *husart, uint8_t *pTxData, uint16_t Size, uint32_t Timeout)
Simplex Send an amount of data in blocking mode.
HAL_StatusTypeDef HAL_USART_Receive (USART_HandleTypeDef *husart, uint8_t *pRxData, uint16_t Size, uint32_t Timeout)
Full-Duplex Receive an amount of data in blocking mode.
HAL_StatusTypeDef HAL_USART_TransmitReceive (USART_HandleTypeDef *husart, uint8_t *pTxData, uint8_t *pRxData, uint16_t Size, uint32_t Timeout)
Full-Duplex Send receive an amount of data in full-duplex mode (blocking mode).
HAL_StatusTypeDef HAL_USART_Transmit_IT (USART_HandleTypeDef *husart, uint8_t *pTxData, uint16_t Size)
Simplex Send an amount of data in non-blocking mode.
HAL_StatusTypeDef HAL_USART_Receive_IT (USART_HandleTypeDef *husart, uint8_t *pRxData, uint16_t Size)
Simplex Receive an amount of data in non-blocking mode.
HAL_StatusTypeDef HAL_USART_TransmitReceive_IT (USART_HandleTypeDef *husart, uint8_t *pTxData, uint8_t *pRxData, uint16_t Size)
Full-Duplex Send receive an amount of data in full-duplex mode (non-blocking).
HAL_StatusTypeDef HAL_USART_Transmit_DMA (USART_HandleTypeDef *husart, uint8_t *pTxData, uint16_t Size)
Simplex Send an amount of data in non-blocking mode.
HAL_StatusTypeDef HAL_USART_Receive_DMA (USART_HandleTypeDef *husart, uint8_t *pRxData, uint16_t Size)
Full-Duplex Receive an amount of data in non-blocking mode.
HAL_StatusTypeDef HAL_USART_TransmitReceive_DMA (USART_HandleTypeDef *husart, uint8_t *pTxData, uint8_t *pRxData, uint16_t Size)
Full-Duplex Transmit Receive an amount of data in non-blocking mode.
HAL_StatusTypeDef HAL_USART_DMAPause (USART_HandleTypeDef *husart)
Pauses the DMA Transfer.
HAL_StatusTypeDef HAL_USART_DMAResume (USART_HandleTypeDef *husart)
Resumes the DMA Transfer.
HAL_StatusTypeDef HAL_USART_DMAStop (USART_HandleTypeDef *husart)
Stops the DMA Transfer.
HAL_StatusTypeDef HAL_USART_Abort (USART_HandleTypeDef *husart)
Abort ongoing transfer (blocking mode).
HAL_StatusTypeDef HAL_USART_Abort_IT (USART_HandleTypeDef *husart)
Abort ongoing transfer (Interrupt mode).
void HAL_USART_IRQHandler (USART_HandleTypeDef *husart)
This function handles USART interrupt request.
__weak void HAL_USART_TxCpltCallback (USART_HandleTypeDef *husart)
Tx Transfer completed callbacks.
__weak void HAL_USART_TxHalfCpltCallback (USART_HandleTypeDef *husart)
Tx Half Transfer completed callbacks.
__weak void HAL_USART_RxCpltCallback (USART_HandleTypeDef *husart)
Rx Transfer completed callbacks.
__weak void HAL_USART_RxHalfCpltCallback (USART_HandleTypeDef *husart)
Rx Half Transfer completed callbacks.
__weak void HAL_USART_TxRxCpltCallback (USART_HandleTypeDef *husart)
Tx/Rx Transfers completed callback for the non-blocking process.
__weak void HAL_USART_ErrorCallback (USART_HandleTypeDef *husart)
USART error callbacks.
__weak void HAL_USART_AbortCpltCallback (USART_HandleTypeDef *husart)
USART Abort Complete callback.
Detailed Description
USART Transmit and Receive functions.
  ==============================================================================
                         ##### IO operation functions #####
  ==============================================================================
  [..]
    This subsection provides a set of functions allowing to manage the USART synchronous
    data transfers.
  [..]
    The USART supports master mode only: it cannot receive or send data related to an input
    clock (SCLK is always an output).
    (#) There are two modes of transfer:
        (++) Blocking mode: The communication is performed in polling mode.
             The HAL status of all data processing is returned by the same function
             after finishing transfer.
        (++) No-Blocking mode: The communication is performed using Interrupts
             or DMA, These API's return the HAL status.
             The end of the data processing will be indicated through the
             dedicated USART IRQ when using Interrupt mode or the DMA IRQ when
             using DMA mode.
             The HAL_USART_TxCpltCallback(), HAL_USART_RxCpltCallback() and HAL_USART_TxRxCpltCallback()
              user callbacks
             will be executed respectively at the end of the transmit or Receive process
             The HAL_USART_ErrorCallback() user callback will be executed when a communication
             error is detected
    (#) Blocking mode APIs are :
        (++) HAL_USART_Transmit() in simplex mode
        (++) HAL_USART_Receive() in full duplex receive only
        (++) HAL_USART_TransmitReceive() in full duplex mode
    (#) Non Blocking mode APIs with Interrupt are :
        (++) HAL_USART_Transmit_IT()in simplex mode
        (++) HAL_USART_Receive_IT() in full duplex receive only
        (++) HAL_USART_TransmitReceive_IT() in full duplex mode
        (++) HAL_USART_IRQHandler()
    (#) Non Blocking mode functions with DMA are :
        (++) HAL_USART_Transmit_DMA()in simplex mode
        (++) HAL_USART_Receive_DMA() in full duplex receive only
        (++) HAL_USART_TransmitReceive_DMA() in full duplex mode
        (++) HAL_USART_DMAPause()
        (++) HAL_USART_DMAResume()
        (++) HAL_USART_DMAStop()
    (#) A set of Transfer Complete Callbacks are provided in non Blocking mode:
        (++) HAL_USART_TxHalfCpltCallback()
        (++) HAL_USART_TxCpltCallback()
        (++) HAL_USART_RxHalfCpltCallback()
        (++) HAL_USART_RxCpltCallback()
        (++) HAL_USART_ErrorCallback()
        (++) HAL_USART_TxRxCpltCallback()
    (#) Non-Blocking mode transfers could be aborted using Abort API's :
        (++) HAL_USART_Abort()
        (++) HAL_USART_Abort_IT()
    (#) For Abort services based on interrupts (HAL_USART_Abort_IT), a Abort Complete Callbacks is provided:
        (++) HAL_USART_AbortCpltCallback()
    (#) In Non-Blocking mode transfers, possible errors are split into 2 categories.
        Errors are handled as follows :
        (++) Error is considered as Recoverable and non blocking : Transfer could go till end, but error severity is
             to be evaluated by user : this concerns Frame Error, Parity Error or Noise Error in Interrupt mode reception .
             Received character is then retrieved and stored in Rx buffer, Error code is set to allow user to identify error type,
             and HAL_USART_ErrorCallback() user callback is executed. Transfer is kept ongoing on USART side.
             If user wants to abort it, Abort services should be called by user.
        (++) Error is considered as Blocking : Transfer could not be completed properly and is aborted.
             This concerns Overrun Error In Interrupt mode reception and all errors in DMA mode.
             Error code is set to allow user to identify error type, and HAL_USART_ErrorCallback() user callback is executed.
Function Documentation
HAL_StatusTypeDef HAL_USART_Abort (USART_HandleTypeDef * husart)
Abort ongoing transfer (blocking mode).
Parameters:
husart USART handle.
Note:
This procedure could be used for aborting any ongoing transfer (either Tx or Rx, as described by TransferType parameter) started in Interrupt or DMA mode. This procedure performs following operations :
Disable PPP Interrupts (depending of transfer direction)
Disable the DMA transfer in the peripheral register (if enabled)
Abort DMA transfer by calling HAL_DMA_Abort (in case of transfer in DMA mode)
Set handle State to READY
This procedure is executed in blocking mode : when exiting function, Abort is considered as completed.
Return values:
HAL status
Definition at line 1530 of file stm32f1xx_hal_usart.c.
References __USART_HandleTypeDef::ErrorCode, HAL_DMA_Abort(), HAL_USART_ERROR_NONE, HAL_USART_STATE_READY, __USART_HandleTypeDef::hdmarx, __USART_HandleTypeDef::hdmatx, __USART_HandleTypeDef::Instance, __USART_HandleTypeDef::RxXferCount, __USART_HandleTypeDef::State, __USART_HandleTypeDef::TxXferCount, and __DMA_HandleTypeDef::XferAbortCallback.
HAL_StatusTypeDef HAL_USART_Abort_IT (USART_HandleTypeDef * husart)
Abort ongoing transfer (Interrupt mode).
Parameters:
husart USART handle.
Note:
This procedure could be used for aborting any ongoing transfer (either Tx or Rx, as described by TransferType parameter) started in Interrupt or DMA mode. This procedure performs following operations :
Disable PPP Interrupts (depending of transfer direction)
Disable the DMA transfer in the peripheral register (if enabled)
Abort DMA transfer by calling HAL_DMA_Abort_IT (in case of transfer in DMA mode)
Set handle State to READY
At abort completion, call user abort complete callback
This procedure is executed in Interrupt mode, meaning that abort procedure could be considered as completed only when user abort complete callback is executed (not when exiting function).
Return values:
HAL status
Definition at line 1596 of file stm32f1xx_hal_usart.c.
References __USART_HandleTypeDef::ErrorCode, HAL_DMA_Abort_IT(), HAL_USART_AbortCpltCallback(), HAL_USART_ERROR_NONE, HAL_USART_STATE_READY, __USART_HandleTypeDef::hdmarx, __USART_HandleTypeDef::hdmatx, __USART_HandleTypeDef::Instance, __USART_HandleTypeDef::RxXferCount, __USART_HandleTypeDef::State, __USART_HandleTypeDef::TxXferCount, USART_DMARxAbortCallback(), USART_DMATxAbortCallback(), and __DMA_HandleTypeDef::XferAbortCallback.
void HAL_USART_AbortCpltCallback (USART_HandleTypeDef * husart)
USART Abort Complete callback.
Parameters:
husart USART handle.
Return values:
None
Definition at line 1966 of file stm32f1xx_hal_usart.c.
Referenced by HAL_USART_Abort_IT(), USART_DMARxAbortCallback(), and USART_DMATxAbortCallback().
HAL_StatusTypeDef HAL_USART_DMAPause (USART_HandleTypeDef * husart)
Pauses the DMA Transfer.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
Return values:
HAL status
Definition at line 1433 of file stm32f1xx_hal_usart.c.
References __USART_HandleTypeDef::Instance.
HAL_StatusTypeDef HAL_USART_DMAResume (USART_HandleTypeDef * husart)
Resumes the DMA Transfer.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
Return values:
HAL status
Definition at line 1453 of file stm32f1xx_hal_usart.c.
References __USART_HandleTypeDef::Instance.
HAL_StatusTypeDef HAL_USART_DMAStop (USART_HandleTypeDef * husart)
Stops the DMA Transfer.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
Return values:
HAL status
Definition at line 1473 of file stm32f1xx_hal_usart.c.
References HAL_DMA_Abort(), HAL_USART_STATE_BUSY_RX, HAL_USART_STATE_BUSY_TX, __USART_HandleTypeDef::hdmarx, __USART_HandleTypeDef::hdmatx, __USART_HandleTypeDef::Instance, __USART_HandleTypeDef::State, USART_EndRxTransfer(), and USART_EndTxTransfer().
void HAL_USART_ErrorCallback (USART_HandleTypeDef * husart)
USART error callbacks.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
Return values:
None
Definition at line 1952 of file stm32f1xx_hal_usart.c.
Referenced by HAL_USART_IRQHandler(), USART_DMAAbortOnError(), and USART_DMAError().
void HAL_USART_IRQHandler (USART_HandleTypeDef * husart)
This function handles USART interrupt request.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
Return values:
None
Definition at line 1715 of file stm32f1xx_hal_usart.c.
References __USART_HandleTypeDef::ErrorCode, HAL_DMA_Abort_IT(), HAL_USART_ERROR_FE, HAL_USART_ERROR_NE, HAL_USART_ERROR_NONE, HAL_USART_ERROR_ORE, HAL_USART_ERROR_PE, HAL_USART_ErrorCallback(), HAL_USART_STATE_BUSY_RX, HAL_USART_STATE_BUSY_TX, __USART_HandleTypeDef::hdmarx, __USART_HandleTypeDef::Instance, __USART_HandleTypeDef::State, USART_DMAAbortOnError(), USART_EndRxTransfer(), USART_EndTransmit_IT(), USART_Receive_IT(), USART_Transmit_IT(), USART_TransmitReceive_IT(), and __DMA_HandleTypeDef::XferAbortCallback.
HAL_StatusTypeDef HAL_USART_Receive (USART_HandleTypeDef * husart, uint8_t * pRxData, uint16_t Size, uint32_t Timeout)
Full-Duplex Receive an amount of data in blocking mode.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
pRxData Pointer to data buffer
Size Amount of data to be received
Timeout Timeout duration
Return values:
HAL status
Definition at line 822 of file stm32f1xx_hal_usart.c.
References DUMMY_DATA, __USART_HandleTypeDef::ErrorCode, HAL_GetTick(), HAL_USART_ERROR_NONE, HAL_USART_STATE_BUSY_RX, HAL_USART_STATE_READY, __USART_HandleTypeDef::Init, __USART_HandleTypeDef::Instance, USART_InitTypeDef::Parity, __USART_HandleTypeDef::RxXferCount, __USART_HandleTypeDef::RxXferSize, __USART_HandleTypeDef::State, USART_FLAG_RXNE, USART_FLAG_TXE, USART_PARITY_NONE, USART_WaitOnFlagUntilTimeout(), USART_WORDLENGTH_9B, and USART_InitTypeDef::WordLength.
HAL_StatusTypeDef HAL_USART_Receive_DMA (USART_HandleTypeDef * husart, uint8_t * pRxData, uint16_t Size)
Full-Duplex Receive an amount of data in non-blocking mode.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
pRxData Pointer to data buffer
Size Amount of data to be received
Return values:
HAL status
Note:
The USART DMA transmit channel must be configured in order to generate the clock for the slave.
When the USART parity is enabled (PCE = 1) the data received contain the parity bit.
Definition at line 1254 of file stm32f1xx_hal_usart.c.
References __HAL_USART_CLEAR_OREFLAG, __USART_HandleTypeDef::ErrorCode, HAL_DMA_Start_IT(), HAL_USART_ERROR_NONE, HAL_USART_STATE_BUSY_RX, HAL_USART_STATE_READY, __USART_HandleTypeDef::hdmarx, __USART_HandleTypeDef::hdmatx, __USART_HandleTypeDef::Instance, __USART_HandleTypeDef::pRxBuffPtr, __USART_HandleTypeDef::pTxBuffPtr, __USART_HandleTypeDef::RxXferSize, __USART_HandleTypeDef::State, __USART_HandleTypeDef::TxXferSize, USART_DMAError(), USART_DMAReceiveCplt(), USART_DMARxHalfCplt(), __DMA_HandleTypeDef::XferAbortCallback, __DMA_HandleTypeDef::XferCpltCallback, __DMA_HandleTypeDef::XferErrorCallback, and __DMA_HandleTypeDef::XferHalfCpltCallback.
HAL_StatusTypeDef HAL_USART_Receive_IT (USART_HandleTypeDef * husart, uint8_t * pRxData, uint16_t Size)
Simplex Receive an amount of data in non-blocking mode.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
pRxData Pointer to data buffer
Size Amount of data to be received
Return values:
HAL status
Definition at line 1091 of file stm32f1xx_hal_usart.c.
References DUMMY_DATA, __USART_HandleTypeDef::ErrorCode, HAL_USART_ERROR_NONE, HAL_USART_STATE_BUSY_RX, HAL_USART_STATE_READY, __USART_HandleTypeDef::Instance, __USART_HandleTypeDef::pRxBuffPtr, __USART_HandleTypeDef::RxXferCount, __USART_HandleTypeDef::RxXferSize, and __USART_HandleTypeDef::State.
void HAL_USART_RxCpltCallback (USART_HandleTypeDef * husart)
Rx Transfer completed callbacks.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
Return values:
None
Definition at line 1907 of file stm32f1xx_hal_usart.c.
Referenced by USART_DMAReceiveCplt(), and USART_Receive_IT().
void HAL_USART_RxHalfCpltCallback (USART_HandleTypeDef * husart)
Rx Half Transfer completed callbacks.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
Return values:
None
Definition at line 1922 of file stm32f1xx_hal_usart.c.
Referenced by USART_DMARxHalfCplt().
HAL_StatusTypeDef HAL_USART_Transmit (USART_HandleTypeDef * husart, uint8_t * pTxData, uint16_t Size, uint32_t Timeout)
Simplex Send an amount of data in blocking mode.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
pTxData Pointer to data buffer
Size Amount of data to be sent
Timeout Timeout duration
Return values:
HAL status
Definition at line 741 of file stm32f1xx_hal_usart.c.
References __USART_HandleTypeDef::ErrorCode, HAL_GetTick(), HAL_USART_ERROR_NONE, HAL_USART_STATE_BUSY_TX, HAL_USART_STATE_READY, __USART_HandleTypeDef::Init, __USART_HandleTypeDef::Instance, USART_InitTypeDef::Parity, __USART_HandleTypeDef::State, __USART_HandleTypeDef::TxXferCount, __USART_HandleTypeDef::TxXferSize, USART_FLAG_TC, USART_FLAG_TXE, USART_PARITY_NONE, USART_WaitOnFlagUntilTimeout(), USART_WORDLENGTH_9B, and USART_InitTypeDef::WordLength.
HAL_StatusTypeDef HAL_USART_Transmit_DMA (USART_HandleTypeDef * husart, uint8_t * pTxData, uint16_t Size)
Simplex Send an amount of data in non-blocking mode.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
pTxData Pointer to data buffer
Size Amount of data to be sent
Return values:
HAL status
Definition at line 1190 of file stm32f1xx_hal_usart.c.
References __HAL_USART_CLEAR_FLAG, __USART_HandleTypeDef::ErrorCode, HAL_DMA_Start_IT(), HAL_USART_ERROR_NONE, HAL_USART_STATE_BUSY_TX, HAL_USART_STATE_READY, __USART_HandleTypeDef::hdmatx, __USART_HandleTypeDef::Instance, __USART_HandleTypeDef::pTxBuffPtr, __USART_HandleTypeDef::State, __USART_HandleTypeDef::TxXferCount, __USART_HandleTypeDef::TxXferSize, USART_DMAError(), USART_DMATransmitCplt(), USART_DMATxHalfCplt(), USART_FLAG_TC, __DMA_HandleTypeDef::XferAbortCallback, __DMA_HandleTypeDef::XferCpltCallback, __DMA_HandleTypeDef::XferErrorCallback, and __DMA_HandleTypeDef::XferHalfCpltCallback.
HAL_StatusTypeDef HAL_USART_Transmit_IT (USART_HandleTypeDef * husart, uint8_t * pTxData, uint16_t Size)
Simplex Send an amount of data in non-blocking mode.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
pTxData Pointer to data buffer
Size Amount of data to be sent
Return values:
HAL status
Note:
The USART errors are not managed to avoid the overrun error.
Definition at line 1042 of file stm32f1xx_hal_usart.c.
References __USART_HandleTypeDef::ErrorCode, HAL_USART_ERROR_NONE, HAL_USART_STATE_BUSY_TX, HAL_USART_STATE_READY, __USART_HandleTypeDef::Instance, __USART_HandleTypeDef::pTxBuffPtr, __USART_HandleTypeDef::State, __USART_HandleTypeDef::TxXferCount, and __USART_HandleTypeDef::TxXferSize.
HAL_StatusTypeDef HAL_USART_TransmitReceive (USART_HandleTypeDef * husart, uint8_t * pTxData, uint8_t * pRxData, uint16_t Size, uint32_t Timeout)
Full-Duplex Send receive an amount of data in full-duplex mode (blocking mode).
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
pTxData Pointer to data transmitted buffer
pRxData Pointer to data received buffer
Size Amount of data to be sent
Timeout Timeout duration
Return values:
HAL status
Definition at line 928 of file stm32f1xx_hal_usart.c.
References __USART_HandleTypeDef::ErrorCode, HAL_GetTick(), HAL_USART_ERROR_NONE, HAL_USART_STATE_BUSY_RX, HAL_USART_STATE_READY, __USART_HandleTypeDef::Init, __USART_HandleTypeDef::Instance, USART_InitTypeDef::Parity, __USART_HandleTypeDef::RxXferCount, __USART_HandleTypeDef::RxXferSize, __USART_HandleTypeDef::State, __USART_HandleTypeDef::TxXferCount, __USART_HandleTypeDef::TxXferSize, USART_FLAG_RXNE, USART_FLAG_TXE, USART_PARITY_NONE, USART_WaitOnFlagUntilTimeout(), USART_WORDLENGTH_9B, and USART_InitTypeDef::WordLength.
HAL_StatusTypeDef HAL_USART_TransmitReceive_DMA (USART_HandleTypeDef * husart, uint8_t * pTxData, uint8_t * pRxData, uint16_t Size)
Full-Duplex Transmit Receive an amount of data in non-blocking mode.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
pTxData Pointer to data transmitted buffer
pRxData Pointer to data received buffer
Size Amount of data to be received
Note:
When the USART parity is enabled (PCE = 1) the data received contain the parity bit.
Return values:
HAL status
Definition at line 1346 of file stm32f1xx_hal_usart.c.
References __HAL_USART_CLEAR_FLAG, __HAL_USART_CLEAR_OREFLAG, __USART_HandleTypeDef::ErrorCode, HAL_DMA_Start_IT(), HAL_USART_ERROR_NONE, HAL_USART_STATE_BUSY_TX_RX, HAL_USART_STATE_READY, __USART_HandleTypeDef::hdmarx, __USART_HandleTypeDef::hdmatx, __USART_HandleTypeDef::Instance, __USART_HandleTypeDef::pRxBuffPtr, __USART_HandleTypeDef::pTxBuffPtr, __USART_HandleTypeDef::RxXferSize, __USART_HandleTypeDef::State, __USART_HandleTypeDef::TxXferSize, USART_DMAError(), USART_DMAReceiveCplt(), USART_DMARxHalfCplt(), USART_DMATransmitCplt(), USART_DMATxHalfCplt(), USART_FLAG_TC, __DMA_HandleTypeDef::XferAbortCallback, __DMA_HandleTypeDef::XferCpltCallback, __DMA_HandleTypeDef::XferErrorCallback, and __DMA_HandleTypeDef::XferHalfCpltCallback.
HAL_StatusTypeDef HAL_USART_TransmitReceive_IT (USART_HandleTypeDef * husart, uint8_t * pTxData, uint8_t * pRxData, uint16_t Size)
Full-Duplex Send receive an amount of data in full-duplex mode (non-blocking).
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
pTxData Pointer to data transmitted buffer
pRxData Pointer to data received buffer
Size Amount of data to be received
Return values:
HAL status
Definition at line 1138 of file stm32f1xx_hal_usart.c.
References __USART_HandleTypeDef::ErrorCode, HAL_USART_ERROR_NONE, HAL_USART_STATE_BUSY_TX_RX, HAL_USART_STATE_READY, __USART_HandleTypeDef::Instance, __USART_HandleTypeDef::pRxBuffPtr, __USART_HandleTypeDef::pTxBuffPtr, __USART_HandleTypeDef::RxXferCount, __USART_HandleTypeDef::RxXferSize, __USART_HandleTypeDef::State, __USART_HandleTypeDef::TxXferCount, and __USART_HandleTypeDef::TxXferSize.
void HAL_USART_TxCpltCallback (USART_HandleTypeDef * husart)
Tx Transfer completed callbacks.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
Return values:
None
Definition at line 1877 of file stm32f1xx_hal_usart.c.
Referenced by USART_DMATransmitCplt(), and USART_EndTransmit_IT().
void HAL_USART_TxHalfCpltCallback (USART_HandleTypeDef * husart)
Tx Half Transfer completed callbacks.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
Return values:
None
Definition at line 1892 of file stm32f1xx_hal_usart.c.
Referenced by USART_DMATxHalfCplt().
void HAL_USART_TxRxCpltCallback (USART_HandleTypeDef * husart)
Tx/Rx Transfers completed callback for the non-blocking process.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
Return values:
None
Definition at line 1937 of file stm32f1xx_hal_usart.c.
Referenced by USART_DMAReceiveCplt(), and USART_TransmitReceive_IT().