STM32F100xE HAL User Manual: Initialization and de-initialization functions
Initialization and de-initialization functions
CRC Exported Functions
Initialization and Configuration functions.
Functions
HAL_StatusTypeDef HAL_CRC_Init (CRC_HandleTypeDef *hcrc)
Initialize the CRC according to the specified parameters in the CRC_InitTypeDef and create the associated handle.
HAL_StatusTypeDef HAL_CRC_DeInit (CRC_HandleTypeDef *hcrc)
DeInitialize the CRC peripheral.
__weak void HAL_CRC_MspInit (CRC_HandleTypeDef *hcrc)
Initializes the CRC MSP.
__weak void HAL_CRC_MspDeInit (CRC_HandleTypeDef *hcrc)
DeInitialize the CRC MSP.
Detailed Description
Initialization and Configuration functions.
 ===============================================================================
            ##### Initialization and de-initialization functions #####
 ===============================================================================
    [..]  This section provides functions allowing to:
      (+) Initialize the CRC according to the specified parameters
          in the CRC_InitTypeDef and create the associated handle
      (+) DeInitialize the CRC peripheral
      (+) Initialize the CRC MSP (MCU Specific Package)
      (+) DeInitialize the CRC MSP
Function Documentation
HAL_StatusTypeDef HAL_CRC_DeInit (CRC_HandleTypeDef * hcrc)
DeInitialize the CRC peripheral.
Parameters:
hcrc CRC handle
Return values:
HAL status
Definition at line 126 of file stm32f1xx_hal_crc.c.
References __HAL_CRC_DR_RESET, assert_param, HAL_CRC_MspDeInit(), HAL_CRC_STATE_BUSY, HAL_CRC_STATE_RESET, CRC_HandleTypeDef::Instance, and CRC_HandleTypeDef::State.
HAL_StatusTypeDef HAL_CRC_Init (CRC_HandleTypeDef * hcrc)
Initialize the CRC according to the specified parameters in the CRC_InitTypeDef and create the associated handle.
Parameters:
hcrc CRC handle
Return values:
HAL status
Definition at line 95 of file stm32f1xx_hal_crc.c.
References assert_param, HAL_CRC_MspInit(), HAL_CRC_STATE_READY, HAL_CRC_STATE_RESET, CRC_HandleTypeDef::Instance, CRC_HandleTypeDef::Lock, and CRC_HandleTypeDef::State.
void HAL_CRC_MspDeInit (CRC_HandleTypeDef * hcrc)
DeInitialize the CRC MSP.
Parameters:
hcrc CRC handle
Return values:
None
Definition at line 185 of file stm32f1xx_hal_crc.c.
Referenced by HAL_CRC_DeInit().
void HAL_CRC_MspInit (CRC_HandleTypeDef * hcrc)
Initializes the CRC MSP.
Parameters:
hcrc CRC handle
Return values:
None
Definition at line 170 of file stm32f1xx_hal_crc.c.
Referenced by HAL_CRC_Init().