STM32F100xE HAL User Manual: Get system and peripherals clocks frequency functions
Get system and peripherals clocks frequency functions
RCC Exported Functions
Return the frequencies of different on chip clocks; System, AHB, APB1 and APB2 buses clocks and different peripheral clocks available on the device.
Functions
void LL_RCC_GetSystemClocksFreq (LL_RCC_ClocksTypeDef *RCC_Clocks)
Return the frequencies of different on chip clocks; System, AHB, APB1 and APB2 buses clocks.
uint32_t LL_RCC_GetADCClockFreq (uint32_t ADCxSource)
Return ADCx clock frequency.
Detailed Description
Return the frequencies of different on chip clocks; System, AHB, APB1 and APB2 buses clocks and different peripheral clocks available on the device.
Note:
If SYSCLK source is HSI, function returns values based on HSI_VALUE(**)
If SYSCLK source is HSE, function returns values based on HSE_VALUE(***)
If SYSCLK source is PLL, function returns values based on HSI_VALUE(**) or HSE_VALUE(***) multiplied/divided by the PLL factors.
(**) HSI_VALUE is a defined constant but the real value may vary depending on the variations in voltage and temperature.
(***) HSE_VALUE is a defined constant, user has to ensure that HSE_VALUE is same as the real frequency of the crystal used. Otherwise, this function may have wrong result.
The result of this function could be incorrect when using fractional value for HSE crystal.
This function can be used by the user application to compute the baud-rate for the communication peripherals or configure other parameters.
Function Documentation
uint32_t LL_RCC_GetADCClockFreq (uint32_t ADCxSource)
Return ADCx clock frequency.
Parameters:
ADCxSource This parameter can be one of the following values:
LL_RCC_ADC_CLKSOURCE
Return values:
ADC clock frequency (in Hz)
Definition at line 306 of file stm32f1xx_ll_rcc.c.
References assert_param, IS_LL_RCC_ADC_CLKSOURCE, LL_RCC_GetADCClockSource(), RCC_GetHCLKClockFreq(), RCC_GetPCLK2ClockFreq(), and RCC_GetSystemClockFreq().
void LL_RCC_GetSystemClocksFreq (LL_RCC_ClocksTypeDef * RCC_Clocks)
Return the frequencies of different on chip clocks; System, AHB, APB1 and APB2 buses clocks.
Note:
Each time SYSCLK, HCLK, PCLK1 and/or PCLK2 clock changes, this function must be called to update structure fields. Otherwise, any configuration based on this function will be incorrect.
Parameters:
RCC_Clocks pointer to a LL_RCC_ClocksTypeDef structure which will hold the clocks frequencies
Return values:
None
Definition at line 190 of file stm32f1xx_ll_rcc.c.
References LL_RCC_ClocksTypeDef::HCLK_Frequency, LL_RCC_ClocksTypeDef::PCLK1_Frequency, LL_RCC_ClocksTypeDef::PCLK2_Frequency, RCC_GetHCLKClockFreq(), RCC_GetPCLK1ClockFreq(), RCC_GetPCLK2ClockFreq(), RCC_GetSystemClockFreq(), and LL_RCC_ClocksTypeDef::SYSCLK_Frequency.
Referenced by LL_I2C_Init(), and LL_USART_Init().