STM32F100xE HAL User Manual: IRQ Handler and Callbacks
IRQ Handler and Callbacks
I2C Exported Functions
Functions
void HAL_I2C_EV_IRQHandler (I2C_HandleTypeDef *hi2c)
This function handles I2C event interrupt request.
void HAL_I2C_ER_IRQHandler (I2C_HandleTypeDef *hi2c)
This function handles I2C error interrupt request.
__weak void HAL_I2C_MasterTxCpltCallback (I2C_HandleTypeDef *hi2c)
Master Tx Transfer completed callback.
__weak void HAL_I2C_MasterRxCpltCallback (I2C_HandleTypeDef *hi2c)
Master Rx Transfer completed callback.
__weak void HAL_I2C_SlaveTxCpltCallback (I2C_HandleTypeDef *hi2c)
Slave Tx Transfer completed callback.
__weak void HAL_I2C_SlaveRxCpltCallback (I2C_HandleTypeDef *hi2c)
Slave Rx Transfer completed callback.
__weak void HAL_I2C_AddrCallback (I2C_HandleTypeDef *hi2c, uint8_t TransferDirection, uint16_t AddrMatchCode)
Slave Address Match callback.
__weak void HAL_I2C_ListenCpltCallback (I2C_HandleTypeDef *hi2c)
Listen Complete callback.
__weak void HAL_I2C_MemTxCpltCallback (I2C_HandleTypeDef *hi2c)
Memory Tx Transfer completed callback.
__weak void HAL_I2C_MemRxCpltCallback (I2C_HandleTypeDef *hi2c)
Memory Rx Transfer completed callback.
__weak void HAL_I2C_ErrorCallback (I2C_HandleTypeDef *hi2c)
I2C error callback.
__weak void HAL_I2C_AbortCpltCallback (I2C_HandleTypeDef *hi2c)
I2C abort callback.
Function Documentation
void HAL_I2C_AbortCpltCallback (I2C_HandleTypeDef * hi2c)
I2C abort callback.
Parameters:
hi2c Pointer to a I2C_HandleTypeDef structure that contains the configuration information for the specified I2C.
Return values:
None
Definition at line 4981 of file stm32f1xx_hal_i2c.c.
Referenced by HAL_I2C_Init(), I2C_DMAAbort(), and I2C_ITError().
void HAL_I2C_AddrCallback (I2C_HandleTypeDef * hi2c, uint8_t TransferDirection, uint16_t AddrMatchCode)
Slave Address Match callback.
Parameters:
hi2c Pointer to a I2C_HandleTypeDef structure that contains the configuration information for the specified I2C.
TransferDirection Master request Transfer Direction (Write/Read), value of I2C XferDirection definition
AddrMatchCode Address Match Code
Return values:
None
Definition at line 4899 of file stm32f1xx_hal_i2c.c.
Referenced by HAL_I2C_Init(), and I2C_Slave_ADDR().
void HAL_I2C_ER_IRQHandler (I2C_HandleTypeDef * hi2c)
This function handles I2C error interrupt request.
Parameters:
hi2c Pointer to a I2C_HandleTypeDef structure that contains the configuration information for the specified I2C.
Return values:
None
Definition at line 4752 of file stm32f1xx_hal_i2c.c.
References __HAL_I2C_CLEAR_FLAG, __I2C_HandleTypeDef::ErrorCode, HAL_I2C_ERROR_AF, HAL_I2C_ERROR_ARLO, HAL_I2C_ERROR_BERR, HAL_I2C_ERROR_NONE, HAL_I2C_ERROR_OVR, HAL_I2C_MODE_MASTER, HAL_I2C_MODE_SLAVE, HAL_I2C_STATE_BUSY_TX, HAL_I2C_STATE_BUSY_TX_LISTEN, HAL_I2C_STATE_LISTEN, I2C_CHECK_FLAG, I2C_CHECK_IT_SOURCE, I2C_FLAG_AF, I2C_FLAG_ARLO, I2C_FLAG_BERR, I2C_FLAG_OVR, I2C_IT_ERR, I2C_ITError(), I2C_Slave_AF(), I2C_STATE_SLAVE_BUSY_TX, __I2C_HandleTypeDef::Instance, __I2C_HandleTypeDef::Mode, __I2C_HandleTypeDef::PreviousState, __I2C_HandleTypeDef::State, and __I2C_HandleTypeDef::XferCount.
void HAL_I2C_ErrorCallback (I2C_HandleTypeDef * hi2c)
I2C error callback.
Parameters:
hi2c Pointer to a I2C_HandleTypeDef structure that contains the configuration information for the specified I2C.
Return values:
None
Definition at line 4965 of file stm32f1xx_hal_i2c.c.
Referenced by HAL_I2C_Init(), I2C_DMAAbort(), I2C_DMAError(), I2C_DMAXferCplt(), and I2C_ITError().
void HAL_I2C_EV_IRQHandler (I2C_HandleTypeDef * hi2c)
This function handles I2C event interrupt request.
Parameters:
hi2c Pointer to a I2C_HandleTypeDef structure that contains the configuration information for the specified I2C.
Return values:
None
Definition at line 4593 of file stm32f1xx_hal_i2c.c.
References __I2C_HandleTypeDef::ErrorCode, HAL_I2C_ERROR_NONE, HAL_I2C_MODE_MASTER, HAL_I2C_MODE_MEM, HAL_I2C_STATE_BUSY_TX, HAL_I2C_STATE_BUSY_TX_LISTEN, I2C_CHECK_FLAG, I2C_CHECK_IT_SOURCE, I2C_ConvertOtherXferOptions(), I2C_FLAG_ADD10, I2C_FLAG_ADDR, I2C_FLAG_BTF, I2C_FLAG_RXNE, I2C_FLAG_SB, I2C_FLAG_STOPF, I2C_FLAG_TRA, I2C_FLAG_TXE, I2C_IT_BUF, I2C_IT_EVT, I2C_Master_ADD10(), I2C_Master_ADDR(), I2C_Master_SB(), I2C_MasterReceive_BTF(), I2C_MasterReceive_RXNE(), I2C_MasterTransmit_BTF(), I2C_MasterTransmit_TXE(), I2C_Slave_ADDR(), I2C_Slave_STOPF(), I2C_SlaveReceive_BTF(), I2C_SlaveReceive_RXNE(), I2C_SlaveTransmit_BTF(), I2C_SlaveTransmit_TXE(), __I2C_HandleTypeDef::Instance, IS_I2C_TRANSFER_OTHER_OPTIONS_REQUEST, __I2C_HandleTypeDef::Mode, __I2C_HandleTypeDef::State, and __I2C_HandleTypeDef::XferOptions.
void HAL_I2C_ListenCpltCallback (I2C_HandleTypeDef * hi2c)
Listen Complete callback.
Parameters:
hi2c Pointer to a I2C_HandleTypeDef structure that contains the configuration information for the specified I2C.
Return values:
None
Definition at line 4917 of file stm32f1xx_hal_i2c.c.
Referenced by HAL_I2C_Init(), I2C_ITError(), I2C_Slave_AF(), and I2C_Slave_STOPF().
void HAL_I2C_MasterRxCpltCallback (I2C_HandleTypeDef * hi2c)
Master Rx Transfer completed callback.
Parameters:
hi2c Pointer to a I2C_HandleTypeDef structure that contains the configuration information for the specified I2C.
Return values:
None
Definition at line 4850 of file stm32f1xx_hal_i2c.c.
Referenced by HAL_I2C_Init(), I2C_DMAXferCplt(), I2C_MasterReceive_BTF(), and I2C_MasterReceive_RXNE().
void HAL_I2C_MasterTxCpltCallback (I2C_HandleTypeDef * hi2c)
Master Tx Transfer completed callback.
Parameters:
hi2c Pointer to a I2C_HandleTypeDef structure that contains the configuration information for the specified I2C.
Return values:
None
Definition at line 4834 of file stm32f1xx_hal_i2c.c.
Referenced by HAL_I2C_Init(), I2C_MasterTransmit_BTF(), and I2C_MasterTransmit_TXE().
void HAL_I2C_MemRxCpltCallback (I2C_HandleTypeDef * hi2c)
Memory Rx Transfer completed callback.
Parameters:
hi2c Pointer to a I2C_HandleTypeDef structure that contains the configuration information for the specified I2C.
Return values:
None
Definition at line 4949 of file stm32f1xx_hal_i2c.c.
Referenced by HAL_I2C_Init(), I2C_DMAXferCplt(), I2C_MasterReceive_BTF(), and I2C_MasterReceive_RXNE().
void HAL_I2C_MemTxCpltCallback (I2C_HandleTypeDef * hi2c)
Memory Tx Transfer completed callback.
Parameters:
hi2c Pointer to a I2C_HandleTypeDef structure that contains the configuration information for the specified I2C.
Return values:
None
Definition at line 4933 of file stm32f1xx_hal_i2c.c.
Referenced by HAL_I2C_Init(), I2C_MasterTransmit_BTF(), and I2C_MasterTransmit_TXE().
void HAL_I2C_SlaveRxCpltCallback (I2C_HandleTypeDef * hi2c)
Slave Rx Transfer completed callback.
Parameters:
hi2c Pointer to a I2C_HandleTypeDef structure that contains the configuration information for the specified I2C.
Return values:
None
Definition at line 4881 of file stm32f1xx_hal_i2c.c.
Referenced by HAL_I2C_Init(), I2C_DMAXferCplt(), I2C_Slave_STOPF(), and I2C_SlaveReceive_RXNE().
void HAL_I2C_SlaveTxCpltCallback (I2C_HandleTypeDef * hi2c)
Slave Tx Transfer completed callback.
Parameters:
hi2c Pointer to a I2C_HandleTypeDef structure that contains the configuration information for the specified I2C.
Return values:
None
Definition at line 4865 of file stm32f1xx_hal_i2c.c.
Referenced by HAL_I2C_Init(), I2C_DMAXferCplt(), I2C_Slave_AF(), and I2C_SlaveTransmit_TXE().