STM32F100xE HAL User Manual: Initialization and de-initialization functions
Initialization and de-initialization functions
NOR Exported Functions
Initialization and Configuration functions.
Functions
HAL_StatusTypeDef HAL_NOR_Init (NOR_HandleTypeDef *hnor, FSMC_NORSRAM_TimingTypeDef *Timing, FSMC_NORSRAM_TimingTypeDef *ExtTiming)
Perform the NOR memory Initialization sequence.
HAL_StatusTypeDef HAL_NOR_DeInit (NOR_HandleTypeDef *hnor)
Perform NOR memory De-Initialization sequence.
__weak void HAL_NOR_MspInit (NOR_HandleTypeDef *hnor)
NOR MSP Init.
__weak void HAL_NOR_MspDeInit (NOR_HandleTypeDef *hnor)
NOR MSP DeInit.
__weak void HAL_NOR_MspWait (NOR_HandleTypeDef *hnor, uint32_t Timeout)
NOR MSP Wait for Ready/Busy signal.
Detailed Description
Initialization and Configuration functions.
  ==============================================================================
           ##### NOR Initialization and de_initialization functions #####
  ==============================================================================
  [..]
    This section provides functions allowing to initialize/de-initialize
    the NOR memory
Function Documentation
HAL_StatusTypeDef HAL_NOR_DeInit (NOR_HandleTypeDef * hnor)
Perform NOR memory De-Initialization sequence.
Parameters:
hnor pointer to a NOR_HandleTypeDef structure that contains the configuration information for NOR module.
Return values:
HAL status
Definition at line 264 of file stm32f1xx_hal_nor.c.
References HAL_NOR_MspDeInit().
HAL_StatusTypeDef HAL_NOR_Init (NOR_HandleTypeDef * hnor, FSMC_NORSRAM_TimingTypeDef * Timing, FSMC_NORSRAM_TimingTypeDef * ExtTiming)
Perform the NOR memory Initialization sequence.
Parameters:
hnor pointer to a NOR_HandleTypeDef structure that contains the configuration information for NOR module.
Timing pointer to NOR control timing structure
ExtTiming pointer to NOR extended mode timing structure
Return values:
HAL status
Definition at line 203 of file stm32f1xx_hal_nor.c.
References HAL_NOR_MspInit(), and uwNORMemoryDataWidth.
__weak void HAL_NOR_MspDeInit (NOR_HandleTypeDef * hnor)
NOR MSP DeInit.
Parameters:
hnor pointer to a NOR_HandleTypeDef structure that contains the configuration information for NOR module.
Return values:
None
Definition at line 313 of file stm32f1xx_hal_nor.c.
Referenced by HAL_NOR_DeInit().
__weak void HAL_NOR_MspInit (NOR_HandleTypeDef * hnor)
NOR MSP Init.
Parameters:
hnor pointer to a NOR_HandleTypeDef structure that contains the configuration information for NOR module.
Return values:
None
Definition at line 297 of file stm32f1xx_hal_nor.c.
Referenced by HAL_NOR_Init().
__weak void HAL_NOR_MspWait (NOR_HandleTypeDef * hnor, uint32_t Timeout)
NOR MSP Wait for Ready/Busy signal.
Parameters:
hnor pointer to a NOR_HandleTypeDef structure that contains the configuration information for NOR module.
Timeout Maximum timeout value
Return values:
None
Definition at line 330 of file stm32f1xx_hal_nor.c.
Referenced by HAL_NOR_GetStatus().