STM32F100xE HAL User Manual: Initialization and de-initialization functions
Initialization and de-initialization functions
DAC Exported Functions
Initialization and Configuration functions.
Functions
HAL_StatusTypeDef HAL_DAC_Init (DAC_HandleTypeDef *hdac)
Initialize the DAC peripheral according to the specified parameters in the DAC_InitStruct and initialize the associated handle.
HAL_StatusTypeDef HAL_DAC_DeInit (DAC_HandleTypeDef *hdac)
Deinitialize the DAC peripheral registers to their default reset values.
__weak void HAL_DAC_MspInit (DAC_HandleTypeDef *hdac)
Initialize the DAC MSP.
__weak void HAL_DAC_MspDeInit (DAC_HandleTypeDef *hdac)
DeInitialize the DAC MSP.
Detailed Description
Initialization and Configuration functions.
  ==============================================================================
              ##### Initialization and de-initialization functions #####
  ==============================================================================
    [..]  This section provides functions allowing to:
      (+) Initialize and configure the DAC.
      (+) De-initialize the DAC.
Function Documentation
HAL_StatusTypeDef HAL_DAC_DeInit (DAC_HandleTypeDef * hdac)
Deinitialize the DAC peripheral registers to their default reset values.
Parameters:
hdac pointer to a DAC_HandleTypeDef structure that contains the configuration information for the specified DAC.
Return values:
HAL status
Definition at line 359 of file stm32f1xx_hal_dac.c.
References assert_param, DAC_HandleTypeDef::ErrorCode, HAL_DAC_ERROR_NONE, HAL_DAC_MspDeInit(), HAL_DAC_STATE_BUSY, HAL_DAC_STATE_RESET, DAC_HandleTypeDef::Instance, and DAC_HandleTypeDef::State.
HAL_StatusTypeDef HAL_DAC_Init (DAC_HandleTypeDef * hdac)
Initialize the DAC peripheral according to the specified parameters in the DAC_InitStruct and initialize the associated handle.
Parameters:
hdac pointer to a DAC_HandleTypeDef structure that contains the configuration information for the specified DAC.
Return values:
HAL status
Definition at line 298 of file stm32f1xx_hal_dac.c.
References assert_param, DAC_HandleTypeDef::ErrorCode, HAL_DAC_ConvCpltCallbackCh1(), HAL_DAC_ConvHalfCpltCallbackCh1(), HAL_DAC_DMAUnderrunCallbackCh1(), HAL_DAC_ERROR_NONE, HAL_DAC_ErrorCallbackCh1(), HAL_DAC_MspInit(), HAL_DAC_STATE_BUSY, HAL_DAC_STATE_READY, HAL_DAC_STATE_RESET, HAL_DACEx_ConvCpltCallbackCh2(), HAL_DACEx_ConvHalfCpltCallbackCh2(), HAL_DACEx_DMAUnderrunCallbackCh2(), HAL_DACEx_ErrorCallbackCh2(), DAC_HandleTypeDef::Instance, DAC_HandleTypeDef::Lock, and DAC_HandleTypeDef::State.
void HAL_DAC_MspDeInit (DAC_HandleTypeDef * hdac)
DeInitialize the DAC MSP.
Parameters:
hdac pointer to a DAC_HandleTypeDef structure that contains the configuration information for the specified DAC.
Return values:
None
Definition at line 420 of file stm32f1xx_hal_dac.c.
Referenced by HAL_DAC_DeInit().
void HAL_DAC_MspInit (DAC_HandleTypeDef * hdac)
Initialize the DAC MSP.
Parameters:
hdac pointer to a DAC_HandleTypeDef structure that contains the configuration information for the specified DAC.
Return values:
None
Definition at line 404 of file stm32f1xx_hal_dac.c.
Referenced by HAL_DAC_Init().