STM32F100xE HAL User Manual: Initialization and de-initialization functions
Initialization and de-initialization functions
SRAM Exported Functions
Initialization and Configuration functions.
Functions
HAL_StatusTypeDef HAL_SRAM_Init (SRAM_HandleTypeDef *hsram, FSMC_NORSRAM_TimingTypeDef *Timing, FSMC_NORSRAM_TimingTypeDef *ExtTiming)
Performs the SRAM device initialization sequence.
HAL_StatusTypeDef HAL_SRAM_DeInit (SRAM_HandleTypeDef *hsram)
Performs the SRAM device De-initialization sequence.
__weak void HAL_SRAM_MspInit (SRAM_HandleTypeDef *hsram)
SRAM MSP Init.
__weak void HAL_SRAM_MspDeInit (SRAM_HandleTypeDef *hsram)
SRAM MSP DeInit.
__weak void HAL_SRAM_DMA_XferCpltCallback (DMA_HandleTypeDef *hdma)
DMA transfer complete callback.
__weak void HAL_SRAM_DMA_XferErrorCallback (DMA_HandleTypeDef *hdma)
DMA transfer complete error callback.
Detailed Description
Initialization and Configuration functions.
  ==============================================================================
           ##### SRAM Initialization and de_initialization functions #####
  ==============================================================================
    [..]  This section provides functions allowing to initialize/de-initialize
          the SRAM memory
Function Documentation
HAL_StatusTypeDef HAL_SRAM_DeInit (SRAM_HandleTypeDef * hsram)
Performs the SRAM device De-initialization sequence.
Parameters:
hsram pointer to a SRAM_HandleTypeDef structure that contains the configuration information for SRAM module.
Return values:
HAL status
Definition at line 227 of file stm32f1xx_hal_sram.c.
References HAL_SRAM_MspDeInit().
__weak void HAL_SRAM_DMA_XferCpltCallback (DMA_HandleTypeDef * hdma)
DMA transfer complete callback.
Parameters:
hdma pointer to a SRAM_HandleTypeDef structure that contains the configuration information for SRAM module.
Return values:
None
Definition at line 292 of file stm32f1xx_hal_sram.c.
Referenced by HAL_SRAM_Init().
__weak void HAL_SRAM_DMA_XferErrorCallback (DMA_HandleTypeDef * hdma)
DMA transfer complete error callback.
Parameters:
hdma pointer to a SRAM_HandleTypeDef structure that contains the configuration information for SRAM module.
Return values:
None
Definition at line 308 of file stm32f1xx_hal_sram.c.
Referenced by HAL_SRAM_Init().
HAL_StatusTypeDef HAL_SRAM_Init (SRAM_HandleTypeDef * hsram, FSMC_NORSRAM_TimingTypeDef * Timing, FSMC_NORSRAM_TimingTypeDef * ExtTiming)
Performs the SRAM device initialization sequence.
Parameters:
hsram pointer to a SRAM_HandleTypeDef structure that contains the configuration information for SRAM module.
Timing Pointer to SRAM control timing structure
ExtTiming Pointer to SRAM extended mode timing structure
Return values:
HAL status
Definition at line 174 of file stm32f1xx_hal_sram.c.
References HAL_SRAM_DMA_XferCpltCallback(), HAL_SRAM_DMA_XferErrorCallback(), and HAL_SRAM_MspInit().
__weak void HAL_SRAM_MspDeInit (SRAM_HandleTypeDef * hsram)
SRAM MSP DeInit.
Parameters:
hsram pointer to a SRAM_HandleTypeDef structure that contains the configuration information for SRAM module.
Return values:
None
Definition at line 276 of file stm32f1xx_hal_sram.c.
Referenced by HAL_SRAM_DeInit().
__weak void HAL_SRAM_MspInit (SRAM_HandleTypeDef * hsram)
SRAM MSP Init.
Parameters:
hsram pointer to a SRAM_HandleTypeDef structure that contains the configuration information for SRAM module.
Return values:
None
Definition at line 260 of file stm32f1xx_hal_sram.c.
Referenced by HAL_SRAM_Init().