STM32F100xE HAL User Manual: Extended Callbacks functions
Extended Callbacks functions
TIM Extended Exported Functions
Extended Callbacks functions.
Functions
__weak void HAL_TIMEx_CommutCallback (TIM_HandleTypeDef *htim)
Hall commutation changed callback in non-blocking mode.
__weak void HAL_TIMEx_CommutHalfCpltCallback (TIM_HandleTypeDef *htim)
Hall commutation changed half complete callback in non-blocking mode.
__weak void HAL_TIMEx_BreakCallback (TIM_HandleTypeDef *htim)
Hall Break detection callback in non-blocking mode.
Detailed Description
Extended Callbacks functions.
  ==============================================================================
                    ##### Extended Callbacks functions #####
  ==============================================================================
  [..]
    This section provides Extended TIM callback functions:
    (+) Timer Commutation callback
    (+) Timer Break callback
Function Documentation
void HAL_TIMEx_BreakCallback (TIM_HandleTypeDef * htim)
Hall Break detection callback in non-blocking mode.
Parameters:
htim TIM handle
Return values:
None
Definition at line 1794 of file stm32f1xx_hal_tim_ex.c.
Referenced by HAL_TIM_IRQHandler().
void HAL_TIMEx_CommutCallback (TIM_HandleTypeDef * htim)
Hall commutation changed callback in non-blocking mode.
Parameters:
htim TIM handle
Return values:
None
Definition at line 1765 of file stm32f1xx_hal_tim_ex.c.
Referenced by HAL_TIM_IRQHandler(), and TIMEx_DMACommutationCplt().
void HAL_TIMEx_CommutHalfCpltCallback (TIM_HandleTypeDef * htim)
Hall commutation changed half complete callback in non-blocking mode.
Parameters:
htim TIM handle
Return values:
None
Definition at line 1779 of file stm32f1xx_hal_tim_ex.c.
Referenced by TIMEx_DMACommutationHalfCplt().