STM32F100xE HAL User Manual: Configuration
Configuration
I2C Exported Functions
Functions
__STATIC_INLINE void LL_I2C_Enable (I2C_TypeDef *I2Cx)
Enable I2C peripheral (PE = 1).
__STATIC_INLINE void LL_I2C_Disable (I2C_TypeDef *I2Cx)
Disable I2C peripheral (PE = 0).
__STATIC_INLINE uint32_t LL_I2C_IsEnabled (I2C_TypeDef *I2Cx)
Check if the I2C peripheral is enabled or disabled.
__STATIC_INLINE void LL_I2C_EnableDMAReq_TX (I2C_TypeDef *I2Cx)
Enable DMA transmission requests.
__STATIC_INLINE void LL_I2C_DisableDMAReq_TX (I2C_TypeDef *I2Cx)
Disable DMA transmission requests.
__STATIC_INLINE uint32_t LL_I2C_IsEnabledDMAReq_TX (I2C_TypeDef *I2Cx)
Check if DMA transmission requests are enabled or disabled.
__STATIC_INLINE void LL_I2C_EnableDMAReq_RX (I2C_TypeDef *I2Cx)
Enable DMA reception requests.
__STATIC_INLINE void LL_I2C_DisableDMAReq_RX (I2C_TypeDef *I2Cx)
Disable DMA reception requests.
__STATIC_INLINE uint32_t LL_I2C_IsEnabledDMAReq_RX (I2C_TypeDef *I2Cx)
Check if DMA reception requests are enabled or disabled.
__STATIC_INLINE uint32_t LL_I2C_DMA_GetRegAddr (I2C_TypeDef *I2Cx)
Get the data register address used for DMA transfer.
__STATIC_INLINE void LL_I2C_EnableClockStretching (I2C_TypeDef *I2Cx)
Enable Clock stretching.
__STATIC_INLINE void LL_I2C_DisableClockStretching (I2C_TypeDef *I2Cx)
Disable Clock stretching.
__STATIC_INLINE uint32_t LL_I2C_IsEnabledClockStretching (I2C_TypeDef *I2Cx)
Check if Clock stretching is enabled or disabled.
__STATIC_INLINE void LL_I2C_EnableGeneralCall (I2C_TypeDef *I2Cx)
Enable General Call.
__STATIC_INLINE void LL_I2C_DisableGeneralCall (I2C_TypeDef *I2Cx)
Disable General Call.
__STATIC_INLINE uint32_t LL_I2C_IsEnabledGeneralCall (I2C_TypeDef *I2Cx)
Check if General Call is enabled or disabled.
__STATIC_INLINE void LL_I2C_SetOwnAddress1 (I2C_TypeDef *I2Cx, uint32_t OwnAddress1, uint32_t OwnAddrSize)
Set the Own Address1.
__STATIC_INLINE void LL_I2C_SetOwnAddress2 (I2C_TypeDef *I2Cx, uint32_t OwnAddress2)
Set the 7bits Own Address2.
__STATIC_INLINE void LL_I2C_EnableOwnAddress2 (I2C_TypeDef *I2Cx)
Enable acknowledge on Own Address2 match address.
__STATIC_INLINE void LL_I2C_DisableOwnAddress2 (I2C_TypeDef *I2Cx)
Disable acknowledge on Own Address2 match address.
__STATIC_INLINE uint32_t LL_I2C_IsEnabledOwnAddress2 (I2C_TypeDef *I2Cx)
Check if Own Address1 acknowledge is enabled or disabled.
__STATIC_INLINE void LL_I2C_SetPeriphClock (I2C_TypeDef *I2Cx, uint32_t PeriphClock)
Configure the Peripheral clock frequency.
__STATIC_INLINE uint32_t LL_I2C_GetPeriphClock (I2C_TypeDef *I2Cx)
Get the Peripheral clock frequency.
__STATIC_INLINE void LL_I2C_SetDutyCycle (I2C_TypeDef *I2Cx, uint32_t DutyCycle)
Configure the Duty cycle (Fast mode only).
__STATIC_INLINE uint32_t LL_I2C_GetDutyCycle (I2C_TypeDef *I2Cx)
Get the Duty cycle (Fast mode only).
__STATIC_INLINE void LL_I2C_SetClockSpeedMode (I2C_TypeDef *I2Cx, uint32_t ClockSpeedMode)
Configure the I2C master clock speed mode.
__STATIC_INLINE uint32_t LL_I2C_GetClockSpeedMode (I2C_TypeDef *I2Cx)
Get the the I2C master speed mode.
__STATIC_INLINE void LL_I2C_SetRiseTime (I2C_TypeDef *I2Cx, uint32_t RiseTime)
Configure the SCL, SDA rising time.
__STATIC_INLINE uint32_t LL_I2C_GetRiseTime (I2C_TypeDef *I2Cx)
Get the SCL, SDA rising time.
__STATIC_INLINE void LL_I2C_SetClockPeriod (I2C_TypeDef *I2Cx, uint32_t ClockPeriod)
Configure the SCL high and low period.
__STATIC_INLINE uint32_t LL_I2C_GetClockPeriod (I2C_TypeDef *I2Cx)
Get the SCL high and low period.
__STATIC_INLINE void LL_I2C_ConfigSpeed (I2C_TypeDef *I2Cx, uint32_t PeriphClock, uint32_t ClockSpeed, uint32_t DutyCycle)
Configure the SCL speed.
__STATIC_INLINE void LL_I2C_SetMode (I2C_TypeDef *I2Cx, uint32_t PeripheralMode)
Configure peripheral mode.
__STATIC_INLINE uint32_t LL_I2C_GetMode (I2C_TypeDef *I2Cx)
Get peripheral mode.
__STATIC_INLINE void LL_I2C_EnableSMBusAlert (I2C_TypeDef *I2Cx)
Enable SMBus alert (Host or Device mode)
__STATIC_INLINE void LL_I2C_DisableSMBusAlert (I2C_TypeDef *I2Cx)
Disable SMBus alert (Host or Device mode)
__STATIC_INLINE uint32_t LL_I2C_IsEnabledSMBusAlert (I2C_TypeDef *I2Cx)
Check if SMBus alert (Host or Device mode) is enabled or disabled.
__STATIC_INLINE void LL_I2C_EnableSMBusPEC (I2C_TypeDef *I2Cx)
Enable SMBus Packet Error Calculation (PEC).
__STATIC_INLINE void LL_I2C_DisableSMBusPEC (I2C_TypeDef *I2Cx)
Disable SMBus Packet Error Calculation (PEC).
__STATIC_INLINE uint32_t LL_I2C_IsEnabledSMBusPEC (I2C_TypeDef *I2Cx)
Check if SMBus Packet Error Calculation (PEC) is enabled or disabled.
Function Documentation
__STATIC_INLINE void LL_I2C_ConfigSpeed (I2C_TypeDef * I2Cx, uint32_t PeriphClock, uint32_t ClockSpeed, uint32_t DutyCycle)
Configure the SCL speed.
Note:
This bit can only be programmed when the I2C is disabled (PE = 0).
Reference Manual to LL API cross reference:
CR2 FREQ LL_I2C_ConfigSpeed
TRISE TRISE LL_I2C_ConfigSpeed
CCR FS LL_I2C_ConfigSpeed
CCR DUTY LL_I2C_ConfigSpeed
CCR CCR LL_I2C_ConfigSpeed
Parameters:
I2Cx I2C Instance.
PeriphClock Peripheral Clock (in Hz)
ClockSpeed This parameter must be a value lower than 400kHz (in Hz).
DutyCycle This parameter can be one of the following values:
LL_I2C_DUTYCYCLE_2
LL_I2C_DUTYCYCLE_16_9
Return values:
None
Definition at line 729 of file stm32f1xx_ll_i2c.h.
References __LL_I2C_FREQ_HZ_TO_MHZ, __LL_I2C_RISE_TIME, LL_I2C_CLOCK_SPEED_FAST_MODE, LL_I2C_CLOCK_SPEED_STANDARD_MODE, and LL_I2C_MAX_SPEED_STANDARD.
Referenced by LL_I2C_Init().
__STATIC_INLINE void LL_I2C_Disable (I2C_TypeDef * I2Cx)
Disable I2C peripheral (PE = 0).
Reference Manual to LL API cross reference:
CR1 PE LL_I2C_Disable
Parameters:
I2Cx I2C Instance.
Return values:
None
Definition at line 360 of file stm32f1xx_ll_i2c.h.
Referenced by LL_I2C_Init().
__STATIC_INLINE void LL_I2C_DisableClockStretching (I2C_TypeDef * I2Cx)
Disable Clock stretching.
Note:
This bit can only be programmed when the I2C is disabled (PE = 0).
Reference Manual to LL API cross reference:
CR1 NOSTRETCH LL_I2C_DisableClockStretching
Parameters:
I2Cx I2C Instance.
Return values:
None
Definition at line 473 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE void LL_I2C_DisableDMAReq_RX (I2C_TypeDef * I2Cx)
Disable DMA reception requests.
Reference Manual to LL API cross reference:
CR2 DMAEN LL_I2C_DisableDMAReq_RX
Parameters:
I2Cx I2C Instance.
Return values:
None
Definition at line 427 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE void LL_I2C_DisableDMAReq_TX (I2C_TypeDef * I2Cx)
Disable DMA transmission requests.
Reference Manual to LL API cross reference:
CR2 DMAEN LL_I2C_DisableDMAReq_TX
Parameters:
I2Cx I2C Instance.
Return values:
None
Definition at line 394 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE void LL_I2C_DisableGeneralCall (I2C_TypeDef * I2Cx)
Disable General Call.
Note:
When disabled the Address 0x00 is NACKed.
Reference Manual to LL API cross reference:
CR1 ENGC LL_I2C_DisableGeneralCall
Parameters:
I2Cx I2C Instance.
Return values:
None
Definition at line 508 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE void LL_I2C_DisableOwnAddress2 (I2C_TypeDef * I2Cx)
Disable acknowledge on Own Address2 match address.
Reference Manual to LL API cross reference:
OAR2 ENDUAL LL_I2C_DisableOwnAddress2
Parameters:
I2Cx I2C Instance.
Return values:
None
Definition at line 572 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE void LL_I2C_DisableSMBusAlert (I2C_TypeDef * I2Cx)
Disable SMBus alert (Host or Device mode)
Note:
Macro IS_SMBUS_ALL_INSTANCE(I2Cx) can be used to check whether or not SMBus feature is supported by the I2Cx Instance.
SMBus Device mode:
SMBus Alert pin is not drived (can be used as a standard GPIO) and Alert Response Address Header acknowledge is disabled. SMBus Host mode:
SMBus Alert pin management is not supported.
Reference Manual to LL API cross reference:
CR1 ALERT LL_I2C_DisableSMBusAlert
Parameters:
I2Cx I2C Instance.
Return values:
None
Definition at line 833 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE void LL_I2C_DisableSMBusPEC (I2C_TypeDef * I2Cx)
Disable SMBus Packet Error Calculation (PEC).
Note:
Macro IS_SMBUS_ALL_INSTANCE(I2Cx) can be used to check whether or not SMBus feature is supported by the I2Cx Instance.
Reference Manual to LL API cross reference:
CR1 ENPEC LL_I2C_DisableSMBusPEC
Parameters:
I2Cx I2C Instance.
Return values:
None
Definition at line 872 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE uint32_t LL_I2C_DMA_GetRegAddr (I2C_TypeDef * I2Cx)
Get the data register address used for DMA transfer.
Reference Manual to LL API cross reference:
DR DR LL_I2C_DMA_GetRegAddr
Parameters:
I2Cx I2C Instance.
Return values:
Address of data register
Definition at line 449 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE void LL_I2C_Enable (I2C_TypeDef * I2Cx)
Enable I2C peripheral (PE = 1).
Reference Manual to LL API cross reference:
CR1 PE LL_I2C_Enable
Parameters:
I2Cx I2C Instance.
Return values:
None
Definition at line 349 of file stm32f1xx_ll_i2c.h.
Referenced by LL_I2C_Init().
__STATIC_INLINE void LL_I2C_EnableClockStretching (I2C_TypeDef * I2Cx)
Enable Clock stretching.
Note:
This bit can only be programmed when the I2C is disabled (PE = 0).
Reference Manual to LL API cross reference:
CR1 NOSTRETCH LL_I2C_EnableClockStretching
Parameters:
I2Cx I2C Instance.
Return values:
None
Definition at line 461 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE void LL_I2C_EnableDMAReq_RX (I2C_TypeDef * I2Cx)
Enable DMA reception requests.
Reference Manual to LL API cross reference:
CR2 DMAEN LL_I2C_EnableDMAReq_RX
Parameters:
I2Cx I2C Instance.
Return values:
None
Definition at line 416 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE void LL_I2C_EnableDMAReq_TX (I2C_TypeDef * I2Cx)
Enable DMA transmission requests.
Reference Manual to LL API cross reference:
CR2 DMAEN LL_I2C_EnableDMAReq_TX
Parameters:
I2Cx I2C Instance.
Return values:
None
Definition at line 383 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE void LL_I2C_EnableGeneralCall (I2C_TypeDef * I2Cx)
Enable General Call.
Note:
When enabled the Address 0x00 is ACKed.
Reference Manual to LL API cross reference:
CR1 ENGC LL_I2C_EnableGeneralCall
Parameters:
I2Cx I2C Instance.
Return values:
None
Definition at line 496 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE void LL_I2C_EnableOwnAddress2 (I2C_TypeDef * I2Cx)
Enable acknowledge on Own Address2 match address.
Reference Manual to LL API cross reference:
OAR2 ENDUAL LL_I2C_EnableOwnAddress2
Parameters:
I2Cx I2C Instance.
Return values:
None
Definition at line 561 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE void LL_I2C_EnableSMBusAlert (I2C_TypeDef * I2Cx)
Enable SMBus alert (Host or Device mode)
Note:
Macro IS_SMBUS_ALL_INSTANCE(I2Cx) can be used to check whether or not SMBus feature is supported by the I2Cx Instance.
SMBus Device mode:
SMBus Alert pin is drived low and Alert Response Address Header acknowledge is enabled. SMBus Host mode:
SMBus Alert pin management is supported.
Reference Manual to LL API cross reference:
CR1 ALERT LL_I2C_EnableSMBusAlert
Parameters:
I2Cx I2C Instance.
Return values:
None
Definition at line 815 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE void LL_I2C_EnableSMBusPEC (I2C_TypeDef * I2Cx)
Enable SMBus Packet Error Calculation (PEC).
Note:
Macro IS_SMBUS_ALL_INSTANCE(I2Cx) can be used to check whether or not SMBus feature is supported by the I2Cx Instance.
Reference Manual to LL API cross reference:
CR1 ENPEC LL_I2C_EnableSMBusPEC
Parameters:
I2Cx I2C Instance.
Return values:
None
Definition at line 859 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE uint32_t LL_I2C_GetClockPeriod (I2C_TypeDef * I2Cx)
Get the SCL high and low period.
Reference Manual to LL API cross reference:
CCR CCR LL_I2C_GetClockPeriod
Parameters:
I2Cx I2C Instance.
Return values:
Value between Min_Data=0x004 and Max_Data=0xFFF, except in FAST DUTY mode where Min_Data=0x001.
Definition at line 708 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE uint32_t LL_I2C_GetClockSpeedMode (I2C_TypeDef * I2Cx)
Get the the I2C master speed mode.
Reference Manual to LL API cross reference:
CCR FS LL_I2C_GetClockSpeedMode
Parameters:
I2Cx I2C Instance.
Return values:
Returned value can be one of the following values:
LL_I2C_CLOCK_SPEED_STANDARD_MODE
LL_I2C_CLOCK_SPEED_FAST_MODE
Definition at line 660 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE uint32_t LL_I2C_GetDutyCycle (I2C_TypeDef * I2Cx)
Get the Duty cycle (Fast mode only).
Reference Manual to LL API cross reference:
CCR DUTY LL_I2C_GetDutyCycle
Parameters:
I2Cx I2C Instance.
Return values:
Returned value can be one of the following values:
LL_I2C_DUTYCYCLE_2
LL_I2C_DUTYCYCLE_16_9
Definition at line 633 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE uint32_t LL_I2C_GetMode (I2C_TypeDef * I2Cx)
Get peripheral mode.
Note:
Macro IS_SMBUS_ALL_INSTANCE(I2Cx) can be used to check whether or not SMBus feature is supported by the I2Cx Instance.
Reference Manual to LL API cross reference:
CR1 SMBUS LL_I2C_GetMode
CR1 SMBTYPE LL_I2C_GetMode
CR1 ENARP LL_I2C_GetMode
Parameters:
I2Cx I2C Instance.
Return values:
Returned value can be one of the following values:
LL_I2C_MODE_I2C
LL_I2C_MODE_SMBUS_HOST
LL_I2C_MODE_SMBUS_DEVICE
LL_I2C_MODE_SMBUS_DEVICE_ARP
Definition at line 797 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE uint32_t LL_I2C_GetPeriphClock (I2C_TypeDef * I2Cx)
Get the Peripheral clock frequency.
Reference Manual to LL API cross reference:
CR2 FREQ LL_I2C_GetPeriphClock
Parameters:
I2Cx I2C Instance.
Return values:
Value of Peripheral Clock (in Hz)
Definition at line 606 of file stm32f1xx_ll_i2c.h.
References __LL_I2C_FREQ_MHZ_TO_HZ.
__STATIC_INLINE uint32_t LL_I2C_GetRiseTime (I2C_TypeDef * I2Cx)
Get the SCL, SDA rising time.
Reference Manual to LL API cross reference:
TRISE TRISE LL_I2C_GetRiseTime
Parameters:
I2Cx I2C Instance.
Return values:
Value between Min_Data=0x02 and Max_Data=0x3F
Definition at line 684 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE uint32_t LL_I2C_IsEnabled (I2C_TypeDef * I2Cx)
Check if the I2C peripheral is enabled or disabled.
Reference Manual to LL API cross reference:
CR1 PE LL_I2C_IsEnabled
Parameters:
I2Cx I2C Instance.
Return values:
State of bit (1 or 0).
Definition at line 371 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE uint32_t LL_I2C_IsEnabledClockStretching (I2C_TypeDef * I2Cx)
Check if Clock stretching is enabled or disabled.
Reference Manual to LL API cross reference:
CR1 NOSTRETCH LL_I2C_IsEnabledClockStretching
Parameters:
I2Cx I2C Instance.
Return values:
State of bit (1 or 0).
Definition at line 484 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE uint32_t LL_I2C_IsEnabledDMAReq_RX (I2C_TypeDef * I2Cx)
Check if DMA reception requests are enabled or disabled.
Reference Manual to LL API cross reference:
CR2 DMAEN LL_I2C_IsEnabledDMAReq_RX
Parameters:
I2Cx I2C Instance.
Return values:
State of bit (1 or 0).
Definition at line 438 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE uint32_t LL_I2C_IsEnabledDMAReq_TX (I2C_TypeDef * I2Cx)
Check if DMA transmission requests are enabled or disabled.
Reference Manual to LL API cross reference:
CR2 DMAEN LL_I2C_IsEnabledDMAReq_TX
Parameters:
I2Cx I2C Instance.
Return values:
State of bit (1 or 0).
Definition at line 405 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE uint32_t LL_I2C_IsEnabledGeneralCall (I2C_TypeDef * I2Cx)
Check if General Call is enabled or disabled.
Reference Manual to LL API cross reference:
CR1 ENGC LL_I2C_IsEnabledGeneralCall
Parameters:
I2Cx I2C Instance.
Return values:
State of bit (1 or 0).
Definition at line 519 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE uint32_t LL_I2C_IsEnabledOwnAddress2 (I2C_TypeDef * I2Cx)
Check if Own Address1 acknowledge is enabled or disabled.
Reference Manual to LL API cross reference:
OAR2 ENDUAL LL_I2C_IsEnabledOwnAddress2
Parameters:
I2Cx I2C Instance.
Return values:
State of bit (1 or 0).
Definition at line 583 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE uint32_t LL_I2C_IsEnabledSMBusAlert (I2C_TypeDef * I2Cx)
Check if SMBus alert (Host or Device mode) is enabled or disabled.
Note:
Macro IS_SMBUS_ALL_INSTANCE(I2Cx) can be used to check whether or not SMBus feature is supported by the I2Cx Instance.
Reference Manual to LL API cross reference:
CR1 ALERT LL_I2C_IsEnabledSMBusAlert
Parameters:
I2Cx I2C Instance.
Return values:
State of bit (1 or 0).
Definition at line 846 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE uint32_t LL_I2C_IsEnabledSMBusPEC (I2C_TypeDef * I2Cx)
Check if SMBus Packet Error Calculation (PEC) is enabled or disabled.
Note:
Macro IS_SMBUS_ALL_INSTANCE(I2Cx) can be used to check whether or not SMBus feature is supported by the I2Cx Instance.
Reference Manual to LL API cross reference:
CR1 ENPEC LL_I2C_IsEnabledSMBusPEC
Parameters:
I2Cx I2C Instance.
Return values:
State of bit (1 or 0).
Definition at line 885 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE void LL_I2C_SetClockPeriod (I2C_TypeDef * I2Cx, uint32_t ClockPeriod)
Configure the SCL high and low period.
Note:
This bit can only be programmed when the I2C is disabled (PE = 0).
Reference Manual to LL API cross reference:
CCR CCR LL_I2C_SetClockPeriod
Parameters:
I2Cx I2C Instance.
ClockPeriod This parameter must be a value between Min_Data=0x004 and Max_Data=0xFFF, except in FAST DUTY mode where Min_Data=0x001.
Return values:
None
Definition at line 697 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE void LL_I2C_SetClockSpeedMode (I2C_TypeDef * I2Cx, uint32_t ClockSpeedMode)
Configure the I2C master clock speed mode.
Reference Manual to LL API cross reference:
CCR FS LL_I2C_SetClockSpeedMode
Parameters:
I2Cx I2C Instance.
ClockSpeedMode This parameter can be one of the following values:
LL_I2C_CLOCK_SPEED_STANDARD_MODE
LL_I2C_CLOCK_SPEED_FAST_MODE
Return values:
None
Definition at line 647 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE void LL_I2C_SetDutyCycle (I2C_TypeDef * I2Cx, uint32_t DutyCycle)
Configure the Duty cycle (Fast mode only).
Reference Manual to LL API cross reference:
CCR DUTY LL_I2C_SetDutyCycle
Parameters:
I2Cx I2C Instance.
DutyCycle This parameter can be one of the following values:
LL_I2C_DUTYCYCLE_2
LL_I2C_DUTYCYCLE_16_9
Return values:
None
Definition at line 620 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE void LL_I2C_SetMode (I2C_TypeDef * I2Cx, uint32_t PeripheralMode)
Configure peripheral mode.
Note:
Macro IS_SMBUS_ALL_INSTANCE(I2Cx) can be used to check whether or not SMBus feature is supported by the I2Cx Instance.
Reference Manual to LL API cross reference:
CR1 SMBUS LL_I2C_SetMode
CR1 SMBTYPE LL_I2C_SetMode
CR1 ENARP LL_I2C_SetMode
Parameters:
I2Cx I2C Instance.
PeripheralMode This parameter can be one of the following values:
LL_I2C_MODE_I2C
LL_I2C_MODE_SMBUS_HOST
LL_I2C_MODE_SMBUS_DEVICE
LL_I2C_MODE_SMBUS_DEVICE_ARP
Return values:
None
Definition at line 778 of file stm32f1xx_ll_i2c.h.
Referenced by LL_I2C_Init().
__STATIC_INLINE void LL_I2C_SetOwnAddress1 (I2C_TypeDef * I2Cx, uint32_t OwnAddress1, uint32_t OwnAddrSize)
Set the Own Address1.
Reference Manual to LL API cross reference:
OAR1 ADD0 LL_I2C_SetOwnAddress1
OAR1 ADD1_7 LL_I2C_SetOwnAddress1
OAR1 ADD8_9 LL_I2C_SetOwnAddress1
OAR1 ADDMODE LL_I2C_SetOwnAddress1
Parameters:
I2Cx I2C Instance.
OwnAddress1 This parameter must be a value between Min_Data=0 and Max_Data=0x3FF.
OwnAddrSize This parameter can be one of the following values:
LL_I2C_OWNADDRESS1_7BIT
LL_I2C_OWNADDRESS1_10BIT
Return values:
None
Definition at line 537 of file stm32f1xx_ll_i2c.h.
Referenced by LL_I2C_Init().
__STATIC_INLINE void LL_I2C_SetOwnAddress2 (I2C_TypeDef * I2Cx, uint32_t OwnAddress2)
Set the 7bits Own Address2.
Note:
This action has no effect if own address2 is enabled.
Reference Manual to LL API cross reference:
OAR2 ADD2 LL_I2C_SetOwnAddress2
Parameters:
I2Cx I2C Instance.
OwnAddress2 This parameter must be a value between Min_Data=0 and Max_Data=0x7F.
Return values:
None
Definition at line 550 of file stm32f1xx_ll_i2c.h.
__STATIC_INLINE void LL_I2C_SetPeriphClock (I2C_TypeDef * I2Cx, uint32_t PeriphClock)
Configure the Peripheral clock frequency.
Reference Manual to LL API cross reference:
CR2 FREQ LL_I2C_SetPeriphClock
Parameters:
I2Cx I2C Instance.
PeriphClock Peripheral Clock (in Hz)
Return values:
None
Definition at line 595 of file stm32f1xx_ll_i2c.h.
References __LL_I2C_FREQ_HZ_TO_MHZ.
__STATIC_INLINE void LL_I2C_SetRiseTime (I2C_TypeDef * I2Cx, uint32_t RiseTime)
Configure the SCL, SDA rising time.
Note:
This bit can only be programmed when the I2C is disabled (PE = 0).
Reference Manual to LL API cross reference:
TRISE TRISE LL_I2C_SetRiseTime
Parameters:
I2Cx I2C Instance.
RiseTime This parameter must be a value between Min_Data=0x02 and Max_Data=0x3F.
Return values:
None
Definition at line 673 of file stm32f1xx_ll_i2c.h.