STM32F100xE HAL User Manual: RCC Private functions
RCC Private functions
RCC
Functions
uint32_t RCC_GetSystemClockFreq (void)
Return SYSTEM clock frequency.
uint32_t RCC_GetHCLKClockFreq (uint32_t SYSCLK_Frequency)
Return HCLK clock frequency.
uint32_t RCC_GetPCLK1ClockFreq (uint32_t HCLK_Frequency)
Return PCLK1 clock frequency.
uint32_t RCC_GetPCLK2ClockFreq (uint32_t HCLK_Frequency)
Return PCLK2 clock frequency.
uint32_t RCC_PLL_GetFreqDomain_SYS (void)
Return PLL clock frequency used for system domain.
Function Documentation
uint32_t RCC_GetHCLKClockFreq (uint32_t SYSCLK_Frequency)
Return HCLK clock frequency.
Parameters:
SYSCLK_Frequency SYSCLK clock frequency
Return values:
HCLK clock frequency (in Hz)
Definition at line 372 of file stm32f1xx_ll_rcc.c.
References __LL_RCC_CALC_HCLK_FREQ, and LL_RCC_GetAHBPrescaler().
Referenced by LL_RCC_GetADCClockFreq(), and LL_RCC_GetSystemClocksFreq().
uint32_t RCC_GetPCLK1ClockFreq (uint32_t HCLK_Frequency)
Return PCLK1 clock frequency.
Parameters:
HCLK_Frequency HCLK clock frequency
Return values:
PCLK1 clock frequency (in Hz)
Definition at line 383 of file stm32f1xx_ll_rcc.c.
References __LL_RCC_CALC_PCLK1_FREQ, and LL_RCC_GetAPB1Prescaler().
Referenced by LL_RCC_GetSystemClocksFreq().
uint32_t RCC_GetPCLK2ClockFreq (uint32_t HCLK_Frequency)
Return PCLK2 clock frequency.
Parameters:
HCLK_Frequency HCLK clock frequency
Return values:
PCLK2 clock frequency (in Hz)
Definition at line 394 of file stm32f1xx_ll_rcc.c.
References __LL_RCC_CALC_PCLK2_FREQ, and LL_RCC_GetAPB2Prescaler().
Referenced by LL_RCC_GetADCClockFreq(), and LL_RCC_GetSystemClocksFreq().
uint32_t RCC_GetSystemClockFreq (void)
Return SYSTEM clock frequency.
Return values:
SYSTEM clock frequency (in Hz)
Definition at line 340 of file stm32f1xx_ll_rcc.c.
References HSE_VALUE, HSI_VALUE, LL_RCC_GetSysClkSource(), LL_RCC_SYS_CLKSOURCE_STATUS_HSE, LL_RCC_SYS_CLKSOURCE_STATUS_HSI, LL_RCC_SYS_CLKSOURCE_STATUS_PLL, and RCC_PLL_GetFreqDomain_SYS().
Referenced by LL_RCC_GetADCClockFreq(), and LL_RCC_GetSystemClocksFreq().
uint32_t RCC_PLL_GetFreqDomain_SYS (void)
Return PLL clock frequency used for system domain.
Return values:
PLL clock frequency (in Hz)
Definition at line 404 of file stm32f1xx_ll_rcc.c.
References __LL_RCC_CALC_PLLCLK_FREQ, HSE_VALUE, HSI_VALUE, LL_RCC_PLL_GetMainSource(), LL_RCC_PLL_GetMultiplicator(), LL_RCC_PLL_GetPrediv(), LL_RCC_PLLSOURCE_HSE, and LL_RCC_PLLSOURCE_HSI_DIV_2.
Referenced by RCC_GetSystemClockFreq().