STM32F100xE HAL User Manual: RTC Second functions
RTC Second functions
RTCEx Exported Functions
RTC Second functions.
Functions
HAL_StatusTypeDef HAL_RTCEx_SetSecond_IT (RTC_HandleTypeDef *hrtc)
Sets Interrupt for second.
HAL_StatusTypeDef HAL_RTCEx_DeactivateSecond (RTC_HandleTypeDef *hrtc)
Deactivates Second.
void HAL_RTCEx_RTCIRQHandler (RTC_HandleTypeDef *hrtc)
This function handles second interrupt request.
__weak void HAL_RTCEx_RTCEventCallback (RTC_HandleTypeDef *hrtc)
Second event callback.
__weak void HAL_RTCEx_RTCEventErrorCallback (RTC_HandleTypeDef *hrtc)
Second event error callback.
Detailed Description
RTC Second functions.
 ===============================================================================
                 ##### RTC Second functions #####
 ===============================================================================
 [..] This section provides functions implementing second interupt handlers
Function Documentation
HAL_StatusTypeDef HAL_RTCEx_DeactivateSecond (RTC_HandleTypeDef * hrtc)
Deactivates Second.
Parameters:
hrtc,: pointer to a RTC_HandleTypeDef structure that contains the configuration information for RTC.
Return values:
HAL status
Definition at line 349 of file stm32f1xx_hal_rtc_ex.c.
References __HAL_RTC_SECOND_DISABLE_IT, HAL_RTC_STATE_BUSY, HAL_RTC_STATE_READY, RTC_IT_SEC, and RTC_HandleTypeDef::State.
void HAL_RTCEx_RTCEventCallback (RTC_HandleTypeDef * hrtc)
Second event callback.
Parameters:
hrtc,: pointer to a RTC_HandleTypeDef structure that contains the configuration information for RTC.
Return values:
None
Definition at line 419 of file stm32f1xx_hal_rtc_ex.c.
Referenced by HAL_RTCEx_RTCIRQHandler().
void HAL_RTCEx_RTCEventErrorCallback (RTC_HandleTypeDef * hrtc)
Second event error callback.
Parameters:
hrtc,: pointer to a RTC_HandleTypeDef structure that contains the configuration information for RTC.
Return values:
None
Definition at line 434 of file stm32f1xx_hal_rtc_ex.c.
Referenced by HAL_RTCEx_RTCIRQHandler().
void HAL_RTCEx_RTCIRQHandler (RTC_HandleTypeDef * hrtc)
This function handles second interrupt request.
Parameters:
hrtc,: pointer to a RTC_HandleTypeDef structure that contains the configuration information for RTC.
Return values:
None
Definition at line 379 of file stm32f1xx_hal_rtc_ex.c.
References __HAL_RTC_OVERFLOW_CLEAR_FLAG, __HAL_RTC_SECOND_CLEAR_FLAG, __HAL_RTC_SECOND_GET_FLAG, __HAL_RTC_SECOND_GET_IT_SOURCE, HAL_RTC_STATE_ERROR, HAL_RTC_STATE_READY, HAL_RTCEx_RTCEventCallback(), HAL_RTCEx_RTCEventErrorCallback(), RTC_FLAG_OW, RTC_FLAG_SEC, RTC_IT_SEC, and RTC_HandleTypeDef::State.
HAL_StatusTypeDef HAL_RTCEx_SetSecond_IT (RTC_HandleTypeDef * hrtc)
Sets Interrupt for second.
Parameters:
hrtc,: pointer to a RTC_HandleTypeDef structure that contains the configuration information for RTC.
Return values:
HAL status
Definition at line 319 of file stm32f1xx_hal_rtc_ex.c.
References __HAL_RTC_SECOND_ENABLE_IT, HAL_RTC_STATE_BUSY, HAL_RTC_STATE_READY, RTC_IT_SEC, and RTC_HandleTypeDef::State.