STM32F100xE HAL User Manual: SPI Private Functions
SPI Private Functions
SPI
Private functions.
Functions
static void SPI_DMATransmitCplt (DMA_HandleTypeDef *hdma)
DMA SPI transmit process complete callback.
static void SPI_DMAReceiveCplt (DMA_HandleTypeDef *hdma)
DMA SPI receive process complete callback.
static void SPI_DMATransmitReceiveCplt (DMA_HandleTypeDef *hdma)
DMA SPI transmit receive process complete callback.
static void SPI_DMAHalfTransmitCplt (DMA_HandleTypeDef *hdma)
DMA SPI half transmit process complete callback.
static void SPI_DMAHalfReceiveCplt (DMA_HandleTypeDef *hdma)
DMA SPI half receive process complete callback.
static void SPI_DMAHalfTransmitReceiveCplt (DMA_HandleTypeDef *hdma)
DMA SPI half transmit receive process complete callback.
static void SPI_DMAError (DMA_HandleTypeDef *hdma)
DMA SPI communication error callback.
static void SPI_DMAAbortOnError (DMA_HandleTypeDef *hdma)
DMA SPI communication abort callback, when initiated by HAL services on Error (To be called at end of DMA Abort procedure following error occurrence).
static void SPI_DMATxAbortCallback (DMA_HandleTypeDef *hdma)
DMA SPI Tx communication abort callback, when initiated by user (To be called at end of DMA Tx Abort procedure following user abort request).
static void SPI_DMARxAbortCallback (DMA_HandleTypeDef *hdma)
DMA SPI Rx communication abort callback, when initiated by user (To be called at end of DMA Rx Abort procedure following user abort request).
static HAL_StatusTypeDef SPI_WaitFlagStateUntilTimeout (SPI_HandleTypeDef *hspi, uint32_t Flag, FlagStatus State, uint32_t Timeout, uint32_t Tickstart)
Handle SPI Communication Timeout.
static void SPI_TxISR_8BIT (struct __SPI_HandleTypeDef *hspi)
Handle the data 8-bit transmit in Interrupt mode.
static void SPI_TxISR_16BIT (struct __SPI_HandleTypeDef *hspi)
Handle the data 16-bit transmit in Interrupt mode.
static void SPI_RxISR_8BIT (struct __SPI_HandleTypeDef *hspi)
Manage the receive 8-bit in Interrupt context.
static void SPI_RxISR_16BIT (struct __SPI_HandleTypeDef *hspi)
Manage the 16-bit receive in Interrupt context.
static void SPI_2linesRxISR_8BIT (struct __SPI_HandleTypeDef *hspi)
Rx 8-bit handler for Transmit and Receive in Interrupt mode.
static void SPI_2linesTxISR_8BIT (struct __SPI_HandleTypeDef *hspi)
Tx 8-bit handler for Transmit and Receive in Interrupt mode.
static void SPI_2linesTxISR_16BIT (struct __SPI_HandleTypeDef *hspi)
Tx 16-bit handler for Transmit and Receive in Interrupt mode.
static void SPI_2linesRxISR_16BIT (struct __SPI_HandleTypeDef *hspi)
Rx 16-bit handler for Transmit and Receive in Interrupt mode.
static void SPI_RxISR_8BITCRC (struct __SPI_HandleTypeDef *hspi)
Manage the CRC 8-bit receive in Interrupt context.
static void SPI_RxISR_16BITCRC (struct __SPI_HandleTypeDef *hspi)
Manage the CRC 16-bit receive in Interrupt context.
static void SPI_2linesRxISR_8BITCRC (struct __SPI_HandleTypeDef *hspi)
Rx 8-bit handler for Transmit and Receive in Interrupt mode.
static void SPI_2linesRxISR_16BITCRC (struct __SPI_HandleTypeDef *hspi)
Manage the CRC 16-bit receive for Transmit and Receive in Interrupt mode.
static void SPI_AbortRx_ISR (SPI_HandleTypeDef *hspi)
Handle abort a Rx transaction.
static void SPI_AbortTx_ISR (SPI_HandleTypeDef *hspi)
Handle abort a Tx or Rx/Tx transaction.
static void SPI_CloseRxTx_ISR (SPI_HandleTypeDef *hspi)
Handle the end of the RXTX transaction.
static void SPI_CloseRx_ISR (SPI_HandleTypeDef *hspi)
Handle the end of the RX transaction.
static void SPI_CloseTx_ISR (SPI_HandleTypeDef *hspi)
Handle the end of the TX transaction.
static HAL_StatusTypeDef SPI_EndRxTransaction (SPI_HandleTypeDef *hspi, uint32_t Timeout, uint32_t Tickstart)
Handle the check of the RX transaction complete.
static HAL_StatusTypeDef SPI_EndRxTxTransaction (SPI_HandleTypeDef *hspi, uint32_t Timeout, uint32_t Tickstart)
Handle the check of the RXTX or TX transaction complete.
uint8_t SPI_ISCRCErrorValid (SPI_HandleTypeDef *hspi)
Checks if encountered CRC error could be corresponding to wrongly detected errors according to SPI instance, Device type, and revision ID.
Detailed Description
Private functions.
Function Documentation
static void SPI_2linesRxISR_16BIT (struct __SPI_HandleTypeDef * hspi) [static]
Rx 16-bit handler for Transmit and Receive in Interrupt mode.
Parameters:
hspi pointer to a SPI_HandleTypeDef structure that contains the configuration information for SPI module.
Return values:
None
Definition at line 3203 of file stm32f1xx_hal_spi.c.
References __HAL_SPI_DISABLE_IT, SPI_InitTypeDef::CRCCalculation, __SPI_HandleTypeDef::Init, __SPI_HandleTypeDef::Instance, __SPI_HandleTypeDef::pRxBuffPtr, __SPI_HandleTypeDef::RxISR, __SPI_HandleTypeDef::RxXferCount, SPI_2linesRxISR_16BITCRC(), SPI_CloseRxTx_ISR(), SPI_CRCCALCULATION_ENABLE, SPI_IT_RXNE, and __SPI_HandleTypeDef::TxXferCount.
Referenced by HAL_SPI_TransmitReceive_IT().
static void SPI_2linesRxISR_16BITCRC (struct __SPI_HandleTypeDef * hspi) [static]
Manage the CRC 16-bit receive for Transmit and Receive in Interrupt mode.
Parameters:
hspi pointer to a SPI_HandleTypeDef structure that contains the configuration information for SPI module.
Return values:
None
Definition at line 3237 of file stm32f1xx_hal_spi.c.
References __HAL_SPI_DISABLE_IT, __SPI_HandleTypeDef::Instance, SPI_CloseRxTx_ISR(), and SPI_IT_RXNE.
Referenced by SPI_2linesRxISR_16BIT().
static void SPI_2linesRxISR_8BIT (struct __SPI_HandleTypeDef * hspi) [static]
Rx 8-bit handler for Transmit and Receive in Interrupt mode.
Parameters:
hspi pointer to a SPI_HandleTypeDef structure that contains the configuration information for SPI module.
Return values:
None
Definition at line 3111 of file stm32f1xx_hal_spi.c.
References __HAL_SPI_DISABLE_IT, SPI_InitTypeDef::CRCCalculation, __SPI_HandleTypeDef::Init, __SPI_HandleTypeDef::Instance, __SPI_HandleTypeDef::pRxBuffPtr, __SPI_HandleTypeDef::RxISR, __SPI_HandleTypeDef::RxXferCount, SPI_2linesRxISR_8BITCRC(), SPI_CloseRxTx_ISR(), SPI_CRCCALCULATION_ENABLE, SPI_IT_ERR, SPI_IT_RXNE, and __SPI_HandleTypeDef::TxXferCount.
Referenced by HAL_SPI_TransmitReceive_IT().
static void SPI_2linesRxISR_8BITCRC (struct __SPI_HandleTypeDef * hspi) [static]
Rx 8-bit handler for Transmit and Receive in Interrupt mode.
Parameters:
hspi pointer to a SPI_HandleTypeDef structure that contains the configuration information for SPI module.
Return values:
None
Definition at line 3146 of file stm32f1xx_hal_spi.c.
References __HAL_SPI_DISABLE_IT, __SPI_HandleTypeDef::Instance, SPI_CloseRxTx_ISR(), SPI_IT_ERR, SPI_IT_RXNE, and __SPI_HandleTypeDef::TxXferCount.
Referenced by SPI_2linesRxISR_8BIT().
static void SPI_2linesTxISR_16BIT (struct __SPI_HandleTypeDef * hspi) [static]
Tx 16-bit handler for Transmit and Receive in Interrupt mode.
Parameters:
hspi pointer to a SPI_HandleTypeDef structure that contains the configuration information for SPI module.
Return values:
None
Definition at line 3255 of file stm32f1xx_hal_spi.c.
References __HAL_SPI_DISABLE_IT, SPI_InitTypeDef::CRCCalculation, __SPI_HandleTypeDef::Init, __SPI_HandleTypeDef::Instance, __SPI_HandleTypeDef::pTxBuffPtr, __SPI_HandleTypeDef::RxXferCount, SPI_CloseRxTx_ISR(), SPI_CRCCALCULATION_ENABLE, SPI_IT_TXE, and __SPI_HandleTypeDef::TxXferCount.
Referenced by HAL_SPI_TransmitReceive_IT().
static void SPI_2linesTxISR_8BIT (struct __SPI_HandleTypeDef * hspi) [static]
Tx 8-bit handler for Transmit and Receive in Interrupt mode.
Parameters:
hspi pointer to a SPI_HandleTypeDef structure that contains the configuration information for SPI module.
Return values:
None
Definition at line 3167 of file stm32f1xx_hal_spi.c.
References __HAL_SPI_DISABLE_IT, SPI_InitTypeDef::CRCCalculation, __SPI_HandleTypeDef::Init, __SPI_HandleTypeDef::Instance, __SPI_HandleTypeDef::pTxBuffPtr, __SPI_HandleTypeDef::RxXferCount, SPI_CloseRxTx_ISR(), SPI_CRCCALCULATION_ENABLE, SPI_IT_TXE, and __SPI_HandleTypeDef::TxXferCount.
Referenced by HAL_SPI_TransmitReceive_IT().
static void SPI_AbortRx_ISR (SPI_HandleTypeDef * hspi) [static]
Handle abort a Rx transaction.
Parameters:
hspi pointer to a SPI_HandleTypeDef structure that contains the configuration information for SPI module.
Return values:
None
Definition at line 3781 of file stm32f1xx_hal_spi.c.
References __HAL_SPI_DISABLE, __SPI_HandleTypeDef::ErrorCode, HAL_SPI_ERROR_ABORT, HAL_SPI_STATE_ABORT, __SPI_HandleTypeDef::Instance, SPI_DEFAULT_TIMEOUT, SPI_FLAG_TXE, and __SPI_HandleTypeDef::State.
Referenced by HAL_SPI_Abort(), and HAL_SPI_Abort_IT().
static void SPI_AbortTx_ISR (SPI_HandleTypeDef * hspi) [static]
Handle abort a Tx or Rx/Tx transaction.
Parameters:
hspi pointer to a SPI_HandleTypeDef structure that contains the configuration information for SPI module.
Return values:
None
Definition at line 3814 of file stm32f1xx_hal_spi.c.
References __HAL_SPI_DISABLE, HAL_SPI_STATE_ABORT, __SPI_HandleTypeDef::Instance, and __SPI_HandleTypeDef::State.
Referenced by HAL_SPI_Abort(), and HAL_SPI_Abort_IT().
static void SPI_CloseRx_ISR (SPI_HandleTypeDef * hspi) [static]
Handle the end of the RX transaction.
Parameters:
hspi pointer to a SPI_HandleTypeDef structure that contains the configuration information for SPI module.
Return values:
None
Definition at line 3646 of file stm32f1xx_hal_spi.c.
References __HAL_SPI_CLEAR_CRCERRFLAG, __HAL_SPI_CLEAR_OVRFLAG, __HAL_SPI_DISABLE_IT, __HAL_SPI_GET_FLAG, SPI_InitTypeDef::Direction, __SPI_HandleTypeDef::ErrorCode, HAL_GetTick(), HAL_SPI_ERROR_CRC, HAL_SPI_ERROR_FLAG, HAL_SPI_ERROR_NONE, HAL_SPI_ErrorCallback(), HAL_SPI_RxCpltCallback(), HAL_SPI_STATE_READY, __SPI_HandleTypeDef::Init, SPI_DEFAULT_TIMEOUT, SPI_DIRECTION_2LINES, SPI_EndRxTransaction(), SPI_FLAG_CRCERR, SPI_ISCRCErrorValid(), SPI_IT_ERR, SPI_IT_RXNE, SPI_RESET_CRC, SPI_VALID_CRC_ERROR, and __SPI_HandleTypeDef::State.
Referenced by SPI_RxISR_16BIT(), SPI_RxISR_16BITCRC(), SPI_RxISR_8BIT(), and SPI_RxISR_8BITCRC().
static void SPI_CloseRxTx_ISR (SPI_HandleTypeDef * hspi) [static]
Handle the end of the RXTX transaction.
Parameters:
hspi pointer to a SPI_HandleTypeDef structure that contains the configuration information for SPI module.
Return values:
None
Definition at line 3540 of file stm32f1xx_hal_spi.c.
References __HAL_SPI_CLEAR_CRCERRFLAG, __HAL_SPI_CLEAR_OVRFLAG, __HAL_SPI_DISABLE_IT, __HAL_SPI_GET_FLAG, SPI_InitTypeDef::Direction, __SPI_HandleTypeDef::ErrorCode, HAL_GetTick(), HAL_SPI_ERROR_CRC, HAL_SPI_ERROR_FLAG, HAL_SPI_ERROR_NONE, HAL_SPI_ErrorCallback(), HAL_SPI_RxCpltCallback(), HAL_SPI_STATE_BUSY_RX, HAL_SPI_STATE_READY, HAL_SPI_TxRxCpltCallback(), __SPI_HandleTypeDef::Init, __SPI_HandleTypeDef::Instance, SPI_DEFAULT_TIMEOUT, SPI_DIRECTION_2LINES, SPI_EndRxTxTransaction(), SPI_FLAG_CRCERR, SPI_FLAG_TXE, SPI_ISCRCErrorValid(), SPI_IT_ERR, SPI_RESET_CRC, SPI_VALID_CRC_ERROR, and __SPI_HandleTypeDef::State.
Referenced by SPI_2linesRxISR_16BIT(), SPI_2linesRxISR_16BITCRC(), SPI_2linesRxISR_8BIT(), SPI_2linesRxISR_8BITCRC(), SPI_2linesTxISR_16BIT(), and SPI_2linesTxISR_8BIT().
static void SPI_CloseTx_ISR (SPI_HandleTypeDef * hspi) [static]
Handle the end of the TX transaction.
Parameters:
hspi pointer to a SPI_HandleTypeDef structure that contains the configuration information for SPI module.
Return values:
None
Definition at line 3720 of file stm32f1xx_hal_spi.c.
References __HAL_SPI_CLEAR_OVRFLAG, __HAL_SPI_DISABLE_IT, SPI_InitTypeDef::Direction, __SPI_HandleTypeDef::ErrorCode, HAL_GetTick(), HAL_SPI_ERROR_FLAG, HAL_SPI_ERROR_NONE, HAL_SPI_ErrorCallback(), HAL_SPI_STATE_READY, HAL_SPI_TxCpltCallback(), __SPI_HandleTypeDef::Init, __SPI_HandleTypeDef::Instance, SPI_DEFAULT_TIMEOUT, SPI_DIRECTION_2LINES, SPI_EndRxTxTransaction(), SPI_FLAG_TXE, SPI_IT_ERR, SPI_IT_TXE, and __SPI_HandleTypeDef::State.
Referenced by SPI_TxISR_16BIT(), and SPI_TxISR_8BIT().
static void SPI_DMAAbortOnError (DMA_HandleTypeDef * hdma) [static]
DMA SPI communication abort callback, when initiated by HAL services on Error (To be called at end of DMA Abort procedure following error occurrence).
Parameters:
hdma DMA handle.
Return values:
None
Definition at line 2967 of file stm32f1xx_hal_spi.c.
References HAL_SPI_ErrorCallback(), __SPI_HandleTypeDef::RxXferCount, and __SPI_HandleTypeDef::TxXferCount.
Referenced by HAL_SPI_IRQHandler().
static void SPI_DMAError (DMA_HandleTypeDef * hdma) [static]
DMA SPI communication error callback.
Parameters:
hdma pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 2944 of file stm32f1xx_hal_spi.c.
References __SPI_HandleTypeDef::ErrorCode, HAL_SPI_ERROR_DMA, HAL_SPI_ErrorCallback(), HAL_SPI_STATE_READY, __SPI_HandleTypeDef::Instance, and __SPI_HandleTypeDef::State.
Referenced by HAL_SPI_Receive_DMA(), HAL_SPI_Transmit_DMA(), and HAL_SPI_TransmitReceive_DMA().
static void SPI_DMAHalfReceiveCplt (DMA_HandleTypeDef * hdma) [static]
DMA SPI half receive process complete callback.
Parameters:
hdma pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 2908 of file stm32f1xx_hal_spi.c.
References HAL_SPI_RxHalfCpltCallback().
Referenced by HAL_SPI_Receive_DMA(), and HAL_SPI_TransmitReceive_DMA().
static void SPI_DMAHalfTransmitCplt (DMA_HandleTypeDef * hdma) [static]
DMA SPI half transmit process complete callback.
Parameters:
hdma pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 2890 of file stm32f1xx_hal_spi.c.
References HAL_SPI_TxHalfCpltCallback().
Referenced by HAL_SPI_Transmit_DMA().
static void SPI_DMAHalfTransmitReceiveCplt (DMA_HandleTypeDef * hdma) [static]
DMA SPI half transmit receive process complete callback.
Parameters:
hdma pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 2926 of file stm32f1xx_hal_spi.c.
References HAL_SPI_TxRxHalfCpltCallback().
Referenced by HAL_SPI_TransmitReceive_DMA().
static void SPI_DMAReceiveCplt (DMA_HandleTypeDef * hdma) [static]
DMA SPI receive process complete callback.
Parameters:
hdma pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 2720 of file stm32f1xx_hal_spi.c.
References __HAL_SPI_CLEAR_CRCERRFLAG, __HAL_SPI_DISABLE_IT, __HAL_SPI_GET_FLAG, SPI_InitTypeDef::CRCCalculation, __SPI_HandleTypeDef::ErrorCode, HAL_GetTick(), HAL_SPI_ERROR_CRC, HAL_SPI_ERROR_FLAG, HAL_SPI_ERROR_NONE, HAL_SPI_ErrorCallback(), HAL_SPI_RxCpltCallback(), HAL_SPI_STATE_READY, __SPI_HandleTypeDef::Init, __SPI_HandleTypeDef::Instance, __DMA_HandleTypeDef::Instance, __SPI_HandleTypeDef::RxXferCount, SPI_CRCCALCULATION_ENABLE, SPI_DEFAULT_TIMEOUT, SPI_EndRxTransaction(), SPI_FLAG_CRCERR, SPI_FLAG_RXNE, SPI_ISCRCErrorValid(), SPI_IT_ERR, SPI_RESET_CRC, SPI_VALID_CRC_ERROR, SPI_WaitFlagStateUntilTimeout(), and __SPI_HandleTypeDef::State.
Referenced by HAL_SPI_Receive_DMA(), and HAL_SPI_TransmitReceive_DMA().
static void SPI_DMARxAbortCallback (DMA_HandleTypeDef * hdma) [static]
DMA SPI Rx communication abort callback, when initiated by user (To be called at end of DMA Rx Abort procedure following user abort request).
Note:
When this callback is executed, User Abort complete call back is called only if no Abort still ongoing for Tx DMA Handle.
Parameters:
hdma DMA handle.
Return values:
None
Definition at line 3053 of file stm32f1xx_hal_spi.c.
References __HAL_SPI_CLEAR_OVRFLAG, __HAL_SPI_DISABLE, __SPI_HandleTypeDef::ErrorCode, HAL_GetTick(), HAL_SPI_AbortCpltCallback(), HAL_SPI_ERROR_ABORT, HAL_SPI_ERROR_NONE, HAL_SPI_STATE_READY, __SPI_HandleTypeDef::hdmarx, __SPI_HandleTypeDef::hdmatx, __SPI_HandleTypeDef::Instance, __SPI_HandleTypeDef::RxXferCount, SPI_DEFAULT_TIMEOUT, SPI_EndRxTxTransaction(), __SPI_HandleTypeDef::State, __SPI_HandleTypeDef::TxXferCount, and __DMA_HandleTypeDef::XferAbortCallback.
Referenced by HAL_SPI_Abort_IT().
static void SPI_DMATransmitCplt (DMA_HandleTypeDef * hdma) [static]
DMA SPI transmit process complete callback.
Parameters:
hdma pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 2663 of file stm32f1xx_hal_spi.c.
References __HAL_SPI_CLEAR_OVRFLAG, __HAL_SPI_DISABLE_IT, SPI_InitTypeDef::Direction, __SPI_HandleTypeDef::ErrorCode, HAL_GetTick(), HAL_SPI_ERROR_FLAG, HAL_SPI_ERROR_NONE, HAL_SPI_ErrorCallback(), HAL_SPI_STATE_READY, HAL_SPI_TxCpltCallback(), __SPI_HandleTypeDef::Init, __SPI_HandleTypeDef::Instance, __DMA_HandleTypeDef::Instance, SPI_DEFAULT_TIMEOUT, SPI_DIRECTION_2LINES, SPI_EndRxTxTransaction(), SPI_IT_ERR, __SPI_HandleTypeDef::State, and __SPI_HandleTypeDef::TxXferCount.
Referenced by HAL_SPI_Transmit_DMA().
static void SPI_DMATransmitReceiveCplt (DMA_HandleTypeDef * hdma) [static]
DMA SPI transmit receive process complete callback.
Parameters:
hdma pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 2805 of file stm32f1xx_hal_spi.c.
References __HAL_SPI_CLEAR_CRCERRFLAG, __HAL_SPI_DISABLE_IT, __HAL_SPI_GET_FLAG, SPI_InitTypeDef::CRCCalculation, __SPI_HandleTypeDef::ErrorCode, HAL_GetTick(), HAL_SPI_ERROR_CRC, HAL_SPI_ERROR_FLAG, HAL_SPI_ERROR_NONE, HAL_SPI_ErrorCallback(), HAL_SPI_STATE_READY, HAL_SPI_TxRxCpltCallback(), __SPI_HandleTypeDef::Init, __SPI_HandleTypeDef::Instance, __DMA_HandleTypeDef::Instance, __SPI_HandleTypeDef::RxXferCount, SPI_CRCCALCULATION_ENABLE, SPI_DEFAULT_TIMEOUT, SPI_EndRxTxTransaction(), SPI_FLAG_CRCERR, SPI_FLAG_RXNE, SPI_ISCRCErrorValid(), SPI_IT_ERR, SPI_RESET_CRC, SPI_VALID_CRC_ERROR, SPI_WaitFlagStateUntilTimeout(), __SPI_HandleTypeDef::State, and __SPI_HandleTypeDef::TxXferCount.
Referenced by HAL_SPI_TransmitReceive_DMA().
static void SPI_DMATxAbortCallback (DMA_HandleTypeDef * hdma) [static]
DMA SPI Tx communication abort callback, when initiated by user (To be called at end of DMA Tx Abort procedure following user abort request).
Note:
When this callback is executed, User Abort complete call back is called only if no Abort still ongoing for Rx DMA Handle.
Parameters:
hdma DMA handle.
Return values:
None
Definition at line 2989 of file stm32f1xx_hal_spi.c.
References __HAL_SPI_CLEAR_OVRFLAG, __SPI_HandleTypeDef::ErrorCode, HAL_SPI_AbortCpltCallback(), HAL_SPI_ERROR_ABORT, HAL_SPI_ERROR_NONE, HAL_SPI_STATE_READY, __SPI_HandleTypeDef::hdmarx, __SPI_HandleTypeDef::hdmatx, __SPI_HandleTypeDef::Instance, __SPI_HandleTypeDef::RxXferCount, SPI_DEFAULT_TIMEOUT, SPI_FLAG_TXE, __SPI_HandleTypeDef::State, __SPI_HandleTypeDef::TxXferCount, and __DMA_HandleTypeDef::XferAbortCallback.
Referenced by HAL_SPI_Abort_IT().
static HAL_StatusTypeDef SPI_EndRxTransaction (SPI_HandleTypeDef * hspi, uint32_t Timeout, uint32_t Tickstart) [static]
Handle the check of the RX transaction complete.
Parameters:
hspi pointer to a SPI_HandleTypeDef structure that contains the configuration information for SPI module.
Timeout Timeout duration
Tickstart tick start value
Return values:
HAL status
Definition at line 3498 of file stm32f1xx_hal_spi.c.
References __HAL_SPI_DISABLE, SPI_InitTypeDef::Direction, __SPI_HandleTypeDef::ErrorCode, HAL_SPI_ERROR_FLAG, __SPI_HandleTypeDef::Init, SPI_InitTypeDef::Mode, SPI_DIRECTION_1LINE, SPI_DIRECTION_2LINES_RXONLY, SPI_FLAG_BSY, SPI_MODE_MASTER, and SPI_WaitFlagStateUntilTimeout().
Referenced by HAL_SPI_Receive(), SPI_CloseRx_ISR(), and SPI_DMAReceiveCplt().
static HAL_StatusTypeDef SPI_EndRxTxTransaction (SPI_HandleTypeDef * hspi, uint32_t Timeout, uint32_t Tickstart) [static]
Handle the check of the RXTX or TX transaction complete.
Parameters:
hspi SPI handle
Timeout Timeout duration
Tickstart tick start value
Return values:
HAL status
Definition at line 3523 of file stm32f1xx_hal_spi.c.
References __SPI_HandleTypeDef::ErrorCode, HAL_SPI_ERROR_FLAG, SPI_FLAG_BSY, and SPI_WaitFlagStateUntilTimeout().
Referenced by HAL_SPI_Transmit(), HAL_SPI_TransmitReceive(), SPI_CloseRxTx_ISR(), SPI_CloseTx_ISR(), SPI_DMARxAbortCallback(), SPI_DMATransmitCplt(), and SPI_DMATransmitReceiveCplt().
uint8_t SPI_ISCRCErrorValid (SPI_HandleTypeDef * hspi)
Checks if encountered CRC error could be corresponding to wrongly detected errors according to SPI instance, Device type, and revision ID.
Parameters:
hspi,: pointer to a SPI_HandleTypeDef structure that contains the configuration information for SPI module.
Return values:
CRC error validity (SPI_INVALID_CRC_ERROR or SPI_VALID_CRC_ERROR).
Definition at line 3833 of file stm32f1xx_hal_spi.c.
References __SPI_HandleTypeDef::Instance, SPI_INVALID_CRC_ERROR, and SPI_VALID_CRC_ERROR.
Referenced by HAL_SPI_Receive(), HAL_SPI_TransmitReceive(), SPI_CloseRx_ISR(), SPI_CloseRxTx_ISR(), SPI_DMAReceiveCplt(), and SPI_DMATransmitReceiveCplt().
static void SPI_RxISR_16BIT (struct __SPI_HandleTypeDef * hspi) [static]
Manage the 16-bit receive in Interrupt context.
Parameters:
hspi pointer to a SPI_HandleTypeDef structure that contains the configuration information for SPI module.
Return values:
None
Definition at line 3360 of file stm32f1xx_hal_spi.c.
References SPI_InitTypeDef::CRCCalculation, __SPI_HandleTypeDef::Init, __SPI_HandleTypeDef::Instance, __SPI_HandleTypeDef::pRxBuffPtr, __SPI_HandleTypeDef::RxISR, __SPI_HandleTypeDef::RxXferCount, SPI_CloseRx_ISR(), SPI_CRCCALCULATION_ENABLE, and SPI_RxISR_16BITCRC().
Referenced by HAL_SPI_Receive_IT().
static void SPI_RxISR_16BITCRC (struct __SPI_HandleTypeDef * hspi) [static]
Manage the CRC 16-bit receive in Interrupt context.
Parameters:
hspi pointer to a SPI_HandleTypeDef structure that contains the configuration information for SPI module.
Return values:
None
Definition at line 3342 of file stm32f1xx_hal_spi.c.
References __HAL_SPI_DISABLE_IT, __SPI_HandleTypeDef::Instance, SPI_CloseRx_ISR(), SPI_IT_ERR, and SPI_IT_RXNE.
Referenced by SPI_RxISR_16BIT().
static void SPI_RxISR_8BIT (struct __SPI_HandleTypeDef * hspi) [static]
Manage the receive 8-bit in Interrupt context.
Parameters:
hspi pointer to a SPI_HandleTypeDef structure that contains the configuration information for SPI module.
Return values:
None
Definition at line 3308 of file stm32f1xx_hal_spi.c.
References SPI_InitTypeDef::CRCCalculation, __SPI_HandleTypeDef::Init, __SPI_HandleTypeDef::Instance, __SPI_HandleTypeDef::pRxBuffPtr, __SPI_HandleTypeDef::RxISR, __SPI_HandleTypeDef::RxXferCount, SPI_CloseRx_ISR(), SPI_CRCCALCULATION_ENABLE, and SPI_RxISR_8BITCRC().
Referenced by HAL_SPI_Receive_IT().
static void SPI_RxISR_8BITCRC (struct __SPI_HandleTypeDef * hspi) [static]
Manage the CRC 8-bit receive in Interrupt context.
Parameters:
hspi pointer to a SPI_HandleTypeDef structure that contains the configuration information for SPI module.
Return values:
None
Definition at line 3293 of file stm32f1xx_hal_spi.c.
References __SPI_HandleTypeDef::Instance, and SPI_CloseRx_ISR().
Referenced by SPI_RxISR_8BIT().
static void SPI_TxISR_16BIT (struct __SPI_HandleTypeDef * hspi) [static]
Handle the data 16-bit transmit in Interrupt mode.
Parameters:
hspi pointer to a SPI_HandleTypeDef structure that contains the configuration information for SPI module.
Return values:
None
Definition at line 3418 of file stm32f1xx_hal_spi.c.
References SPI_InitTypeDef::CRCCalculation, __SPI_HandleTypeDef::Init, __SPI_HandleTypeDef::Instance, __SPI_HandleTypeDef::pTxBuffPtr, SPI_CloseTx_ISR(), SPI_CRCCALCULATION_ENABLE, and __SPI_HandleTypeDef::TxXferCount.
Referenced by HAL_SPI_Transmit_IT().
static void SPI_TxISR_8BIT (struct __SPI_HandleTypeDef * hspi) [static]
Handle the data 8-bit transmit in Interrupt mode.
Parameters:
hspi pointer to a SPI_HandleTypeDef structure that contains the configuration information for SPI module.
Return values:
None
Definition at line 3393 of file stm32f1xx_hal_spi.c.
References SPI_InitTypeDef::CRCCalculation, __SPI_HandleTypeDef::Init, __SPI_HandleTypeDef::Instance, __SPI_HandleTypeDef::pTxBuffPtr, SPI_CloseTx_ISR(), SPI_CRCCALCULATION_ENABLE, and __SPI_HandleTypeDef::TxXferCount.
Referenced by HAL_SPI_Transmit_IT().
static HAL_StatusTypeDef SPI_WaitFlagStateUntilTimeout (SPI_HandleTypeDef * hspi, uint32_t Flag, FlagStatus State, uint32_t Timeout, uint32_t Tickstart) [static]
Handle SPI Communication Timeout.
Parameters:
hspi pointer to a SPI_HandleTypeDef structure that contains the configuration information for SPI module.
Flag SPI flag to check
State flag state to check
Timeout Timeout duration
Tickstart tick start value
Return values:
HAL status
Definition at line 3448 of file stm32f1xx_hal_spi.c.
References __HAL_SPI_DISABLE, __HAL_SPI_DISABLE_IT, __HAL_SPI_GET_FLAG, SPI_InitTypeDef::CRCCalculation, SPI_InitTypeDef::Direction, HAL_GetTick(), HAL_SPI_STATE_READY, __SPI_HandleTypeDef::Init, SPI_InitTypeDef::Mode, SPI_CRCCALCULATION_ENABLE, SPI_DIRECTION_1LINE, SPI_DIRECTION_2LINES_RXONLY, SPI_IT_ERR, SPI_IT_RXNE, SPI_IT_TXE, SPI_MODE_MASTER, SPI_RESET_CRC, and __SPI_HandleTypeDef::State.
Referenced by HAL_SPI_Receive(), HAL_SPI_TransmitReceive(), SPI_DMAReceiveCplt(), SPI_DMATransmitReceiveCplt(), SPI_EndRxTransaction(), and SPI_EndRxTxTransaction().