STM32F100xE HAL User Manual: Initialization and de-initialization functions
Initialization and de-initialization functions
UART Exported Functions
Initialization and Configuration functions.
Functions
HAL_StatusTypeDef HAL_UART_Init (UART_HandleTypeDef *huart)
Initializes the UART mode according to the specified parameters in the UART_InitTypeDef and create the associated handle.
HAL_StatusTypeDef HAL_HalfDuplex_Init (UART_HandleTypeDef *huart)
Initializes the half-duplex mode according to the specified parameters in the UART_InitTypeDef and create the associated handle.
HAL_StatusTypeDef HAL_LIN_Init (UART_HandleTypeDef *huart, uint32_t BreakDetectLength)
Initializes the LIN mode according to the specified parameters in the UART_InitTypeDef and create the associated handle.
HAL_StatusTypeDef HAL_MultiProcessor_Init (UART_HandleTypeDef *huart, uint8_t Address, uint32_t WakeUpMethod)
Initializes the Multi-Processor mode according to the specified parameters in the UART_InitTypeDef and create the associated handle.
HAL_StatusTypeDef HAL_UART_DeInit (UART_HandleTypeDef *huart)
DeInitializes the UART peripheral.
__weak void HAL_UART_MspInit (UART_HandleTypeDef *huart)
UART MSP Init.
__weak void HAL_UART_MspDeInit (UART_HandleTypeDef *huart)
UART MSP DeInit.
Detailed Description
Initialization and Configuration functions.
 ===============================================================================
            ##### Initialization and Configuration functions #####
 ===============================================================================
    [..]
    This subsection provides a set of functions allowing to initialize the USARTx or the UARTy
    in asynchronous mode.
      (+) For the asynchronous mode only these parameters can be configured:
        (++) Baud Rate
        (++) Word Length
        (++) Stop Bit
        (++) Parity: If the parity is enabled, then the MSB bit of the data written
             in the data register is transmitted but is changed by the parity bit.
             Depending on the frame length defined by the M bit (8-bits or 9-bits),
             please refer to Reference manual for possible UART frame formats.
        (++) Hardware flow control
        (++) Receiver/transmitter modes
        (++) Over Sampling Method
    [..]
    The HAL_UART_Init(), HAL_HalfDuplex_Init(), HAL_LIN_Init() and HAL_MultiProcessor_Init() APIs
    follow respectively the UART asynchronous, UART Half duplex, LIN and Multi-Processor configuration
    procedures (details for the procedures are available in reference manuals
    (RM0008 for STM32F10Xxx MCUs and RM0041 for STM32F100xx MCUs)).
Function Documentation
HAL_StatusTypeDef HAL_HalfDuplex_Init (UART_HandleTypeDef * huart)
Initializes the half-duplex mode according to the specified parameters in the UART_InitTypeDef and create the associated handle.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
Return values:
HAL status
Definition at line 391 of file stm32f1xx_hal_uart.c.
References __HAL_UART_DISABLE, __HAL_UART_ENABLE, assert_param, __UART_HandleTypeDef::ErrorCode, __UART_HandleTypeDef::gState, HAL_UART_ERROR_NONE, HAL_UART_MspInit(), HAL_UART_STATE_BUSY, HAL_UART_STATE_READY, HAL_UART_STATE_RESET, __UART_HandleTypeDef::Init, __UART_HandleTypeDef::Instance, IS_UART_OVERSAMPLING, IS_UART_WORD_LENGTH, __UART_HandleTypeDef::Lock, UART_InitTypeDef::OverSampling, __UART_HandleTypeDef::RxState, UART_SetConfig(), and UART_InitTypeDef::WordLength.
HAL_StatusTypeDef HAL_LIN_Init (UART_HandleTypeDef * huart, uint32_t BreakDetectLength)
Initializes the LIN mode according to the specified parameters in the UART_InitTypeDef and create the associated handle.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
BreakDetectLength Specifies the LIN break detection length. This parameter can be one of the following values:
UART_LINBREAKDETECTLENGTH_10B: 10-bit break detection
UART_LINBREAKDETECTLENGTH_11B: 11-bit break detection
Return values:
HAL status
Definition at line 466 of file stm32f1xx_hal_uart.c.
References __HAL_UART_DISABLE, __HAL_UART_ENABLE, assert_param, __UART_HandleTypeDef::ErrorCode, __UART_HandleTypeDef::gState, HAL_UART_ERROR_NONE, HAL_UART_MspInit(), HAL_UART_STATE_BUSY, HAL_UART_STATE_READY, HAL_UART_STATE_RESET, __UART_HandleTypeDef::Init, __UART_HandleTypeDef::Instance, IS_UART_LIN_BREAK_DETECT_LENGTH, IS_UART_LIN_OVERSAMPLING, IS_UART_LIN_WORD_LENGTH, __UART_HandleTypeDef::Lock, UART_InitTypeDef::OverSampling, __UART_HandleTypeDef::RxState, UART_SetConfig(), and UART_InitTypeDef::WordLength.
HAL_StatusTypeDef HAL_MultiProcessor_Init (UART_HandleTypeDef * huart, uint8_t Address, uint32_t WakeUpMethod)
Initializes the Multi-Processor mode according to the specified parameters in the UART_InitTypeDef and create the associated handle.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
Address USART address
WakeUpMethod specifies the USART wake-up method. This parameter can be one of the following values:
UART_WAKEUPMETHOD_IDLELINE: Wake-up by an idle line detection
UART_WAKEUPMETHOD_ADDRESSMARK: Wake-up by an address mark
Return values:
HAL status
Definition at line 549 of file stm32f1xx_hal_uart.c.
References __HAL_UART_DISABLE, __HAL_UART_ENABLE, assert_param, __UART_HandleTypeDef::ErrorCode, __UART_HandleTypeDef::gState, HAL_UART_ERROR_NONE, HAL_UART_MspInit(), HAL_UART_STATE_BUSY, HAL_UART_STATE_READY, HAL_UART_STATE_RESET, __UART_HandleTypeDef::Init, __UART_HandleTypeDef::Instance, IS_UART_ADDRESS, IS_UART_OVERSAMPLING, IS_UART_WAKEUPMETHOD, IS_UART_WORD_LENGTH, __UART_HandleTypeDef::Lock, UART_InitTypeDef::OverSampling, __UART_HandleTypeDef::RxState, UART_SetConfig(), and UART_InitTypeDef::WordLength.
HAL_StatusTypeDef HAL_UART_DeInit (UART_HandleTypeDef * huart)
DeInitializes the UART peripheral.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
Return values:
HAL status
Definition at line 628 of file stm32f1xx_hal_uart.c.
References __HAL_UART_DISABLE, assert_param, __UART_HandleTypeDef::ErrorCode, __UART_HandleTypeDef::gState, HAL_UART_ERROR_NONE, HAL_UART_MspDeInit(), HAL_UART_STATE_BUSY, HAL_UART_STATE_RESET, __UART_HandleTypeDef::Instance, and __UART_HandleTypeDef::RxState.
HAL_StatusTypeDef HAL_UART_Init (UART_HandleTypeDef * huart)
Initializes the UART mode according to the specified parameters in the UART_InitTypeDef and create the associated handle.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
Return values:
HAL status
Definition at line 314 of file stm32f1xx_hal_uart.c.
References __HAL_UART_DISABLE, __HAL_UART_ENABLE, assert_param, __UART_HandleTypeDef::ErrorCode, __UART_HandleTypeDef::gState, HAL_UART_ERROR_NONE, HAL_UART_MspInit(), HAL_UART_STATE_BUSY, HAL_UART_STATE_READY, HAL_UART_STATE_RESET, UART_InitTypeDef::HwFlowCtl, __UART_HandleTypeDef::Init, __UART_HandleTypeDef::Instance, IS_UART_HARDWARE_FLOW_CONTROL, IS_UART_OVERSAMPLING, IS_UART_WORD_LENGTH, __UART_HandleTypeDef::Lock, UART_InitTypeDef::OverSampling, __UART_HandleTypeDef::RxState, UART_HWCONTROL_NONE, UART_SetConfig(), and UART_InitTypeDef::WordLength.
void HAL_UART_MspDeInit (UART_HandleTypeDef * huart)
UART MSP DeInit.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
Return values:
None
Definition at line 687 of file stm32f1xx_hal_uart.c.
Referenced by HAL_UART_DeInit().
void HAL_UART_MspInit (UART_HandleTypeDef * huart)
UART MSP Init.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
Return values:
None
Definition at line 672 of file stm32f1xx_hal_uart.c.
Referenced by HAL_HalfDuplex_Init(), HAL_LIN_Init(), HAL_MultiProcessor_Init(), and HAL_UART_Init().