STM32F100xE HAL User Manual: DAC Private Functions
DAC Private Functions
DAC
Functions
void DAC_DMAConvCpltCh1 (DMA_HandleTypeDef *hdma)
DMA conversion complete callback.
void DAC_DMAHalfConvCpltCh1 (DMA_HandleTypeDef *hdma)
DMA half transfer complete callback.
void DAC_DMAErrorCh1 (DMA_HandleTypeDef *hdma)
DMA error callback.
Function Documentation
void DAC_DMAConvCpltCh1 (DMA_HandleTypeDef * hdma)
DMA conversion complete callback.
Parameters:
hdma pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 1299 of file stm32f1xx_hal_dac.c.
References HAL_DAC_ConvCpltCallbackCh1(), HAL_DAC_STATE_READY, and DAC_HandleTypeDef::State.
Referenced by HAL_DAC_Start_DMA().
void DAC_DMAErrorCh1 (DMA_HandleTypeDef * hdma)
DMA error callback.
Parameters:
hdma pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 1335 of file stm32f1xx_hal_dac.c.
References DAC_HandleTypeDef::ErrorCode, HAL_DAC_ERROR_DMA, HAL_DAC_ErrorCallbackCh1(), HAL_DAC_STATE_READY, and DAC_HandleTypeDef::State.
Referenced by HAL_DAC_Start_DMA().
void DAC_DMAHalfConvCpltCh1 (DMA_HandleTypeDef * hdma)
DMA half transfer complete callback.
Parameters:
hdma pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 1318 of file stm32f1xx_hal_dac.c.
References HAL_DAC_ConvHalfCpltCallbackCh1().
Referenced by HAL_DAC_Start_DMA().