STM32F100xE HAL User Manual: UART Private Functions
UART Private Functions
UART
Functions
static void UART_EndTxTransfer (UART_HandleTypeDef *huart)
End ongoing Tx transfer on UART peripheral (following error detection or Transmit completion).
static void UART_EndRxTransfer (UART_HandleTypeDef *huart)
End ongoing Rx transfer on UART peripheral (following error detection or Reception completion).
static void UART_DMATransmitCplt (DMA_HandleTypeDef *hdma)
Initialize the callbacks to their default values.
static void UART_DMAReceiveCplt (DMA_HandleTypeDef *hdma)
DMA UART receive process complete callback.
static void UART_DMATxHalfCplt (DMA_HandleTypeDef *hdma)
DMA UART transmit process half complete callback.
static void UART_DMARxHalfCplt (DMA_HandleTypeDef *hdma)
DMA UART receive process half complete callback.
static void UART_DMAError (DMA_HandleTypeDef *hdma)
DMA UART communication error callback.
static void UART_DMAAbortOnError (DMA_HandleTypeDef *hdma)
DMA UART communication abort callback, when initiated by HAL services on Error (To be called at end of DMA Abort procedure following error occurrence).
static void UART_DMATxAbortCallback (DMA_HandleTypeDef *hdma)
DMA UART Tx communication abort callback, when initiated by user (To be called at end of DMA Tx Abort procedure following user abort request).
static void UART_DMARxAbortCallback (DMA_HandleTypeDef *hdma)
DMA UART Rx communication abort callback, when initiated by user (To be called at end of DMA Rx Abort procedure following user abort request).
static void UART_DMATxOnlyAbortCallback (DMA_HandleTypeDef *hdma)
DMA UART Tx communication abort callback, when initiated by user by a call to HAL_UART_AbortTransmit_IT API (Abort only Tx transfer) (This callback is executed at end of DMA Tx Abort procedure following user abort request, and leads to user Tx Abort Complete callback execution).
static void UART_DMARxOnlyAbortCallback (DMA_HandleTypeDef *hdma)
DMA UART Rx communication abort callback, when initiated by user by a call to HAL_UART_AbortReceive_IT API (Abort only Rx transfer) (This callback is executed at end of DMA Rx Abort procedure following user abort request, and leads to user Rx Abort Complete callback execution).
static HAL_StatusTypeDef UART_Transmit_IT (UART_HandleTypeDef *huart)
Sends an amount of data in non blocking mode.
static HAL_StatusTypeDef UART_EndTransmit_IT (UART_HandleTypeDef *huart)
Wraps up transmission in non blocking mode.
static HAL_StatusTypeDef UART_Receive_IT (UART_HandleTypeDef *huart)
Receives an amount of data in non blocking mode.
static HAL_StatusTypeDef UART_WaitOnFlagUntilTimeout (UART_HandleTypeDef *huart, uint32_t Flag, FlagStatus Status, uint32_t Tickstart, uint32_t Timeout)
This function handles UART Communication Timeout.
static void UART_SetConfig (UART_HandleTypeDef *huart)
Configures the UART peripheral.
Function Documentation
static void UART_DMAAbortOnError (DMA_HandleTypeDef * hdma) [static]
DMA UART communication abort callback, when initiated by HAL services on Error (To be called at end of DMA Abort procedure following error occurrence).
Parameters:
hdma Pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 2735 of file stm32f1xx_hal_uart.c.
References HAL_UART_ErrorCallback(), __UART_HandleTypeDef::RxXferCount, and __UART_HandleTypeDef::TxXferCount.
Referenced by HAL_UART_IRQHandler().
static void UART_DMAError (DMA_HandleTypeDef * hdma) [static]
DMA UART communication error callback.
Parameters:
hdma Pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 2631 of file stm32f1xx_hal_uart.c.
References __UART_HandleTypeDef::ErrorCode, __UART_HandleTypeDef::gState, HAL_UART_ERROR_DMA, HAL_UART_ErrorCallback(), HAL_UART_STATE_BUSY_RX, HAL_UART_STATE_BUSY_TX, __UART_HandleTypeDef::Instance, __UART_HandleTypeDef::RxState, __UART_HandleTypeDef::RxXferCount, __UART_HandleTypeDef::TxXferCount, UART_EndRxTransfer(), and UART_EndTxTransfer().
Referenced by HAL_UART_Receive_DMA(), and HAL_UART_Transmit_DMA().
static void UART_DMAReceiveCplt (DMA_HandleTypeDef * hdma) [static]
DMA UART receive process complete callback.
Parameters:
hdma Pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 2578 of file stm32f1xx_hal_uart.c.
References HAL_UART_RxCpltCallback(), HAL_UART_STATE_READY, __DMA_HandleTypeDef::Instance, __UART_HandleTypeDef::Instance, __UART_HandleTypeDef::RxState, and __UART_HandleTypeDef::RxXferCount.
Referenced by HAL_UART_Receive_DMA().
static void UART_DMARxAbortCallback (DMA_HandleTypeDef * hdma) [static]
DMA UART Rx communication abort callback, when initiated by user (To be called at end of DMA Rx Abort procedure following user abort request).
Note:
When this callback is executed, User Abort complete call back is called only if no Abort still ongoing for Tx DMA Handle.
Parameters:
hdma Pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 2804 of file stm32f1xx_hal_uart.c.
References __UART_HandleTypeDef::ErrorCode, __UART_HandleTypeDef::gState, HAL_UART_AbortCpltCallback(), HAL_UART_ERROR_NONE, HAL_UART_STATE_READY, __UART_HandleTypeDef::hdmarx, __UART_HandleTypeDef::hdmatx, __UART_HandleTypeDef::RxState, __UART_HandleTypeDef::RxXferCount, __UART_HandleTypeDef::TxXferCount, and __DMA_HandleTypeDef::XferAbortCallback.
Referenced by HAL_UART_Abort_IT().
static void UART_DMARxHalfCplt (DMA_HandleTypeDef * hdma) [static]
DMA UART receive process half complete callback.
Parameters:
hdma Pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 2612 of file stm32f1xx_hal_uart.c.
References HAL_UART_RxHalfCpltCallback().
Referenced by HAL_UART_Receive_DMA().
static void UART_DMARxOnlyAbortCallback (DMA_HandleTypeDef * hdma) [static]
DMA UART Rx communication abort callback, when initiated by user by a call to HAL_UART_AbortReceive_IT API (Abort only Rx transfer) (This callback is executed at end of DMA Rx Abort procedure following user abort request, and leads to user Rx Abort Complete callback execution).
Parameters:
hdma Pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 2877 of file stm32f1xx_hal_uart.c.
References HAL_UART_AbortReceiveCpltCallback(), HAL_UART_STATE_READY, __UART_HandleTypeDef::RxState, and __UART_HandleTypeDef::RxXferCount.
Referenced by HAL_UART_AbortReceive_IT().
static void UART_DMATransmitCplt (DMA_HandleTypeDef * hdma) [static]
Initialize the callbacks to their default values.
Parameters:
huart UART handle.
Return values:
none DMA UART transmit process complete callback.
Parameters:
hdma Pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 2524 of file stm32f1xx_hal_uart.c.
References HAL_UART_TxCpltCallback(), __DMA_HandleTypeDef::Instance, __UART_HandleTypeDef::Instance, and __UART_HandleTypeDef::TxXferCount.
Referenced by HAL_UART_Transmit_DMA().
static void UART_DMATxAbortCallback (DMA_HandleTypeDef * hdma) [static]
DMA UART Tx communication abort callback, when initiated by user (To be called at end of DMA Tx Abort procedure following user abort request).
Note:
When this callback is executed, User Abort complete call back is called only if no Abort still ongoing for Rx DMA Handle.
Parameters:
hdma Pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 2759 of file stm32f1xx_hal_uart.c.
References __UART_HandleTypeDef::ErrorCode, __UART_HandleTypeDef::gState, HAL_UART_AbortCpltCallback(), HAL_UART_ERROR_NONE, HAL_UART_STATE_READY, __UART_HandleTypeDef::hdmarx, __UART_HandleTypeDef::hdmatx, __UART_HandleTypeDef::RxState, __UART_HandleTypeDef::RxXferCount, __UART_HandleTypeDef::TxXferCount, and __DMA_HandleTypeDef::XferAbortCallback.
Referenced by HAL_UART_Abort_IT().
static void UART_DMATxHalfCplt (DMA_HandleTypeDef * hdma) [static]
DMA UART transmit process half complete callback.
Parameters:
hdma Pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 2559 of file stm32f1xx_hal_uart.c.
References HAL_UART_TxHalfCpltCallback().
Referenced by HAL_UART_Transmit_DMA().
static void UART_DMATxOnlyAbortCallback (DMA_HandleTypeDef * hdma) [static]
DMA UART Tx communication abort callback, when initiated by user by a call to HAL_UART_AbortTransmit_IT API (Abort only Tx transfer) (This callback is executed at end of DMA Tx Abort procedure following user abort request, and leads to user Tx Abort Complete callback execution).
Parameters:
hdma Pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 2849 of file stm32f1xx_hal_uart.c.
References __UART_HandleTypeDef::gState, HAL_UART_AbortTransmitCpltCallback(), HAL_UART_STATE_READY, and __UART_HandleTypeDef::TxXferCount.
Referenced by HAL_UART_AbortTransmit_IT().
static void UART_EndRxTransfer (UART_HandleTypeDef * huart) [static]
End ongoing Rx transfer on UART peripheral (following error detection or Reception completion).
Parameters:
huart UART handle.
Return values:
None
Definition at line 2718 of file stm32f1xx_hal_uart.c.
References HAL_UART_STATE_READY, __UART_HandleTypeDef::Instance, and __UART_HandleTypeDef::RxState.
Referenced by HAL_UART_DMAStop(), HAL_UART_IRQHandler(), and UART_DMAError().
static HAL_StatusTypeDef UART_EndTransmit_IT (UART_HandleTypeDef * huart) [static]
Wraps up transmission in non blocking mode.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
Return values:
HAL status
Definition at line 2949 of file stm32f1xx_hal_uart.c.
References __HAL_UART_DISABLE_IT, __UART_HandleTypeDef::gState, HAL_UART_STATE_READY, HAL_UART_TxCpltCallback(), and UART_IT_TC.
Referenced by HAL_UART_IRQHandler().
static void UART_EndTxTransfer (UART_HandleTypeDef * huart) [static]
End ongoing Tx transfer on UART peripheral (following error detection or Transmit completion).
Parameters:
huart UART handle.
Return values:
None
Definition at line 2704 of file stm32f1xx_hal_uart.c.
References __UART_HandleTypeDef::gState, HAL_UART_STATE_READY, and __UART_HandleTypeDef::Instance.
Referenced by HAL_UART_DMAStop(), and UART_DMAError().
static HAL_StatusTypeDef UART_Receive_IT (UART_HandleTypeDef * huart) [static]
Receives an amount of data in non blocking mode.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
Return values:
HAL status
Definition at line 2974 of file stm32f1xx_hal_uart.c.
References __HAL_UART_DISABLE_IT, HAL_UART_RxCpltCallback(), HAL_UART_STATE_BUSY_RX, HAL_UART_STATE_READY, __UART_HandleTypeDef::Init, __UART_HandleTypeDef::Instance, UART_InitTypeDef::Parity, __UART_HandleTypeDef::pRxBuffPtr, __UART_HandleTypeDef::RxState, __UART_HandleTypeDef::RxXferCount, UART_IT_ERR, UART_IT_PE, UART_IT_RXNE, UART_PARITY_NONE, UART_WORDLENGTH_9B, and UART_InitTypeDef::WordLength.
Referenced by HAL_UART_IRQHandler().
static void UART_SetConfig (UART_HandleTypeDef * huart) [static]
Configures the UART peripheral.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
Return values:
None
Definition at line 3045 of file stm32f1xx_hal_uart.c.
References assert_param, UART_InitTypeDef::BaudRate, HAL_RCC_GetPCLK1Freq(), HAL_RCC_GetPCLK2Freq(), UART_InitTypeDef::HwFlowCtl, __UART_HandleTypeDef::Init, __UART_HandleTypeDef::Instance, IS_UART_BAUDRATE, IS_UART_MODE, IS_UART_PARITY, IS_UART_STOPBITS, UART_InitTypeDef::Mode, UART_InitTypeDef::OverSampling, UART_InitTypeDef::Parity, UART_InitTypeDef::StopBits, UART_BRR_SAMPLING16, UART_BRR_SAMPLING8, UART_OVERSAMPLING_8, and UART_InitTypeDef::WordLength.
Referenced by HAL_HalfDuplex_Init(), HAL_LIN_Init(), HAL_MultiProcessor_Init(), and HAL_UART_Init().
static HAL_StatusTypeDef UART_Transmit_IT (UART_HandleTypeDef * huart) [static]
Sends an amount of data in non blocking mode.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
Return values:
HAL status
Definition at line 2902 of file stm32f1xx_hal_uart.c.
References __HAL_UART_DISABLE_IT, __HAL_UART_ENABLE_IT, __UART_HandleTypeDef::gState, HAL_UART_STATE_BUSY_TX, __UART_HandleTypeDef::Init, __UART_HandleTypeDef::Instance, UART_InitTypeDef::Parity, __UART_HandleTypeDef::pTxBuffPtr, __UART_HandleTypeDef::TxXferCount, UART_IT_TC, UART_IT_TXE, UART_PARITY_NONE, UART_WORDLENGTH_9B, and UART_InitTypeDef::WordLength.
Referenced by HAL_UART_IRQHandler().
static HAL_StatusTypeDef UART_WaitOnFlagUntilTimeout (UART_HandleTypeDef * huart, uint32_t Flag, FlagStatus Status, uint32_t Tickstart, uint32_t Timeout) [static]
This function handles UART Communication Timeout.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
Flag specifies the UART flag to check.
Status The new Flag status (SET or RESET).
Tickstart Tick start value
Timeout Timeout duration
Return values:
HAL status
Definition at line 2672 of file stm32f1xx_hal_uart.c.
References __HAL_UART_GET_FLAG, __UART_HandleTypeDef::gState, HAL_GetTick(), HAL_UART_STATE_READY, __UART_HandleTypeDef::Instance, and __UART_HandleTypeDef::RxState.
Referenced by HAL_UART_Receive(), and HAL_UART_Transmit().