STM32F100xE HAL User Manual: Peripheral Control functions
Peripheral Control functions
RCCEx Exported Functions
Extended Peripheral Control functions.
Functions
HAL_StatusTypeDef HAL_RCCEx_PeriphCLKConfig (RCC_PeriphCLKInitTypeDef *PeriphClkInit)
Initializes the RCC extended peripherals clocks according to the specified parameters in the RCC_PeriphCLKInitTypeDef.
void HAL_RCCEx_GetPeriphCLKConfig (RCC_PeriphCLKInitTypeDef *PeriphClkInit)
Get the PeriphClkInit according to the internal RCC configuration registers.
uint32_t HAL_RCCEx_GetPeriphCLKFreq (uint32_t PeriphClk)
Returns the peripheral clock frequency.
Detailed Description
Extended Peripheral Control functions.
 ===============================================================================
                ##### Extended Peripheral Control functions  #####
 ===============================================================================
    [..]
    This subsection provides a set of functions allowing to control the RCC Clocks
    frequencies.
    [..]
    (@) Important note: Care must be taken when HAL_RCCEx_PeriphCLKConfig() is used to
        select the RTC clock source; in this case the Backup domain will be reset in
        order to modify the RTC Clock source, as consequence RTC registers (including
        the backup registers) are set to their reset values.
Function Documentation
void HAL_RCCEx_GetPeriphCLKConfig (RCC_PeriphCLKInitTypeDef * PeriphClkInit)
Get the PeriphClkInit according to the internal RCC configuration registers.
Parameters:
PeriphClkInit pointer to an RCC_PeriphCLKInitTypeDef structure that returns the configuration information for the Extended Peripherals clocks(RTC, I2S, ADC clocks).
Return values:
None
Definition at line 294 of file stm32f1xx_hal_rcc_ex.c.
References __HAL_RCC_GET_ADC_SOURCE, __HAL_RCC_GET_RTC_SOURCE, RCC_PeriphCLKInitTypeDef::AdcClockSelection, RCC_PeriphCLKInitTypeDef::PeriphClockSelection, RCC_PERIPHCLK_ADC, RCC_PERIPHCLK_RTC, and RCC_PeriphCLKInitTypeDef::RTCClockSelection.
uint32_t HAL_RCCEx_GetPeriphCLKFreq (uint32_t PeriphClk)
Returns the peripheral clock frequency.
Note:
Returns 0 if peripheral clock is unknown
Parameters:
PeriphClk Peripheral clock identifier This parameter can be one of the following values:
RCC_PERIPHCLK_RTC RTC peripheral clock
RCC_PERIPHCLK_ADC ADC peripheral clock
Return values:
Frequency in Hz (0: means that no available frequency for the peripheral)
Definition at line 387 of file stm32f1xx_hal_rcc_ex.c.
References __HAL_RCC_GET_ADC_SOURCE, assert_param, HAL_RCC_GetPCLK2Freq(), HAL_RCC_GetSysClockFreq(), HSE_VALUE, HSI_VALUE, IS_RCC_PERIPHCLOCK, LSE_VALUE, LSI_VALUE, RCC_PERIPHCLK_ADC, RCC_PERIPHCLK_RTC, RCC_PLLSOURCE_HSI_DIV2, RCC_RTCCLKSOURCE_HSE_DIV128, RCC_RTCCLKSOURCE_LSE, and RCC_RTCCLKSOURCE_LSI.
Referenced by HAL_ADC_PollForConversion(), HAL_ADCEx_Calibration_Start(), HAL_ADCEx_InjectedPollForConversion(), and HAL_RTC_Init().
HAL_StatusTypeDef HAL_RCCEx_PeriphCLKConfig (RCC_PeriphCLKInitTypeDef * PeriphClkInit)
Initializes the RCC extended peripherals clocks according to the specified parameters in the RCC_PeriphCLKInitTypeDef.
Parameters:
PeriphClkInit pointer to an RCC_PeriphCLKInitTypeDef structure that contains the configuration information for the Extended Peripherals clocks(RTC clock).
Note:
Care must be taken when HAL_RCCEx_PeriphCLKConfig() is used to select the RTC clock source; in this case the Backup domain will be reset in order to modify the RTC Clock source, as consequence RTC registers (including the backup registers) are set to their reset values.
In case of STM32F105xC or STM32F107xC devices, PLLI2S will be enabled if requested on one of 2 I2S interfaces. When PLLI2S is enabled, you need to call HAL_RCCEx_DisablePLLI2S to manually disable it.
Return values:
HAL status
Definition at line 100 of file stm32f1xx_hal_rcc_ex.c.
References __HAL_RCC_ADC_CONFIG, __HAL_RCC_BACKUPRESET_FORCE, __HAL_RCC_BACKUPRESET_RELEASE, __HAL_RCC_GET_FLAG, __HAL_RCC_PWR_CLK_DISABLE, __HAL_RCC_PWR_CLK_ENABLE, __HAL_RCC_PWR_IS_CLK_DISABLED, __HAL_RCC_RTC_CONFIG, RCC_PeriphCLKInitTypeDef::AdcClockSelection, assert_param, HAL_GetTick(), IS_RCC_ADCPLLCLK_DIV, IS_RCC_PERIPHCLOCK, IS_RCC_RTCCLKSOURCE, RCC_PeriphCLKInitTypeDef::PeriphClockSelection, RCC_DBP_TIMEOUT_VALUE, RCC_FLAG_LSERDY, RCC_LSE_TIMEOUT_VALUE, RCC_PERIPHCLK_ADC, RCC_PERIPHCLK_RTC, and RCC_PeriphCLKInitTypeDef::RTCClockSelection.