STM32F103xB HAL User Manual: APB2
APB2
BUS Exported Functions
Functions
__STATIC_INLINE void LL_APB2_GRP1_EnableClock (uint32_t Periphs)
Enable APB2 peripherals clock.
__STATIC_INLINE uint32_t LL_APB2_GRP1_IsEnabledClock (uint32_t Periphs)
Check if APB2 peripheral clock is enabled or not.
__STATIC_INLINE void LL_APB2_GRP1_DisableClock (uint32_t Periphs)
Disable APB2 peripherals clock.
__STATIC_INLINE void LL_APB2_GRP1_ForceReset (uint32_t Periphs)
Force APB2 peripherals reset.
__STATIC_INLINE void LL_APB2_GRP1_ReleaseReset (uint32_t Periphs)
Release APB2 peripherals reset.
Function Documentation
__STATIC_INLINE void LL_APB2_GRP1_DisableClock (uint32_t Periphs)
Disable APB2 peripherals clock.
Reference Manual to LL API cross reference:
APB2ENR ADC1EN LL_APB2_GRP1_DisableClock
APB2ENR ADC2EN LL_APB2_GRP1_DisableClock
APB2ENR ADC3EN LL_APB2_GRP1_DisableClock
APB2ENR AFIOEN LL_APB2_GRP1_DisableClock
APB2ENR IOPAEN LL_APB2_GRP1_DisableClock
APB2ENR IOPBEN LL_APB2_GRP1_DisableClock
APB2ENR IOPCEN LL_APB2_GRP1_DisableClock
APB2ENR IOPDEN LL_APB2_GRP1_DisableClock
APB2ENR IOPEEN LL_APB2_GRP1_DisableClock
APB2ENR IOPFEN LL_APB2_GRP1_DisableClock
APB2ENR IOPGEN LL_APB2_GRP1_DisableClock
APB2ENR SPI1EN LL_APB2_GRP1_DisableClock
APB2ENR TIM10EN LL_APB2_GRP1_DisableClock
APB2ENR TIM11EN LL_APB2_GRP1_DisableClock
APB2ENR TIM15EN LL_APB2_GRP1_DisableClock
APB2ENR TIM16EN LL_APB2_GRP1_DisableClock
APB2ENR TIM17EN LL_APB2_GRP1_DisableClock
APB2ENR TIM1EN LL_APB2_GRP1_DisableClock
APB2ENR TIM8EN LL_APB2_GRP1_DisableClock
APB2ENR TIM9EN LL_APB2_GRP1_DisableClock
APB2ENR USART1EN LL_APB2_GRP1_DisableClock
Parameters:
Periphs This parameter can be a combination of the following values:
LL_APB2_GRP1_PERIPH_ADC1
LL_APB2_GRP1_PERIPH_ADC2 (*)
LL_APB2_GRP1_PERIPH_ADC3 (*)
LL_APB2_GRP1_PERIPH_AFIO
LL_APB2_GRP1_PERIPH_GPIOA
LL_APB2_GRP1_PERIPH_GPIOB
LL_APB2_GRP1_PERIPH_GPIOC
LL_APB2_GRP1_PERIPH_GPIOD
LL_APB2_GRP1_PERIPH_GPIOE (*)
LL_APB2_GRP1_PERIPH_GPIOF (*)
LL_APB2_GRP1_PERIPH_GPIOG (*)
LL_APB2_GRP1_PERIPH_SPI1
LL_APB2_GRP1_PERIPH_TIM10 (*)
LL_APB2_GRP1_PERIPH_TIM11 (*)
LL_APB2_GRP1_PERIPH_TIM15 (*)
LL_APB2_GRP1_PERIPH_TIM16 (*)
LL_APB2_GRP1_PERIPH_TIM17 (*)
LL_APB2_GRP1_PERIPH_TIM1
LL_APB2_GRP1_PERIPH_TIM8 (*)
LL_APB2_GRP1_PERIPH_TIM9 (*)
LL_APB2_GRP1_PERIPH_USART1
(*) value not defined in all devices.
Return values:
None
Definition at line 875 of file stm32f1xx_ll_bus.h.
__STATIC_INLINE void LL_APB2_GRP1_EnableClock (uint32_t Periphs)
Enable APB2 peripherals clock.
Reference Manual to LL API cross reference:
APB2ENR ADC1EN LL_APB2_GRP1_EnableClock
APB2ENR ADC2EN LL_APB2_GRP1_EnableClock
APB2ENR ADC3EN LL_APB2_GRP1_EnableClock
APB2ENR AFIOEN LL_APB2_GRP1_EnableClock
APB2ENR IOPAEN LL_APB2_GRP1_EnableClock
APB2ENR IOPBEN LL_APB2_GRP1_EnableClock
APB2ENR IOPCEN LL_APB2_GRP1_EnableClock
APB2ENR IOPDEN LL_APB2_GRP1_EnableClock
APB2ENR IOPEEN LL_APB2_GRP1_EnableClock
APB2ENR IOPFEN LL_APB2_GRP1_EnableClock
APB2ENR IOPGEN LL_APB2_GRP1_EnableClock
APB2ENR SPI1EN LL_APB2_GRP1_EnableClock
APB2ENR TIM10EN LL_APB2_GRP1_EnableClock
APB2ENR TIM11EN LL_APB2_GRP1_EnableClock
APB2ENR TIM15EN LL_APB2_GRP1_EnableClock
APB2ENR TIM16EN LL_APB2_GRP1_EnableClock
APB2ENR TIM17EN LL_APB2_GRP1_EnableClock
APB2ENR TIM1EN LL_APB2_GRP1_EnableClock
APB2ENR TIM8EN LL_APB2_GRP1_EnableClock
APB2ENR TIM9EN LL_APB2_GRP1_EnableClock
APB2ENR USART1EN LL_APB2_GRP1_EnableClock
Parameters:
Periphs This parameter can be a combination of the following values:
LL_APB2_GRP1_PERIPH_ADC1
LL_APB2_GRP1_PERIPH_ADC2 (*)
LL_APB2_GRP1_PERIPH_ADC3 (*)
LL_APB2_GRP1_PERIPH_AFIO
LL_APB2_GRP1_PERIPH_GPIOA
LL_APB2_GRP1_PERIPH_GPIOB
LL_APB2_GRP1_PERIPH_GPIOC
LL_APB2_GRP1_PERIPH_GPIOD
LL_APB2_GRP1_PERIPH_GPIOE (*)
LL_APB2_GRP1_PERIPH_GPIOF (*)
LL_APB2_GRP1_PERIPH_GPIOG (*)
LL_APB2_GRP1_PERIPH_SPI1
LL_APB2_GRP1_PERIPH_TIM10 (*)
LL_APB2_GRP1_PERIPH_TIM11 (*)
LL_APB2_GRP1_PERIPH_TIM15 (*)
LL_APB2_GRP1_PERIPH_TIM16 (*)
LL_APB2_GRP1_PERIPH_TIM17 (*)
LL_APB2_GRP1_PERIPH_TIM1
LL_APB2_GRP1_PERIPH_TIM8 (*)
LL_APB2_GRP1_PERIPH_TIM9 (*)
LL_APB2_GRP1_PERIPH_USART1
(*) value not defined in all devices.
Return values:
None
Definition at line 763 of file stm32f1xx_ll_bus.h.
__STATIC_INLINE void LL_APB2_GRP1_ForceReset (uint32_t Periphs)
Force APB2 peripherals reset.
Reference Manual to LL API cross reference:
APB2RSTR ADC1RST LL_APB2_GRP1_ForceReset
APB2RSTR ADC2RST LL_APB2_GRP1_ForceReset
APB2RSTR ADC3RST LL_APB2_GRP1_ForceReset
APB2RSTR AFIORST LL_APB2_GRP1_ForceReset
APB2RSTR IOPARST LL_APB2_GRP1_ForceReset
APB2RSTR IOPBRST LL_APB2_GRP1_ForceReset
APB2RSTR IOPCRST LL_APB2_GRP1_ForceReset
APB2RSTR IOPDRST LL_APB2_GRP1_ForceReset
APB2RSTR IOPERST LL_APB2_GRP1_ForceReset
APB2RSTR IOPFRST LL_APB2_GRP1_ForceReset
APB2RSTR IOPGRST LL_APB2_GRP1_ForceReset
APB2RSTR SPI1RST LL_APB2_GRP1_ForceReset
APB2RSTR TIM10RST LL_APB2_GRP1_ForceReset
APB2RSTR TIM11RST LL_APB2_GRP1_ForceReset
APB2RSTR TIM15RST LL_APB2_GRP1_ForceReset
APB2RSTR TIM16RST LL_APB2_GRP1_ForceReset
APB2RSTR TIM17RST LL_APB2_GRP1_ForceReset
APB2RSTR TIM1RST LL_APB2_GRP1_ForceReset
APB2RSTR TIM8RST LL_APB2_GRP1_ForceReset
APB2RSTR TIM9RST LL_APB2_GRP1_ForceReset
APB2RSTR USART1RST LL_APB2_GRP1_ForceReset
Parameters:
Periphs This parameter can be a combination of the following values:
LL_APB2_GRP1_PERIPH_ALL
LL_APB2_GRP1_PERIPH_ADC1
LL_APB2_GRP1_PERIPH_ADC2 (*)
LL_APB2_GRP1_PERIPH_ADC3 (*)
LL_APB2_GRP1_PERIPH_AFIO
LL_APB2_GRP1_PERIPH_GPIOA
LL_APB2_GRP1_PERIPH_GPIOB
LL_APB2_GRP1_PERIPH_GPIOC
LL_APB2_GRP1_PERIPH_GPIOD
LL_APB2_GRP1_PERIPH_GPIOE (*)
LL_APB2_GRP1_PERIPH_GPIOF (*)
LL_APB2_GRP1_PERIPH_GPIOG (*)
LL_APB2_GRP1_PERIPH_SPI1
LL_APB2_GRP1_PERIPH_TIM10 (*)
LL_APB2_GRP1_PERIPH_TIM11 (*)
LL_APB2_GRP1_PERIPH_TIM15 (*)
LL_APB2_GRP1_PERIPH_TIM16 (*)
LL_APB2_GRP1_PERIPH_TIM17 (*)
LL_APB2_GRP1_PERIPH_TIM1
LL_APB2_GRP1_PERIPH_TIM8 (*)
LL_APB2_GRP1_PERIPH_TIM9 (*)
LL_APB2_GRP1_PERIPH_USART1
(*) value not defined in all devices.
Return values:
None
Definition at line 930 of file stm32f1xx_ll_bus.h.
Referenced by LL_ADC_CommonDeInit(), LL_GPIO_DeInit(), LL_SPI_DeInit(), LL_TIM_DeInit(), and LL_USART_DeInit().
__STATIC_INLINE uint32_t LL_APB2_GRP1_IsEnabledClock (uint32_t Periphs)
Check if APB2 peripheral clock is enabled or not.
Reference Manual to LL API cross reference:
APB2ENR ADC1EN LL_APB2_GRP1_IsEnabledClock
APB2ENR ADC2EN LL_APB2_GRP1_IsEnabledClock
APB2ENR ADC3EN LL_APB2_GRP1_IsEnabledClock
APB2ENR AFIOEN LL_APB2_GRP1_IsEnabledClock
APB2ENR IOPAEN LL_APB2_GRP1_IsEnabledClock
APB2ENR IOPBEN LL_APB2_GRP1_IsEnabledClock
APB2ENR IOPCEN LL_APB2_GRP1_IsEnabledClock
APB2ENR IOPDEN LL_APB2_GRP1_IsEnabledClock
APB2ENR IOPEEN LL_APB2_GRP1_IsEnabledClock
APB2ENR IOPFEN LL_APB2_GRP1_IsEnabledClock
APB2ENR IOPGEN LL_APB2_GRP1_IsEnabledClock
APB2ENR SPI1EN LL_APB2_GRP1_IsEnabledClock
APB2ENR TIM10EN LL_APB2_GRP1_IsEnabledClock
APB2ENR TIM11EN LL_APB2_GRP1_IsEnabledClock
APB2ENR TIM15EN LL_APB2_GRP1_IsEnabledClock
APB2ENR TIM16EN LL_APB2_GRP1_IsEnabledClock
APB2ENR TIM17EN LL_APB2_GRP1_IsEnabledClock
APB2ENR TIM1EN LL_APB2_GRP1_IsEnabledClock
APB2ENR TIM8EN LL_APB2_GRP1_IsEnabledClock
APB2ENR TIM9EN LL_APB2_GRP1_IsEnabledClock
APB2ENR USART1EN LL_APB2_GRP1_IsEnabledClock
Parameters:
Periphs This parameter can be a combination of the following values:
LL_APB2_GRP1_PERIPH_ADC1
LL_APB2_GRP1_PERIPH_ADC2 (*)
LL_APB2_GRP1_PERIPH_ADC3 (*)
LL_APB2_GRP1_PERIPH_AFIO
LL_APB2_GRP1_PERIPH_GPIOA
LL_APB2_GRP1_PERIPH_GPIOB
LL_APB2_GRP1_PERIPH_GPIOC
LL_APB2_GRP1_PERIPH_GPIOD
LL_APB2_GRP1_PERIPH_GPIOE (*)
LL_APB2_GRP1_PERIPH_GPIOF (*)
LL_APB2_GRP1_PERIPH_GPIOG (*)
LL_APB2_GRP1_PERIPH_SPI1
LL_APB2_GRP1_PERIPH_TIM10 (*)
LL_APB2_GRP1_PERIPH_TIM11 (*)
LL_APB2_GRP1_PERIPH_TIM15 (*)
LL_APB2_GRP1_PERIPH_TIM16 (*)
LL_APB2_GRP1_PERIPH_TIM17 (*)
LL_APB2_GRP1_PERIPH_TIM1
LL_APB2_GRP1_PERIPH_TIM8 (*)
LL_APB2_GRP1_PERIPH_TIM9 (*)
LL_APB2_GRP1_PERIPH_USART1
(*) value not defined in all devices.
Return values:
State of Periphs (1 or 0).
Definition at line 821 of file stm32f1xx_ll_bus.h.
__STATIC_INLINE void LL_APB2_GRP1_ReleaseReset (uint32_t Periphs)
Release APB2 peripherals reset.
Reference Manual to LL API cross reference:
APB2RSTR ADC1RST LL_APB2_GRP1_ReleaseReset
APB2RSTR ADC2RST LL_APB2_GRP1_ReleaseReset
APB2RSTR ADC3RST LL_APB2_GRP1_ReleaseReset
APB2RSTR AFIORST LL_APB2_GRP1_ReleaseReset
APB2RSTR IOPARST LL_APB2_GRP1_ReleaseReset
APB2RSTR IOPBRST LL_APB2_GRP1_ReleaseReset
APB2RSTR IOPCRST LL_APB2_GRP1_ReleaseReset
APB2RSTR IOPDRST LL_APB2_GRP1_ReleaseReset
APB2RSTR IOPERST LL_APB2_GRP1_ReleaseReset
APB2RSTR IOPFRST LL_APB2_GRP1_ReleaseReset
APB2RSTR IOPGRST LL_APB2_GRP1_ReleaseReset
APB2RSTR SPI1RST LL_APB2_GRP1_ReleaseReset
APB2RSTR TIM10RST LL_APB2_GRP1_ReleaseReset
APB2RSTR TIM11RST LL_APB2_GRP1_ReleaseReset
APB2RSTR TIM15RST LL_APB2_GRP1_ReleaseReset
APB2RSTR TIM16RST LL_APB2_GRP1_ReleaseReset
APB2RSTR TIM17RST LL_APB2_GRP1_ReleaseReset
APB2RSTR TIM1RST LL_APB2_GRP1_ReleaseReset
APB2RSTR TIM8RST LL_APB2_GRP1_ReleaseReset
APB2RSTR TIM9RST LL_APB2_GRP1_ReleaseReset
APB2RSTR USART1RST LL_APB2_GRP1_ReleaseReset
Parameters:
Periphs This parameter can be a combination of the following values:
LL_APB2_GRP1_PERIPH_ALL
LL_APB2_GRP1_PERIPH_ADC1
LL_APB2_GRP1_PERIPH_ADC2 (*)
LL_APB2_GRP1_PERIPH_ADC3 (*)
LL_APB2_GRP1_PERIPH_AFIO
LL_APB2_GRP1_PERIPH_GPIOA
LL_APB2_GRP1_PERIPH_GPIOB
LL_APB2_GRP1_PERIPH_GPIOC
LL_APB2_GRP1_PERIPH_GPIOD
LL_APB2_GRP1_PERIPH_GPIOE (*)
LL_APB2_GRP1_PERIPH_GPIOF (*)
LL_APB2_GRP1_PERIPH_GPIOG (*)
LL_APB2_GRP1_PERIPH_SPI1
LL_APB2_GRP1_PERIPH_TIM10 (*)
LL_APB2_GRP1_PERIPH_TIM11 (*)
LL_APB2_GRP1_PERIPH_TIM15 (*)
LL_APB2_GRP1_PERIPH_TIM16 (*)
LL_APB2_GRP1_PERIPH_TIM17 (*)
LL_APB2_GRP1_PERIPH_TIM1
LL_APB2_GRP1_PERIPH_TIM8 (*)
LL_APB2_GRP1_PERIPH_TIM9 (*)
LL_APB2_GRP1_PERIPH_USART1
(*) value not defined in all devices.
Return values:
None
Definition at line 985 of file stm32f1xx_ll_bus.h.
Referenced by LL_ADC_CommonDeInit(), LL_GPIO_DeInit(), LL_SPI_DeInit(), LL_TIM_DeInit(), and LL_USART_DeInit().