STM32F103xB HAL User Manual: Output channel configuration
Output channel configuration
TIM Exported Functions
Functions
__STATIC_INLINE void LL_TIM_OC_ConfigOutput (TIM_TypeDef *TIMx, uint32_t Channel, uint32_t Configuration)
Configure an output channel.
__STATIC_INLINE void LL_TIM_OC_SetMode (TIM_TypeDef *TIMx, uint32_t Channel, uint32_t Mode)
Define the behavior of the output reference signal OCxREF from which OCx and OCxN (when relevant) are derived.
__STATIC_INLINE uint32_t LL_TIM_OC_GetMode (TIM_TypeDef *TIMx, uint32_t Channel)
Get the output compare mode of an output channel.
__STATIC_INLINE void LL_TIM_OC_SetPolarity (TIM_TypeDef *TIMx, uint32_t Channel, uint32_t Polarity)
Set the polarity of an output channel.
__STATIC_INLINE uint32_t LL_TIM_OC_GetPolarity (TIM_TypeDef *TIMx, uint32_t Channel)
Get the polarity of an output channel.
__STATIC_INLINE void LL_TIM_OC_SetIdleState (TIM_TypeDef *TIMx, uint32_t Channel, uint32_t IdleState)
Set the IDLE state of an output channel.
__STATIC_INLINE uint32_t LL_TIM_OC_GetIdleState (TIM_TypeDef *TIMx, uint32_t Channel)
Get the IDLE state of an output channel.
__STATIC_INLINE void LL_TIM_OC_EnableFast (TIM_TypeDef *TIMx, uint32_t Channel)
Enable fast mode for the output channel.
__STATIC_INLINE void LL_TIM_OC_DisableFast (TIM_TypeDef *TIMx, uint32_t Channel)
Disable fast mode for the output channel.
__STATIC_INLINE uint32_t LL_TIM_OC_IsEnabledFast (TIM_TypeDef *TIMx, uint32_t Channel)
Indicates whether fast mode is enabled for the output channel.
__STATIC_INLINE void LL_TIM_OC_EnablePreload (TIM_TypeDef *TIMx, uint32_t Channel)
Enable compare register (TIMx_CCRx) preload for the output channel.
__STATIC_INLINE void LL_TIM_OC_DisablePreload (TIM_TypeDef *TIMx, uint32_t Channel)
Disable compare register (TIMx_CCRx) preload for the output channel.
__STATIC_INLINE uint32_t LL_TIM_OC_IsEnabledPreload (TIM_TypeDef *TIMx, uint32_t Channel)
Indicates whether compare register (TIMx_CCRx) preload is enabled for the output channel.
__STATIC_INLINE void LL_TIM_OC_EnableClear (TIM_TypeDef *TIMx, uint32_t Channel)
Enable clearing the output channel on an external event.
__STATIC_INLINE void LL_TIM_OC_DisableClear (TIM_TypeDef *TIMx, uint32_t Channel)
Disable clearing the output channel on an external event.
__STATIC_INLINE uint32_t LL_TIM_OC_IsEnabledClear (TIM_TypeDef *TIMx, uint32_t Channel)
Indicates clearing the output channel on an external event is enabled for the output channel.
__STATIC_INLINE void LL_TIM_OC_SetDeadTime (TIM_TypeDef *TIMx, uint32_t DeadTime)
Set the dead-time delay (delay inserted between the rising edge of the OCxREF signal and the rising edge of the Ocx and OCxN signals).
__STATIC_INLINE void LL_TIM_OC_SetCompareCH1 (TIM_TypeDef *TIMx, uint32_t CompareValue)
Set compare value for output channel 1 (TIMx_CCR1).
__STATIC_INLINE void LL_TIM_OC_SetCompareCH2 (TIM_TypeDef *TIMx, uint32_t CompareValue)
Set compare value for output channel 2 (TIMx_CCR2).
__STATIC_INLINE void LL_TIM_OC_SetCompareCH3 (TIM_TypeDef *TIMx, uint32_t CompareValue)
Set compare value for output channel 3 (TIMx_CCR3).
__STATIC_INLINE void LL_TIM_OC_SetCompareCH4 (TIM_TypeDef *TIMx, uint32_t CompareValue)
Set compare value for output channel 4 (TIMx_CCR4).
__STATIC_INLINE uint32_t LL_TIM_OC_GetCompareCH1 (TIM_TypeDef *TIMx)
Get compare value (TIMx_CCR1) set for output channel 1.
__STATIC_INLINE uint32_t LL_TIM_OC_GetCompareCH2 (TIM_TypeDef *TIMx)
Get compare value (TIMx_CCR2) set for output channel 2.
__STATIC_INLINE uint32_t LL_TIM_OC_GetCompareCH3 (TIM_TypeDef *TIMx)
Get compare value (TIMx_CCR3) set for output channel 3.
__STATIC_INLINE uint32_t LL_TIM_OC_GetCompareCH4 (TIM_TypeDef *TIMx)
Get compare value (TIMx_CCR4) set for output channel 4.
Function Documentation
__STATIC_INLINE void LL_TIM_OC_ConfigOutput (TIM_TypeDef * TIMx, uint32_t Channel, uint32_t Configuration)
Configure an output channel.
Reference Manual to LL API cross reference:
CCMR1 CC1S LL_TIM_OC_ConfigOutput
CCMR1 CC2S LL_TIM_OC_ConfigOutput
CCMR2 CC3S LL_TIM_OC_ConfigOutput
CCMR2 CC4S LL_TIM_OC_ConfigOutput
CCER CC1P LL_TIM_OC_ConfigOutput
CCER CC2P LL_TIM_OC_ConfigOutput
CCER CC3P LL_TIM_OC_ConfigOutput
CCER CC4P LL_TIM_OC_ConfigOutput
CR2 OIS1 LL_TIM_OC_ConfigOutput
CR2 OIS2 LL_TIM_OC_ConfigOutput
CR2 OIS3 LL_TIM_OC_ConfigOutput
CR2 OIS4 LL_TIM_OC_ConfigOutput
Parameters:
TIMx Timer instance
Channel This parameter can be one of the following values:
LL_TIM_CHANNEL_CH1
LL_TIM_CHANNEL_CH2
LL_TIM_CHANNEL_CH3
LL_TIM_CHANNEL_CH4
Configuration This parameter must be a combination of all the following values:
LL_TIM_OCPOLARITY_HIGH or LL_TIM_OCPOLARITY_LOW
LL_TIM_OCIDLESTATE_LOW or LL_TIM_OCIDLESTATE_HIGH
Return values:
None
Definition at line 1560 of file stm32f1xx_ll_tim.h.
References TIM_GET_CHANNEL_INDEX.
__STATIC_INLINE void LL_TIM_OC_DisableClear (TIM_TypeDef * TIMx, uint32_t Channel)
Disable clearing the output channel on an external event.
Note:
Macro IS_TIM_OCXREF_CLEAR_INSTANCE(TIMx) can be used to check whether or not a timer instance can clear the OCxREF signal on an external event.
Reference Manual to LL API cross reference:
CCMR1 OC1CE LL_TIM_OC_DisableClear
CCMR1 OC2CE LL_TIM_OC_DisableClear
CCMR2 OC3CE LL_TIM_OC_DisableClear
CCMR2 OC4CE LL_TIM_OC_DisableClear
Parameters:
TIMx Timer instance
Channel This parameter can be one of the following values:
LL_TIM_CHANNEL_CH1
LL_TIM_CHANNEL_CH2
LL_TIM_CHANNEL_CH3
LL_TIM_CHANNEL_CH4
Return values:
None
Definition at line 1920 of file stm32f1xx_ll_tim.h.
References TIM_GET_CHANNEL_INDEX.
__STATIC_INLINE void LL_TIM_OC_DisableFast (TIM_TypeDef * TIMx, uint32_t Channel)
Disable fast mode for the output channel.
Reference Manual to LL API cross reference:
CCMR1 OC1FE LL_TIM_OC_DisableFast
CCMR1 OC2FE LL_TIM_OC_DisableFast
CCMR2 OC3FE LL_TIM_OC_DisableFast
CCMR2 OC4FE LL_TIM_OC_DisableFast
Parameters:
TIMx Timer instance
Channel This parameter can be one of the following values:
LL_TIM_CHANNEL_CH1
LL_TIM_CHANNEL_CH2
LL_TIM_CHANNEL_CH3
LL_TIM_CHANNEL_CH4
Return values:
None
Definition at line 1786 of file stm32f1xx_ll_tim.h.
References TIM_GET_CHANNEL_INDEX.
__STATIC_INLINE void LL_TIM_OC_DisablePreload (TIM_TypeDef * TIMx, uint32_t Channel)
Disable compare register (TIMx_CCRx) preload for the output channel.
Reference Manual to LL API cross reference:
CCMR1 OC1PE LL_TIM_OC_DisablePreload
CCMR1 OC2PE LL_TIM_OC_DisablePreload
CCMR2 OC3PE LL_TIM_OC_DisablePreload
CCMR2 OC4PE LL_TIM_OC_DisablePreload
Parameters:
TIMx Timer instance
Channel This parameter can be one of the following values:
LL_TIM_CHANNEL_CH1
LL_TIM_CHANNEL_CH2
LL_TIM_CHANNEL_CH3
LL_TIM_CHANNEL_CH4
Return values:
None
Definition at line 1851 of file stm32f1xx_ll_tim.h.
References TIM_GET_CHANNEL_INDEX.
__STATIC_INLINE void LL_TIM_OC_EnableClear (TIM_TypeDef * TIMx, uint32_t Channel)
Enable clearing the output channel on an external event.
Note:
This function can only be used in Output compare and PWM modes. It does not work in Forced mode.
Macro IS_TIM_OCXREF_CLEAR_INSTANCE(TIMx) can be used to check whether or not a timer instance can clear the OCxREF signal on an external event.
Reference Manual to LL API cross reference:
CCMR1 OC1CE LL_TIM_OC_EnableClear
CCMR1 OC2CE LL_TIM_OC_EnableClear
CCMR2 OC3CE LL_TIM_OC_EnableClear
CCMR2 OC4CE LL_TIM_OC_EnableClear
Parameters:
TIMx Timer instance
Channel This parameter can be one of the following values:
LL_TIM_CHANNEL_CH1
LL_TIM_CHANNEL_CH2
LL_TIM_CHANNEL_CH3
LL_TIM_CHANNEL_CH4
Return values:
None
Definition at line 1897 of file stm32f1xx_ll_tim.h.
References TIM_GET_CHANNEL_INDEX.
__STATIC_INLINE void LL_TIM_OC_EnableFast (TIM_TypeDef * TIMx, uint32_t Channel)
Enable fast mode for the output channel.
Note:
Acts only if the channel is configured in PWM1 or PWM2 mode.
Reference Manual to LL API cross reference:
CCMR1 OC1FE LL_TIM_OC_EnableFast
CCMR1 OC2FE LL_TIM_OC_EnableFast
CCMR2 OC3FE LL_TIM_OC_EnableFast
CCMR2 OC4FE LL_TIM_OC_EnableFast
Parameters:
TIMx Timer instance
Channel This parameter can be one of the following values:
LL_TIM_CHANNEL_CH1
LL_TIM_CHANNEL_CH2
LL_TIM_CHANNEL_CH3
LL_TIM_CHANNEL_CH4
Return values:
None
Definition at line 1764 of file stm32f1xx_ll_tim.h.
References TIM_GET_CHANNEL_INDEX.
__STATIC_INLINE void LL_TIM_OC_EnablePreload (TIM_TypeDef * TIMx, uint32_t Channel)
Enable compare register (TIMx_CCRx) preload for the output channel.
Reference Manual to LL API cross reference:
CCMR1 OC1PE LL_TIM_OC_EnablePreload
CCMR1 OC2PE LL_TIM_OC_EnablePreload
CCMR2 OC3PE LL_TIM_OC_EnablePreload
CCMR2 OC4PE LL_TIM_OC_EnablePreload
Parameters:
TIMx Timer instance
Channel This parameter can be one of the following values:
LL_TIM_CHANNEL_CH1
LL_TIM_CHANNEL_CH2
LL_TIM_CHANNEL_CH3
LL_TIM_CHANNEL_CH4
Return values:
None
Definition at line 1830 of file stm32f1xx_ll_tim.h.
References TIM_GET_CHANNEL_INDEX.
__STATIC_INLINE uint32_t LL_TIM_OC_GetCompareCH1 (TIM_TypeDef * TIMx)
Get compare value (TIMx_CCR1) set for output channel 1.
Note:
Macro IS_TIM_CC1_INSTANCE(TIMx) can be used to check whether or not output channel 1 is supported by a timer instance.
Reference Manual to LL API cross reference:
CCR1 CCR1 LL_TIM_OC_GetCompareCH1
Parameters:
TIMx Timer instance
Return values:
CompareValue (between Min_Data=0 and Max_Data=65535)
Definition at line 2032 of file stm32f1xx_ll_tim.h.
__STATIC_INLINE uint32_t LL_TIM_OC_GetCompareCH2 (TIM_TypeDef * TIMx)
Get compare value (TIMx_CCR2) set for output channel 2.
Note:
Macro IS_TIM_CC2_INSTANCE(TIMx) can be used to check whether or not output channel 2 is supported by a timer instance.
Reference Manual to LL API cross reference:
CCR2 CCR2 LL_TIM_OC_GetCompareCH2
Parameters:
TIMx Timer instance
Return values:
CompareValue (between Min_Data=0 and Max_Data=65535)
Definition at line 2045 of file stm32f1xx_ll_tim.h.
__STATIC_INLINE uint32_t LL_TIM_OC_GetCompareCH3 (TIM_TypeDef * TIMx)
Get compare value (TIMx_CCR3) set for output channel 3.
Note:
Macro IS_TIM_CC3_INSTANCE(TIMx) can be used to check whether or not output channel 3 is supported by a timer instance.
Reference Manual to LL API cross reference:
CCR3 CCR3 LL_TIM_OC_GetCompareCH3
Parameters:
TIMx Timer instance
Return values:
CompareValue (between Min_Data=0 and Max_Data=65535)
Definition at line 2058 of file stm32f1xx_ll_tim.h.
__STATIC_INLINE uint32_t LL_TIM_OC_GetCompareCH4 (TIM_TypeDef * TIMx)
Get compare value (TIMx_CCR4) set for output channel 4.
Note:
Macro IS_TIM_CC4_INSTANCE(TIMx) can be used to check whether or not output channel 4 is supported by a timer instance.
Reference Manual to LL API cross reference:
CCR4 CCR4 LL_TIM_OC_GetCompareCH4
Parameters:
TIMx Timer instance
Return values:
CompareValue (between Min_Data=0 and Max_Data=65535)
Definition at line 2071 of file stm32f1xx_ll_tim.h.
__STATIC_INLINE uint32_t LL_TIM_OC_GetIdleState (TIM_TypeDef * TIMx, uint32_t Channel)
Get the IDLE state of an output channel.
Reference Manual to LL API cross reference:
CR2 OIS1 LL_TIM_OC_GetIdleState
CR2 OIS1N LL_TIM_OC_GetIdleState
CR2 OIS2 LL_TIM_OC_GetIdleState
CR2 OIS2N LL_TIM_OC_GetIdleState
CR2 OIS3 LL_TIM_OC_GetIdleState
CR2 OIS3N LL_TIM_OC_GetIdleState
CR2 OIS4 LL_TIM_OC_GetIdleState
Parameters:
TIMx Timer instance
Channel This parameter can be one of the following values:
LL_TIM_CHANNEL_CH1
LL_TIM_CHANNEL_CH1N
LL_TIM_CHANNEL_CH2
LL_TIM_CHANNEL_CH2N
LL_TIM_CHANNEL_CH3
LL_TIM_CHANNEL_CH3N
LL_TIM_CHANNEL_CH4
Return values:
Returned value can be one of the following values:
LL_TIM_OCIDLESTATE_LOW
LL_TIM_OCIDLESTATE_HIGH
Definition at line 1743 of file stm32f1xx_ll_tim.h.
References TIM_GET_CHANNEL_INDEX.
__STATIC_INLINE uint32_t LL_TIM_OC_GetMode (TIM_TypeDef * TIMx, uint32_t Channel)
Get the output compare mode of an output channel.
Reference Manual to LL API cross reference:
CCMR1 OC1M LL_TIM_OC_GetMode
CCMR1 OC2M LL_TIM_OC_GetMode
CCMR2 OC3M LL_TIM_OC_GetMode
CCMR2 OC4M LL_TIM_OC_GetMode
Parameters:
TIMx Timer instance
Channel This parameter can be one of the following values:
LL_TIM_CHANNEL_CH1
LL_TIM_CHANNEL_CH2
LL_TIM_CHANNEL_CH3
LL_TIM_CHANNEL_CH4
Return values:
Returned value can be one of the following values:
LL_TIM_OCMODE_FROZEN
LL_TIM_OCMODE_ACTIVE
LL_TIM_OCMODE_INACTIVE
LL_TIM_OCMODE_TOGGLE
LL_TIM_OCMODE_FORCED_INACTIVE
LL_TIM_OCMODE_FORCED_ACTIVE
LL_TIM_OCMODE_PWM1
LL_TIM_OCMODE_PWM2
Definition at line 1624 of file stm32f1xx_ll_tim.h.
References TIM_GET_CHANNEL_INDEX.
__STATIC_INLINE uint32_t LL_TIM_OC_GetPolarity (TIM_TypeDef * TIMx, uint32_t Channel)
Get the polarity of an output channel.
Reference Manual to LL API cross reference:
CCER CC1P LL_TIM_OC_GetPolarity
CCER CC1NP LL_TIM_OC_GetPolarity
CCER CC2P LL_TIM_OC_GetPolarity
CCER CC2NP LL_TIM_OC_GetPolarity
CCER CC3P LL_TIM_OC_GetPolarity
CCER CC3NP LL_TIM_OC_GetPolarity
CCER CC4P LL_TIM_OC_GetPolarity
Parameters:
TIMx Timer instance
Channel This parameter can be one of the following values:
LL_TIM_CHANNEL_CH1
LL_TIM_CHANNEL_CH1N
LL_TIM_CHANNEL_CH2
LL_TIM_CHANNEL_CH2N
LL_TIM_CHANNEL_CH3
LL_TIM_CHANNEL_CH3N
LL_TIM_CHANNEL_CH4
Return values:
Returned value can be one of the following values:
LL_TIM_OCPOLARITY_HIGH
LL_TIM_OCPOLARITY_LOW
Definition at line 1682 of file stm32f1xx_ll_tim.h.
References TIM_GET_CHANNEL_INDEX.
__STATIC_INLINE uint32_t LL_TIM_OC_IsEnabledClear (TIM_TypeDef * TIMx, uint32_t Channel)
Indicates clearing the output channel on an external event is enabled for the output channel.
Note:
This function enables clearing the output channel on an external event.
This function can only be used in Output compare and PWM modes. It does not work in Forced mode.
Macro IS_TIM_OCXREF_CLEAR_INSTANCE(TIMx) can be used to check whether or not a timer instance can clear the OCxREF signal on an external event.
Reference Manual to LL API cross reference:
CCMR1 OC1CE LL_TIM_OC_IsEnabledClear
CCMR1 OC2CE LL_TIM_OC_IsEnabledClear
CCMR2 OC3CE LL_TIM_OC_IsEnabledClear
CCMR2 OC4CE LL_TIM_OC_IsEnabledClear
Parameters:
TIMx Timer instance
Channel This parameter can be one of the following values:
LL_TIM_CHANNEL_CH1
LL_TIM_CHANNEL_CH2
LL_TIM_CHANNEL_CH3
LL_TIM_CHANNEL_CH4
Return values:
State of bit (1 or 0).
Definition at line 1945 of file stm32f1xx_ll_tim.h.
References TIM_GET_CHANNEL_INDEX.
__STATIC_INLINE uint32_t LL_TIM_OC_IsEnabledFast (TIM_TypeDef * TIMx, uint32_t Channel)
Indicates whether fast mode is enabled for the output channel.
Reference Manual to LL API cross reference:
CCMR1 OC1FE LL_TIM_OC_IsEnabledFast
CCMR1 OC2FE LL_TIM_OC_IsEnabledFast
CCMR2 OC3FE LL_TIM_OC_IsEnabledFast
CCMR2 OC4FE LL_TIM_OC_IsEnabledFast
Parameters:
TIMx Timer instance
Channel This parameter can be one of the following values:
LL_TIM_CHANNEL_CH1
LL_TIM_CHANNEL_CH2
LL_TIM_CHANNEL_CH3
LL_TIM_CHANNEL_CH4
Return values:
State of bit (1 or 0).
Definition at line 1808 of file stm32f1xx_ll_tim.h.
References TIM_GET_CHANNEL_INDEX.
__STATIC_INLINE uint32_t LL_TIM_OC_IsEnabledPreload (TIM_TypeDef * TIMx, uint32_t Channel)
Indicates whether compare register (TIMx_CCRx) preload is enabled for the output channel.
Reference Manual to LL API cross reference:
CCMR1 OC1PE LL_TIM_OC_IsEnabledPreload
CCMR1 OC2PE LL_TIM_OC_IsEnabledPreload
CCMR2 OC3PE LL_TIM_OC_IsEnabledPreload
CCMR2 OC4PE LL_TIM_OC_IsEnabledPreload
Parameters:
TIMx Timer instance
Channel This parameter can be one of the following values:
LL_TIM_CHANNEL_CH1
LL_TIM_CHANNEL_CH2
LL_TIM_CHANNEL_CH3
LL_TIM_CHANNEL_CH4
Return values:
State of bit (1 or 0).
Definition at line 1872 of file stm32f1xx_ll_tim.h.
References TIM_GET_CHANNEL_INDEX.
__STATIC_INLINE void LL_TIM_OC_SetCompareCH1 (TIM_TypeDef * TIMx, uint32_t CompareValue)
Set compare value for output channel 1 (TIMx_CCR1).
Note:
Macro IS_TIM_CC1_INSTANCE(TIMx) can be used to check whether or not output channel 1 is supported by a timer instance.
Reference Manual to LL API cross reference:
CCR1 CCR1 LL_TIM_OC_SetCompareCH1
Parameters:
TIMx Timer instance
CompareValue between Min_Data=0 and Max_Data=65535
Return values:
None
Definition at line 1977 of file stm32f1xx_ll_tim.h.
Referenced by OC1Config().
__STATIC_INLINE void LL_TIM_OC_SetCompareCH2 (TIM_TypeDef * TIMx, uint32_t CompareValue)
Set compare value for output channel 2 (TIMx_CCR2).
Note:
Macro IS_TIM_CC2_INSTANCE(TIMx) can be used to check whether or not output channel 2 is supported by a timer instance.
Reference Manual to LL API cross reference:
CCR2 CCR2 LL_TIM_OC_SetCompareCH2
Parameters:
TIMx Timer instance
CompareValue between Min_Data=0 and Max_Data=65535
Return values:
None
Definition at line 1991 of file stm32f1xx_ll_tim.h.
Referenced by LL_TIM_HALLSENSOR_Init(), and OC2Config().
__STATIC_INLINE void LL_TIM_OC_SetCompareCH3 (TIM_TypeDef * TIMx, uint32_t CompareValue)
Set compare value for output channel 3 (TIMx_CCR3).
Note:
Macro IS_TIM_CC3_INSTANCE(TIMx) can be used to check whether or not output channel is supported by a timer instance.
Reference Manual to LL API cross reference:
CCR3 CCR3 LL_TIM_OC_SetCompareCH3
Parameters:
TIMx Timer instance
CompareValue between Min_Data=0 and Max_Data=65535
Return values:
None
Definition at line 2005 of file stm32f1xx_ll_tim.h.
Referenced by OC3Config().
__STATIC_INLINE void LL_TIM_OC_SetCompareCH4 (TIM_TypeDef * TIMx, uint32_t CompareValue)
Set compare value for output channel 4 (TIMx_CCR4).
Note:
Macro IS_TIM_CC4_INSTANCE(TIMx) can be used to check whether or not output channel 4 is supported by a timer instance.
Reference Manual to LL API cross reference:
CCR4 CCR4 LL_TIM_OC_SetCompareCH4
Parameters:
TIMx Timer instance
CompareValue between Min_Data=0 and Max_Data=65535
Return values:
None
Definition at line 2019 of file stm32f1xx_ll_tim.h.
Referenced by OC4Config().
__STATIC_INLINE void LL_TIM_OC_SetDeadTime (TIM_TypeDef * TIMx, uint32_t DeadTime)
Set the dead-time delay (delay inserted between the rising edge of the OCxREF signal and the rising edge of the Ocx and OCxN signals).
Note:
Macro IS_TIM_BREAK_INSTANCE(TIMx) can be used to check whether or not dead-time insertion feature is supported by a timer instance.
Helper macro __LL_TIM_CALC_DEADTIME can be used to calculate the DeadTime parameter
Reference Manual to LL API cross reference:
BDTR DTG LL_TIM_OC_SetDeadTime
Parameters:
TIMx Timer instance
DeadTime between Min_Data=0 and Max_Data=255
Return values:
None
Definition at line 1963 of file stm32f1xx_ll_tim.h.
__STATIC_INLINE void LL_TIM_OC_SetIdleState (TIM_TypeDef * TIMx, uint32_t Channel, uint32_t IdleState)
Set the IDLE state of an output channel.
Note:
This function is significant only for the timer instances supporting the break feature. Macro IS_TIM_BREAK_INSTANCE(TIMx) can be used to check whether or not a timer instance provides a break input.
Reference Manual to LL API cross reference:
CR2 OIS1 LL_TIM_OC_SetIdleState
CR2 OIS1N LL_TIM_OC_SetIdleState
CR2 OIS2 LL_TIM_OC_SetIdleState
CR2 OIS2N LL_TIM_OC_SetIdleState
CR2 OIS3 LL_TIM_OC_SetIdleState
CR2 OIS3N LL_TIM_OC_SetIdleState
CR2 OIS4 LL_TIM_OC_SetIdleState
Parameters:
TIMx Timer instance
Channel This parameter can be one of the following values:
LL_TIM_CHANNEL_CH1
LL_TIM_CHANNEL_CH1N
LL_TIM_CHANNEL_CH2
LL_TIM_CHANNEL_CH2N
LL_TIM_CHANNEL_CH3
LL_TIM_CHANNEL_CH3N
LL_TIM_CHANNEL_CH4
IdleState This parameter can be one of the following values:
LL_TIM_OCIDLESTATE_LOW
LL_TIM_OCIDLESTATE_HIGH
Return values:
None
Definition at line 1715 of file stm32f1xx_ll_tim.h.
References TIM_GET_CHANNEL_INDEX.
__STATIC_INLINE void LL_TIM_OC_SetMode (TIM_TypeDef * TIMx, uint32_t Channel, uint32_t Mode)
Define the behavior of the output reference signal OCxREF from which OCx and OCxN (when relevant) are derived.
Reference Manual to LL API cross reference:
CCMR1 OC1M LL_TIM_OC_SetMode
CCMR1 OC2M LL_TIM_OC_SetMode
CCMR2 OC3M LL_TIM_OC_SetMode
CCMR2 OC4M LL_TIM_OC_SetMode
Parameters:
TIMx Timer instance
Channel This parameter can be one of the following values:
LL_TIM_CHANNEL_CH1
LL_TIM_CHANNEL_CH2
LL_TIM_CHANNEL_CH3
LL_TIM_CHANNEL_CH4
Mode This parameter can be one of the following values:
LL_TIM_OCMODE_FROZEN
LL_TIM_OCMODE_ACTIVE
LL_TIM_OCMODE_INACTIVE
LL_TIM_OCMODE_TOGGLE
LL_TIM_OCMODE_FORCED_INACTIVE
LL_TIM_OCMODE_FORCED_ACTIVE
LL_TIM_OCMODE_PWM1
LL_TIM_OCMODE_PWM2
Return values:
None
Definition at line 1595 of file stm32f1xx_ll_tim.h.
References TIM_GET_CHANNEL_INDEX.
__STATIC_INLINE void LL_TIM_OC_SetPolarity (TIM_TypeDef * TIMx, uint32_t Channel, uint32_t Polarity)
Set the polarity of an output channel.
Reference Manual to LL API cross reference:
CCER CC1P LL_TIM_OC_SetPolarity
CCER CC1NP LL_TIM_OC_SetPolarity
CCER CC2P LL_TIM_OC_SetPolarity
CCER CC2NP LL_TIM_OC_SetPolarity
CCER CC3P LL_TIM_OC_SetPolarity
CCER CC3NP LL_TIM_OC_SetPolarity
CCER CC4P LL_TIM_OC_SetPolarity
Parameters:
TIMx Timer instance
Channel This parameter can be one of the following values:
LL_TIM_CHANNEL_CH1
LL_TIM_CHANNEL_CH1N
LL_TIM_CHANNEL_CH2
LL_TIM_CHANNEL_CH2N
LL_TIM_CHANNEL_CH3
LL_TIM_CHANNEL_CH3N
LL_TIM_CHANNEL_CH4
Polarity This parameter can be one of the following values:
LL_TIM_OCPOLARITY_HIGH
LL_TIM_OCPOLARITY_LOW
Return values:
None
Definition at line 1654 of file stm32f1xx_ll_tim.h.
References TIM_GET_CHANNEL_INDEX.