STM32F103xB HAL User Manual: RTC Tamper functions
RTC Tamper functions
RTCEx Exported Functions
RTC Tamper functions.
Functions
HAL_StatusTypeDef HAL_RTCEx_SetTamper (RTC_HandleTypeDef *hrtc, RTC_TamperTypeDef *sTamper)
Sets Tamper.
HAL_StatusTypeDef HAL_RTCEx_SetTamper_IT (RTC_HandleTypeDef *hrtc, RTC_TamperTypeDef *sTamper)
Sets Tamper with interrupt.
HAL_StatusTypeDef HAL_RTCEx_DeactivateTamper (RTC_HandleTypeDef *hrtc, uint32_t Tamper)
Deactivates Tamper.
void HAL_RTCEx_TamperIRQHandler (RTC_HandleTypeDef *hrtc)
This function handles Tamper interrupt request.
__weak void HAL_RTCEx_Tamper1EventCallback (RTC_HandleTypeDef *hrtc)
Tamper 1 callback.
HAL_StatusTypeDef HAL_RTCEx_PollForTamper1Event (RTC_HandleTypeDef *hrtc, uint32_t Timeout)
This function handles Tamper1 Polling.
Detailed Description
RTC Tamper functions.
 ===============================================================================
                 ##### RTC Tamper functions #####
 ===============================================================================
 [..] This section provides functions allowing to configure Tamper feature
Function Documentation
HAL_StatusTypeDef HAL_RTCEx_DeactivateTamper (RTC_HandleTypeDef * hrtc, uint32_t Tamper)
Deactivates Tamper.
Parameters:
hrtc,: pointer to a RTC_HandleTypeDef structure that contains the configuration information for RTC.
Tamper,: Selected tamper pin. This parameter can be a value of Tamper Pins Definitions
Return values:
HAL status
Definition at line 175 of file stm32f1xx_hal_rtc_ex.c.
References __HAL_RTC_TAMPER_CLEAR_FLAG, __HAL_RTC_TAMPER_DISABLE_IT, assert_param, HAL_RTC_STATE_BUSY, HAL_RTC_STATE_READY, IS_RTC_TAMPER, RTC_FLAG_TAMP1F, RTC_IT_TAMP1, and RTC_HandleTypeDef::State.
HAL_StatusTypeDef HAL_RTCEx_PollForTamper1Event (RTC_HandleTypeDef * hrtc, uint32_t Timeout)
This function handles Tamper1 Polling.
Parameters:
hrtc,: pointer to a RTC_HandleTypeDef structure that contains the configuration information for RTC.
Timeout,: Timeout duration
Return values:
HAL status
Definition at line 263 of file stm32f1xx_hal_rtc_ex.c.
References __HAL_RTC_TAMPER_CLEAR_FLAG, __HAL_RTC_TAMPER_GET_FLAG, HAL_GetTick(), HAL_RTC_STATE_READY, HAL_RTC_STATE_TIMEOUT, RTC_FLAG_TAMP1F, and RTC_HandleTypeDef::State.
HAL_StatusTypeDef HAL_RTCEx_SetTamper (RTC_HandleTypeDef * hrtc, RTC_TamperTypeDef * sTamper)
Sets Tamper.
Note:
By calling this API we disable the tamper interrupt for all tampers.
Parameters:
hrtc,: pointer to a RTC_HandleTypeDef structure that contains the configuration information for RTC.
sTamper,: Pointer to Tamper Structure.
Note:
Tamper can be enabled only if ASOE and CCO bit are reset
Return values:
HAL status
Definition at line 81 of file stm32f1xx_hal_rtc_ex.c.
References assert_param, HAL_RTC_STATE_BUSY, HAL_RTC_STATE_ERROR, HAL_RTC_STATE_READY, IS_RTC_TAMPER, IS_RTC_TAMPER_TRIGGER, RTC_HandleTypeDef::State, RTC_TamperTypeDef::Tamper, and RTC_TamperTypeDef::Trigger.
HAL_StatusTypeDef HAL_RTCEx_SetTamper_IT (RTC_HandleTypeDef * hrtc, RTC_TamperTypeDef * sTamper)
Sets Tamper with interrupt.
Note:
By calling this API we force the tamper interrupt for all tampers.
Parameters:
hrtc,: pointer to a RTC_HandleTypeDef structure that contains the configuration information for RTC.
sTamper,: Pointer to RTC Tamper.
Note:
Tamper can be enabled only if ASOE and CCO bit are reset
Return values:
HAL status
Definition at line 127 of file stm32f1xx_hal_rtc_ex.c.
References __HAL_RTC_TAMPER_ENABLE_IT, assert_param, HAL_RTC_STATE_BUSY, HAL_RTC_STATE_ERROR, HAL_RTC_STATE_READY, IS_RTC_TAMPER, IS_RTC_TAMPER_TRIGGER, RTC_IT_TAMP1, RTC_HandleTypeDef::State, RTC_TamperTypeDef::Tamper, and RTC_TamperTypeDef::Trigger.
void HAL_RTCEx_Tamper1EventCallback (RTC_HandleTypeDef * hrtc)
Tamper 1 callback.
Parameters:
hrtc,: pointer to a RTC_HandleTypeDef structure that contains the configuration information for RTC.
Return values:
None
Definition at line 247 of file stm32f1xx_hal_rtc_ex.c.
Referenced by HAL_RTC_Init(), and HAL_RTCEx_TamperIRQHandler().
void HAL_RTCEx_TamperIRQHandler (RTC_HandleTypeDef * hrtc)
This function handles Tamper interrupt request.
Parameters:
hrtc,: pointer to a RTC_HandleTypeDef structure that contains the configuration information for RTC.
Return values:
None
Definition at line 217 of file stm32f1xx_hal_rtc_ex.c.
References __HAL_RTC_TAMPER_CLEAR_FLAG, __HAL_RTC_TAMPER_GET_FLAG, __HAL_RTC_TAMPER_GET_IT_SOURCE, HAL_RTC_STATE_READY, HAL_RTCEx_Tamper1EventCallback(), RTC_FLAG_TAMP1F, RTC_IT_TAMP1, and RTC_HandleTypeDef::State.