STM32F103xB HAL User Manual: ADC Private Functions
ADC Private Functions
ADC
Functions
HAL_StatusTypeDef ADC_Enable (ADC_HandleTypeDef *hadc)
Enable the selected ADC.
HAL_StatusTypeDef ADC_ConversionStop_Disable (ADC_HandleTypeDef *hadc)
Stop ADC conversion and disable the selected ADC.
void ADC_DMAConvCplt (DMA_HandleTypeDef *hdma)
DMA transfer complete callback.
void ADC_DMAHalfConvCplt (DMA_HandleTypeDef *hdma)
DMA half transfer complete callback.
void ADC_DMAError (DMA_HandleTypeDef *hdma)
DMA error callback.
void ADC_StabilizationTime (uint32_t DelayUs)
Function Documentation
HAL_StatusTypeDef ADC_ConversionStop_Disable (ADC_HandleTypeDef * hadc)
Stop ADC conversion and disable the selected ADC.
Note:
Prerequisite condition to use this function: ADC conversions must be stopped to disable the ADC.
Parameters:
hadc,: ADC handle
Return values:
HAL status.
Definition at line 2279 of file stm32f1xx_hal_adc.c.
References __HAL_ADC_DISABLE, ADC_DISABLE_TIMEOUT, ADC_IS_ENABLE, __ADC_HandleTypeDef::ErrorCode, HAL_ADC_ERROR_INTERNAL, HAL_ADC_STATE_ERROR_INTERNAL, HAL_GetTick(), and __ADC_HandleTypeDef::State.
Referenced by HAL_ADC_DeInit(), HAL_ADC_Init(), HAL_ADC_Stop(), HAL_ADC_Stop_DMA(), HAL_ADC_Stop_IT(), HAL_ADCEx_Calibration_Start(), HAL_ADCEx_InjectedStop(), HAL_ADCEx_InjectedStop_IT(), and HAL_ADCEx_MultiModeStop_DMA().
void ADC_DMAConvCplt (DMA_HandleTypeDef * hdma)
DMA transfer complete callback.
Parameters:
hdma,: pointer to DMA handle.
Return values:
None
Definition at line 2317 of file stm32f1xx_hal_adc.c.
References ADC_IS_SOFTWARE_START_REGULAR, ADC_InitTypeDef::ContinuousConvMode, __ADC_HandleTypeDef::DMA_Handle, HAL_ADC_ConvCpltCallback(), HAL_ADC_STATE_ERROR_DMA, HAL_ADC_STATE_ERROR_INTERNAL, HAL_ADC_STATE_INJ_BUSY, HAL_ADC_STATE_READY, HAL_ADC_STATE_REG_BUSY, HAL_ADC_STATE_REG_EOC, __ADC_HandleTypeDef::Init, __ADC_HandleTypeDef::State, and __DMA_HandleTypeDef::XferErrorCallback.
Referenced by HAL_ADC_Start_DMA(), and HAL_ADCEx_MultiModeStart_DMA().
void ADC_DMAError (DMA_HandleTypeDef * hdma)
DMA error callback.
Parameters:
hdma,: pointer to DMA handle.
Return values:
None
Definition at line 2382 of file stm32f1xx_hal_adc.c.
References __ADC_HandleTypeDef::ErrorCode, HAL_ADC_ERROR_DMA, HAL_ADC_ErrorCallback(), HAL_ADC_STATE_ERROR_DMA, and __ADC_HandleTypeDef::State.
Referenced by HAL_ADC_Start_DMA(), and HAL_ADCEx_MultiModeStart_DMA().
void ADC_DMAHalfConvCplt (DMA_HandleTypeDef * hdma)
DMA half transfer complete callback.
Parameters:
hdma,: pointer to DMA handle.
Return values:
None
Definition at line 2364 of file stm32f1xx_hal_adc.c.
References HAL_ADC_ConvHalfCpltCallback().
Referenced by HAL_ADC_Start_DMA(), and HAL_ADCEx_MultiModeStart_DMA().
HAL_StatusTypeDef ADC_Enable (ADC_HandleTypeDef * hadc)
Enable the selected ADC.
Note:
Prerequisite condition to use this function: ADC must be disabled and voltage regulator must be enabled (done into HAL_ADC_Init()).
Parameters:
hadc,: ADC handle
Return values:
HAL status.
Definition at line 2224 of file stm32f1xx_hal_adc.c.
References __HAL_ADC_ENABLE, ADC_ENABLE_TIMEOUT, ADC_IS_ENABLE, ADC_STAB_DELAY_US, __ADC_HandleTypeDef::ErrorCode, HAL_ADC_ERROR_INTERNAL, HAL_ADC_STATE_ERROR_INTERNAL, HAL_GetTick(), and __ADC_HandleTypeDef::State.
Referenced by HAL_ADC_Start(), HAL_ADC_Start_DMA(), HAL_ADC_Start_IT(), HAL_ADCEx_Calibration_Start(), HAL_ADCEx_InjectedStart(), HAL_ADCEx_InjectedStart_IT(), and HAL_ADCEx_MultiModeStart_DMA().
void ADC_StabilizationTime (uint32_t DelayUs)