STM32F103xB HAL User Manual: HAL Private Variables
HAL Private Variables
HAL
Variables
__IO uint32_t uwTick
uint32_t uwTickPrio = (1UL << __NVIC_PRIO_BITS)
HAL_TickFreqTypeDef uwTickFreq = HAL_TICK_FREQ_DEFAULT
Variable Documentation
__IO uint32_t uwTick
Definition at line 79 of file stm32f1xx_hal.c.
Referenced by HAL_GetTick(), and HAL_IncTick().
HAL_TickFreqTypeDef uwTickFreq = HAL_TICK_FREQ_DEFAULT
Definition at line 81 of file stm32f1xx_hal.c.
Referenced by HAL_Delay(), HAL_GetTickFreq(), HAL_IncTick(), HAL_InitTick(), and HAL_SetTickFreq().
uint32_t uwTickPrio = (1UL << __NVIC_PRIO_BITS)
Definition at line 80 of file stm32f1xx_hal.c.
Referenced by HAL_GetTickPrio(), HAL_InitTick(), HAL_RCC_ClockConfig(), HAL_RCC_DeInit(), and HAL_SetTickFreq().