STM32F103xB HAL User Manual: Peripheral State and Errors functions
Peripheral State and Errors functions
DMA Exported Functions
Peripheral State and Errors functions.
Functions
HAL_DMA_StateTypeDef HAL_DMA_GetState (DMA_HandleTypeDef *hdma)
Return the DMA hande state.
uint32_t HAL_DMA_GetError (DMA_HandleTypeDef *hdma)
Return the DMA error code.
Detailed Description
Peripheral State and Errors functions.
 ===============================================================================
            ##### Peripheral State and Errors functions #####
 ===============================================================================
    [..]
    This subsection provides functions allowing to
      (+) Check the DMA state
      (+) Get error code
Function Documentation
uint32_t HAL_DMA_GetError (DMA_HandleTypeDef * hdma)
Return the DMA error code.
Parameters:
hdma : pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA Channel.
Return values:
DMA Error Code
Definition at line 832 of file stm32f1xx_hal_dma.c.
References __DMA_HandleTypeDef::ErrorCode.
Referenced by HAL_UART_Abort(), HAL_UART_AbortReceive(), and HAL_UART_AbortTransmit().
HAL_DMA_StateTypeDef HAL_DMA_GetState (DMA_HandleTypeDef * hdma)
Return the DMA hande state.
Parameters:
hdma,: pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA Channel.
Return values:
HAL state
Definition at line 820 of file stm32f1xx_hal_dma.c.
References __DMA_HandleTypeDef::State.
Referenced by I2C_Slave_STOPF().