STM32F103xB HAL User Manual: APB1
APB1
BUS Exported Functions
Functions
__STATIC_INLINE void LL_APB1_GRP1_EnableClock (uint32_t Periphs)
Enable APB1 peripherals clock.
__STATIC_INLINE uint32_t LL_APB1_GRP1_IsEnabledClock (uint32_t Periphs)
Check if APB1 peripheral clock is enabled or not.
__STATIC_INLINE void LL_APB1_GRP1_DisableClock (uint32_t Periphs)
Disable APB1 peripherals clock.
__STATIC_INLINE void LL_APB1_GRP1_ForceReset (uint32_t Periphs)
Force APB1 peripherals reset.
__STATIC_INLINE void LL_APB1_GRP1_ReleaseReset (uint32_t Periphs)
Release APB1 peripherals reset.
Function Documentation
__STATIC_INLINE void LL_APB1_GRP1_DisableClock (uint32_t Periphs)
Disable APB1 peripherals clock.
Reference Manual to LL API cross reference:
APB1ENR BKPEN LL_APB1_GRP1_DisableClock
APB1ENR CAN1EN LL_APB1_GRP1_DisableClock
APB1ENR CAN2EN LL_APB1_GRP1_DisableClock
APB1ENR CECEN LL_APB1_GRP1_DisableClock
APB1ENR DACEN LL_APB1_GRP1_DisableClock
APB1ENR I2C1EN LL_APB1_GRP1_DisableClock
APB1ENR I2C2EN LL_APB1_GRP1_DisableClock
APB1ENR PWREN LL_APB1_GRP1_DisableClock
APB1ENR SPI2EN LL_APB1_GRP1_DisableClock
APB1ENR SPI3EN LL_APB1_GRP1_DisableClock
APB1ENR TIM12EN LL_APB1_GRP1_DisableClock
APB1ENR TIM13EN LL_APB1_GRP1_DisableClock
APB1ENR TIM14EN LL_APB1_GRP1_DisableClock
APB1ENR TIM2EN LL_APB1_GRP1_DisableClock
APB1ENR TIM3EN LL_APB1_GRP1_DisableClock
APB1ENR TIM4EN LL_APB1_GRP1_DisableClock
APB1ENR TIM5EN LL_APB1_GRP1_DisableClock
APB1ENR TIM6EN LL_APB1_GRP1_DisableClock
APB1ENR TIM7EN LL_APB1_GRP1_DisableClock
APB1ENR UART4EN LL_APB1_GRP1_DisableClock
APB1ENR UART5EN LL_APB1_GRP1_DisableClock
APB1ENR USART2EN LL_APB1_GRP1_DisableClock
APB1ENR USART3EN LL_APB1_GRP1_DisableClock
APB1ENR USBEN LL_APB1_GRP1_DisableClock
APB1ENR WWDGEN LL_APB1_GRP1_DisableClock
Parameters:
Periphs This parameter can be a combination of the following values:
LL_APB1_GRP1_PERIPH_BKP
LL_APB1_GRP1_PERIPH_CAN1 (*)
LL_APB1_GRP1_PERIPH_CAN2 (*)
LL_APB1_GRP1_PERIPH_CEC (*)
LL_APB1_GRP1_PERIPH_DAC1 (*)
LL_APB1_GRP1_PERIPH_I2C1
LL_APB1_GRP1_PERIPH_I2C2 (*)
LL_APB1_GRP1_PERIPH_PWR
LL_APB1_GRP1_PERIPH_SPI2 (*)
LL_APB1_GRP1_PERIPH_SPI3 (*)
LL_APB1_GRP1_PERIPH_TIM12 (*)
LL_APB1_GRP1_PERIPH_TIM13 (*)
LL_APB1_GRP1_PERIPH_TIM14 (*)
LL_APB1_GRP1_PERIPH_TIM2
LL_APB1_GRP1_PERIPH_TIM3
LL_APB1_GRP1_PERIPH_TIM4 (*)
LL_APB1_GRP1_PERIPH_TIM5 (*)
LL_APB1_GRP1_PERIPH_TIM6 (*)
LL_APB1_GRP1_PERIPH_TIM7 (*)
LL_APB1_GRP1_PERIPH_UART4 (*)
LL_APB1_GRP1_PERIPH_UART5 (*)
LL_APB1_GRP1_PERIPH_USART2
LL_APB1_GRP1_PERIPH_USART3 (*)
LL_APB1_GRP1_PERIPH_USB (*)
LL_APB1_GRP1_PERIPH_WWDG
(*) value not defined in all devices.
Return values:
None
Definition at line 575 of file stm32f1xx_ll_bus.h.
__STATIC_INLINE void LL_APB1_GRP1_EnableClock (uint32_t Periphs)
Enable APB1 peripherals clock.
Reference Manual to LL API cross reference:
APB1ENR BKPEN LL_APB1_GRP1_EnableClock
APB1ENR CAN1EN LL_APB1_GRP1_EnableClock
APB1ENR CAN2EN LL_APB1_GRP1_EnableClock
APB1ENR CECEN LL_APB1_GRP1_EnableClock
APB1ENR DACEN LL_APB1_GRP1_EnableClock
APB1ENR I2C1EN LL_APB1_GRP1_EnableClock
APB1ENR I2C2EN LL_APB1_GRP1_EnableClock
APB1ENR PWREN LL_APB1_GRP1_EnableClock
APB1ENR SPI2EN LL_APB1_GRP1_EnableClock
APB1ENR SPI3EN LL_APB1_GRP1_EnableClock
APB1ENR TIM12EN LL_APB1_GRP1_EnableClock
APB1ENR TIM13EN LL_APB1_GRP1_EnableClock
APB1ENR TIM14EN LL_APB1_GRP1_EnableClock
APB1ENR TIM2EN LL_APB1_GRP1_EnableClock
APB1ENR TIM3EN LL_APB1_GRP1_EnableClock
APB1ENR TIM4EN LL_APB1_GRP1_EnableClock
APB1ENR TIM5EN LL_APB1_GRP1_EnableClock
APB1ENR TIM6EN LL_APB1_GRP1_EnableClock
APB1ENR TIM7EN LL_APB1_GRP1_EnableClock
APB1ENR UART4EN LL_APB1_GRP1_EnableClock
APB1ENR UART5EN LL_APB1_GRP1_EnableClock
APB1ENR USART2EN LL_APB1_GRP1_EnableClock
APB1ENR USART3EN LL_APB1_GRP1_EnableClock
APB1ENR USBEN LL_APB1_GRP1_EnableClock
APB1ENR WWDGEN LL_APB1_GRP1_EnableClock
Parameters:
Periphs This parameter can be a combination of the following values:
LL_APB1_GRP1_PERIPH_BKP
LL_APB1_GRP1_PERIPH_CAN1 (*)
LL_APB1_GRP1_PERIPH_CAN2 (*)
LL_APB1_GRP1_PERIPH_CEC (*)
LL_APB1_GRP1_PERIPH_DAC1 (*)
LL_APB1_GRP1_PERIPH_I2C1
LL_APB1_GRP1_PERIPH_I2C2 (*)
LL_APB1_GRP1_PERIPH_PWR
LL_APB1_GRP1_PERIPH_SPI2 (*)
LL_APB1_GRP1_PERIPH_SPI3 (*)
LL_APB1_GRP1_PERIPH_TIM12 (*)
LL_APB1_GRP1_PERIPH_TIM13 (*)
LL_APB1_GRP1_PERIPH_TIM14 (*)
LL_APB1_GRP1_PERIPH_TIM2
LL_APB1_GRP1_PERIPH_TIM3
LL_APB1_GRP1_PERIPH_TIM4 (*)
LL_APB1_GRP1_PERIPH_TIM5 (*)
LL_APB1_GRP1_PERIPH_TIM6 (*)
LL_APB1_GRP1_PERIPH_TIM7 (*)
LL_APB1_GRP1_PERIPH_UART4 (*)
LL_APB1_GRP1_PERIPH_UART5 (*)
LL_APB1_GRP1_PERIPH_USART2
LL_APB1_GRP1_PERIPH_USART3 (*)
LL_APB1_GRP1_PERIPH_USB (*)
LL_APB1_GRP1_PERIPH_WWDG
(*) value not defined in all devices.
Return values:
None
Definition at line 447 of file stm32f1xx_ll_bus.h.
__STATIC_INLINE void LL_APB1_GRP1_ForceReset (uint32_t Periphs)
Force APB1 peripherals reset.
Reference Manual to LL API cross reference:
APB1RSTR BKPRST LL_APB1_GRP1_ForceReset
APB1RSTR CAN1RST LL_APB1_GRP1_ForceReset
APB1RSTR CAN2RST LL_APB1_GRP1_ForceReset
APB1RSTR CECRST LL_APB1_GRP1_ForceReset
APB1RSTR DACRST LL_APB1_GRP1_ForceReset
APB1RSTR I2C1RST LL_APB1_GRP1_ForceReset
APB1RSTR I2C2RST LL_APB1_GRP1_ForceReset
APB1RSTR PWRRST LL_APB1_GRP1_ForceReset
APB1RSTR SPI2RST LL_APB1_GRP1_ForceReset
APB1RSTR SPI3RST LL_APB1_GRP1_ForceReset
APB1RSTR TIM12RST LL_APB1_GRP1_ForceReset
APB1RSTR TIM13RST LL_APB1_GRP1_ForceReset
APB1RSTR TIM14RST LL_APB1_GRP1_ForceReset
APB1RSTR TIM2RST LL_APB1_GRP1_ForceReset
APB1RSTR TIM3RST LL_APB1_GRP1_ForceReset
APB1RSTR TIM4RST LL_APB1_GRP1_ForceReset
APB1RSTR TIM5RST LL_APB1_GRP1_ForceReset
APB1RSTR TIM6RST LL_APB1_GRP1_ForceReset
APB1RSTR TIM7RST LL_APB1_GRP1_ForceReset
APB1RSTR UART4RST LL_APB1_GRP1_ForceReset
APB1RSTR UART5RST LL_APB1_GRP1_ForceReset
APB1RSTR USART2RST LL_APB1_GRP1_ForceReset
APB1RSTR USART3RST LL_APB1_GRP1_ForceReset
APB1RSTR USBRST LL_APB1_GRP1_ForceReset
APB1RSTR WWDGRST LL_APB1_GRP1_ForceReset
Parameters:
Periphs This parameter can be a combination of the following values:
LL_APB1_GRP1_PERIPH_ALL
LL_APB1_GRP1_PERIPH_BKP
LL_APB1_GRP1_PERIPH_CAN1 (*)
LL_APB1_GRP1_PERIPH_CAN2 (*)
LL_APB1_GRP1_PERIPH_CEC (*)
LL_APB1_GRP1_PERIPH_DAC1 (*)
LL_APB1_GRP1_PERIPH_I2C1
LL_APB1_GRP1_PERIPH_I2C2 (*)
LL_APB1_GRP1_PERIPH_PWR
LL_APB1_GRP1_PERIPH_SPI2 (*)
LL_APB1_GRP1_PERIPH_SPI3 (*)
LL_APB1_GRP1_PERIPH_TIM12 (*)
LL_APB1_GRP1_PERIPH_TIM13 (*)
LL_APB1_GRP1_PERIPH_TIM14 (*)
LL_APB1_GRP1_PERIPH_TIM2
LL_APB1_GRP1_PERIPH_TIM3
LL_APB1_GRP1_PERIPH_TIM4 (*)
LL_APB1_GRP1_PERIPH_TIM5 (*)
LL_APB1_GRP1_PERIPH_TIM6 (*)
LL_APB1_GRP1_PERIPH_TIM7 (*)
LL_APB1_GRP1_PERIPH_UART4 (*)
LL_APB1_GRP1_PERIPH_UART5 (*)
LL_APB1_GRP1_PERIPH_USART2
LL_APB1_GRP1_PERIPH_USART3 (*)
LL_APB1_GRP1_PERIPH_USB (*)
LL_APB1_GRP1_PERIPH_WWDG
(*) value not defined in all devices.
Return values:
None
Definition at line 638 of file stm32f1xx_ll_bus.h.
Referenced by LL_I2C_DeInit(), LL_PWR_DeInit(), LL_SPI_DeInit(), LL_TIM_DeInit(), and LL_USART_DeInit().
__STATIC_INLINE uint32_t LL_APB1_GRP1_IsEnabledClock (uint32_t Periphs)
Check if APB1 peripheral clock is enabled or not.
Reference Manual to LL API cross reference:
APB1ENR BKPEN LL_APB1_GRP1_IsEnabledClock
APB1ENR CAN1EN LL_APB1_GRP1_IsEnabledClock
APB1ENR CAN2EN LL_APB1_GRP1_IsEnabledClock
APB1ENR CECEN LL_APB1_GRP1_IsEnabledClock
APB1ENR DACEN LL_APB1_GRP1_IsEnabledClock
APB1ENR I2C1EN LL_APB1_GRP1_IsEnabledClock
APB1ENR I2C2EN LL_APB1_GRP1_IsEnabledClock
APB1ENR PWREN LL_APB1_GRP1_IsEnabledClock
APB1ENR SPI2EN LL_APB1_GRP1_IsEnabledClock
APB1ENR SPI3EN LL_APB1_GRP1_IsEnabledClock
APB1ENR TIM12EN LL_APB1_GRP1_IsEnabledClock
APB1ENR TIM13EN LL_APB1_GRP1_IsEnabledClock
APB1ENR TIM14EN LL_APB1_GRP1_IsEnabledClock
APB1ENR TIM2EN LL_APB1_GRP1_IsEnabledClock
APB1ENR TIM3EN LL_APB1_GRP1_IsEnabledClock
APB1ENR TIM4EN LL_APB1_GRP1_IsEnabledClock
APB1ENR TIM5EN LL_APB1_GRP1_IsEnabledClock
APB1ENR TIM6EN LL_APB1_GRP1_IsEnabledClock
APB1ENR TIM7EN LL_APB1_GRP1_IsEnabledClock
APB1ENR UART4EN LL_APB1_GRP1_IsEnabledClock
APB1ENR UART5EN LL_APB1_GRP1_IsEnabledClock
APB1ENR USART2EN LL_APB1_GRP1_IsEnabledClock
APB1ENR USART3EN LL_APB1_GRP1_IsEnabledClock
APB1ENR USBEN LL_APB1_GRP1_IsEnabledClock
APB1ENR WWDGEN LL_APB1_GRP1_IsEnabledClock
Parameters:
Periphs This parameter can be a combination of the following values:
LL_APB1_GRP1_PERIPH_BKP
LL_APB1_GRP1_PERIPH_CAN1 (*)
LL_APB1_GRP1_PERIPH_CAN2 (*)
LL_APB1_GRP1_PERIPH_CEC (*)
LL_APB1_GRP1_PERIPH_DAC1 (*)
LL_APB1_GRP1_PERIPH_I2C1
LL_APB1_GRP1_PERIPH_I2C2 (*)
LL_APB1_GRP1_PERIPH_PWR
LL_APB1_GRP1_PERIPH_SPI2 (*)
LL_APB1_GRP1_PERIPH_SPI3 (*)
LL_APB1_GRP1_PERIPH_TIM12 (*)
LL_APB1_GRP1_PERIPH_TIM13 (*)
LL_APB1_GRP1_PERIPH_TIM14 (*)
LL_APB1_GRP1_PERIPH_TIM2
LL_APB1_GRP1_PERIPH_TIM3
LL_APB1_GRP1_PERIPH_TIM4 (*)
LL_APB1_GRP1_PERIPH_TIM5 (*)
LL_APB1_GRP1_PERIPH_TIM6 (*)
LL_APB1_GRP1_PERIPH_TIM7 (*)
LL_APB1_GRP1_PERIPH_UART4 (*)
LL_APB1_GRP1_PERIPH_UART5 (*)
LL_APB1_GRP1_PERIPH_USART2
LL_APB1_GRP1_PERIPH_USART3 (*)
LL_APB1_GRP1_PERIPH_USB (*)
LL_APB1_GRP1_PERIPH_WWDG
(*) value not defined in all devices.
Return values:
State of Periphs (1 or 0).
Definition at line 513 of file stm32f1xx_ll_bus.h.
__STATIC_INLINE void LL_APB1_GRP1_ReleaseReset (uint32_t Periphs)
Release APB1 peripherals reset.
Reference Manual to LL API cross reference:
APB1RSTR BKPRST LL_APB1_GRP1_ReleaseReset
APB1RSTR CAN1RST LL_APB1_GRP1_ReleaseReset
APB1RSTR CAN2RST LL_APB1_GRP1_ReleaseReset
APB1RSTR CECRST LL_APB1_GRP1_ReleaseReset
APB1RSTR DACRST LL_APB1_GRP1_ReleaseReset
APB1RSTR I2C1RST LL_APB1_GRP1_ReleaseReset
APB1RSTR I2C2RST LL_APB1_GRP1_ReleaseReset
APB1RSTR PWRRST LL_APB1_GRP1_ReleaseReset
APB1RSTR SPI2RST LL_APB1_GRP1_ReleaseReset
APB1RSTR SPI3RST LL_APB1_GRP1_ReleaseReset
APB1RSTR TIM12RST LL_APB1_GRP1_ReleaseReset
APB1RSTR TIM13RST LL_APB1_GRP1_ReleaseReset
APB1RSTR TIM14RST LL_APB1_GRP1_ReleaseReset
APB1RSTR TIM2RST LL_APB1_GRP1_ReleaseReset
APB1RSTR TIM3RST LL_APB1_GRP1_ReleaseReset
APB1RSTR TIM4RST LL_APB1_GRP1_ReleaseReset
APB1RSTR TIM5RST LL_APB1_GRP1_ReleaseReset
APB1RSTR TIM6RST LL_APB1_GRP1_ReleaseReset
APB1RSTR TIM7RST LL_APB1_GRP1_ReleaseReset
APB1RSTR UART4RST LL_APB1_GRP1_ReleaseReset
APB1RSTR UART5RST LL_APB1_GRP1_ReleaseReset
APB1RSTR USART2RST LL_APB1_GRP1_ReleaseReset
APB1RSTR USART3RST LL_APB1_GRP1_ReleaseReset
APB1RSTR USBRST LL_APB1_GRP1_ReleaseReset
APB1RSTR WWDGRST LL_APB1_GRP1_ReleaseReset
Parameters:
Periphs This parameter can be a combination of the following values:
LL_APB1_GRP1_PERIPH_ALL
LL_APB1_GRP1_PERIPH_BKP
LL_APB1_GRP1_PERIPH_CAN1 (*)
LL_APB1_GRP1_PERIPH_CAN2 (*)
LL_APB1_GRP1_PERIPH_CEC (*)
LL_APB1_GRP1_PERIPH_DAC1 (*)
LL_APB1_GRP1_PERIPH_I2C1
LL_APB1_GRP1_PERIPH_I2C2 (*)
LL_APB1_GRP1_PERIPH_PWR
LL_APB1_GRP1_PERIPH_SPI2 (*)
LL_APB1_GRP1_PERIPH_SPI3 (*)
LL_APB1_GRP1_PERIPH_TIM12 (*)
LL_APB1_GRP1_PERIPH_TIM13 (*)
LL_APB1_GRP1_PERIPH_TIM14 (*)
LL_APB1_GRP1_PERIPH_TIM2
LL_APB1_GRP1_PERIPH_TIM3
LL_APB1_GRP1_PERIPH_TIM4 (*)
LL_APB1_GRP1_PERIPH_TIM5 (*)
LL_APB1_GRP1_PERIPH_TIM6 (*)
LL_APB1_GRP1_PERIPH_TIM7 (*)
LL_APB1_GRP1_PERIPH_UART4 (*)
LL_APB1_GRP1_PERIPH_UART5 (*)
LL_APB1_GRP1_PERIPH_USART2
LL_APB1_GRP1_PERIPH_USART3 (*)
LL_APB1_GRP1_PERIPH_USB (*)
LL_APB1_GRP1_PERIPH_WWDG
(*) value not defined in all devices.
Return values:
None
Definition at line 701 of file stm32f1xx_ll_bus.h.
Referenced by LL_I2C_DeInit(), LL_PWR_DeInit(), LL_SPI_DeInit(), LL_TIM_DeInit(), and LL_USART_DeInit().