STM32F103xB HAL User Manual: Initialization and Configuration functions
Initialization and Configuration functions
WWDG Exported Functions
Initialization and Configuration functions.
Functions
HAL_StatusTypeDef HAL_WWDG_Init (WWDG_HandleTypeDef *hwwdg)
Initialize the WWDG according to the specified.
__weak void HAL_WWDG_MspInit (WWDG_HandleTypeDef *hwwdg)
Initialize the WWDG MSP.
Detailed Description
Initialization and Configuration functions.
  ==============================================================================
          ##### Initialization and Configuration functions #####
  ==============================================================================
  [..]
    This section provides functions allowing to:
      (+) Initialize and start the WWDG according to the specified parameters
          in the WWDG_InitTypeDef of associated handle.
      (+) Initialize the WWDG MSP.
Function Documentation
HAL_StatusTypeDef HAL_WWDG_Init (WWDG_HandleTypeDef * hwwdg)
Initialize the WWDG according to the specified.
parameters in the WWDG_InitTypeDef of associated handle.
Parameters:
hwwdg pointer to a WWDG_HandleTypeDef structure that contains the configuration information for the specified WWDG module.
Return values:
HAL status
Definition at line 150 of file stm32f1xx_hal_wwdg.c.
References assert_param, WWDG_InitTypeDef::Counter, WWDG_InitTypeDef::EWIMode, HAL_WWDG_EarlyWakeupCallback(), HAL_WWDG_MspInit(), WWDG_HandleTypeDef::Init, WWDG_HandleTypeDef::Instance, IS_WWDG_COUNTER, IS_WWDG_EWI_MODE, IS_WWDG_PRESCALER, IS_WWDG_WINDOW, WWDG_InitTypeDef::Prescaler, and WWDG_InitTypeDef::Window.
void HAL_WWDG_MspInit (WWDG_HandleTypeDef * hwwdg)
Initialize the WWDG MSP.
Parameters:
hwwdg pointer to a WWDG_HandleTypeDef structure that contains the configuration information for the specified WWDG module.
Note:
When rewriting this function in user file, mechanism may be added to avoid multiple initialize when HAL_WWDG_Init function is called again to change parameters.
Return values:
None
Definition at line 203 of file stm32f1xx_hal_wwdg.c.
Referenced by HAL_WWDG_Init().