STM32F103xB HAL User Manual: Initialization and de-initialization functions
Initialization and de-initialization functions
I2C Exported Functions
Functions
uint32_t LL_I2C_DeInit (I2C_TypeDef *I2Cx)
De-initialize the I2C registers to their default reset values.
uint32_t LL_I2C_Init (I2C_TypeDef *I2Cx, LL_I2C_InitTypeDef *I2C_InitStruct)
Initialize the I2C registers according to the specified parameters in I2C_InitStruct.
void LL_I2C_StructInit (LL_I2C_InitTypeDef *I2C_InitStruct)
Set each LL_I2C_InitTypeDef field to default value.
Function Documentation
uint32_t LL_I2C_DeInit (I2C_TypeDef * I2Cx)
De-initialize the I2C registers to their default reset values.
Parameters:
I2Cx I2C Instance.
Return values:
An ErrorStatus enumeration value:
SUCCESS I2C registers are de-initialized
ERROR I2C registers are not de-initialized
Definition at line 88 of file stm32f1xx_ll_i2c.c.
References assert_param, LL_APB1_GRP1_ForceReset(), LL_APB1_GRP1_PERIPH_I2C1, LL_APB1_GRP1_PERIPH_I2C2, and LL_APB1_GRP1_ReleaseReset().
uint32_t LL_I2C_Init (I2C_TypeDef * I2Cx, LL_I2C_InitTypeDef * I2C_InitStruct)
Initialize the I2C registers according to the specified parameters in I2C_InitStruct.
Parameters:
I2Cx I2C Instance.
I2C_InitStruct pointer to a LL_I2C_InitTypeDef structure.
Return values:
An ErrorStatus enumeration value:
SUCCESS I2C registers are initialized
ERROR Not applicable
Definition at line 130 of file stm32f1xx_ll_i2c.c.
References assert_param, LL_I2C_InitTypeDef::ClockSpeed, LL_I2C_InitTypeDef::DutyCycle, IS_LL_I2C_CLOCK_SPEED, IS_LL_I2C_DUTY_CYCLE, IS_LL_I2C_OWN_ADDRESS1, IS_LL_I2C_OWN_ADDRSIZE, IS_LL_I2C_PERIPHERAL_MODE, IS_LL_I2C_TYPE_ACKNOWLEDGE, LL_I2C_AcknowledgeNextData(), LL_I2C_ConfigSpeed(), LL_I2C_Disable(), LL_I2C_Enable(), LL_I2C_SetMode(), LL_I2C_SetOwnAddress1(), LL_RCC_GetSystemClocksFreq(), LL_I2C_InitTypeDef::OwnAddress1, LL_I2C_InitTypeDef::OwnAddrSize, LL_RCC_ClocksTypeDef::PCLK1_Frequency, LL_I2C_InitTypeDef::PeripheralMode, and LL_I2C_InitTypeDef::TypeAcknowledge.
void LL_I2C_StructInit (LL_I2C_InitTypeDef * I2C_InitStruct)
Set each LL_I2C_InitTypeDef field to default value.
Parameters:
I2C_InitStruct Pointer to a LL_I2C_InitTypeDef structure.
Return values:
None
Definition at line 190 of file stm32f1xx_ll_i2c.c.
References LL_I2C_InitTypeDef::ClockSpeed, LL_I2C_InitTypeDef::DutyCycle, LL_I2C_DUTYCYCLE_2, LL_I2C_MODE_I2C, LL_I2C_NACK, LL_I2C_OWNADDRESS1_7BIT, LL_I2C_InitTypeDef::OwnAddress1, LL_I2C_InitTypeDef::OwnAddrSize, LL_I2C_InitTypeDef::PeripheralMode, and LL_I2C_InitTypeDef::TypeAcknowledge.