STM32F103xB HAL User Manual: Configuration
Configuration
DMA Exported Functions
Functions
__STATIC_INLINE void LL_DMA_EnableChannel (DMA_TypeDef *DMAx, uint32_t Channel)
Enable DMA channel.
__STATIC_INLINE void LL_DMA_DisableChannel (DMA_TypeDef *DMAx, uint32_t Channel)
Disable DMA channel.
__STATIC_INLINE uint32_t LL_DMA_IsEnabledChannel (DMA_TypeDef *DMAx, uint32_t Channel)
Check if DMA channel is enabled or disabled.
__STATIC_INLINE void LL_DMA_ConfigTransfer (DMA_TypeDef *DMAx, uint32_t Channel, uint32_t Configuration)
Configure all parameters link to DMA transfer.
__STATIC_INLINE void LL_DMA_SetDataTransferDirection (DMA_TypeDef *DMAx, uint32_t Channel, uint32_t Direction)
Set Data transfer direction (read from peripheral or from memory).
__STATIC_INLINE uint32_t LL_DMA_GetDataTransferDirection (DMA_TypeDef *DMAx, uint32_t Channel)
Get Data transfer direction (read from peripheral or from memory).
__STATIC_INLINE void LL_DMA_SetMode (DMA_TypeDef *DMAx, uint32_t Channel, uint32_t Mode)
Set DMA mode circular or normal.
__STATIC_INLINE uint32_t LL_DMA_GetMode (DMA_TypeDef *DMAx, uint32_t Channel)
Get DMA mode circular or normal.
__STATIC_INLINE void LL_DMA_SetPeriphIncMode (DMA_TypeDef *DMAx, uint32_t Channel, uint32_t PeriphOrM2MSrcIncMode)
Set Peripheral increment mode.
__STATIC_INLINE uint32_t LL_DMA_GetPeriphIncMode (DMA_TypeDef *DMAx, uint32_t Channel)
Get Peripheral increment mode.
__STATIC_INLINE void LL_DMA_SetMemoryIncMode (DMA_TypeDef *DMAx, uint32_t Channel, uint32_t MemoryOrM2MDstIncMode)
Set Memory increment mode.
__STATIC_INLINE uint32_t LL_DMA_GetMemoryIncMode (DMA_TypeDef *DMAx, uint32_t Channel)
Get Memory increment mode.
__STATIC_INLINE void LL_DMA_SetPeriphSize (DMA_TypeDef *DMAx, uint32_t Channel, uint32_t PeriphOrM2MSrcDataSize)
Set Peripheral size.
__STATIC_INLINE uint32_t LL_DMA_GetPeriphSize (DMA_TypeDef *DMAx, uint32_t Channel)
Get Peripheral size.
__STATIC_INLINE void LL_DMA_SetMemorySize (DMA_TypeDef *DMAx, uint32_t Channel, uint32_t MemoryOrM2MDstDataSize)
Set Memory size.
__STATIC_INLINE uint32_t LL_DMA_GetMemorySize (DMA_TypeDef *DMAx, uint32_t Channel)
Get Memory size.
__STATIC_INLINE void LL_DMA_SetChannelPriorityLevel (DMA_TypeDef *DMAx, uint32_t Channel, uint32_t Priority)
Set Channel priority level.
__STATIC_INLINE uint32_t LL_DMA_GetChannelPriorityLevel (DMA_TypeDef *DMAx, uint32_t Channel)
Get Channel priority level.
__STATIC_INLINE void LL_DMA_SetDataLength (DMA_TypeDef *DMAx, uint32_t Channel, uint32_t NbData)
Set Number of data to transfer.
__STATIC_INLINE uint32_t LL_DMA_GetDataLength (DMA_TypeDef *DMAx, uint32_t Channel)
Get Number of data to transfer.
__STATIC_INLINE void LL_DMA_ConfigAddresses (DMA_TypeDef *DMAx, uint32_t Channel, uint32_t SrcAddress, uint32_t DstAddress, uint32_t Direction)
Configure the Source and Destination addresses.
__STATIC_INLINE void LL_DMA_SetMemoryAddress (DMA_TypeDef *DMAx, uint32_t Channel, uint32_t MemoryAddress)
Set the Memory address.
__STATIC_INLINE void LL_DMA_SetPeriphAddress (DMA_TypeDef *DMAx, uint32_t Channel, uint32_t PeriphAddress)
Set the Peripheral address.
__STATIC_INLINE uint32_t LL_DMA_GetMemoryAddress (DMA_TypeDef *DMAx, uint32_t Channel)
Get Memory address.
__STATIC_INLINE uint32_t LL_DMA_GetPeriphAddress (DMA_TypeDef *DMAx, uint32_t Channel)
Get Peripheral address.
__STATIC_INLINE void LL_DMA_SetM2MSrcAddress (DMA_TypeDef *DMAx, uint32_t Channel, uint32_t MemoryAddress)
Set the Memory to Memory Source address.
__STATIC_INLINE void LL_DMA_SetM2MDstAddress (DMA_TypeDef *DMAx, uint32_t Channel, uint32_t MemoryAddress)
Set the Memory to Memory Destination address.
__STATIC_INLINE uint32_t LL_DMA_GetM2MSrcAddress (DMA_TypeDef *DMAx, uint32_t Channel)
Get the Memory to Memory Source address.
__STATIC_INLINE uint32_t LL_DMA_GetM2MDstAddress (DMA_TypeDef *DMAx, uint32_t Channel)
Get the Memory to Memory Destination address.
Function Documentation
__STATIC_INLINE void LL_DMA_ConfigAddresses (DMA_TypeDef * DMAx, uint32_t Channel, uint32_t SrcAddress, uint32_t DstAddress, uint32_t Direction)
Configure the Source and Destination addresses.
Note:
This API must not be called when the DMA channel is enabled.
Each IP using DMA provides an API to get directly the register adress (LL_PPP_DMA_GetRegAddr).
Reference Manual to LL API cross reference:
CPAR PA LL_DMA_ConfigAddresses
CMAR MA LL_DMA_ConfigAddresses
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
SrcAddress Between Min_Data = 0 and Max_Data = 0xFFFFFFFF
DstAddress Between Min_Data = 0 and Max_Data = 0xFFFFFFFF
Direction This parameter can be one of the following values:
LL_DMA_DIRECTION_PERIPH_TO_MEMORY
LL_DMA_DIRECTION_MEMORY_TO_PERIPH
LL_DMA_DIRECTION_MEMORY_TO_MEMORY
Return values:
None
Definition at line 931 of file stm32f1xx_ll_dma.h.
References LL_DMA_DIRECTION_MEMORY_TO_PERIPH.
__STATIC_INLINE void LL_DMA_ConfigTransfer (DMA_TypeDef * DMAx, uint32_t Channel, uint32_t Configuration)
Configure all parameters link to DMA transfer.
Reference Manual to LL API cross reference:
CCR DIR LL_DMA_ConfigTransfer
CCR MEM2MEM LL_DMA_ConfigTransfer
CCR CIRC LL_DMA_ConfigTransfer
CCR PINC LL_DMA_ConfigTransfer
CCR MINC LL_DMA_ConfigTransfer
CCR PSIZE LL_DMA_ConfigTransfer
CCR MSIZE LL_DMA_ConfigTransfer
CCR PL LL_DMA_ConfigTransfer
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
Configuration This parameter must be a combination of all the following values:
LL_DMA_DIRECTION_PERIPH_TO_MEMORY or LL_DMA_DIRECTION_MEMORY_TO_PERIPH or LL_DMA_DIRECTION_MEMORY_TO_MEMORY
LL_DMA_MODE_NORMAL or LL_DMA_MODE_CIRCULAR
LL_DMA_PERIPH_INCREMENT or LL_DMA_PERIPH_NOINCREMENT
LL_DMA_MEMORY_INCREMENT or LL_DMA_MEMORY_NOINCREMENT
LL_DMA_PDATAALIGN_BYTE or LL_DMA_PDATAALIGN_HALFWORD or LL_DMA_PDATAALIGN_WORD
LL_DMA_MDATAALIGN_BYTE or LL_DMA_MDATAALIGN_HALFWORD or LL_DMA_MDATAALIGN_WORD
LL_DMA_PRIORITY_LOW or LL_DMA_PRIORITY_MEDIUM or LL_DMA_PRIORITY_HIGH or LL_DMA_PRIORITY_VERYHIGH
Return values:
None
Definition at line 527 of file stm32f1xx_ll_dma.h.
Referenced by LL_DMA_Init().
__STATIC_INLINE void LL_DMA_DisableChannel (DMA_TypeDef * DMAx, uint32_t Channel)
Disable DMA channel.
Reference Manual to LL API cross reference:
CCR EN LL_DMA_DisableChannel
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
Return values:
None
Definition at line 473 of file stm32f1xx_ll_dma.h.
__STATIC_INLINE void LL_DMA_EnableChannel (DMA_TypeDef * DMAx, uint32_t Channel)
Enable DMA channel.
Reference Manual to LL API cross reference:
CCR EN LL_DMA_EnableChannel
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
Return values:
None
Definition at line 454 of file stm32f1xx_ll_dma.h.
__STATIC_INLINE uint32_t LL_DMA_GetChannelPriorityLevel (DMA_TypeDef * DMAx, uint32_t Channel)
Get Channel priority level.
Reference Manual to LL API cross reference:
CCR PL LL_DMA_GetChannelPriorityLevel
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
Return values:
Returned value can be one of the following values:
LL_DMA_PRIORITY_LOW
LL_DMA_PRIORITY_MEDIUM
LL_DMA_PRIORITY_HIGH
LL_DMA_PRIORITY_VERYHIGH
Definition at line 857 of file stm32f1xx_ll_dma.h.
__STATIC_INLINE uint32_t LL_DMA_GetDataLength (DMA_TypeDef * DMAx, uint32_t Channel)
Get Number of data to transfer.
Note:
Once the channel is enabled, the return value indicate the remaining bytes to be transmitted.
Reference Manual to LL API cross reference:
CNDTR NDT LL_DMA_GetDataLength
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
Return values:
Between Min_Data = 0 and Max_Data = 0xFFFFFFFF
Definition at line 902 of file stm32f1xx_ll_dma.h.
__STATIC_INLINE uint32_t LL_DMA_GetDataTransferDirection (DMA_TypeDef * DMAx, uint32_t Channel)
Get Data transfer direction (read from peripheral or from memory).
Reference Manual to LL API cross reference:
CCR DIR LL_DMA_GetDataTransferDirection
CCR MEM2MEM LL_DMA_GetDataTransferDirection
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
Return values:
Returned value can be one of the following values:
LL_DMA_DIRECTION_PERIPH_TO_MEMORY
LL_DMA_DIRECTION_MEMORY_TO_PERIPH
LL_DMA_DIRECTION_MEMORY_TO_MEMORY
Definition at line 577 of file stm32f1xx_ll_dma.h.
__STATIC_INLINE uint32_t LL_DMA_GetM2MDstAddress (DMA_TypeDef * DMAx, uint32_t Channel)
Get the Memory to Memory Destination address.
Note:
Interface used for direction LL_DMA_DIRECTION_MEMORY_TO_MEMORY only.
Reference Manual to LL API cross reference:
CMAR MA LL_DMA_GetM2MDstAddress
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
Return values:
Between Min_Data = 0 and Max_Data = 0xFFFFFFFF
Definition at line 1111 of file stm32f1xx_ll_dma.h.
__STATIC_INLINE uint32_t LL_DMA_GetM2MSrcAddress (DMA_TypeDef * DMAx, uint32_t Channel)
Get the Memory to Memory Source address.
Note:
Interface used for direction LL_DMA_DIRECTION_MEMORY_TO_MEMORY only.
Reference Manual to LL API cross reference:
CPAR PA LL_DMA_GetM2MSrcAddress
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
Return values:
Between Min_Data = 0 and Max_Data = 0xFFFFFFFF
Definition at line 1091 of file stm32f1xx_ll_dma.h.
__STATIC_INLINE uint32_t LL_DMA_GetMemoryAddress (DMA_TypeDef * DMAx, uint32_t Channel)
Get Memory address.
Note:
Interface used for direction LL_DMA_DIRECTION_PERIPH_TO_MEMORY or LL_DMA_DIRECTION_MEMORY_TO_PERIPH only.
Reference Manual to LL API cross reference:
CMAR MA LL_DMA_GetMemoryAddress
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
Return values:
Between Min_Data = 0 and Max_Data = 0xFFFFFFFF
Definition at line 1007 of file stm32f1xx_ll_dma.h.
__STATIC_INLINE uint32_t LL_DMA_GetMemoryIncMode (DMA_TypeDef * DMAx, uint32_t Channel)
Get Memory increment mode.
Reference Manual to LL API cross reference:
CCR MINC LL_DMA_GetMemoryIncMode
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
Return values:
Returned value can be one of the following values:
LL_DMA_MEMORY_INCREMENT
LL_DMA_MEMORY_NOINCREMENT
Definition at line 714 of file stm32f1xx_ll_dma.h.
__STATIC_INLINE uint32_t LL_DMA_GetMemorySize (DMA_TypeDef * DMAx, uint32_t Channel)
Get Memory size.
Reference Manual to LL API cross reference:
CCR MSIZE LL_DMA_GetMemorySize
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
Return values:
Returned value can be one of the following values:
LL_DMA_MDATAALIGN_BYTE
LL_DMA_MDATAALIGN_HALFWORD
LL_DMA_MDATAALIGN_WORD
Definition at line 808 of file stm32f1xx_ll_dma.h.
__STATIC_INLINE uint32_t LL_DMA_GetMode (DMA_TypeDef * DMAx, uint32_t Channel)
Get DMA mode circular or normal.
Reference Manual to LL API cross reference:
CCR CIRC LL_DMA_GetMode
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
Return values:
Returned value can be one of the following values:
LL_DMA_MODE_NORMAL
LL_DMA_MODE_CIRCULAR
Definition at line 624 of file stm32f1xx_ll_dma.h.
__STATIC_INLINE uint32_t LL_DMA_GetPeriphAddress (DMA_TypeDef * DMAx, uint32_t Channel)
Get Peripheral address.
Note:
Interface used for direction LL_DMA_DIRECTION_PERIPH_TO_MEMORY or LL_DMA_DIRECTION_MEMORY_TO_PERIPH only.
Reference Manual to LL API cross reference:
CPAR PA LL_DMA_GetPeriphAddress
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
Return values:
Between Min_Data = 0 and Max_Data = 0xFFFFFFFF
Definition at line 1027 of file stm32f1xx_ll_dma.h.
__STATIC_INLINE uint32_t LL_DMA_GetPeriphIncMode (DMA_TypeDef * DMAx, uint32_t Channel)
Get Peripheral increment mode.
Reference Manual to LL API cross reference:
CCR PINC LL_DMA_GetPeriphIncMode
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
Return values:
Returned value can be one of the following values:
LL_DMA_PERIPH_INCREMENT
LL_DMA_PERIPH_NOINCREMENT
Definition at line 669 of file stm32f1xx_ll_dma.h.
__STATIC_INLINE uint32_t LL_DMA_GetPeriphSize (DMA_TypeDef * DMAx, uint32_t Channel)
Get Peripheral size.
Reference Manual to LL API cross reference:
CCR PSIZE LL_DMA_GetPeriphSize
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
Return values:
Returned value can be one of the following values:
LL_DMA_PDATAALIGN_BYTE
LL_DMA_PDATAALIGN_HALFWORD
LL_DMA_PDATAALIGN_WORD
Definition at line 761 of file stm32f1xx_ll_dma.h.
__STATIC_INLINE uint32_t LL_DMA_IsEnabledChannel (DMA_TypeDef * DMAx, uint32_t Channel)
Check if DMA channel is enabled or disabled.
Reference Manual to LL API cross reference:
CCR EN LL_DMA_IsEnabledChannel
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
Return values:
State of bit (1 or 0).
Definition at line 492 of file stm32f1xx_ll_dma.h.
__STATIC_INLINE void LL_DMA_SetChannelPriorityLevel (DMA_TypeDef * DMAx, uint32_t Channel, uint32_t Priority)
Set Channel priority level.
Reference Manual to LL API cross reference:
CCR PL LL_DMA_SetChannelPriorityLevel
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
Priority This parameter can be one of the following values:
LL_DMA_PRIORITY_LOW
LL_DMA_PRIORITY_MEDIUM
LL_DMA_PRIORITY_HIGH
LL_DMA_PRIORITY_VERYHIGH
Return values:
None
Definition at line 833 of file stm32f1xx_ll_dma.h.
__STATIC_INLINE void LL_DMA_SetDataLength (DMA_TypeDef * DMAx, uint32_t Channel, uint32_t NbData)
Set Number of data to transfer.
Note:
This action has no effect if channel is enabled.
Reference Manual to LL API cross reference:
CNDTR NDT LL_DMA_SetDataLength
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
NbData Between Min_Data = 0 and Max_Data = 0x0000FFFF
Return values:
None
Definition at line 880 of file stm32f1xx_ll_dma.h.
Referenced by LL_DMA_Init().
__STATIC_INLINE void LL_DMA_SetDataTransferDirection (DMA_TypeDef * DMAx, uint32_t Channel, uint32_t Direction)
Set Data transfer direction (read from peripheral or from memory).
Reference Manual to LL API cross reference:
CCR DIR LL_DMA_SetDataTransferDirection
CCR MEM2MEM LL_DMA_SetDataTransferDirection
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
Direction This parameter can be one of the following values:
LL_DMA_DIRECTION_PERIPH_TO_MEMORY
LL_DMA_DIRECTION_MEMORY_TO_PERIPH
LL_DMA_DIRECTION_MEMORY_TO_MEMORY
Return values:
None
Definition at line 553 of file stm32f1xx_ll_dma.h.
__STATIC_INLINE void LL_DMA_SetM2MDstAddress (DMA_TypeDef * DMAx, uint32_t Channel, uint32_t MemoryAddress)
Set the Memory to Memory Destination address.
Note:
Interface used for direction LL_DMA_DIRECTION_MEMORY_TO_MEMORY only.
This API must not be called when the DMA channel is enabled.
Reference Manual to LL API cross reference:
CMAR MA LL_DMA_SetM2MDstAddress
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
MemoryAddress Between Min_Data = 0 and Max_Data = 0xFFFFFFFF
Return values:
None
Definition at line 1071 of file stm32f1xx_ll_dma.h.
__STATIC_INLINE void LL_DMA_SetM2MSrcAddress (DMA_TypeDef * DMAx, uint32_t Channel, uint32_t MemoryAddress)
Set the Memory to Memory Source address.
Note:
Interface used for direction LL_DMA_DIRECTION_MEMORY_TO_MEMORY only.
This API must not be called when the DMA channel is enabled.
Reference Manual to LL API cross reference:
CPAR PA LL_DMA_SetM2MSrcAddress
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
MemoryAddress Between Min_Data = 0 and Max_Data = 0xFFFFFFFF
Return values:
None
Definition at line 1049 of file stm32f1xx_ll_dma.h.
__STATIC_INLINE void LL_DMA_SetMemoryAddress (DMA_TypeDef * DMAx, uint32_t Channel, uint32_t MemoryAddress)
Set the Memory address.
Note:
Interface used for direction LL_DMA_DIRECTION_PERIPH_TO_MEMORY or LL_DMA_DIRECTION_MEMORY_TO_PERIPH only.
This API must not be called when the DMA channel is enabled.
Reference Manual to LL API cross reference:
CMAR MA LL_DMA_SetMemoryAddress
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
MemoryAddress Between Min_Data = 0 and Max_Data = 0xFFFFFFFF
Return values:
None
Definition at line 965 of file stm32f1xx_ll_dma.h.
Referenced by LL_DMA_Init().
__STATIC_INLINE void LL_DMA_SetMemoryIncMode (DMA_TypeDef * DMAx, uint32_t Channel, uint32_t MemoryOrM2MDstIncMode)
Set Memory increment mode.
Reference Manual to LL API cross reference:
CCR MINC LL_DMA_SetMemoryIncMode
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
MemoryOrM2MDstIncMode This parameter can be one of the following values:
LL_DMA_MEMORY_INCREMENT
LL_DMA_MEMORY_NOINCREMENT
Return values:
None
Definition at line 692 of file stm32f1xx_ll_dma.h.
__STATIC_INLINE void LL_DMA_SetMemorySize (DMA_TypeDef * DMAx, uint32_t Channel, uint32_t MemoryOrM2MDstDataSize)
Set Memory size.
Reference Manual to LL API cross reference:
CCR MSIZE LL_DMA_SetMemorySize
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
MemoryOrM2MDstDataSize This parameter can be one of the following values:
LL_DMA_MDATAALIGN_BYTE
LL_DMA_MDATAALIGN_HALFWORD
LL_DMA_MDATAALIGN_WORD
Return values:
None
Definition at line 785 of file stm32f1xx_ll_dma.h.
__STATIC_INLINE void LL_DMA_SetMode (DMA_TypeDef * DMAx, uint32_t Channel, uint32_t Mode)
Set DMA mode circular or normal.
Note:
The circular buffer mode cannot be used if the memory-to-memory data transfer is configured on the selected Channel.
Reference Manual to LL API cross reference:
CCR CIRC LL_DMA_SetMode
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
Mode This parameter can be one of the following values:
LL_DMA_MODE_NORMAL
LL_DMA_MODE_CIRCULAR
Return values:
None
Definition at line 602 of file stm32f1xx_ll_dma.h.
__STATIC_INLINE void LL_DMA_SetPeriphAddress (DMA_TypeDef * DMAx, uint32_t Channel, uint32_t PeriphAddress)
Set the Peripheral address.
Note:
Interface used for direction LL_DMA_DIRECTION_PERIPH_TO_MEMORY or LL_DMA_DIRECTION_MEMORY_TO_PERIPH only.
This API must not be called when the DMA channel is enabled.
Reference Manual to LL API cross reference:
CPAR PA LL_DMA_SetPeriphAddress
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
PeriphAddress Between Min_Data = 0 and Max_Data = 0xFFFFFFFF
Return values:
None
Definition at line 987 of file stm32f1xx_ll_dma.h.
Referenced by LL_DMA_Init().
__STATIC_INLINE void LL_DMA_SetPeriphIncMode (DMA_TypeDef * DMAx, uint32_t Channel, uint32_t PeriphOrM2MSrcIncMode)
Set Peripheral increment mode.
Reference Manual to LL API cross reference:
CCR PINC LL_DMA_SetPeriphIncMode
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
PeriphOrM2MSrcIncMode This parameter can be one of the following values:
LL_DMA_PERIPH_INCREMENT
LL_DMA_PERIPH_NOINCREMENT
Return values:
None
Definition at line 647 of file stm32f1xx_ll_dma.h.
__STATIC_INLINE void LL_DMA_SetPeriphSize (DMA_TypeDef * DMAx, uint32_t Channel, uint32_t PeriphOrM2MSrcDataSize)
Set Peripheral size.
Reference Manual to LL API cross reference:
CCR PSIZE LL_DMA_SetPeriphSize
Parameters:
DMAx DMAx Instance
Channel This parameter can be one of the following values:
LL_DMA_CHANNEL_1
LL_DMA_CHANNEL_2
LL_DMA_CHANNEL_3
LL_DMA_CHANNEL_4
LL_DMA_CHANNEL_5
LL_DMA_CHANNEL_6
LL_DMA_CHANNEL_7
PeriphOrM2MSrcDataSize This parameter can be one of the following values:
LL_DMA_PDATAALIGN_BYTE
LL_DMA_PDATAALIGN_HALFWORD
LL_DMA_PDATAALIGN_WORD
Return values:
None
Definition at line 738 of file stm32f1xx_ll_dma.h.