STM32F103xB HAL User Manual: UTILS Private functions
UTILS Private functions
UTILS
Functions
static uint32_t UTILS_GetPLLOutputFrequency (uint32_t PLL_InputFrequency, LL_UTILS_PLLInitTypeDef *UTILS_PLLInitStruct)
Function to check that PLL can be modified.
static ErrorStatus UTILS_SetFlashLatency (uint32_t Frequency)
Update number of Flash wait states in line with new frequency and current voltage range.
static ErrorStatus UTILS_EnablePLLAndSwitchSystem (uint32_t SYSCLK_Frequency, LL_UTILS_ClkInitTypeDef *UTILS_ClkInitStruct)
Function to enable PLL and switch system clock to PLL.
static ErrorStatus UTILS_PLL_IsBusy (void)
Function to check that PLL can be modified.
Function Documentation
static ErrorStatus UTILS_EnablePLLAndSwitchSystem (uint32_t SYSCLK_Frequency, LL_UTILS_ClkInitTypeDef * UTILS_ClkInitStruct) [static]
Function to enable PLL and switch system clock to PLL.
Parameters:
SYSCLK_Frequency SYSCLK frequency
UTILS_ClkInitStruct pointer to a LL_UTILS_ClkInitTypeDef structure that contains the configuration information for the BUS prescalers.
Return values:
An ErrorStatus enumeration value:
SUCCESS: No problem to switch system to PLL
ERROR: Problem to switch system to PLL
Definition at line 519 of file stm32f1xx_ll_utils.c.
References __LL_RCC_CALC_HCLK_FREQ, LL_UTILS_ClkInitTypeDef::AHBCLKDivider, LL_UTILS_ClkInitTypeDef::APB1CLKDivider, LL_UTILS_ClkInitTypeDef::APB2CLKDivider, assert_param, IS_LL_UTILS_APB1_DIV, IS_LL_UTILS_APB2_DIV, IS_LL_UTILS_SYSCLK_DIV, LL_RCC_GetSysClkSource(), LL_RCC_PLL_Enable(), LL_RCC_PLL_IsReady(), LL_RCC_SetAHBPrescaler(), LL_RCC_SetAPB1Prescaler(), LL_RCC_SetAPB2Prescaler(), LL_RCC_SetSysClkSource(), LL_RCC_SYS_CLKSOURCE_PLL, LL_RCC_SYS_CLKSOURCE_STATUS_PLL, LL_SetSystemCoreClock(), and UTILS_SetFlashLatency().
Referenced by LL_PLL_ConfigSystemClock_HSE(), and LL_PLL_ConfigSystemClock_HSI().
static uint32_t UTILS_GetPLLOutputFrequency (uint32_t PLL_InputFrequency, LL_UTILS_PLLInitTypeDef * UTILS_PLLInitStruct) [static]
Function to check that PLL can be modified.
Parameters:
PLL_InputFrequency PLL input frequency (in Hz)
UTILS_PLLInitStruct pointer to a LL_UTILS_PLLInitTypeDef structure that contains the configuration information for the PLL.
Return values:
PLL output frequency (in Hz)
Definition at line 453 of file stm32f1xx_ll_utils.c.
References __LL_RCC_CALC_PLLCLK_FREQ, assert_param, IS_LL_UTILS_PLL_FREQUENCY, IS_LL_UTILS_PLLMUL_VALUE, LL_UTILS_PLLInitTypeDef::PLLMul, and LL_UTILS_PLLInitTypeDef::Prediv.
Referenced by LL_PLL_ConfigSystemClock_HSE(), and LL_PLL_ConfigSystemClock_HSI().
static ErrorStatus UTILS_PLL_IsBusy (void) [static]
Function to check that PLL can be modified.
Return values:
An ErrorStatus enumeration value:
SUCCESS: PLL modification can be done
ERROR: PLL is busy
Definition at line 479 of file stm32f1xx_ll_utils.c.
References LL_RCC_PLL_IsReady().
Referenced by LL_PLL_ConfigSystemClock_HSE(), and LL_PLL_ConfigSystemClock_HSI().
static ErrorStatus UTILS_SetFlashLatency (uint32_t Frequency) [static]
Update number of Flash wait states in line with new frequency and current voltage range.
Parameters:
Frequency SYSCLK frequency
Return values:
An ErrorStatus enumeration value:
SUCCESS: Latency has been modified
ERROR: Latency cannot be modified
Definition at line 405 of file stm32f1xx_ll_utils.c.
References LL_FLASH_GetLatency(), LL_FLASH_LATENCY_0, LL_FLASH_LATENCY_1, LL_FLASH_LATENCY_2, LL_FLASH_SetLatency(), UTILS_LATENCY1_FREQ, and UTILS_LATENCY2_FREQ.
Referenced by UTILS_EnablePLLAndSwitchSystem().