STM32F103xB HAL User Manual: Peripheral Control functions
Peripheral Control functions
RTC Exported Functions
Peripheral Control functions.
Functions
HAL_StatusTypeDef HAL_RTC_WaitForSynchro (RTC_HandleTypeDef *hrtc)
Waits until the RTC registers (RTC_CNT, RTC_ALR and RTC_PRL) are synchronized with RTC APB clock.
Detailed Description
Peripheral Control functions.
 ===============================================================================
                     ##### Peripheral Control functions #####
 ===============================================================================
    [..]
    This subsection provides functions allowing to
      (+) Wait for RTC Time and Date Synchronization
Function Documentation
HAL_StatusTypeDef HAL_RTC_WaitForSynchro (RTC_HandleTypeDef * hrtc)
Waits until the RTC registers (RTC_CNT, RTC_ALR and RTC_PRL) are synchronized with RTC APB clock.
Note:
This function must be called before any read operation after an APB reset or an APB clock stop.
Parameters:
hrtc pointer to a RTC_HandleTypeDef structure that contains the configuration information for RTC.
Return values:
HAL status
Definition at line 1537 of file stm32f1xx_hal_rtc.c.
References HAL_GetTick(), RTC_HandleTypeDef::Instance, RTC_FLAG_RSF, and RTC_TIMEOUT_VALUE.
Referenced by HAL_RTC_DeInit(), and HAL_RTC_Init().