STM32F103xB HAL User Manual: IO operation functions
IO operation functions
UART Exported Functions
UART Transmit and Receive functions.
Functions
HAL_StatusTypeDef HAL_UART_Transmit (UART_HandleTypeDef *huart, uint8_t *pData, uint16_t Size, uint32_t Timeout)
Sends an amount of data in blocking mode.
HAL_StatusTypeDef HAL_UART_Receive (UART_HandleTypeDef *huart, uint8_t *pData, uint16_t Size, uint32_t Timeout)
Receives an amount of data in blocking mode.
HAL_StatusTypeDef HAL_UART_Transmit_IT (UART_HandleTypeDef *huart, uint8_t *pData, uint16_t Size)
Sends an amount of data in non blocking mode.
HAL_StatusTypeDef HAL_UART_Receive_IT (UART_HandleTypeDef *huart, uint8_t *pData, uint16_t Size)
Receives an amount of data in non blocking mode.
HAL_StatusTypeDef HAL_UART_Transmit_DMA (UART_HandleTypeDef *huart, uint8_t *pData, uint16_t Size)
Sends an amount of data in non blocking mode.
HAL_StatusTypeDef HAL_UART_Receive_DMA (UART_HandleTypeDef *huart, uint8_t *pData, uint16_t Size)
Receives an amount of data in non blocking mode.
HAL_StatusTypeDef HAL_UART_DMAPause (UART_HandleTypeDef *huart)
Pauses the DMA Transfer.
HAL_StatusTypeDef HAL_UART_DMAResume (UART_HandleTypeDef *huart)
Resumes the DMA Transfer.
HAL_StatusTypeDef HAL_UART_DMAStop (UART_HandleTypeDef *huart)
Stops the DMA Transfer.
HAL_StatusTypeDef HAL_UART_Abort (UART_HandleTypeDef *huart)
Abort ongoing transfers (blocking mode).
HAL_StatusTypeDef HAL_UART_AbortTransmit (UART_HandleTypeDef *huart)
Abort ongoing Transmit transfer (blocking mode).
HAL_StatusTypeDef HAL_UART_AbortReceive (UART_HandleTypeDef *huart)
Abort ongoing Receive transfer (blocking mode).
HAL_StatusTypeDef HAL_UART_Abort_IT (UART_HandleTypeDef *huart)
Abort ongoing transfers (Interrupt mode).
HAL_StatusTypeDef HAL_UART_AbortTransmit_IT (UART_HandleTypeDef *huart)
Abort ongoing Transmit transfer (Interrupt mode).
HAL_StatusTypeDef HAL_UART_AbortReceive_IT (UART_HandleTypeDef *huart)
Abort ongoing Receive transfer (Interrupt mode).
void HAL_UART_IRQHandler (UART_HandleTypeDef *huart)
This function handles UART interrupt request.
__weak void HAL_UART_TxCpltCallback (UART_HandleTypeDef *huart)
Tx Transfer completed callbacks.
__weak void HAL_UART_TxHalfCpltCallback (UART_HandleTypeDef *huart)
Tx Half Transfer completed callbacks.
__weak void HAL_UART_RxCpltCallback (UART_HandleTypeDef *huart)
Rx Transfer completed callbacks.
__weak void HAL_UART_RxHalfCpltCallback (UART_HandleTypeDef *huart)
Rx Half Transfer completed callbacks.
__weak void HAL_UART_ErrorCallback (UART_HandleTypeDef *huart)
UART error callbacks.
__weak void HAL_UART_AbortCpltCallback (UART_HandleTypeDef *huart)
UART Abort Complete callback.
__weak void HAL_UART_AbortTransmitCpltCallback (UART_HandleTypeDef *huart)
UART Abort Complete callback.
__weak void HAL_UART_AbortReceiveCpltCallback (UART_HandleTypeDef *huart)
UART Abort Receive Complete callback.
Detailed Description
UART Transmit and Receive functions.
 ===============================================================================
                      ##### IO operation functions #####
 ===============================================================================
    This subsection provides a set of functions allowing to manage the UART asynchronous
    and Half duplex data transfers.
    (#) There are two modes of transfer:
       (+) Blocking mode: The communication is performed in polling mode.
           The HAL status of all data processing is returned by the same function
           after finishing transfer.
       (+) Non-Blocking mode: The communication is performed using Interrupts
           or DMA, these API's return the HAL status.
           The end of the data processing will be indicated through the
           dedicated UART IRQ when using Interrupt mode or the DMA IRQ when
           using DMA mode.
           The HAL_UART_TxCpltCallback(), HAL_UART_RxCpltCallback() user callbacks
           will be executed respectively at the end of the transmit or receive process
           The HAL_UART_ErrorCallback()user callback will be executed when a communication error is detected.
    (#) Blocking mode API's are :
        (+) HAL_UART_Transmit()
        (+) HAL_UART_Receive()
    (#) Non-Blocking mode API's with Interrupt are :
        (+) HAL_UART_Transmit_IT()
        (+) HAL_UART_Receive_IT()
        (+) HAL_UART_IRQHandler()
    (#) Non-Blocking mode API's with DMA are :
        (+) HAL_UART_Transmit_DMA()
        (+) HAL_UART_Receive_DMA()
        (+) HAL_UART_DMAPause()
        (+) HAL_UART_DMAResume()
        (+) HAL_UART_DMAStop()
    (#) A set of Transfer Complete Callbacks are provided in Non_Blocking mode:
        (+) HAL_UART_TxHalfCpltCallback()
        (+) HAL_UART_TxCpltCallback()
        (+) HAL_UART_RxHalfCpltCallback()
        (+) HAL_UART_RxCpltCallback()
        (+) HAL_UART_ErrorCallback()
    (#) Non-Blocking mode transfers could be aborted using Abort API's :
        (+) HAL_UART_Abort()
        (+) HAL_UART_AbortTransmit()
        (+) HAL_UART_AbortReceive()
        (+) HAL_UART_Abort_IT()
        (+) HAL_UART_AbortTransmit_IT()
        (+) HAL_UART_AbortReceive_IT()
    (#) For Abort services based on interrupts (HAL_UART_Abortxxx_IT), a set of Abort Complete Callbacks are provided:
        (+) HAL_UART_AbortCpltCallback()
        (+) HAL_UART_AbortTransmitCpltCallback()
        (+) HAL_UART_AbortReceiveCpltCallback()
    (#) In Non-Blocking mode transfers, possible errors are split into 2 categories.
        Errors are handled as follows :
       (+) Error is considered as Recoverable and non blocking : Transfer could go till end, but error severity is
           to be evaluated by user : this concerns Frame Error, Parity Error or Noise Error in Interrupt mode reception .
           Received character is then retrieved and stored in Rx buffer, Error code is set to allow user to identify error type,
           and HAL_UART_ErrorCallback() user callback is executed. Transfer is kept ongoing on UART side.
           If user wants to abort it, Abort services should be called by user.
       (+) Error is considered as Blocking : Transfer could not be completed properly and is aborted.
           This concerns Overrun Error In Interrupt mode reception and all errors in DMA mode.
           Error code is set to allow user to identify error type, and HAL_UART_ErrorCallback() user callback is executed.
    -@- In the Half duplex communication, it is forbidden to run the transmit
        and receive process in parallel, the UART state HAL_UART_STATE_BUSY_TX_RX can't be useful.
Function Documentation
HAL_StatusTypeDef HAL_UART_Abort (UART_HandleTypeDef * huart)
Abort ongoing transfers (blocking mode).
Parameters:
huart UART handle.
Note:
This procedure could be used for aborting any ongoing transfer started in Interrupt or DMA mode. This procedure performs following operations :
Disable UART Interrupts (Tx and Rx)
Disable the DMA transfer in the peripheral register (if enabled)
Abort DMA transfer by calling HAL_DMA_Abort (in case of transfer in DMA mode)
Set handle State to READY
This procedure is executed in blocking mode : when exiting function, Abort is considered as completed.
Return values:
HAL status
Definition at line 1541 of file stm32f1xx_hal_uart.c.
References __UART_HandleTypeDef::ErrorCode, __UART_HandleTypeDef::gState, HAL_DMA_Abort(), HAL_DMA_ERROR_TIMEOUT, HAL_DMA_GetError(), HAL_UART_ERROR_DMA, HAL_UART_ERROR_NONE, HAL_UART_STATE_READY, __UART_HandleTypeDef::hdmarx, __UART_HandleTypeDef::hdmatx, __UART_HandleTypeDef::Instance, __UART_HandleTypeDef::RxState, __UART_HandleTypeDef::RxXferCount, __UART_HandleTypeDef::TxXferCount, and __DMA_HandleTypeDef::XferAbortCallback.
HAL_StatusTypeDef HAL_UART_Abort_IT (UART_HandleTypeDef * huart)
Abort ongoing transfers (Interrupt mode).
Parameters:
huart UART handle.
Note:
This procedure could be used for aborting any ongoing transfer started in Interrupt or DMA mode. This procedure performs following operations :
Disable UART Interrupts (Tx and Rx)
Disable the DMA transfer in the peripheral register (if enabled)
Abort DMA transfer by calling HAL_DMA_Abort_IT (in case of transfer in DMA mode)
Set handle State to READY
At abort completion, call user abort complete callback
This procedure is executed in Interrupt mode, meaning that abort procedure could be considered as completed only when user abort complete callback is executed (not when exiting function).
Return values:
HAL status
Definition at line 1728 of file stm32f1xx_hal_uart.c.
References __UART_HandleTypeDef::ErrorCode, __UART_HandleTypeDef::gState, HAL_DMA_Abort_IT(), HAL_UART_AbortCpltCallback(), HAL_UART_ERROR_NONE, HAL_UART_STATE_READY, __UART_HandleTypeDef::hdmarx, __UART_HandleTypeDef::hdmatx, __UART_HandleTypeDef::Instance, __UART_HandleTypeDef::RxState, __UART_HandleTypeDef::RxXferCount, __UART_HandleTypeDef::TxXferCount, UART_DMARxAbortCallback(), UART_DMATxAbortCallback(), and __DMA_HandleTypeDef::XferAbortCallback.
void HAL_UART_AbortCpltCallback (UART_HandleTypeDef * huart)
UART Abort Complete callback.
Parameters:
huart UART handle.
Return values:
None
Definition at line 2223 of file stm32f1xx_hal_uart.c.
Referenced by HAL_UART_Abort_IT(), UART_DMARxAbortCallback(), and UART_DMATxAbortCallback().
HAL_StatusTypeDef HAL_UART_AbortReceive (UART_HandleTypeDef * huart)
Abort ongoing Receive transfer (blocking mode).
Parameters:
huart UART handle.
Note:
This procedure could be used for aborting any ongoing Rx transfer started in Interrupt or DMA mode. This procedure performs following operations :
Disable UART Interrupts (Rx)
Disable the DMA transfer in the peripheral register (if enabled)
Abort DMA transfer by calling HAL_DMA_Abort (in case of transfer in DMA mode)
Set handle State to READY
This procedure is executed in blocking mode : when exiting function, Abort is considered as completed.
Return values:
HAL status
Definition at line 1674 of file stm32f1xx_hal_uart.c.
References __UART_HandleTypeDef::ErrorCode, HAL_DMA_Abort(), HAL_DMA_ERROR_TIMEOUT, HAL_DMA_GetError(), HAL_UART_ERROR_DMA, HAL_UART_STATE_READY, __UART_HandleTypeDef::hdmarx, __UART_HandleTypeDef::Instance, __UART_HandleTypeDef::RxState, __UART_HandleTypeDef::RxXferCount, and __DMA_HandleTypeDef::XferAbortCallback.
HAL_StatusTypeDef HAL_UART_AbortReceive_IT (UART_HandleTypeDef * huart)
Abort ongoing Receive transfer (Interrupt mode).
Parameters:
huart UART handle.
Note:
This procedure could be used for aborting any ongoing Rx transfer started in Interrupt or DMA mode. This procedure performs following operations :
Disable UART Interrupts (Rx)
Disable the DMA transfer in the peripheral register (if enabled)
Abort DMA transfer by calling HAL_DMA_Abort_IT (in case of transfer in DMA mode)
Set handle State to READY
At abort completion, call user abort complete callback
This procedure is executed in Interrupt mode, meaning that abort procedure could be considered as completed only when user abort complete callback is executed (not when exiting function).
Return values:
HAL status
Definition at line 1933 of file stm32f1xx_hal_uart.c.
References HAL_DMA_Abort_IT(), HAL_UART_AbortReceiveCpltCallback(), HAL_UART_STATE_READY, __UART_HandleTypeDef::hdmarx, __UART_HandleTypeDef::Instance, __UART_HandleTypeDef::RxState, __UART_HandleTypeDef::RxXferCount, UART_DMARxOnlyAbortCallback(), and __DMA_HandleTypeDef::XferAbortCallback.
void HAL_UART_AbortReceiveCpltCallback (UART_HandleTypeDef * huart)
UART Abort Receive Complete callback.
Parameters:
huart UART handle.
Return values:
None
Definition at line 2253 of file stm32f1xx_hal_uart.c.
Referenced by HAL_UART_AbortReceive_IT(), and UART_DMARxOnlyAbortCallback().
HAL_StatusTypeDef HAL_UART_AbortTransmit (UART_HandleTypeDef * huart)
Abort ongoing Transmit transfer (blocking mode).
Parameters:
huart UART handle.
Note:
This procedure could be used for aborting any ongoing Tx transfer started in Interrupt or DMA mode. This procedure performs following operations :
Disable UART Interrupts (Tx)
Disable the DMA transfer in the peripheral register (if enabled)
Abort DMA transfer by calling HAL_DMA_Abort (in case of transfer in DMA mode)
Set handle State to READY
This procedure is executed in blocking mode : when exiting function, Abort is considered as completed.
Return values:
HAL status
Definition at line 1623 of file stm32f1xx_hal_uart.c.
References __UART_HandleTypeDef::ErrorCode, __UART_HandleTypeDef::gState, HAL_DMA_Abort(), HAL_DMA_ERROR_TIMEOUT, HAL_DMA_GetError(), HAL_UART_ERROR_DMA, HAL_UART_STATE_READY, __UART_HandleTypeDef::hdmatx, __UART_HandleTypeDef::Instance, __UART_HandleTypeDef::TxXferCount, and __DMA_HandleTypeDef::XferAbortCallback.
HAL_StatusTypeDef HAL_UART_AbortTransmit_IT (UART_HandleTypeDef * huart)
Abort ongoing Transmit transfer (Interrupt mode).
Parameters:
huart UART handle.
Note:
This procedure could be used for aborting any ongoing Tx transfer started in Interrupt or DMA mode. This procedure performs following operations :
Disable UART Interrupts (Tx)
Disable the DMA transfer in the peripheral register (if enabled)
Abort DMA transfer by calling HAL_DMA_Abort_IT (in case of transfer in DMA mode)
Set handle State to READY
At abort completion, call user abort complete callback
This procedure is executed in Interrupt mode, meaning that abort procedure could be considered as completed only when user abort complete callback is executed (not when exiting function).
Return values:
HAL status
Definition at line 1856 of file stm32f1xx_hal_uart.c.
References __UART_HandleTypeDef::gState, HAL_DMA_Abort_IT(), HAL_UART_AbortTransmitCpltCallback(), HAL_UART_STATE_READY, __UART_HandleTypeDef::hdmatx, __UART_HandleTypeDef::Instance, __UART_HandleTypeDef::TxXferCount, UART_DMATxOnlyAbortCallback(), and __DMA_HandleTypeDef::XferAbortCallback.
void HAL_UART_AbortTransmitCpltCallback (UART_HandleTypeDef * huart)
UART Abort Complete callback.
Parameters:
huart UART handle.
Return values:
None
Definition at line 2238 of file stm32f1xx_hal_uart.c.
Referenced by HAL_UART_AbortTransmit_IT(), and UART_DMATxOnlyAbortCallback().
HAL_StatusTypeDef HAL_UART_DMAPause (UART_HandleTypeDef * huart)
Pauses the DMA Transfer.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
Return values:
HAL status
Definition at line 1416 of file stm32f1xx_hal_uart.c.
References __UART_HandleTypeDef::gState, HAL_UART_STATE_BUSY_RX, HAL_UART_STATE_BUSY_TX, __UART_HandleTypeDef::Instance, and __UART_HandleTypeDef::RxState.
HAL_StatusTypeDef HAL_UART_DMAResume (UART_HandleTypeDef * huart)
Resumes the DMA Transfer.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
Return values:
HAL status
Definition at line 1453 of file stm32f1xx_hal_uart.c.
References __HAL_UART_CLEAR_OREFLAG, __UART_HandleTypeDef::gState, HAL_UART_STATE_BUSY_RX, HAL_UART_STATE_BUSY_TX, __UART_HandleTypeDef::Instance, and __UART_HandleTypeDef::RxState.
HAL_StatusTypeDef HAL_UART_DMAStop (UART_HandleTypeDef * huart)
Stops the DMA Transfer.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
Return values:
HAL status
Definition at line 1489 of file stm32f1xx_hal_uart.c.
References __UART_HandleTypeDef::gState, HAL_DMA_Abort(), HAL_UART_STATE_BUSY_RX, HAL_UART_STATE_BUSY_TX, __UART_HandleTypeDef::hdmarx, __UART_HandleTypeDef::hdmatx, __UART_HandleTypeDef::Instance, __UART_HandleTypeDef::RxState, UART_EndRxTransfer(), and UART_EndTxTransfer().
void HAL_UART_ErrorCallback (UART_HandleTypeDef * huart)
UART error callbacks.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
Return values:
None
Definition at line 2209 of file stm32f1xx_hal_uart.c.
Referenced by HAL_UART_IRQHandler(), UART_DMAAbortOnError(), and UART_DMAError().
void HAL_UART_IRQHandler (UART_HandleTypeDef * huart)
This function handles UART interrupt request.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
Return values:
None
Definition at line 2003 of file stm32f1xx_hal_uart.c.
References __UART_HandleTypeDef::ErrorCode, HAL_DMA_Abort_IT(), HAL_UART_ERROR_FE, HAL_UART_ERROR_NE, HAL_UART_ERROR_NONE, HAL_UART_ERROR_ORE, HAL_UART_ERROR_PE, HAL_UART_ErrorCallback(), __UART_HandleTypeDef::hdmarx, __UART_HandleTypeDef::Instance, UART_DMAAbortOnError(), UART_EndRxTransfer(), UART_EndTransmit_IT(), UART_Receive_IT(), UART_Transmit_IT(), and __DMA_HandleTypeDef::XferAbortCallback.
HAL_StatusTypeDef HAL_UART_Receive (UART_HandleTypeDef * huart, uint8_t * pData, uint16_t Size, uint32_t Timeout)
Receives an amount of data in blocking mode.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
pData Pointer to data buffer
Size Amount of data to be received
Timeout Timeout duration
Return values:
HAL status
Definition at line 1106 of file stm32f1xx_hal_uart.c.
References __UART_HandleTypeDef::ErrorCode, HAL_GetTick(), HAL_UART_ERROR_NONE, HAL_UART_STATE_BUSY_RX, HAL_UART_STATE_READY, __UART_HandleTypeDef::Init, __UART_HandleTypeDef::Instance, UART_InitTypeDef::Parity, __UART_HandleTypeDef::RxState, __UART_HandleTypeDef::RxXferCount, __UART_HandleTypeDef::RxXferSize, UART_FLAG_RXNE, UART_PARITY_NONE, UART_WaitOnFlagUntilTimeout(), UART_WORDLENGTH_9B, and UART_InitTypeDef::WordLength.
HAL_StatusTypeDef HAL_UART_Receive_DMA (UART_HandleTypeDef * huart, uint8_t * pData, uint16_t Size)
Receives an amount of data in non blocking mode.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
pData Pointer to data buffer
Size Amount of data to be received
Note:
When the UART parity is enabled (PCE = 1) the received data contains the parity bit.
Return values:
HAL status
Definition at line 1349 of file stm32f1xx_hal_uart.c.
References __HAL_UART_CLEAR_OREFLAG, __UART_HandleTypeDef::ErrorCode, HAL_DMA_Start_IT(), HAL_UART_ERROR_NONE, HAL_UART_STATE_BUSY_RX, HAL_UART_STATE_READY, __UART_HandleTypeDef::hdmarx, __UART_HandleTypeDef::Instance, __UART_HandleTypeDef::pRxBuffPtr, __UART_HandleTypeDef::RxState, __UART_HandleTypeDef::RxXferSize, UART_DMAError(), UART_DMAReceiveCplt(), UART_DMARxHalfCplt(), __DMA_HandleTypeDef::XferAbortCallback, __DMA_HandleTypeDef::XferCpltCallback, __DMA_HandleTypeDef::XferErrorCallback, and __DMA_HandleTypeDef::XferHalfCpltCallback.
HAL_StatusTypeDef HAL_UART_Receive_IT (UART_HandleTypeDef * huart, uint8_t * pData, uint16_t Size)
Receives an amount of data in non blocking mode.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
pData Pointer to data buffer
Size Amount of data to be received
Return values:
HAL status
Definition at line 1236 of file stm32f1xx_hal_uart.c.
References __HAL_UART_ENABLE_IT, __UART_HandleTypeDef::ErrorCode, HAL_UART_ERROR_NONE, HAL_UART_STATE_BUSY_RX, HAL_UART_STATE_READY, __UART_HandleTypeDef::pRxBuffPtr, __UART_HandleTypeDef::RxState, __UART_HandleTypeDef::RxXferCount, __UART_HandleTypeDef::RxXferSize, UART_IT_ERR, UART_IT_PE, and UART_IT_RXNE.
void HAL_UART_RxCpltCallback (UART_HandleTypeDef * huart)
Rx Transfer completed callbacks.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
Return values:
None
Definition at line 2179 of file stm32f1xx_hal_uart.c.
Referenced by UART_DMAReceiveCplt(), and UART_Receive_IT().
void HAL_UART_RxHalfCpltCallback (UART_HandleTypeDef * huart)
Rx Half Transfer completed callbacks.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
Return values:
None
Definition at line 2194 of file stm32f1xx_hal_uart.c.
Referenced by UART_DMARxHalfCplt().
HAL_StatusTypeDef HAL_UART_Transmit (UART_HandleTypeDef * huart, uint8_t * pData, uint16_t Size, uint32_t Timeout)
Sends an amount of data in blocking mode.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
pData Pointer to data buffer
Size Amount of data to be sent
Timeout Timeout duration
Return values:
HAL status
Definition at line 1024 of file stm32f1xx_hal_uart.c.
References __UART_HandleTypeDef::ErrorCode, __UART_HandleTypeDef::gState, HAL_GetTick(), HAL_UART_ERROR_NONE, HAL_UART_STATE_BUSY_TX, HAL_UART_STATE_READY, __UART_HandleTypeDef::Init, __UART_HandleTypeDef::Instance, UART_InitTypeDef::Parity, __UART_HandleTypeDef::TxXferCount, __UART_HandleTypeDef::TxXferSize, UART_FLAG_TC, UART_FLAG_TXE, UART_PARITY_NONE, UART_WaitOnFlagUntilTimeout(), UART_WORDLENGTH_9B, and UART_InitTypeDef::WordLength.
HAL_StatusTypeDef HAL_UART_Transmit_DMA (UART_HandleTypeDef * huart, uint8_t * pData, uint16_t Size)
Sends an amount of data in non blocking mode.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
pData Pointer to data buffer
Size Amount of data to be sent
Return values:
HAL status
Definition at line 1284 of file stm32f1xx_hal_uart.c.
References __HAL_UART_CLEAR_FLAG, __UART_HandleTypeDef::ErrorCode, __UART_HandleTypeDef::gState, HAL_DMA_Start_IT(), HAL_UART_ERROR_NONE, HAL_UART_STATE_BUSY_TX, HAL_UART_STATE_READY, __UART_HandleTypeDef::hdmatx, __UART_HandleTypeDef::Instance, __UART_HandleTypeDef::pTxBuffPtr, __UART_HandleTypeDef::TxXferCount, __UART_HandleTypeDef::TxXferSize, UART_DMAError(), UART_DMATransmitCplt(), UART_DMATxHalfCplt(), UART_FLAG_TC, __DMA_HandleTypeDef::XferAbortCallback, __DMA_HandleTypeDef::XferCpltCallback, __DMA_HandleTypeDef::XferErrorCallback, and __DMA_HandleTypeDef::XferHalfCpltCallback.
HAL_StatusTypeDef HAL_UART_Transmit_IT (UART_HandleTypeDef * huart, uint8_t * pData, uint16_t Size)
Sends an amount of data in non blocking mode.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
pData Pointer to data buffer
Size Amount of data to be sent
Return values:
HAL status
Definition at line 1194 of file stm32f1xx_hal_uart.c.
References __HAL_UART_ENABLE_IT, __UART_HandleTypeDef::ErrorCode, __UART_HandleTypeDef::gState, HAL_UART_ERROR_NONE, HAL_UART_STATE_BUSY_TX, HAL_UART_STATE_READY, __UART_HandleTypeDef::pTxBuffPtr, __UART_HandleTypeDef::TxXferCount, __UART_HandleTypeDef::TxXferSize, and UART_IT_TXE.
void HAL_UART_TxCpltCallback (UART_HandleTypeDef * huart)
Tx Transfer completed callbacks.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
Return values:
None
Definition at line 2149 of file stm32f1xx_hal_uart.c.
Referenced by UART_DMATransmitCplt(), and UART_EndTransmit_IT().
void HAL_UART_TxHalfCpltCallback (UART_HandleTypeDef * huart)
Tx Half Transfer completed callbacks.
Parameters:
huart Pointer to a UART_HandleTypeDef structure that contains the configuration information for the specified UART module.
Return values:
None
Definition at line 2164 of file stm32f1xx_hal_uart.c.
Referenced by UART_DMATxHalfCplt().