STM32F103xB HAL User Manual: TIMEx Private Functions
TIMEx Private Functions
TIMEx
Functions
void TIMEx_DMACommutationCplt (DMA_HandleTypeDef *hdma)
TIM DMA Commutation callback.
void TIMEx_DMACommutationHalfCplt (DMA_HandleTypeDef *hdma)
TIM DMA Commutation half complete callback.
static void TIM_CCxNChannelCmd (TIM_TypeDef *TIMx, uint32_t Channel, uint32_t ChannelNState)
Enables or disables the TIM Capture Compare Channel xN.
Function Documentation
static void TIM_CCxNChannelCmd (TIM_TypeDef * TIMx, uint32_t Channel, uint32_t ChannelNState) [static]
Enables or disables the TIM Capture Compare Channel xN.
Parameters:
TIMx to select the TIM peripheral
Channel specifies the TIM Channel This parameter can be one of the following values:
TIM_CHANNEL_1: TIM Channel 1
TIM_CHANNEL_2: TIM Channel 2
TIM_CHANNEL_3: TIM Channel 3
ChannelNState specifies the TIM Channel CCxNE bit new state. This parameter can be: TIM_CCxN_ENABLE or TIM_CCxN_Disable.
Return values:
None
Definition at line 1896 of file stm32f1xx_hal_tim_ex.c.
Referenced by HAL_TIMEx_OCN_Start(), HAL_TIMEx_OCN_Start_DMA(), HAL_TIMEx_OCN_Start_IT(), HAL_TIMEx_OCN_Stop(), HAL_TIMEx_OCN_Stop_DMA(), HAL_TIMEx_OCN_Stop_IT(), HAL_TIMEx_OnePulseN_Start(), HAL_TIMEx_OnePulseN_Start_IT(), HAL_TIMEx_OnePulseN_Stop(), HAL_TIMEx_OnePulseN_Stop_IT(), HAL_TIMEx_PWMN_Start(), HAL_TIMEx_PWMN_Start_DMA(), HAL_TIMEx_PWMN_Start_IT(), HAL_TIMEx_PWMN_Stop(), HAL_TIMEx_PWMN_Stop_DMA(), and HAL_TIMEx_PWMN_Stop_IT().
void TIMEx_DMACommutationCplt (DMA_HandleTypeDef * hdma)
TIM DMA Commutation callback.
Parameters:
hdma pointer to DMA handle.
Return values:
None
Definition at line 1850 of file stm32f1xx_hal_tim_ex.c.
References HAL_TIM_STATE_READY, HAL_TIMEx_CommutCallback(), and TIM_HandleTypeDef::State.
Referenced by HAL_TIM_DMABurst_ReadStart(), HAL_TIM_DMABurst_WriteStart(), and HAL_TIMEx_ConfigCommutEvent_DMA().
void TIMEx_DMACommutationHalfCplt (DMA_HandleTypeDef * hdma)
TIM DMA Commutation half complete callback.
Parameters:
hdma pointer to DMA handle.
Return values:
None
Definition at line 1869 of file stm32f1xx_hal_tim_ex.c.
References HAL_TIM_STATE_READY, HAL_TIMEx_CommutHalfCpltCallback(), and TIM_HandleTypeDef::State.
Referenced by HAL_TIM_DMABurst_ReadStart(), HAL_TIM_DMABurst_WriteStart(), and HAL_TIMEx_ConfigCommutEvent_DMA().