STM32F103xB HAL User Manual: Peripheral Control functions
Peripheral Control functions
PCDEx Exported Functions
PCDEx control functions.
Functions
HAL_StatusTypeDef HAL_PCDEx_PMAConfig (PCD_HandleTypeDef *hpcd, uint16_t ep_addr, uint16_t ep_kind, uint32_t pmaadress)
Configure PMA for EP.
__weak void HAL_PCDEx_SetConnectionState (PCD_HandleTypeDef *hpcd, uint8_t state)
Software Device Connection, this function is not required by USB OTG FS peripheral, it is used only by USB Device FS peripheral.
__weak void HAL_PCDEx_LPM_Callback (PCD_HandleTypeDef *hpcd, PCD_LPM_MsgTypeDef msg)
Send LPM message to user layer callback.
__weak void HAL_PCDEx_BCD_Callback (PCD_HandleTypeDef *hpcd, PCD_BCD_MsgTypeDef msg)
Send BatteryCharging message to user layer callback.
Detailed Description
PCDEx control functions.
 ===============================================================================
                 ##### Extended features functions #####
 ===============================================================================
    [..]  This section provides functions allowing to:
      (+) Update FIFO configuration
Function Documentation
void HAL_PCDEx_BCD_Callback (PCD_HandleTypeDef * hpcd, PCD_BCD_MsgTypeDef msg)
Send BatteryCharging message to user layer callback.
Parameters:
hpcd PCD handle
msg LPM message
Return values:
HAL status
Definition at line 217 of file stm32f1xx_hal_pcd_ex.c.
void HAL_PCDEx_LPM_Callback (PCD_HandleTypeDef * hpcd, PCD_LPM_MsgTypeDef msg)
Send LPM message to user layer callback.
Parameters:
hpcd PCD handle
msg LPM message
Return values:
HAL status
Definition at line 200 of file stm32f1xx_hal_pcd_ex.c.
HAL_StatusTypeDef HAL_PCDEx_PMAConfig (PCD_HandleTypeDef * hpcd, uint16_t ep_addr, uint16_t ep_kind, uint32_t pmaadress)
Configure PMA for EP.
Parameters:
hpcd Device instance
ep_addr endpoint address
ep_kind endpoint Kind USB_SNG_BUF: Single Buffer used USB_DBL_BUF: Double Buffer used
pmaadress,: EP address in The PMA: In case of single buffer endpoint this parameter is 16-bit value providing the address in PMA allocated to endpoint. In case of double buffer endpoint this parameter is a 32-bit value providing the endpoint buffer 0 address in the LSB part of 32-bit value and endpoint buffer 1 address in the MSB part of 32-bit value.
Return values:
HAL status
Definition at line 138 of file stm32f1xx_hal_pcd_ex.c.
References PCD_HandleTypeDef::IN_ep, PCD_HandleTypeDef::OUT_ep, and PCD_SNG_BUF.
void HAL_PCDEx_SetConnectionState (PCD_HandleTypeDef * hpcd, uint8_t state)
Software Device Connection, this function is not required by USB OTG FS peripheral, it is used only by USB Device FS peripheral.
Parameters:
hpcd,: PCD handle
state,: connection state (0 : disconnected / 1: connected)
Return values:
None
Definition at line 183 of file stm32f1xx_hal_pcd_ex.c.
Referenced by HAL_PCD_DevConnect(), HAL_PCD_DevDisconnect(), and HAL_PCD_Start().