STM32F103xB HAL User Manual: FLASH Private Functions
FLASH Private Functions
FLASH
Functions
static void FLASH_Program_HalfWord (uint32_t Address, uint16_t Data)
Program a half-word (16-bit) at a specified address.
static void FLASH_SetErrorCode (void)
Set the specific FLASH error flag.
void FLASH_PageErase (uint32_t PageAddress)
Erase the specified FLASH memory page.
HAL_StatusTypeDef FLASH_WaitForLastOperation (uint32_t Timeout)
Wait for a FLASH operation to complete.
Function Documentation
void FLASH_PageErase (uint32_t PageAddress)
Erase the specified FLASH memory page.
Parameters:
PageAddress FLASH page to erase The value of this parameter depend on device used within the same series
Return values:
None
Definition at line 1089 of file stm32f1xx_hal_flash_ex.c.
References FLASH_ProcessTypeDef::ErrorCode, and HAL_FLASH_ERROR_NONE.
Referenced by HAL_FLASH_IRQHandler(), HAL_FLASHEx_Erase(), and HAL_FLASHEx_Erase_IT().
static void FLASH_Program_HalfWord (uint32_t Address, uint16_t Data) [static]
Program a half-word (16-bit) at a specified address.
Parameters:
Address specify the address to be programmed.
Data specify the data to be programmed.
Return values:
None
Definition at line 797 of file stm32f1xx_hal_flash.c.
References FLASH_ProcessTypeDef::ErrorCode, and HAL_FLASH_ERROR_NONE.
Referenced by HAL_FLASH_IRQHandler(), HAL_FLASH_Program(), and HAL_FLASH_Program_IT().
static void FLASH_SetErrorCode (void) [static]
Set the specific FLASH error flag.
Return values:
None
Definition at line 914 of file stm32f1xx_hal_flash.c.
References __HAL_FLASH_CLEAR_FLAG, __HAL_FLASH_GET_FLAG, FLASH_ProcessTypeDef::ErrorCode, FLASH_FLAG_OPTVERR, FLASH_FLAG_PGERR, FLASH_FLAG_WRPERR, HAL_FLASH_ERROR_OPTV, HAL_FLASH_ERROR_PROG, and HAL_FLASH_ERROR_WRP.
Referenced by FLASH_WaitForLastOperation(), and HAL_FLASH_IRQHandler().
HAL_StatusTypeDef FLASH_WaitForLastOperation (uint32_t Timeout)
Wait for a FLASH operation to complete.
Parameters:
Timeout maximum flash operation timeout
Return values:
HAL Status
Definition at line 826 of file stm32f1xx_hal_flash.c.
References __HAL_FLASH_CLEAR_FLAG, __HAL_FLASH_GET_FLAG, FLASH_FLAG_BSY, FLASH_FLAG_EOP, FLASH_FLAG_OPTVERR, FLASH_FLAG_PGERR, FLASH_FLAG_WRPERR, FLASH_SetErrorCode(), and HAL_GetTick().
Referenced by FLASH_OB_DisableWRP(), FLASH_OB_EnableWRP(), FLASH_OB_ProgramData(), FLASH_OB_RDP_LevelConfig(), FLASH_OB_UserConfig(), HAL_FLASH_Program(), HAL_FLASHEx_Erase(), and HAL_FLASHEx_OBErase().