STM32F103xB HAL User Manual: IrDA Initialization and de-initialization functions
IrDA Initialization and de-initialization functions
IrDA Exported Functions
Initialization and Configuration functions.
Functions
HAL_StatusTypeDef HAL_IRDA_Init (IRDA_HandleTypeDef *hirda)
Initializes the IRDA mode according to the specified parameters in the IRDA_InitTypeDef and create the associated handle.
HAL_StatusTypeDef HAL_IRDA_DeInit (IRDA_HandleTypeDef *hirda)
DeInitializes the IRDA peripheral.
__weak void HAL_IRDA_MspInit (IRDA_HandleTypeDef *hirda)
IRDA MSP Init.
__weak void HAL_IRDA_MspDeInit (IRDA_HandleTypeDef *hirda)
IRDA MSP DeInit.
Detailed Description
Initialization and Configuration functions.
  ==============================================================================
            ##### Initialization and Configuration functions #####
  ==============================================================================
    [..]
    This subsection provides a set of functions allowing to initialize the USARTx or the UARTy
    in asynchronous IrDA mode.
      (+) For the asynchronous mode only these parameters can be configured:
        (++) BaudRate
        (++) WordLength
        (++) Parity: If the parity is enabled, then the MSB bit of the data written
             in the data register is transmitted but is changed by the parity bit.
             Depending on the frame length defined by the M bit (8-bits or 9-bits),
             please refer to Reference manual for possible IRDA frame formats.
        (++) Prescaler: A pulse of width less than two and greater than one PSC period(s) may or may
             not be rejected. The receiver set up time should be managed by software. The IrDA physical layer
             specification specifies a minimum of 10 ms delay between transmission and
             reception (IrDA is a half duplex protocol).
        (++) Mode: Receiver/transmitter modes
        (++) IrDAMode: the IrDA can operate in the Normal mode or in the Low power mode.
    [..]
    The HAL_IRDA_Init() API follows IRDA configuration procedures (details for the procedures
    are available in reference manual).
Function Documentation
HAL_StatusTypeDef HAL_IRDA_DeInit (IRDA_HandleTypeDef * hirda)
DeInitializes the IRDA peripheral.
Parameters:
hirda Pointer to a IRDA_HandleTypeDef structure that contains the configuration information for the specified IRDA module.
Return values:
HAL status
Definition at line 366 of file stm32f1xx_hal_irda.c.
References __HAL_IRDA_DISABLE, assert_param, IRDA_HandleTypeDef::ErrorCode, IRDA_HandleTypeDef::gState, HAL_IRDA_ERROR_NONE, HAL_IRDA_MspDeInit(), HAL_IRDA_STATE_BUSY, HAL_IRDA_STATE_RESET, IRDA_HandleTypeDef::Instance, and IRDA_HandleTypeDef::RxState.
HAL_StatusTypeDef HAL_IRDA_Init (IRDA_HandleTypeDef * hirda)
Initializes the IRDA mode according to the specified parameters in the IRDA_InitTypeDef and create the associated handle.
Parameters:
hirda Pointer to a IRDA_HandleTypeDef structure that contains the configuration information for the specified IRDA module.
Return values:
HAL status
Definition at line 292 of file stm32f1xx_hal_irda.c.
References __HAL_IRDA_DISABLE, __HAL_IRDA_ENABLE, assert_param, IRDA_HandleTypeDef::ErrorCode, IRDA_HandleTypeDef::gState, HAL_IRDA_ERROR_NONE, HAL_IRDA_MspInit(), HAL_IRDA_STATE_BUSY, HAL_IRDA_STATE_READY, HAL_IRDA_STATE_RESET, IRDA_HandleTypeDef::Init, IRDA_HandleTypeDef::Instance, IRDA_SetConfig(), IRDA_InitTypeDef::IrDAMode, IS_IRDA_POWERMODE, IRDA_HandleTypeDef::Lock, IRDA_InitTypeDef::Prescaler, and IRDA_HandleTypeDef::RxState.
void HAL_IRDA_MspDeInit (IRDA_HandleTypeDef * hirda)
IRDA MSP DeInit.
Parameters:
hirda Pointer to a IRDA_HandleTypeDef structure that contains the configuration information for the specified IRDA module.
Return values:
None
Definition at line 427 of file stm32f1xx_hal_irda.c.
Referenced by HAL_IRDA_DeInit().
void HAL_IRDA_MspInit (IRDA_HandleTypeDef * hirda)
IRDA MSP Init.
Parameters:
hirda Pointer to a IRDA_HandleTypeDef structure that contains the configuration information for the specified IRDA module.
Return values:
None
Definition at line 411 of file stm32f1xx_hal_irda.c.
Referenced by HAL_IRDA_Init().