STM32F103xB HAL User Manual: Operation on ADC hierarchical scope: ADC instance
Operation on ADC hierarchical scope: ADC instance
ADC Exported Functions
Functions
__STATIC_INLINE void LL_ADC_Enable (ADC_TypeDef *ADCx)
Enable the selected ADC instance.
__STATIC_INLINE void LL_ADC_Disable (ADC_TypeDef *ADCx)
Disable the selected ADC instance.
__STATIC_INLINE uint32_t LL_ADC_IsEnabled (ADC_TypeDef *ADCx)
Get the selected ADC instance enable state.
__STATIC_INLINE void LL_ADC_StartCalibration (ADC_TypeDef *ADCx)
Start ADC calibration in the mode single-ended or differential (for devices with differential mode available).
__STATIC_INLINE uint32_t LL_ADC_IsCalibrationOnGoing (ADC_TypeDef *ADCx)
Get ADC calibration state.
Function Documentation
__STATIC_INLINE void LL_ADC_Disable (ADC_TypeDef * ADCx)
Disable the selected ADC instance.
Reference Manual to LL API cross reference:
CR2 ADON LL_ADC_Disable
Parameters:
ADCx ADC instance
Return values:
None
Definition at line 3256 of file stm32f1xx_ll_adc.h.
Referenced by LL_ADC_DeInit().
__STATIC_INLINE void LL_ADC_Enable (ADC_TypeDef * ADCx)
Enable the selected ADC instance.
Note:
On this STM32 serie, after ADC enable, a delay for ADC internal analog stabilization is required before performing a ADC conversion start. Refer to device datasheet, parameter tSTAB.
Reference Manual to LL API cross reference:
CR2 ADON LL_ADC_Enable
Parameters:
ADCx ADC instance
Return values:
None
Definition at line 3245 of file stm32f1xx_ll_adc.h.
__STATIC_INLINE uint32_t LL_ADC_IsCalibrationOnGoing (ADC_TypeDef * ADCx)
Get ADC calibration state.
Reference Manual to LL API cross reference:
CR2 CAL LL_ADC_IsCalibrationOnGoing
Parameters:
ADCx ADC instance
Return values:
0,: calibration complete, 1: calibration in progress.
Definition at line 3298 of file stm32f1xx_ll_adc.h.
__STATIC_INLINE uint32_t LL_ADC_IsEnabled (ADC_TypeDef * ADCx)
Get the selected ADC instance enable state.
Reference Manual to LL API cross reference:
CR2 ADON LL_ADC_IsEnabled
Parameters:
ADCx ADC instance
Return values:
0,: ADC is disabled, 1: ADC is enabled.
Definition at line 3267 of file stm32f1xx_ll_adc.h.
Referenced by LL_ADC_DeInit(), LL_ADC_Init(), LL_ADC_INJ_Init(), and LL_ADC_REG_Init().
__STATIC_INLINE void LL_ADC_StartCalibration (ADC_TypeDef * ADCx)
Start ADC calibration in the mode single-ended or differential (for devices with differential mode available).
Note:
On this STM32 serie, before starting a calibration, ADC must be disabled. A minimum number of ADC clock cycles are required between ADC disable state and calibration start. Refer to literal LL_ADC_DELAY_DISABLE_CALIB_ADC_CYCLES.
On this STM32 serie, hardware prerequisite before starting a calibration: the ADC must have been in power-on state for at least two ADC clock cycles.
Reference Manual to LL API cross reference:
CR2 CAL LL_ADC_StartCalibration
Parameters:
ADCx ADC instance
Return values:
None
Definition at line 3287 of file stm32f1xx_ll_adc.h.