STM32F103xB HAL User Manual: Peripheral Control functions
Peripheral Control functions
PCD Exported Functions
management functions
Functions
HAL_StatusTypeDef HAL_PCD_DevConnect (PCD_HandleTypeDef *hpcd)
Connect the USB device.
HAL_StatusTypeDef HAL_PCD_DevDisconnect (PCD_HandleTypeDef *hpcd)
Disconnect the USB device.
HAL_StatusTypeDef HAL_PCD_SetAddress (PCD_HandleTypeDef *hpcd, uint8_t address)
Set the USB Device address.
HAL_StatusTypeDef HAL_PCD_EP_Open (PCD_HandleTypeDef *hpcd, uint8_t ep_addr, uint16_t ep_mps, uint8_t ep_type)
Open and configure an endpoint.
HAL_StatusTypeDef HAL_PCD_EP_Close (PCD_HandleTypeDef *hpcd, uint8_t ep_addr)
Deactivate an endpoint.
HAL_StatusTypeDef HAL_PCD_EP_Receive (PCD_HandleTypeDef *hpcd, uint8_t ep_addr, uint8_t *pBuf, uint32_t len)
Receive an amount of data.
uint32_t HAL_PCD_EP_GetRxCount (PCD_HandleTypeDef *hpcd, uint8_t ep_addr)
Get Received Data Size.
HAL_StatusTypeDef HAL_PCD_EP_Transmit (PCD_HandleTypeDef *hpcd, uint8_t ep_addr, uint8_t *pBuf, uint32_t len)
Send an amount of data.
HAL_StatusTypeDef HAL_PCD_EP_SetStall (PCD_HandleTypeDef *hpcd, uint8_t ep_addr)
Set a STALL condition over an endpoint.
HAL_StatusTypeDef HAL_PCD_EP_ClrStall (PCD_HandleTypeDef *hpcd, uint8_t ep_addr)
Clear a STALL condition over in an endpoint.
HAL_StatusTypeDef HAL_PCD_EP_Flush (PCD_HandleTypeDef *hpcd, uint8_t ep_addr)
Flush an endpoint.
HAL_StatusTypeDef HAL_PCD_ActivateRemoteWakeup (PCD_HandleTypeDef *hpcd)
Activate remote wakeup signalling.
HAL_StatusTypeDef HAL_PCD_DeActivateRemoteWakeup (PCD_HandleTypeDef *hpcd)
De-activate remote wakeup signalling.
Detailed Description
management functions
 ===============================================================================
                      ##### Peripheral Control functions #####
 ===============================================================================
    [..]
    This subsection provides a set of functions allowing to control the PCD data
    transfers.
Function Documentation
HAL_StatusTypeDef HAL_PCD_ActivateRemoteWakeup (PCD_HandleTypeDef * hpcd)
Activate remote wakeup signalling.
Parameters:
hpcd PCD handle
Return values:
HAL status
Definition at line 1794 of file stm32f1xx_hal_pcd.c.
References PCD_HandleTypeDef::Instance.
HAL_StatusTypeDef HAL_PCD_DeActivateRemoteWakeup (PCD_HandleTypeDef * hpcd)
De-activate remote wakeup signalling.
Parameters:
hpcd PCD handle
Return values:
HAL status
Definition at line 1804 of file stm32f1xx_hal_pcd.c.
References PCD_HandleTypeDef::Instance.
HAL_StatusTypeDef HAL_PCD_DevConnect (PCD_HandleTypeDef * hpcd)
Connect the USB device.
Parameters:
hpcd PCD handle
Return values:
HAL status
Definition at line 1496 of file stm32f1xx_hal_pcd.c.
References HAL_PCDEx_SetConnectionState(), and PCD_HandleTypeDef::Instance.
HAL_StatusTypeDef HAL_PCD_DevDisconnect (PCD_HandleTypeDef * hpcd)
Disconnect the USB device.
Parameters:
hpcd PCD handle
Return values:
HAL status
Definition at line 1512 of file stm32f1xx_hal_pcd.c.
References HAL_PCDEx_SetConnectionState(), and PCD_HandleTypeDef::Instance.
HAL_StatusTypeDef HAL_PCD_EP_Close (PCD_HandleTypeDef * hpcd, uint8_t ep_addr)
Deactivate an endpoint.
Parameters:
hpcd PCD handle
ep_addr endpoint address
Return values:
HAL status
Definition at line 1589 of file stm32f1xx_hal_pcd.c.
References PCD_HandleTypeDef::IN_ep, PCD_HandleTypeDef::Instance, and PCD_HandleTypeDef::OUT_ep.
HAL_StatusTypeDef HAL_PCD_EP_ClrStall (PCD_HandleTypeDef * hpcd, uint8_t ep_addr)
Clear a STALL condition over in an endpoint.
Parameters:
hpcd PCD handle
ep_addr endpoint address
Return values:
HAL status
Definition at line 1735 of file stm32f1xx_hal_pcd.c.
References PCD_HandleTypeDef::IN_ep, PCD_HandleTypeDef::Init, PCD_HandleTypeDef::Instance, and PCD_HandleTypeDef::OUT_ep.
HAL_StatusTypeDef HAL_PCD_EP_Flush (PCD_HandleTypeDef * hpcd, uint8_t ep_addr)
Flush an endpoint.
Parameters:
hpcd PCD handle
ep_addr endpoint address
Return values:
HAL status
Definition at line 1771 of file stm32f1xx_hal_pcd.c.
References PCD_HandleTypeDef::Instance.
uint32_t HAL_PCD_EP_GetRxCount (PCD_HandleTypeDef * hpcd, uint8_t ep_addr)
Get Received Data Size.
Parameters:
hpcd PCD handle
ep_addr endpoint address
Return values:
Data Size
Definition at line 1651 of file stm32f1xx_hal_pcd.c.
References PCD_HandleTypeDef::OUT_ep.
HAL_StatusTypeDef HAL_PCD_EP_Open (PCD_HandleTypeDef * hpcd, uint8_t ep_addr, uint16_t ep_mps, uint8_t ep_type)
Open and configure an endpoint.
Parameters:
hpcd PCD handle
ep_addr endpoint address
ep_mps endpoint max packet size
ep_type endpoint type
Return values:
HAL status
Definition at line 1545 of file stm32f1xx_hal_pcd.c.
References PCD_HandleTypeDef::IN_ep, PCD_HandleTypeDef::Instance, and PCD_HandleTypeDef::OUT_ep.
HAL_StatusTypeDef HAL_PCD_EP_Receive (PCD_HandleTypeDef * hpcd, uint8_t ep_addr, uint8_t * pBuf, uint32_t len)
Receive an amount of data.
Parameters:
hpcd PCD handle
ep_addr endpoint address
pBuf pointer to the reception buffer
len amount of data to be received
Return values:
HAL status
Definition at line 1620 of file stm32f1xx_hal_pcd.c.
References PCD_HandleTypeDef::Instance, PCD_HandleTypeDef::OUT_ep, and USB_EP0StartXfer.
Referenced by PCD_EP_ISR_Handler().
HAL_StatusTypeDef HAL_PCD_EP_SetStall (PCD_HandleTypeDef * hpcd, uint8_t ep_addr)
Set a STALL condition over an endpoint.
Parameters:
hpcd PCD handle
ep_addr endpoint address
Return values:
HAL status
Definition at line 1694 of file stm32f1xx_hal_pcd.c.
References PCD_HandleTypeDef::IN_ep, PCD_HandleTypeDef::Init, PCD_HandleTypeDef::Instance, PCD_HandleTypeDef::OUT_ep, and PCD_HandleTypeDef::Setup.
HAL_StatusTypeDef HAL_PCD_EP_Transmit (PCD_HandleTypeDef * hpcd, uint8_t ep_addr, uint8_t * pBuf, uint32_t len)
Send an amount of data.
Parameters:
hpcd PCD handle
ep_addr endpoint address
pBuf pointer to the transmission buffer
len amount of data to be sent
Return values:
HAL status
Definition at line 1663 of file stm32f1xx_hal_pcd.c.
References PCD_HandleTypeDef::IN_ep, PCD_HandleTypeDef::Instance, and USB_EP0StartXfer.
Referenced by PCD_EP_ISR_Handler().
HAL_StatusTypeDef HAL_PCD_SetAddress (PCD_HandleTypeDef * hpcd, uint8_t address)
Set the USB Device address.
Parameters:
hpcd PCD handle
address new device address
Return values:
HAL status
Definition at line 1529 of file stm32f1xx_hal_pcd.c.
References PCD_HandleTypeDef::Instance, and PCD_HandleTypeDef::USB_Address.
Referenced by HAL_PCD_IRQHandler().