STM32F103xB HAL User Manual: SYSTICK
SYSTICK
CORTEX Exported Functions
Functions
__STATIC_INLINE uint32_t LL_SYSTICK_IsActiveCounterFlag (void)
This function checks if the Systick counter flag is active or not.
__STATIC_INLINE void LL_SYSTICK_SetClkSource (uint32_t Source)
Configures the SysTick clock source.
__STATIC_INLINE uint32_t LL_SYSTICK_GetClkSource (void)
Get the SysTick clock source.
__STATIC_INLINE void LL_SYSTICK_EnableIT (void)
Enable SysTick exception request.
__STATIC_INLINE void LL_SYSTICK_DisableIT (void)
Disable SysTick exception request.
__STATIC_INLINE uint32_t LL_SYSTICK_IsEnabledIT (void)
Checks if the SYSTICK interrupt is enabled or disabled.
Function Documentation
__STATIC_INLINE void LL_SYSTICK_DisableIT (void)
Disable SysTick exception request.
Reference Manual to LL API cross reference:
STK_CTRL TICKINT LL_SYSTICK_DisableIT
Return values:
None
Definition at line 283 of file stm32f1xx_ll_cortex.h.
__STATIC_INLINE void LL_SYSTICK_EnableIT (void)
Enable SysTick exception request.
Reference Manual to LL API cross reference:
STK_CTRL TICKINT LL_SYSTICK_EnableIT
Return values:
None
Definition at line 273 of file stm32f1xx_ll_cortex.h.
__STATIC_INLINE uint32_t LL_SYSTICK_GetClkSource (void)
Get the SysTick clock source.
Reference Manual to LL API cross reference:
STK_CTRL CLKSOURCE LL_SYSTICK_GetClkSource
Return values:
Returned value can be one of the following values:
LL_SYSTICK_CLKSOURCE_HCLK_DIV8
LL_SYSTICK_CLKSOURCE_HCLK
Definition at line 263 of file stm32f1xx_ll_cortex.h.
References LL_SYSTICK_CLKSOURCE_HCLK.
__STATIC_INLINE uint32_t LL_SYSTICK_IsActiveCounterFlag (void)
This function checks if the Systick counter flag is active or not.
Note:
It can be used in timeout function on application side.
Reference Manual to LL API cross reference:
STK_CTRL COUNTFLAG LL_SYSTICK_IsActiveCounterFlag
Return values:
State of bit (1 or 0).
Definition at line 231 of file stm32f1xx_ll_cortex.h.
Referenced by LL_RTC_EnterInitMode(), LL_RTC_ExitInitMode(), and LL_RTC_WaitForSynchro().
__STATIC_INLINE uint32_t LL_SYSTICK_IsEnabledIT (void)
Checks if the SYSTICK interrupt is enabled or disabled.
Reference Manual to LL API cross reference:
STK_CTRL TICKINT LL_SYSTICK_IsEnabledIT
Return values:
State of bit (1 or 0).
Definition at line 293 of file stm32f1xx_ll_cortex.h.
__STATIC_INLINE void LL_SYSTICK_SetClkSource (uint32_t Source)
Configures the SysTick clock source.
Reference Manual to LL API cross reference:
STK_CTRL CLKSOURCE LL_SYSTICK_SetClkSource
Parameters:
Source This parameter can be one of the following values:
LL_SYSTICK_CLKSOURCE_HCLK_DIV8
LL_SYSTICK_CLKSOURCE_HCLK
Return values:
None
Definition at line 244 of file stm32f1xx_ll_cortex.h.
References LL_SYSTICK_CLKSOURCE_HCLK.