STM32F103xB HAL User Manual: Callback functions
Callback functions
CAN Exported Functions
CAN Callback functions.
Functions
__weak void HAL_CAN_TxMailbox0CompleteCallback (CAN_HandleTypeDef *hcan)
Transmission Mailbox 0 complete callback.
__weak void HAL_CAN_TxMailbox1CompleteCallback (CAN_HandleTypeDef *hcan)
Transmission Mailbox 1 complete callback.
__weak void HAL_CAN_TxMailbox2CompleteCallback (CAN_HandleTypeDef *hcan)
Transmission Mailbox 2 complete callback.
__weak void HAL_CAN_TxMailbox0AbortCallback (CAN_HandleTypeDef *hcan)
Transmission Mailbox 0 Cancellation callback.
__weak void HAL_CAN_TxMailbox1AbortCallback (CAN_HandleTypeDef *hcan)
Transmission Mailbox 1 Cancellation callback.
__weak void HAL_CAN_TxMailbox2AbortCallback (CAN_HandleTypeDef *hcan)
Transmission Mailbox 2 Cancellation callback.
__weak void HAL_CAN_RxFifo0MsgPendingCallback (CAN_HandleTypeDef *hcan)
Rx FIFO 0 message pending callback.
__weak void HAL_CAN_RxFifo0FullCallback (CAN_HandleTypeDef *hcan)
Rx FIFO 0 full callback.
__weak void HAL_CAN_RxFifo1MsgPendingCallback (CAN_HandleTypeDef *hcan)
Rx FIFO 1 message pending callback.
__weak void HAL_CAN_RxFifo1FullCallback (CAN_HandleTypeDef *hcan)
Rx FIFO 1 full callback.
__weak void HAL_CAN_SleepCallback (CAN_HandleTypeDef *hcan)
Sleep callback.
__weak void HAL_CAN_WakeUpFromRxMsgCallback (CAN_HandleTypeDef *hcan)
WakeUp from Rx message callback.
__weak void HAL_CAN_ErrorCallback (CAN_HandleTypeDef *hcan)
Error CAN callback.
Detailed Description
CAN Callback functions.
Callback functions.
  ==============================================================================
                          ##### Callback functions #####
  ==============================================================================
    [..]
    This subsection provides the following callback functions:
      (+) HAL_CAN_TxMailbox0CompleteCallback
      (+) HAL_CAN_TxMailbox1CompleteCallback
      (+) HAL_CAN_TxMailbox2CompleteCallback
      (+) HAL_CAN_TxMailbox0AbortCallback
      (+) HAL_CAN_TxMailbox1AbortCallback
      (+) HAL_CAN_TxMailbox2AbortCallback
      (+) HAL_CAN_RxFifo0MsgPendingCallback
      (+) HAL_CAN_RxFifo0FullCallback
      (+) HAL_CAN_RxFifo1MsgPendingCallback
      (+) HAL_CAN_RxFifo1FullCallback
      (+) HAL_CAN_SleepCallback
      (+) HAL_CAN_WakeUpFromRxMsgCallback
      (+) HAL_CAN_ErrorCallback
Function Documentation
void HAL_CAN_ErrorCallback (CAN_HandleTypeDef * hcan)
Error CAN callback.
Parameters:
hcan pointer to a CAN_HandleTypeDef structure that contains the configuration information for the specified CAN.
Return values:
None
Definition at line 2309 of file stm32f1xx_hal_can.c.
Referenced by HAL_CAN_Init(), and HAL_CAN_IRQHandler().
void HAL_CAN_RxFifo0FullCallback (CAN_HandleTypeDef * hcan)
Rx FIFO 0 full callback.
Parameters:
hcan pointer to a CAN_HandleTypeDef structure that contains the configuration information for the specified CAN.
Return values:
None
Definition at line 2225 of file stm32f1xx_hal_can.c.
Referenced by HAL_CAN_Init(), and HAL_CAN_IRQHandler().
void HAL_CAN_RxFifo0MsgPendingCallback (CAN_HandleTypeDef * hcan)
Rx FIFO 0 message pending callback.
Parameters:
hcan pointer to a CAN_HandleTypeDef structure that contains the configuration information for the specified CAN.
Return values:
None
Definition at line 2208 of file stm32f1xx_hal_can.c.
Referenced by HAL_CAN_Init(), and HAL_CAN_IRQHandler().
void HAL_CAN_RxFifo1FullCallback (CAN_HandleTypeDef * hcan)
Rx FIFO 1 full callback.
Parameters:
hcan pointer to a CAN_HandleTypeDef structure that contains the configuration information for the specified CAN.
Return values:
None
Definition at line 2259 of file stm32f1xx_hal_can.c.
Referenced by HAL_CAN_Init(), and HAL_CAN_IRQHandler().
void HAL_CAN_RxFifo1MsgPendingCallback (CAN_HandleTypeDef * hcan)
Rx FIFO 1 message pending callback.
Parameters:
hcan pointer to a CAN_HandleTypeDef structure that contains the configuration information for the specified CAN.
Return values:
None
Definition at line 2242 of file stm32f1xx_hal_can.c.
Referenced by HAL_CAN_Init(), and HAL_CAN_IRQHandler().
void HAL_CAN_SleepCallback (CAN_HandleTypeDef * hcan)
Sleep callback.
Parameters:
hcan pointer to a CAN_HandleTypeDef structure that contains the configuration information for the specified CAN.
Return values:
None
Definition at line 2276 of file stm32f1xx_hal_can.c.
Referenced by HAL_CAN_Init(), and HAL_CAN_IRQHandler().
void HAL_CAN_TxMailbox0AbortCallback (CAN_HandleTypeDef * hcan)
Transmission Mailbox 0 Cancellation callback.
Parameters:
hcan pointer to an CAN_HandleTypeDef structure that contains the configuration information for the specified CAN.
Return values:
None
Definition at line 2157 of file stm32f1xx_hal_can.c.
Referenced by HAL_CAN_Init(), and HAL_CAN_IRQHandler().
void HAL_CAN_TxMailbox0CompleteCallback (CAN_HandleTypeDef * hcan)
Transmission Mailbox 0 complete callback.
Parameters:
hcan pointer to a CAN_HandleTypeDef structure that contains the configuration information for the specified CAN.
Return values:
None
Definition at line 2106 of file stm32f1xx_hal_can.c.
Referenced by HAL_CAN_Init(), and HAL_CAN_IRQHandler().
void HAL_CAN_TxMailbox1AbortCallback (CAN_HandleTypeDef * hcan)
Transmission Mailbox 1 Cancellation callback.
Parameters:
hcan pointer to an CAN_HandleTypeDef structure that contains the configuration information for the specified CAN.
Return values:
None
Definition at line 2174 of file stm32f1xx_hal_can.c.
Referenced by HAL_CAN_Init(), and HAL_CAN_IRQHandler().
void HAL_CAN_TxMailbox1CompleteCallback (CAN_HandleTypeDef * hcan)
Transmission Mailbox 1 complete callback.
Parameters:
hcan pointer to a CAN_HandleTypeDef structure that contains the configuration information for the specified CAN.
Return values:
None
Definition at line 2123 of file stm32f1xx_hal_can.c.
Referenced by HAL_CAN_Init(), and HAL_CAN_IRQHandler().
void HAL_CAN_TxMailbox2AbortCallback (CAN_HandleTypeDef * hcan)
Transmission Mailbox 2 Cancellation callback.
Parameters:
hcan pointer to an CAN_HandleTypeDef structure that contains the configuration information for the specified CAN.
Return values:
None
Definition at line 2191 of file stm32f1xx_hal_can.c.
Referenced by HAL_CAN_Init(), and HAL_CAN_IRQHandler().
void HAL_CAN_TxMailbox2CompleteCallback (CAN_HandleTypeDef * hcan)
Transmission Mailbox 2 complete callback.
Parameters:
hcan pointer to a CAN_HandleTypeDef structure that contains the configuration information for the specified CAN.
Return values:
None
Definition at line 2140 of file stm32f1xx_hal_can.c.
Referenced by HAL_CAN_Init(), and HAL_CAN_IRQHandler().
void HAL_CAN_WakeUpFromRxMsgCallback (CAN_HandleTypeDef * hcan)
WakeUp from Rx message callback.
Parameters:
hcan pointer to a CAN_HandleTypeDef structure that contains the configuration information for the specified CAN.
Return values:
None
Definition at line 2292 of file stm32f1xx_hal_can.c.
Referenced by HAL_CAN_Init(), and HAL_CAN_IRQHandler().