STM32F100xE HAL User Manual: Initialization and de-initialization functions
Initialization and de-initialization functions
USART Exported Functions
Functions
ErrorStatus LL_USART_DeInit (USART_TypeDef *USARTx)
De-initialize USART registers (Registers restored to their default values).
ErrorStatus LL_USART_Init (USART_TypeDef *USARTx, LL_USART_InitTypeDef *USART_InitStruct)
Initialize USART registers according to the specified parameters in USART_InitStruct.
void LL_USART_StructInit (LL_USART_InitTypeDef *USART_InitStruct)
Set each LL_USART_InitTypeDef field to default value.
ErrorStatus LL_USART_ClockInit (USART_TypeDef *USARTx, LL_USART_ClockInitTypeDef *USART_ClockInitStruct)
Initialize USART Clock related settings according to the specified parameters in the USART_ClockInitStruct.
void LL_USART_ClockStructInit (LL_USART_ClockInitTypeDef *USART_ClockInitStruct)
Set each field of a LL_USART_ClockInitTypeDef type structure to default value.
Function Documentation
ErrorStatus LL_USART_ClockInit (USART_TypeDef * USARTx, LL_USART_ClockInitTypeDef * USART_ClockInitStruct)
Initialize USART Clock related settings according to the specified parameters in the USART_ClockInitStruct.
Note:
As some bits in USART configuration registers can only be written when the USART is disabled (USART_CR1_UE bit =0), USART IP should be in disabled state prior calling this function. Otherwise, ERROR result will be returned.
Parameters:
USARTx USART Instance
USART_ClockInitStruct Pointer to a LL_USART_ClockInitTypeDef structure that contains the Clock configuration information for the specified USART peripheral.
Return values:
An ErrorStatus enumeration value:
SUCCESS: USART registers related to Clock settings are initialized according to USART_ClockInitStruct content
ERROR: Problem occurred during USART Registers initialization
Definition at line 357 of file stm32f1xx_ll_usart.c.
References assert_param, LL_USART_ClockInitTypeDef::ClockOutput, LL_USART_ClockInitTypeDef::ClockPhase, LL_USART_ClockInitTypeDef::ClockPolarity, IS_LL_USART_CLOCKOUTPUT, IS_LL_USART_CLOCKPHASE, IS_LL_USART_CLOCKPOLARITY, IS_LL_USART_LASTBITCLKOUTPUT, LL_USART_ClockInitTypeDef::LastBitClockPulse, LL_USART_CLOCK_DISABLE, LL_USART_DisableSCLKOutput(), and LL_USART_IsEnabled().
void LL_USART_ClockStructInit (LL_USART_ClockInitTypeDef * USART_ClockInitStruct)
Set each field of a LL_USART_ClockInitTypeDef type structure to default value.
Parameters:
USART_ClockInitStruct Pointer to a LL_USART_ClockInitTypeDef structure whose fields will be set to default values.
Return values:
None
Definition at line 416 of file stm32f1xx_ll_usart.c.
References LL_USART_ClockInitTypeDef::ClockOutput, LL_USART_ClockInitTypeDef::ClockPhase, LL_USART_ClockInitTypeDef::ClockPolarity, LL_USART_ClockInitTypeDef::LastBitClockPulse, LL_USART_CLOCK_DISABLE, LL_USART_LASTCLKPULSE_NO_OUTPUT, LL_USART_PHASE_1EDGE, and LL_USART_POLARITY_LOW.
ErrorStatus LL_USART_DeInit (USART_TypeDef * USARTx)
De-initialize USART registers (Registers restored to their default values).
Parameters:
USARTx USART Instance
Return values:
An ErrorStatus enumeration value:
SUCCESS: USART registers are de-initialized
ERROR: USART registers are not de-initialized
Definition at line 128 of file stm32f1xx_ll_usart.c.
References assert_param, LL_APB1_GRP1_ForceReset(), LL_APB1_GRP1_PERIPH_UART4, LL_APB1_GRP1_PERIPH_UART5, LL_APB1_GRP1_PERIPH_USART2, LL_APB1_GRP1_PERIPH_USART3, LL_APB1_GRP1_ReleaseReset(), LL_APB2_GRP1_ForceReset(), LL_APB2_GRP1_PERIPH_USART1, and LL_APB2_GRP1_ReleaseReset().
ErrorStatus LL_USART_Init (USART_TypeDef * USARTx, LL_USART_InitTypeDef * USART_InitStruct)
Initialize USART registers according to the specified parameters in USART_InitStruct.
Note:
As some bits in USART configuration registers can only be written when the USART is disabled (USART_CR1_UE bit =0), USART IP should be in disabled state prior calling this function. Otherwise, ERROR result will be returned.
Baud rate value stored in USART_InitStruct BaudRate field, should be valid (different from 0).
Parameters:
USARTx USART Instance
USART_InitStruct pointer to a LL_USART_InitTypeDef structure that contains the configuration information for the specified USART peripheral.
Return values:
An ErrorStatus enumeration value:
SUCCESS: USART registers are initialized according to USART_InitStruct content
ERROR: Problem occurred during USART Registers initialization
Definition at line 202 of file stm32f1xx_ll_usart.c.
References assert_param, LL_USART_InitTypeDef::BaudRate, LL_USART_InitTypeDef::DataWidth, LL_USART_InitTypeDef::HardwareFlowControl, IS_LL_USART_BAUDRATE, IS_LL_USART_BRR_MAX, IS_LL_USART_BRR_MIN, IS_LL_USART_DATAWIDTH, IS_LL_USART_DIRECTION, IS_LL_USART_HWCONTROL, IS_LL_USART_OVERSAMPLING, IS_LL_USART_PARITY, IS_LL_USART_STOPBITS, LL_RCC_GetSystemClocksFreq(), LL_RCC_PERIPH_FREQUENCY_NO, LL_USART_IsEnabled(), LL_USART_SetBaudRate(), LL_USART_SetHWFlowCtrl(), LL_USART_SetStopBitsLength(), LL_USART_InitTypeDef::OverSampling, LL_USART_InitTypeDef::Parity, LL_RCC_ClocksTypeDef::PCLK1_Frequency, LL_RCC_ClocksTypeDef::PCLK2_Frequency, LL_USART_InitTypeDef::StopBits, and LL_USART_InitTypeDef::TransferDirection.
void LL_USART_StructInit (LL_USART_InitTypeDef * USART_InitStruct)
Set each LL_USART_InitTypeDef field to default value.
Parameters:
USART_InitStruct Pointer to a LL_USART_InitTypeDef structure whose fields will be set to default values.
Return values:
None
Definition at line 331 of file stm32f1xx_ll_usart.c.
References LL_USART_InitTypeDef::BaudRate, LL_USART_InitTypeDef::DataWidth, LL_USART_InitTypeDef::HardwareFlowControl, LL_USART_DATAWIDTH_8B, LL_USART_DIRECTION_TX_RX, LL_USART_HWCONTROL_NONE, LL_USART_OVERSAMPLING_16, LL_USART_PARITY_NONE, LL_USART_STOPBITS_1, LL_USART_InitTypeDef::OverSampling, LL_USART_InitTypeDef::Parity, LL_USART_InitTypeDef::StopBits, and LL_USART_InitTypeDef::TransferDirection.