STM32F100xE HAL User Manual: Initialization and de-initialization functions
Initialization and de-initialization functions
CEC Exported Functions
Initialization and Configuration functions.
Functions
HAL_StatusTypeDef HAL_CEC_Init (CEC_HandleTypeDef *hcec)
Initializes the CEC mode according to the specified parameters in the CEC_InitTypeDef and creates the associated handle .
HAL_StatusTypeDef HAL_CEC_DeInit (CEC_HandleTypeDef *hcec)
DeInitializes the CEC peripheral.
HAL_StatusTypeDef HAL_CEC_SetDeviceAddress (CEC_HandleTypeDef *hcec, uint16_t CEC_OwnAddress)
Initializes the Own Address of the CEC device.
__weak void HAL_CEC_MspInit (CEC_HandleTypeDef *hcec)
CEC MSP Init.
__weak void HAL_CEC_MspDeInit (CEC_HandleTypeDef *hcec)
CEC MSP DeInit.
Detailed Description
Initialization and Configuration functions.
===============================================================================
            ##### Initialization and Configuration functions #####
 ===============================================================================
    [..]
    This subsection provides a set of functions allowing to initialize the CEC
      (+) The following parameters need to be configured:
        (++) TimingErrorFree
        (++) PeriodErrorFree
        (++) InitiatorAddress
Function Documentation
HAL_StatusTypeDef HAL_CEC_DeInit (CEC_HandleTypeDef * hcec)
DeInitializes the CEC peripheral.
Parameters:
hcec,: CEC handle
Return values:
HAL status
Definition at line 254 of file stm32f1xx_hal_cec.c.
References __HAL_RCC_CEC_FORCE_RESET, __HAL_RCC_CEC_RELEASE_RESET, assert_param, __CEC_HandleTypeDef::ErrorCode, __CEC_HandleTypeDef::gState, HAL_CEC_ERROR_NONE, HAL_CEC_MspDeInit(), HAL_CEC_STATE_BUSY, HAL_CEC_STATE_RESET, __CEC_HandleTypeDef::Instance, and __CEC_HandleTypeDef::RxState.
HAL_StatusTypeDef HAL_CEC_Init (CEC_HandleTypeDef * hcec)
Initializes the CEC mode according to the specified parameters in the CEC_InitTypeDef and creates the associated handle .
Parameters:
hcec,: CEC handle
Return values:
HAL status
Definition at line 181 of file stm32f1xx_hal_cec.c.
References __HAL_CEC_DISABLE, __HAL_CEC_ENABLE, __HAL_CEC_ENABLE_IT, assert_param, CEC_CFGR_FIELDS, CEC_IT_IE, __CEC_HandleTypeDef::ErrorCode, __CEC_HandleTypeDef::gState, HAL_CEC_ERROR_NONE, HAL_CEC_ErrorCallback(), HAL_CEC_MspInit(), HAL_CEC_RxCpltCallback(), HAL_CEC_STATE_BUSY, HAL_CEC_STATE_READY, HAL_CEC_STATE_RESET, HAL_CEC_TxCpltCallback(), HAL_RCC_GetPCLK1Freq(), __CEC_HandleTypeDef::Init, __CEC_HandleTypeDef::Instance, IS_CEC_ADDRESS, IS_CEC_BIT_PERIOD_ERROR_MODE, IS_CEC_BIT_TIMING_ERROR_MODE, __CEC_HandleTypeDef::Lock, CEC_InitTypeDef::OwnAddress, CEC_InitTypeDef::PeriodErrorFree, CEC_InitTypeDef::RxBuffer, __CEC_HandleTypeDef::RxState, and CEC_InitTypeDef::TimingErrorFree.
void HAL_CEC_MspDeInit (CEC_HandleTypeDef * hcec)
CEC MSP DeInit.
Parameters:
hcec,: CEC handle
Return values:
None
Definition at line 360 of file stm32f1xx_hal_cec.c.
Referenced by HAL_CEC_DeInit().
void HAL_CEC_MspInit (CEC_HandleTypeDef * hcec)
CEC MSP Init.
Parameters:
hcec,: CEC handle
Return values:
None
Definition at line 346 of file stm32f1xx_hal_cec.c.
Referenced by HAL_CEC_Init().
HAL_StatusTypeDef HAL_CEC_SetDeviceAddress (CEC_HandleTypeDef * hcec, uint16_t CEC_OwnAddress)
Initializes the Own Address of the CEC device.
Parameters:
hcec,: CEC handle
CEC_OwnAddress,: The CEC own address.
Return values:
HAL status
Definition at line 300 of file stm32f1xx_hal_cec.c.
References __HAL_CEC_DISABLE, __HAL_CEC_ENABLE, assert_param, CEC_OWN_ADDRESS_NONE, __CEC_HandleTypeDef::ErrorCode, __CEC_HandleTypeDef::gState, HAL_CEC_ERROR_NONE, HAL_CEC_STATE_BUSY, HAL_CEC_STATE_READY, __CEC_HandleTypeDef::Init, __CEC_HandleTypeDef::Instance, IS_CEC_OWN_ADDRESS, CEC_InitTypeDef::OwnAddress, and __CEC_HandleTypeDef::RxState.