STM32F100xE HAL User Manual: SMARTCARD Private Functions
SMARTCARD Private Functions
SMARTCARD
Functions
static void SMARTCARD_EndTxTransfer (SMARTCARD_HandleTypeDef *hsc)
End ongoing Tx transfer on SMARTCARD peripheral (following error detection or Transmit completion).
static void SMARTCARD_EndRxTransfer (SMARTCARD_HandleTypeDef *hsc)
End ongoing Rx transfer on SMARTCARD peripheral (following error detection or Reception completion).
static void SMARTCARD_SetConfig (SMARTCARD_HandleTypeDef *hsc)
Configure the SMARTCARD peripheral.
static HAL_StatusTypeDef SMARTCARD_Transmit_IT (SMARTCARD_HandleTypeDef *hsc)
Send an amount of data in non blocking mode.
static HAL_StatusTypeDef SMARTCARD_EndTransmit_IT (SMARTCARD_HandleTypeDef *hsc)
Wraps up transmission in non blocking mode.
static HAL_StatusTypeDef SMARTCARD_Receive_IT (SMARTCARD_HandleTypeDef *hsc)
Receive an amount of data in non blocking mode.
static void SMARTCARD_DMATransmitCplt (DMA_HandleTypeDef *hdma)
DMA SMARTCARD transmit process complete callback.
static void SMARTCARD_DMAReceiveCplt (DMA_HandleTypeDef *hdma)
DMA SMARTCARD receive process complete callback.
static void SMARTCARD_DMAError (DMA_HandleTypeDef *hdma)
DMA SMARTCARD communication error callback.
static void SMARTCARD_DMAAbortOnError (DMA_HandleTypeDef *hdma)
DMA SMARTCARD communication abort callback, when initiated by HAL services on Error (To be called at end of DMA Abort procedure following error occurrence).
static void SMARTCARD_DMATxAbortCallback (DMA_HandleTypeDef *hdma)
DMA SMARTCARD Tx communication abort callback, when initiated by user (To be called at end of DMA Tx Abort procedure following user abort request).
static void SMARTCARD_DMARxAbortCallback (DMA_HandleTypeDef *hdma)
DMA SMARTCARD Rx communication abort callback, when initiated by user (To be called at end of DMA Rx Abort procedure following user abort request).
static void SMARTCARD_DMATxOnlyAbortCallback (DMA_HandleTypeDef *hdma)
DMA SMARTCARD Tx communication abort callback, when initiated by user by a call to HAL_SMARTCARD_AbortTransmit_IT API (Abort only Tx transfer) (This callback is executed at end of DMA Tx Abort procedure following user abort request, and leads to user Tx Abort Complete callback execution).
static void SMARTCARD_DMARxOnlyAbortCallback (DMA_HandleTypeDef *hdma)
DMA SMARTCARD Rx communication abort callback, when initiated by user by a call to HAL_SMARTCARD_AbortReceive_IT API (Abort only Rx transfer) (This callback is executed at end of DMA Rx Abort procedure following user abort request, and leads to user Rx Abort Complete callback execution).
static HAL_StatusTypeDef SMARTCARD_WaitOnFlagUntilTimeout (SMARTCARD_HandleTypeDef *hsc, uint32_t Flag, FlagStatus Status, uint32_t Tickstart, uint32_t Timeout)
This function handles SMARTCARD Communication Timeout.
Function Documentation
static void SMARTCARD_DMAAbortOnError (DMA_HandleTypeDef * hdma) [static]
DMA SMARTCARD communication abort callback, when initiated by HAL services on Error (To be called at end of DMA Abort procedure following error occurrence).
Parameters:
hdma DMA handle.
Return values:
None
Definition at line 2107 of file stm32f1xx_hal_smartcard.c.
References HAL_SMARTCARD_ErrorCallback(), __SMARTCARD_HandleTypeDef::RxXferCount, and __SMARTCARD_HandleTypeDef::TxXferCount.
Referenced by HAL_SMARTCARD_IRQHandler().
static void SMARTCARD_DMAError (DMA_HandleTypeDef * hdma) [static]
DMA SMARTCARD communication error callback.
Parameters:
hdma Pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 1891 of file stm32f1xx_hal_smartcard.c.
References __SMARTCARD_HandleTypeDef::ErrorCode, __SMARTCARD_HandleTypeDef::gState, HAL_SMARTCARD_ERROR_DMA, HAL_SMARTCARD_ErrorCallback(), HAL_SMARTCARD_STATE_BUSY_RX, HAL_SMARTCARD_STATE_BUSY_TX, __SMARTCARD_HandleTypeDef::Instance, __SMARTCARD_HandleTypeDef::RxState, __SMARTCARD_HandleTypeDef::RxXferCount, SMARTCARD_EndRxTransfer(), SMARTCARD_EndTxTransfer(), and __SMARTCARD_HandleTypeDef::TxXferCount.
Referenced by HAL_SMARTCARD_Receive_DMA(), and HAL_SMARTCARD_Transmit_DMA().
static void SMARTCARD_DMAReceiveCplt (DMA_HandleTypeDef * hdma) [static]
DMA SMARTCARD receive process complete callback.
Parameters:
hdma Pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 1859 of file stm32f1xx_hal_smartcard.c.
References HAL_SMARTCARD_RxCpltCallback(), HAL_SMARTCARD_STATE_READY, __SMARTCARD_HandleTypeDef::Instance, __SMARTCARD_HandleTypeDef::RxState, and __SMARTCARD_HandleTypeDef::RxXferCount.
Referenced by HAL_SMARTCARD_Receive_DMA().
static void SMARTCARD_DMARxAbortCallback (DMA_HandleTypeDef * hdma) [static]
DMA SMARTCARD Rx communication abort callback, when initiated by user (To be called at end of DMA Rx Abort procedure following user abort request).
Note:
When this callback is executed, User Abort complete call back is called only if no Abort still ongoing for Tx DMA Handle.
Parameters:
hdma DMA handle.
Return values:
None
Definition at line 2173 of file stm32f1xx_hal_smartcard.c.
References __SMARTCARD_HandleTypeDef::ErrorCode, __SMARTCARD_HandleTypeDef::gState, HAL_SMARTCARD_AbortCpltCallback(), HAL_SMARTCARD_ERROR_NONE, HAL_SMARTCARD_STATE_READY, __SMARTCARD_HandleTypeDef::hdmarx, __SMARTCARD_HandleTypeDef::hdmatx, __SMARTCARD_HandleTypeDef::RxState, __SMARTCARD_HandleTypeDef::RxXferCount, __SMARTCARD_HandleTypeDef::TxXferCount, and __DMA_HandleTypeDef::XferAbortCallback.
Referenced by HAL_SMARTCARD_Abort_IT().
static void SMARTCARD_DMARxOnlyAbortCallback (DMA_HandleTypeDef * hdma) [static]
DMA SMARTCARD Rx communication abort callback, when initiated by user by a call to HAL_SMARTCARD_AbortReceive_IT API (Abort only Rx transfer) (This callback is executed at end of DMA Rx Abort procedure following user abort request, and leads to user Rx Abort Complete callback execution).
Parameters:
hdma DMA handle.
Return values:
None
Definition at line 2242 of file stm32f1xx_hal_smartcard.c.
References HAL_SMARTCARD_AbortReceiveCpltCallback(), HAL_SMARTCARD_STATE_READY, __SMARTCARD_HandleTypeDef::RxState, and __SMARTCARD_HandleTypeDef::RxXferCount.
Referenced by HAL_SMARTCARD_AbortReceive_IT().
static void SMARTCARD_DMATransmitCplt (DMA_HandleTypeDef * hdma) [static]
DMA SMARTCARD transmit process complete callback.
Parameters:
hdma Pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 1839 of file stm32f1xx_hal_smartcard.c.
References __SMARTCARD_HandleTypeDef::Instance, and __SMARTCARD_HandleTypeDef::TxXferCount.
Referenced by HAL_SMARTCARD_Transmit_DMA().
static void SMARTCARD_DMATxAbortCallback (DMA_HandleTypeDef * hdma) [static]
DMA SMARTCARD Tx communication abort callback, when initiated by user (To be called at end of DMA Tx Abort procedure following user abort request).
Note:
When this callback is executed, User Abort complete call back is called only if no Abort still ongoing for Rx DMA Handle.
Parameters:
hdma DMA handle.
Return values:
None
Definition at line 2130 of file stm32f1xx_hal_smartcard.c.
References __SMARTCARD_HandleTypeDef::ErrorCode, __SMARTCARD_HandleTypeDef::gState, HAL_SMARTCARD_AbortCpltCallback(), HAL_SMARTCARD_ERROR_NONE, HAL_SMARTCARD_STATE_READY, __SMARTCARD_HandleTypeDef::hdmarx, __SMARTCARD_HandleTypeDef::hdmatx, __SMARTCARD_HandleTypeDef::RxState, __SMARTCARD_HandleTypeDef::RxXferCount, __SMARTCARD_HandleTypeDef::TxXferCount, and __DMA_HandleTypeDef::XferAbortCallback.
Referenced by HAL_SMARTCARD_Abort_IT().
static void SMARTCARD_DMATxOnlyAbortCallback (DMA_HandleTypeDef * hdma) [static]
DMA SMARTCARD Tx communication abort callback, when initiated by user by a call to HAL_SMARTCARD_AbortTransmit_IT API (Abort only Tx transfer) (This callback is executed at end of DMA Tx Abort procedure following user abort request, and leads to user Tx Abort Complete callback execution).
Parameters:
hdma DMA handle.
Return values:
None
Definition at line 2216 of file stm32f1xx_hal_smartcard.c.
References __SMARTCARD_HandleTypeDef::gState, HAL_SMARTCARD_AbortTransmitCpltCallback(), HAL_SMARTCARD_STATE_READY, and __SMARTCARD_HandleTypeDef::TxXferCount.
Referenced by HAL_SMARTCARD_AbortTransmit_IT().
static void SMARTCARD_EndRxTransfer (SMARTCARD_HandleTypeDef * hsc) [static]
End ongoing Rx transfer on SMARTCARD peripheral (following error detection or Reception completion).
Parameters:
hsc Pointer to a SMARTCARD_HandleTypeDef structure that contains the configuration information for SMARTCARD module.
Return values:
None
Definition at line 1981 of file stm32f1xx_hal_smartcard.c.
References HAL_SMARTCARD_STATE_READY, __SMARTCARD_HandleTypeDef::Instance, and __SMARTCARD_HandleTypeDef::RxState.
Referenced by HAL_SMARTCARD_IRQHandler(), and SMARTCARD_DMAError().
static HAL_StatusTypeDef SMARTCARD_EndTransmit_IT (SMARTCARD_HandleTypeDef * hsc) [static]
Wraps up transmission in non blocking mode.
Parameters:
hsc Pointer to a SMARTCARD_HandleTypeDef structure that contains the configuration information for the specified SMARTCARD module.
Return values:
HAL status
Definition at line 2031 of file stm32f1xx_hal_smartcard.c.
References __SMARTCARD_HandleTypeDef::gState, HAL_SMARTCARD_STATE_READY, HAL_SMARTCARD_TxCpltCallback(), and __SMARTCARD_HandleTypeDef::Instance.
Referenced by HAL_SMARTCARD_IRQHandler().
static void SMARTCARD_EndTxTransfer (SMARTCARD_HandleTypeDef * hsc) [static]
End ongoing Tx transfer on SMARTCARD peripheral (following error detection or Transmit completion).
Parameters:
hsc Pointer to a SMARTCARD_HandleTypeDef structure that contains the configuration information for SMARTCARD module.
Return values:
None
Definition at line 1965 of file stm32f1xx_hal_smartcard.c.
References __SMARTCARD_HandleTypeDef::gState, HAL_SMARTCARD_STATE_READY, and __SMARTCARD_HandleTypeDef::Instance.
Referenced by SMARTCARD_DMAError().
static HAL_StatusTypeDef SMARTCARD_Receive_IT (SMARTCARD_HandleTypeDef * hsc) [static]
Receive an amount of data in non blocking mode.
Parameters:
hsc Pointer to a SMARTCARD_HandleTypeDef structure that contains the configuration information for SMARTCARD module.
Return values:
HAL status
Definition at line 2059 of file stm32f1xx_hal_smartcard.c.
References HAL_SMARTCARD_RxCpltCallback(), HAL_SMARTCARD_STATE_BUSY_RX, HAL_SMARTCARD_STATE_READY, __SMARTCARD_HandleTypeDef::Instance, __SMARTCARD_HandleTypeDef::pRxBuffPtr, __SMARTCARD_HandleTypeDef::RxState, and __SMARTCARD_HandleTypeDef::RxXferCount.
Referenced by HAL_SMARTCARD_IRQHandler().
static void SMARTCARD_SetConfig (SMARTCARD_HandleTypeDef * hsc) [static]
Configure the SMARTCARD peripheral.
Parameters:
hsc Pointer to a SMARTCARD_HandleTypeDef structure that contains the configuration information for SMARTCARD module.
Return values:
None
Definition at line 2266 of file stm32f1xx_hal_smartcard.c.
References assert_param, SMARTCARD_InitTypeDef::BaudRate, SMARTCARD_InitTypeDef::CLKLastBit, SMARTCARD_InitTypeDef::CLKPhase, SMARTCARD_InitTypeDef::CLKPolarity, HAL_RCC_GetPCLK1Freq(), HAL_RCC_GetPCLK2Freq(), __SMARTCARD_HandleTypeDef::Init, __SMARTCARD_HandleTypeDef::Instance, IS_SMARTCARD_BAUDRATE, IS_SMARTCARD_LASTBIT, IS_SMARTCARD_MODE, IS_SMARTCARD_NACK_STATE, IS_SMARTCARD_PARITY, IS_SMARTCARD_PHASE, IS_SMARTCARD_POLARITY, IS_SMARTCARD_STOPBITS, IS_SMARTCARD_WORD_LENGTH, SMARTCARD_InitTypeDef::Mode, SMARTCARD_InitTypeDef::NACKState, SMARTCARD_InitTypeDef::Parity, SMARTCARD_BRR, SMARTCARD_InitTypeDef::StopBits, and SMARTCARD_InitTypeDef::WordLength.
Referenced by HAL_SMARTCARD_Init().
static HAL_StatusTypeDef SMARTCARD_Transmit_IT (SMARTCARD_HandleTypeDef * hsc) [static]
Send an amount of data in non blocking mode.
Parameters:
hsc Pointer to a SMARTCARD_HandleTypeDef structure that contains the configuration information for SMARTCARD module.
Return values:
HAL status
Definition at line 1997 of file stm32f1xx_hal_smartcard.c.
References __SMARTCARD_HandleTypeDef::gState, HAL_SMARTCARD_STATE_BUSY_TX, __SMARTCARD_HandleTypeDef::Instance, __SMARTCARD_HandleTypeDef::pTxBuffPtr, and __SMARTCARD_HandleTypeDef::TxXferCount.
Referenced by HAL_SMARTCARD_IRQHandler().
static HAL_StatusTypeDef SMARTCARD_WaitOnFlagUntilTimeout (SMARTCARD_HandleTypeDef * hsc, uint32_t Flag, FlagStatus Status, uint32_t Tickstart, uint32_t Timeout) [static]
This function handles SMARTCARD Communication Timeout.
Parameters:
hsc Pointer to a SMARTCARD_HandleTypeDef structure that contains the configuration information for SMARTCARD module.
Flag Specifies the SMARTCARD flag to check.
Status The new Flag status (SET or RESET).
Timeout Timeout duration
Tickstart Tick start value
Return values:
HAL status
Definition at line 1932 of file stm32f1xx_hal_smartcard.c.
References __HAL_SMARTCARD_GET_FLAG, __SMARTCARD_HandleTypeDef::gState, HAL_GetTick(), HAL_SMARTCARD_STATE_READY, __SMARTCARD_HandleTypeDef::Instance, and __SMARTCARD_HandleTypeDef::RxState.
Referenced by HAL_SMARTCARD_Receive(), and HAL_SMARTCARD_Transmit().