STM32F100xE HAL User Manual: USART Initialization and de-initialization functions
USART Initialization and de-initialization functions
USART Exported Functions
Initialization and Configuration functions.
Functions
HAL_StatusTypeDef HAL_USART_Init (USART_HandleTypeDef *husart)
Initialize the USART mode according to the specified parameters in the USART_InitTypeDef and initialize the associated handle.
HAL_StatusTypeDef HAL_USART_DeInit (USART_HandleTypeDef *husart)
DeInitializes the USART peripheral.
__weak void HAL_USART_MspInit (USART_HandleTypeDef *husart)
USART MSP Init.
__weak void HAL_USART_MspDeInit (USART_HandleTypeDef *husart)
USART MSP DeInit.
Detailed Description
Initialization and Configuration functions.
  ==============================================================================
              ##### Initialization and Configuration functions #####
  ==============================================================================
  [..]
  This subsection provides a set of functions allowing to initialize the USART
  in asynchronous and in synchronous modes.
  (+) For the asynchronous mode only these parameters can be configured:
      (++) Baud Rate
      (++) Word Length
      (++) Stop Bit
      (++) Parity: If the parity is enabled, then the MSB bit of the data written
           in the data register is transmitted but is changed by the parity bit.
           Depending on the frame length defined by the M bit (8-bits or 9-bits),
           please refer to Reference manual for possible USART frame formats.
      (++) USART polarity
      (++) USART phase
      (++) USART LastBit
      (++) Receiver/transmitter modes
  [..]
    The HAL_USART_Init() function follows the USART  synchronous configuration
    procedures (details for the procedures are available in reference manuals
    (RM0008 for STM32F10Xxx MCUs and RM0041 for STM32F100xx MCUs)).
Function Documentation
HAL_StatusTypeDef HAL_USART_DeInit (USART_HandleTypeDef * husart)
DeInitializes the USART peripheral.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
Return values:
HAL status
Definition at line 354 of file stm32f1xx_hal_usart.c.
References __HAL_USART_DISABLE, assert_param, __USART_HandleTypeDef::ErrorCode, HAL_USART_ERROR_NONE, HAL_USART_MspDeInit(), HAL_USART_STATE_BUSY, HAL_USART_STATE_RESET, __USART_HandleTypeDef::Instance, and __USART_HandleTypeDef::State.
HAL_StatusTypeDef HAL_USART_Init (USART_HandleTypeDef * husart)
Initialize the USART mode according to the specified parameters in the USART_InitTypeDef and initialize the associated handle.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
Return values:
HAL status
Definition at line 295 of file stm32f1xx_hal_usart.c.
References __HAL_USART_ENABLE, assert_param, __USART_HandleTypeDef::ErrorCode, HAL_USART_ERROR_NONE, HAL_USART_MspInit(), HAL_USART_STATE_BUSY, HAL_USART_STATE_READY, HAL_USART_STATE_RESET, __USART_HandleTypeDef::Instance, __USART_HandleTypeDef::Lock, __USART_HandleTypeDef::State, and USART_SetConfig().
void HAL_USART_MspDeInit (USART_HandleTypeDef * husart)
USART MSP DeInit.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
Return values:
None
Definition at line 412 of file stm32f1xx_hal_usart.c.
Referenced by HAL_USART_DeInit().
void HAL_USART_MspInit (USART_HandleTypeDef * husart)
USART MSP Init.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
Return values:
None
Definition at line 397 of file stm32f1xx_hal_usart.c.
Referenced by HAL_USART_Init().