STM32F100xE HAL User Manual: DACEx private functions
DACEx private functions
DACEx
Extended private functions.
Functions
void DAC_DMAConvCpltCh2 (DMA_HandleTypeDef *hdma)
DMA conversion complete callback.
void DAC_DMAHalfConvCpltCh2 (DMA_HandleTypeDef *hdma)
DMA half transfer complete callback.
void DAC_DMAErrorCh2 (DMA_HandleTypeDef *hdma)
DMA error callback.
Detailed Description
Extended private functions.
Function Documentation
void DAC_DMAConvCpltCh2 (DMA_HandleTypeDef * hdma)
DMA conversion complete callback.
Parameters:
hdma pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 352 of file stm32f1xx_hal_dac_ex.c.
References HAL_DAC_STATE_READY, HAL_DACEx_ConvCpltCallbackCh2(), and DAC_HandleTypeDef::State.
Referenced by HAL_DAC_Start_DMA().
void DAC_DMAErrorCh2 (DMA_HandleTypeDef * hdma)
DMA error callback.
Parameters:
hdma pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 388 of file stm32f1xx_hal_dac_ex.c.
References DAC_HandleTypeDef::ErrorCode, HAL_DAC_ERROR_DMA, HAL_DAC_STATE_READY, HAL_DACEx_ErrorCallbackCh2(), and DAC_HandleTypeDef::State.
Referenced by HAL_DAC_Start_DMA().
void DAC_DMAHalfConvCpltCh2 (DMA_HandleTypeDef * hdma)
DMA half transfer complete callback.
Parameters:
hdma pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 371 of file stm32f1xx_hal_dac_ex.c.
References HAL_DACEx_ConvHalfCpltCallbackCh2().
Referenced by HAL_DAC_Start_DMA().