STM32F100xE HAL User Manual: TIM Private Functions
TIM Private Functions
TIM
Functions
static void TIM_OC1_SetConfig (TIM_TypeDef *TIMx, TIM_OC_InitTypeDef *OC_Config)
Timer Output Compare 1 configuration.
static void TIM_OC3_SetConfig (TIM_TypeDef *TIMx, TIM_OC_InitTypeDef *OC_Config)
Timer Output Compare 3 configuration.
static void TIM_OC4_SetConfig (TIM_TypeDef *TIMx, TIM_OC_InitTypeDef *OC_Config)
Timer Output Compare 4 configuration.
static void TIM_TI1_ConfigInputStage (TIM_TypeDef *TIMx, uint32_t TIM_ICPolarity, uint32_t TIM_ICFilter)
Configure the Polarity and Filter for TI1.
static void TIM_TI2_SetConfig (TIM_TypeDef *TIMx, uint32_t TIM_ICPolarity, uint32_t TIM_ICSelection, uint32_t TIM_ICFilter)
Configure the TI2 as Input.
static void TIM_TI2_ConfigInputStage (TIM_TypeDef *TIMx, uint32_t TIM_ICPolarity, uint32_t TIM_ICFilter)
Configure the Polarity and Filter for TI2.
static void TIM_TI3_SetConfig (TIM_TypeDef *TIMx, uint32_t TIM_ICPolarity, uint32_t TIM_ICSelection, uint32_t TIM_ICFilter)
Configure the TI3 as Input.
static void TIM_TI4_SetConfig (TIM_TypeDef *TIMx, uint32_t TIM_ICPolarity, uint32_t TIM_ICSelection, uint32_t TIM_ICFilter)
Configure the TI4 as Input.
static void TIM_ITRx_SetConfig (TIM_TypeDef *TIMx, uint32_t InputTriggerSource)
Selects the Input Trigger source.
static void TIM_DMAPeriodElapsedCplt (DMA_HandleTypeDef *hdma)
TIM DMA Period Elapse complete callback.
static void TIM_DMAPeriodElapsedHalfCplt (DMA_HandleTypeDef *hdma)
TIM DMA Period Elapse half complete callback.
static void TIM_DMATriggerCplt (DMA_HandleTypeDef *hdma)
TIM DMA Trigger callback.
static void TIM_DMATriggerHalfCplt (DMA_HandleTypeDef *hdma)
TIM DMA Trigger half complete callback.
static HAL_StatusTypeDef TIM_SlaveTimer_SetConfig (TIM_HandleTypeDef *htim, TIM_SlaveConfigTypeDef *sSlaveConfig)
Slave Timer configuration function.
void TIM_DMAError (DMA_HandleTypeDef *hdma)
TIM DMA error callback.
void TIM_DMADelayPulseCplt (DMA_HandleTypeDef *hdma)
TIM DMA Delay Pulse complete callback.
void TIM_DMADelayPulseHalfCplt (DMA_HandleTypeDef *hdma)
TIM DMA Delay Pulse half complete callback.
void TIM_DMACaptureCplt (DMA_HandleTypeDef *hdma)
TIM DMA Capture complete callback.
void TIM_DMACaptureHalfCplt (DMA_HandleTypeDef *hdma)
TIM DMA Capture half complete callback.
void TIM_Base_SetConfig (TIM_TypeDef *TIMx, TIM_Base_InitTypeDef *Structure)
Time Base configuration.
void TIM_OC2_SetConfig (TIM_TypeDef *TIMx, TIM_OC_InitTypeDef *OC_Config)
Timer Output Compare 2 configuration.
void TIM_TI1_SetConfig (TIM_TypeDef *TIMx, uint32_t TIM_ICPolarity, uint32_t TIM_ICSelection, uint32_t TIM_ICFilter)
Configure the TI1 as Input.
void TIM_ETR_SetConfig (TIM_TypeDef *TIMx, uint32_t TIM_ExtTRGPrescaler, uint32_t TIM_ExtTRGPolarity, uint32_t ExtTRGFilter)
Configures the TIMx External Trigger (ETR).
void TIM_CCxChannelCmd (TIM_TypeDef *TIMx, uint32_t Channel, uint32_t ChannelState)
Enables or disables the TIM Capture Compare Channel x.
Function Documentation
void TIM_Base_SetConfig (TIM_TypeDef * TIMx, TIM_Base_InitTypeDef * Structure)
Time Base configuration.
Parameters:
TIMx TIM peripheral
Structure TIM Base configuration structure
Return values:
None
Definition at line 5810 of file stm32f1xx_hal_tim.c.
References TIM_Base_InitTypeDef::AutoReloadPreload, TIM_Base_InitTypeDef::ClockDivision, TIM_Base_InitTypeDef::CounterMode, TIM_Base_InitTypeDef::Period, TIM_Base_InitTypeDef::Prescaler, and TIM_Base_InitTypeDef::RepetitionCounter.
Referenced by HAL_TIM_Base_Init(), HAL_TIM_Encoder_Init(), HAL_TIM_IC_Init(), HAL_TIM_OC_Init(), HAL_TIM_OnePulse_Init(), HAL_TIM_PWM_Init(), and HAL_TIMEx_HallSensor_Init().
void TIM_CCxChannelCmd (TIM_TypeDef * TIMx, uint32_t Channel, uint32_t ChannelState)
Enables or disables the TIM Capture Compare Channel x.
Parameters:
TIMx to select the TIM peripheral
Channel specifies the TIM Channel This parameter can be one of the following values:
TIM_CHANNEL_1: TIM Channel 1
TIM_CHANNEL_2: TIM Channel 2
TIM_CHANNEL_3: TIM Channel 3
TIM_CHANNEL_4: TIM Channel 4
ChannelState specifies the TIM Channel CCxE bit new state. This parameter can be: TIM_CCx_ENABLE or TIM_CCx_DISABLE.
Return values:
None
Definition at line 6596 of file stm32f1xx_hal_tim.c.
References assert_param, and IS_TIM_CHANNELS.
Referenced by HAL_TIM_Encoder_Start(), HAL_TIM_Encoder_Start_DMA(), HAL_TIM_Encoder_Start_IT(), HAL_TIM_Encoder_Stop(), HAL_TIM_Encoder_Stop_DMA(), HAL_TIM_Encoder_Stop_IT(), HAL_TIM_IC_Start(), HAL_TIM_IC_Start_DMA(), HAL_TIM_IC_Start_IT(), HAL_TIM_IC_Stop(), HAL_TIM_IC_Stop_DMA(), HAL_TIM_IC_Stop_IT(), HAL_TIM_OC_Start(), HAL_TIM_OC_Start_DMA(), HAL_TIM_OC_Start_IT(), HAL_TIM_OC_Stop(), HAL_TIM_OC_Stop_DMA(), HAL_TIM_OC_Stop_IT(), HAL_TIM_OnePulse_Start(), HAL_TIM_OnePulse_Start_IT(), HAL_TIM_OnePulse_Stop(), HAL_TIM_OnePulse_Stop_IT(), HAL_TIM_PWM_Start(), HAL_TIM_PWM_Start_DMA(), HAL_TIM_PWM_Start_IT(), HAL_TIM_PWM_Stop(), HAL_TIM_PWM_Stop_DMA(), HAL_TIM_PWM_Stop_IT(), HAL_TIMEx_HallSensor_Start(), HAL_TIMEx_HallSensor_Start_DMA(), HAL_TIMEx_HallSensor_Start_IT(), HAL_TIMEx_HallSensor_Stop(), HAL_TIMEx_HallSensor_Stop_DMA(), and HAL_TIMEx_HallSensor_Stop_IT().
void TIM_DMACaptureCplt (DMA_HandleTypeDef * hdma)
TIM DMA Capture complete callback.
Parameters:
hdma pointer to DMA handle.
Return values:
None
Definition at line 5655 of file stm32f1xx_hal_tim.c.
References TIM_HandleTypeDef::Channel, HAL_TIM_ACTIVE_CHANNEL_1, HAL_TIM_ACTIVE_CHANNEL_2, HAL_TIM_ACTIVE_CHANNEL_3, HAL_TIM_ACTIVE_CHANNEL_4, HAL_TIM_ACTIVE_CHANNEL_CLEARED, HAL_TIM_IC_CaptureCallback(), HAL_TIM_STATE_READY, TIM_HandleTypeDef::hdma, TIM_HandleTypeDef::State, TIM_DMA_ID_CC1, TIM_DMA_ID_CC2, TIM_DMA_ID_CC3, and TIM_DMA_ID_CC4.
Referenced by HAL_TIM_DMABurst_ReadStart(), HAL_TIM_Encoder_Start_DMA(), HAL_TIM_IC_Start_DMA(), and HAL_TIMEx_HallSensor_Start_DMA().
void TIM_DMACaptureHalfCplt (DMA_HandleTypeDef * hdma)
TIM DMA Capture half complete callback.
Parameters:
hdma pointer to DMA handle.
Return values:
None
Definition at line 5696 of file stm32f1xx_hal_tim.c.
References TIM_HandleTypeDef::Channel, HAL_TIM_ACTIVE_CHANNEL_1, HAL_TIM_ACTIVE_CHANNEL_2, HAL_TIM_ACTIVE_CHANNEL_3, HAL_TIM_ACTIVE_CHANNEL_4, HAL_TIM_ACTIVE_CHANNEL_CLEARED, HAL_TIM_IC_CaptureHalfCpltCallback(), HAL_TIM_STATE_READY, TIM_HandleTypeDef::hdma, TIM_HandleTypeDef::State, TIM_DMA_ID_CC1, TIM_DMA_ID_CC2, TIM_DMA_ID_CC3, and TIM_DMA_ID_CC4.
Referenced by HAL_TIM_DMABurst_ReadStart(), HAL_TIM_Encoder_Start_DMA(), HAL_TIM_IC_Start_DMA(), and HAL_TIMEx_HallSensor_Start_DMA().
void TIM_DMADelayPulseCplt (DMA_HandleTypeDef * hdma)
TIM DMA Delay Pulse complete callback.
Parameters:
hdma pointer to DMA handle.
Return values:
None
Definition at line 5573 of file stm32f1xx_hal_tim.c.
References TIM_HandleTypeDef::Channel, HAL_TIM_ACTIVE_CHANNEL_1, HAL_TIM_ACTIVE_CHANNEL_2, HAL_TIM_ACTIVE_CHANNEL_3, HAL_TIM_ACTIVE_CHANNEL_4, HAL_TIM_ACTIVE_CHANNEL_CLEARED, HAL_TIM_PWM_PulseFinishedCallback(), HAL_TIM_STATE_READY, TIM_HandleTypeDef::hdma, TIM_HandleTypeDef::State, TIM_DMA_ID_CC1, TIM_DMA_ID_CC2, TIM_DMA_ID_CC3, and TIM_DMA_ID_CC4.
Referenced by HAL_TIM_DMABurst_WriteStart(), HAL_TIM_OC_Start_DMA(), HAL_TIM_PWM_Start_DMA(), HAL_TIMEx_OCN_Start_DMA(), and HAL_TIMEx_PWMN_Start_DMA().
void TIM_DMADelayPulseHalfCplt (DMA_HandleTypeDef * hdma)
TIM DMA Delay Pulse half complete callback.
Parameters:
hdma pointer to DMA handle.
Return values:
None
Definition at line 5614 of file stm32f1xx_hal_tim.c.
References TIM_HandleTypeDef::Channel, HAL_TIM_ACTIVE_CHANNEL_1, HAL_TIM_ACTIVE_CHANNEL_2, HAL_TIM_ACTIVE_CHANNEL_3, HAL_TIM_ACTIVE_CHANNEL_4, HAL_TIM_ACTIVE_CHANNEL_CLEARED, HAL_TIM_PWM_PulseFinishedHalfCpltCallback(), HAL_TIM_STATE_READY, TIM_HandleTypeDef::hdma, TIM_HandleTypeDef::State, TIM_DMA_ID_CC1, TIM_DMA_ID_CC2, TIM_DMA_ID_CC3, and TIM_DMA_ID_CC4.
Referenced by HAL_TIM_DMABurst_WriteStart(), HAL_TIM_OC_Start_DMA(), HAL_TIM_PWM_Start_DMA(), HAL_TIMEx_OCN_Start_DMA(), and HAL_TIMEx_PWMN_Start_DMA().
void TIM_DMAError (DMA_HandleTypeDef * hdma)
TIM DMA error callback.
Parameters:
hdma pointer to DMA handle.
Return values:
None
Definition at line 5555 of file stm32f1xx_hal_tim.c.
References HAL_TIM_ErrorCallback(), HAL_TIM_STATE_READY, and TIM_HandleTypeDef::State.
Referenced by HAL_TIM_Base_Start_DMA(), HAL_TIM_DMABurst_ReadStart(), HAL_TIM_DMABurst_WriteStart(), HAL_TIM_Encoder_Start_DMA(), HAL_TIM_IC_Start_DMA(), HAL_TIM_OC_Start_DMA(), HAL_TIM_PWM_Start_DMA(), HAL_TIMEx_ConfigCommutEvent_DMA(), HAL_TIMEx_HallSensor_Start_DMA(), HAL_TIMEx_OCN_Start_DMA(), and HAL_TIMEx_PWMN_Start_DMA().
static void TIM_DMAPeriodElapsedCplt (DMA_HandleTypeDef * hdma) [static]
TIM DMA Period Elapse complete callback.
Parameters:
hdma pointer to DMA handle.
Return values:
None
Definition at line 5737 of file stm32f1xx_hal_tim.c.
References HAL_TIM_PeriodElapsedCallback(), HAL_TIM_STATE_READY, and TIM_HandleTypeDef::State.
Referenced by HAL_TIM_Base_Start_DMA(), HAL_TIM_DMABurst_ReadStart(), and HAL_TIM_DMABurst_WriteStart().
static void TIM_DMAPeriodElapsedHalfCplt (DMA_HandleTypeDef * hdma) [static]
TIM DMA Period Elapse half complete callback.
Parameters:
hdma pointer to DMA handle.
Return values:
None
Definition at line 5755 of file stm32f1xx_hal_tim.c.
References HAL_TIM_PeriodElapsedHalfCpltCallback(), HAL_TIM_STATE_READY, and TIM_HandleTypeDef::State.
Referenced by HAL_TIM_Base_Start_DMA(), HAL_TIM_DMABurst_ReadStart(), and HAL_TIM_DMABurst_WriteStart().
static void TIM_DMATriggerCplt (DMA_HandleTypeDef * hdma) [static]
TIM DMA Trigger callback.
Parameters:
hdma pointer to DMA handle.
Return values:
None
Definition at line 5773 of file stm32f1xx_hal_tim.c.
References HAL_TIM_STATE_READY, HAL_TIM_TriggerCallback(), and TIM_HandleTypeDef::State.
Referenced by HAL_TIM_DMABurst_ReadStart(), and HAL_TIM_DMABurst_WriteStart().
static void TIM_DMATriggerHalfCplt (DMA_HandleTypeDef * hdma) [static]
TIM DMA Trigger half complete callback.
Parameters:
hdma pointer to DMA handle.
Return values:
None
Definition at line 5791 of file stm32f1xx_hal_tim.c.
References HAL_TIM_STATE_READY, HAL_TIM_TriggerHalfCpltCallback(), and TIM_HandleTypeDef::State.
Referenced by HAL_TIM_DMABurst_ReadStart(), and HAL_TIM_DMABurst_WriteStart().
void TIM_ETR_SetConfig (TIM_TypeDef * TIMx, uint32_t TIM_ExtTRGPrescaler, uint32_t TIM_ExtTRGPolarity, uint32_t ExtTRGFilter)
Configures the TIMx External Trigger (ETR).
Parameters:
TIMx to select the TIM peripheral
TIM_ExtTRGPrescaler The external Trigger Prescaler. This parameter can be one of the following values:
TIM_ETRPRESCALER_DIV1: ETRP Prescaler OFF.
TIM_ETRPRESCALER_DIV2: ETRP frequency divided by 2.
TIM_ETRPRESCALER_DIV4: ETRP frequency divided by 4.
TIM_ETRPRESCALER_DIV8: ETRP frequency divided by 8.
TIM_ExtTRGPolarity The external Trigger Polarity. This parameter can be one of the following values:
TIM_ETRPOLARITY_INVERTED: active low or falling edge active.
TIM_ETRPOLARITY_NONINVERTED: active high or rising edge active.
ExtTRGFilter External Trigger Filter. This parameter must be a value between 0x00 and 0x0F
Return values:
None
Definition at line 6566 of file stm32f1xx_hal_tim.c.
Referenced by HAL_TIM_ConfigClockSource(), HAL_TIM_ConfigOCrefClear(), and TIM_SlaveTimer_SetConfig().
static void TIM_ITRx_SetConfig (TIM_TypeDef * TIMx, uint32_t InputTriggerSource) [static]
Selects the Input Trigger source.
Parameters:
TIMx to select the TIM peripheral
InputTriggerSource The Input Trigger source. This parameter can be one of the following values:
TIM_TS_ITR0: Internal Trigger 0
TIM_TS_ITR1: Internal Trigger 1
TIM_TS_ITR2: Internal Trigger 2
TIM_TS_ITR3: Internal Trigger 3
TIM_TS_TI1F_ED: TI1 Edge Detector
TIM_TS_TI1FP1: Filtered Timer Input 1
TIM_TS_TI2FP2: Filtered Timer Input 2
TIM_TS_ETRF: External Trigger input
Return values:
None
Definition at line 6536 of file stm32f1xx_hal_tim.c.
References TIM_SLAVEMODE_EXTERNAL1.
Referenced by HAL_TIM_ConfigClockSource().
static void TIM_OC1_SetConfig (TIM_TypeDef * TIMx, TIM_OC_InitTypeDef * OC_Config) [static]
Timer Output Compare 1 configuration.
Parameters:
TIMx to select the TIM peripheral
OC_Config The ouput configuration structure
Return values:
None
Definition at line 5858 of file stm32f1xx_hal_tim.c.
References assert_param, IS_TIM_OCIDLE_STATE, IS_TIM_OCN_POLARITY, IS_TIM_OCNIDLE_STATE, TIM_OC_InitTypeDef::OCIdleState, TIM_OC_InitTypeDef::OCMode, TIM_OC_InitTypeDef::OCNIdleState, TIM_OC_InitTypeDef::OCNPolarity, TIM_OC_InitTypeDef::OCPolarity, TIM_OC_InitTypeDef::Pulse, and TIM_CHANNEL_1.
Referenced by HAL_TIM_OC_ConfigChannel(), HAL_TIM_OnePulse_ConfigChannel(), and HAL_TIM_PWM_ConfigChannel().
void TIM_OC2_SetConfig (TIM_TypeDef * TIMx, TIM_OC_InitTypeDef * OC_Config)
Timer Output Compare 2 configuration.
Parameters:
TIMx to select the TIM peripheral
OC_Config The ouput configuration structure
Return values:
None
Definition at line 5933 of file stm32f1xx_hal_tim.c.
References assert_param, IS_TIM_OCIDLE_STATE, IS_TIM_OCN_POLARITY, IS_TIM_OCNIDLE_STATE, TIM_OC_InitTypeDef::OCIdleState, TIM_OC_InitTypeDef::OCMode, TIM_OC_InitTypeDef::OCNIdleState, TIM_OC_InitTypeDef::OCNPolarity, TIM_OC_InitTypeDef::OCPolarity, TIM_OC_InitTypeDef::Pulse, and TIM_CHANNEL_2.
Referenced by HAL_TIM_OC_ConfigChannel(), HAL_TIM_OnePulse_ConfigChannel(), HAL_TIM_PWM_ConfigChannel(), and HAL_TIMEx_HallSensor_Init().
static void TIM_OC3_SetConfig (TIM_TypeDef * TIMx, TIM_OC_InitTypeDef * OC_Config) [static]
Timer Output Compare 3 configuration.
Parameters:
TIMx to select the TIM peripheral
OC_Config The ouput configuration structure
Return values:
None
Definition at line 6009 of file stm32f1xx_hal_tim.c.
References assert_param, IS_TIM_OCIDLE_STATE, IS_TIM_OCN_POLARITY, IS_TIM_OCNIDLE_STATE, TIM_OC_InitTypeDef::OCIdleState, TIM_OC_InitTypeDef::OCMode, TIM_OC_InitTypeDef::OCNIdleState, TIM_OC_InitTypeDef::OCNPolarity, TIM_OC_InitTypeDef::OCPolarity, TIM_OC_InitTypeDef::Pulse, and TIM_CHANNEL_3.
Referenced by HAL_TIM_OC_ConfigChannel(), and HAL_TIM_PWM_ConfigChannel().
static void TIM_OC4_SetConfig (TIM_TypeDef * TIMx, TIM_OC_InitTypeDef * OC_Config) [static]
Timer Output Compare 4 configuration.
Parameters:
TIMx to select the TIM peripheral
OC_Config The ouput configuration structure
Return values:
None
Definition at line 6083 of file stm32f1xx_hal_tim.c.
References assert_param, IS_TIM_OCIDLE_STATE, TIM_OC_InitTypeDef::OCIdleState, TIM_OC_InitTypeDef::OCMode, TIM_OC_InitTypeDef::OCPolarity, and TIM_OC_InitTypeDef::Pulse.
Referenced by HAL_TIM_OC_ConfigChannel(), and HAL_TIM_PWM_ConfigChannel().
static HAL_StatusTypeDef TIM_SlaveTimer_SetConfig (TIM_HandleTypeDef * htim, TIM_SlaveConfigTypeDef * sSlaveConfig) [static]
Slave Timer configuration function.
Parameters:
htim TIM handle
sSlaveConfig Slave timer configuration
Return values:
None
Definition at line 6143 of file stm32f1xx_hal_tim.c.
References assert_param, TIM_SlaveConfigTypeDef::InputTrigger, TIM_HandleTypeDef::Instance, IS_TIM_TRIGGERFILTER, IS_TIM_TRIGGERPOLARITY, IS_TIM_TRIGGERPRESCALER, TIM_SlaveConfigTypeDef::SlaveMode, TIM_ETR_SetConfig(), TIM_SLAVEMODE_GATED, TIM_TI1_ConfigInputStage(), TIM_TI2_ConfigInputStage(), TIM_TS_ETRF, TIM_TS_ITR0, TIM_TS_ITR1, TIM_TS_ITR2, TIM_TS_ITR3, TIM_TS_TI1F_ED, TIM_TS_TI1FP1, TIM_TS_TI2FP2, TIM_SlaveConfigTypeDef::TriggerFilter, TIM_SlaveConfigTypeDef::TriggerPolarity, and TIM_SlaveConfigTypeDef::TriggerPrescaler.
Referenced by HAL_TIM_SlaveConfigSynchro(), and HAL_TIM_SlaveConfigSynchro_IT().
static void TIM_TI1_ConfigInputStage (TIM_TypeDef * TIMx, uint32_t TIM_ICPolarity, uint32_t TIM_ICFilter) [static]
Configure the Polarity and Filter for TI1.
Parameters:
TIMx to select the TIM peripheral.
TIM_ICPolarity The Input Polarity. This parameter can be one of the following values:
TIM_ICPOLARITY_RISING
TIM_ICPOLARITY_FALLING
TIM_ICPOLARITY_BOTHEDGE
TIM_ICFilter Specifies the Input Capture Filter. This parameter must be a value between 0x00 and 0x0F.
Return values:
None
Definition at line 6321 of file stm32f1xx_hal_tim.c.
Referenced by HAL_TIM_ConfigClockSource(), and TIM_SlaveTimer_SetConfig().
void TIM_TI1_SetConfig (TIM_TypeDef * TIMx, uint32_t TIM_ICPolarity, uint32_t TIM_ICSelection, uint32_t TIM_ICFilter)
Configure the TI1 as Input.
Parameters:
TIMx to select the TIM peripheral.
TIM_ICPolarity The Input Polarity. This parameter can be one of the following values:
TIM_ICPOLARITY_RISING
TIM_ICPOLARITY_FALLING
TIM_ICPOLARITY_BOTHEDGE
TIM_ICSelection specifies the input to be used. This parameter can be one of the following values:
TIM_ICSELECTION_DIRECTTI: TIM Input 1 is selected to be connected to IC1.
TIM_ICSELECTION_INDIRECTTI: TIM Input 1 is selected to be connected to IC2.
TIM_ICSELECTION_TRC: TIM Input 1 is selected to be connected to TRC.
TIM_ICFilter Specifies the Input Capture Filter. This parameter must be a value between 0x00 and 0x0F.
Return values:
None
Note:
TIM_ICFilter and TIM_ICPolarity are not used in INDIRECT mode as TI2FP1 (on channel2 path) is used as the input signal. Therefore CCMR1 must be protected against un-initialized filter and polarity values.
Definition at line 6274 of file stm32f1xx_hal_tim.c.
Referenced by HAL_TIM_IC_ConfigChannel(), HAL_TIM_OnePulse_ConfigChannel(), and HAL_TIMEx_HallSensor_Init().
static void TIM_TI2_ConfigInputStage (TIM_TypeDef * TIMx, uint32_t TIM_ICPolarity, uint32_t TIM_ICFilter) [static]
Configure the Polarity and Filter for TI2.
Parameters:
TIMx to select the TIM peripheral.
TIM_ICPolarity The Input Polarity. This parameter can be one of the following values:
TIM_ICPOLARITY_RISING
TIM_ICPOLARITY_FALLING
TIM_ICPOLARITY_BOTHEDGE
TIM_ICFilter Specifies the Input Capture Filter. This parameter must be a value between 0x00 and 0x0F.
Return values:
None
Definition at line 6404 of file stm32f1xx_hal_tim.c.
Referenced by HAL_TIM_ConfigClockSource(), and TIM_SlaveTimer_SetConfig().
static void TIM_TI2_SetConfig (TIM_TypeDef * TIMx, uint32_t TIM_ICPolarity, uint32_t TIM_ICSelection, uint32_t TIM_ICFilter) [static]
Configure the TI2 as Input.
Parameters:
TIMx to select the TIM peripheral
TIM_ICPolarity The Input Polarity. This parameter can be one of the following values:
TIM_ICPOLARITY_RISING
TIM_ICPOLARITY_FALLING
TIM_ICPOLARITY_BOTHEDGE
TIM_ICSelection specifies the input to be used. This parameter can be one of the following values:
TIM_ICSELECTION_DIRECTTI: TIM Input 2 is selected to be connected to IC2.
TIM_ICSELECTION_INDIRECTTI: TIM Input 2 is selected to be connected to IC1.
TIM_ICSELECTION_TRC: TIM Input 2 is selected to be connected to TRC.
TIM_ICFilter Specifies the Input Capture Filter. This parameter must be a value between 0x00 and 0x0F.
Return values:
None
Note:
TIM_ICFilter and TIM_ICPolarity are not used in INDIRECT mode as TI1FP2 (on channel1 path) is used as the input signal. Therefore CCMR1 must be protected against un-initialized filter and polarity values.
Definition at line 6364 of file stm32f1xx_hal_tim.c.
Referenced by HAL_TIM_IC_ConfigChannel(), and HAL_TIM_OnePulse_ConfigChannel().
static void TIM_TI3_SetConfig (TIM_TypeDef * TIMx, uint32_t TIM_ICPolarity, uint32_t TIM_ICSelection, uint32_t TIM_ICFilter) [static]
Configure the TI3 as Input.
Parameters:
TIMx to select the TIM peripheral
TIM_ICPolarity The Input Polarity. This parameter can be one of the following values:
TIM_ICPOLARITY_RISING
TIM_ICPOLARITY_FALLING
TIM_ICSelection specifies the input to be used. This parameter can be one of the following values:
TIM_ICSELECTION_DIRECTTI: TIM Input 3 is selected to be connected to IC3.
TIM_ICSELECTION_INDIRECTTI: TIM Input 3 is selected to be connected to IC4.
TIM_ICSELECTION_TRC: TIM Input 3 is selected to be connected to TRC.
TIM_ICFilter Specifies the Input Capture Filter. This parameter must be a value between 0x00 and 0x0F.
Return values:
None
Note:
TIM_ICFilter and TIM_ICPolarity are not used in INDIRECT mode as TI3FP4 (on channel1 path) is used as the input signal. Therefore CCMR2 must be protected against un-initialized filter and polarity values.
Definition at line 6446 of file stm32f1xx_hal_tim.c.
Referenced by HAL_TIM_IC_ConfigChannel().
static void TIM_TI4_SetConfig (TIM_TypeDef * TIMx, uint32_t TIM_ICPolarity, uint32_t TIM_ICSelection, uint32_t TIM_ICFilter) [static]
Configure the TI4 as Input.
Parameters:
TIMx to select the TIM peripheral
TIM_ICPolarity The Input Polarity. This parameter can be one of the following values:
TIM_ICPOLARITY_RISING
TIM_ICPOLARITY_FALLING
TIM_ICSelection specifies the input to be used. This parameter can be one of the following values:
TIM_ICSELECTION_DIRECTTI: TIM Input 4 is selected to be connected to IC4.
TIM_ICSELECTION_INDIRECTTI: TIM Input 4 is selected to be connected to IC3.
TIM_ICSELECTION_TRC: TIM Input 4 is selected to be connected to TRC.
TIM_ICFilter Specifies the Input Capture Filter. This parameter must be a value between 0x00 and 0x0F.
Note:
TIM_ICFilter and TIM_ICPolarity are not used in INDIRECT mode as TI4FP3 (on channel1 path) is used as the input signal. Therefore CCMR2 must be protected against un-initialized filter and polarity values.
Return values:
None
Definition at line 6493 of file stm32f1xx_hal_tim.c.
Referenced by HAL_TIM_IC_ConfigChannel().