STM32F103xG HAL User Manual: Initialization and de-initialization functions
Initialization and de-initialization functions
NAND Exported Functions
Initialization and Configuration functions.
Functions
HAL_StatusTypeDef HAL_NAND_Init (NAND_HandleTypeDef *hnand, FSMC_NAND_PCC_TimingTypeDef *ComSpace_Timing, FSMC_NAND_PCC_TimingTypeDef *AttSpace_Timing)
Perform NAND memory Initialization sequence.
HAL_StatusTypeDef HAL_NAND_DeInit (NAND_HandleTypeDef *hnand)
Perform NAND memory De-Initialization sequence.
__weak void HAL_NAND_MspInit (NAND_HandleTypeDef *hnand)
NAND MSP Init.
__weak void HAL_NAND_MspDeInit (NAND_HandleTypeDef *hnand)
NAND MSP DeInit.
void HAL_NAND_IRQHandler (NAND_HandleTypeDef *hnand)
This function handles NAND device interrupt request.
__weak void HAL_NAND_ITCallback (NAND_HandleTypeDef *hnand)
NAND interrupt feature callback.
Detailed Description
Initialization and Configuration functions.
  ==============================================================================
            ##### NAND Initialization and de-initialization functions #####
  ==============================================================================
  [..]
    This section provides functions allowing to initialize/de-initialize
    the NAND memory
Function Documentation
HAL_StatusTypeDef HAL_NAND_DeInit (NAND_HandleTypeDef * hnand)
Perform NAND memory De-Initialization sequence.
Parameters:
hnand pointer to a NAND_HandleTypeDef structure that contains the configuration information for NAND module.
Return values:
HAL status
Definition at line 211 of file stm32f1xx_hal_nand.c.
References HAL_NAND_MspDeInit().
HAL_StatusTypeDef HAL_NAND_Init (NAND_HandleTypeDef * hnand, FSMC_NAND_PCC_TimingTypeDef * ComSpace_Timing, FSMC_NAND_PCC_TimingTypeDef * AttSpace_Timing)
Perform NAND memory Initialization sequence.
Parameters:
hnand pointer to a NAND_HandleTypeDef structure that contains the configuration information for NAND module.
ComSpace_Timing pointer to Common space timing structure
AttSpace_Timing pointer to Attribute space timing structure
Return values:
HAL status
Definition at line 159 of file stm32f1xx_hal_nand.c.
References HAL_NAND_ITCallback(), and HAL_NAND_MspInit().
void HAL_NAND_IRQHandler (NAND_HandleTypeDef * hnand)
This function handles NAND device interrupt request.
Parameters:
hnand pointer to a NAND_HandleTypeDef structure that contains the configuration information for NAND module.
Return values:
HAL status
Definition at line 277 of file stm32f1xx_hal_nand.c.
References HAL_NAND_ITCallback().
__weak void HAL_NAND_ITCallback (NAND_HandleTypeDef * hnand)
NAND interrupt feature callback.
Parameters:
hnand pointer to a NAND_HandleTypeDef structure that contains the configuration information for NAND module.
Return values:
None
Definition at line 343 of file stm32f1xx_hal_nand.c.
Referenced by HAL_NAND_Init(), and HAL_NAND_IRQHandler().
__weak void HAL_NAND_MspDeInit (NAND_HandleTypeDef * hnand)
NAND MSP DeInit.
Parameters:
hnand pointer to a NAND_HandleTypeDef structure that contains the configuration information for NAND module.
Return values:
None
Definition at line 260 of file stm32f1xx_hal_nand.c.
Referenced by HAL_NAND_DeInit().
__weak void HAL_NAND_MspInit (NAND_HandleTypeDef * hnand)
NAND MSP Init.
Parameters:
hnand pointer to a NAND_HandleTypeDef structure that contains the configuration information for NAND module.
Return values:
None
Definition at line 244 of file stm32f1xx_hal_nand.c.
Referenced by HAL_NAND_Init().