STM32F103xG HAL User Manual: SD_Exported_Functions_Group1
SD_Exported_Functions_Group1
SD_Exported_Functions
Initialization and de-initialization functions.
Functions
HAL_StatusTypeDef HAL_SD_Init (SD_HandleTypeDef *hsd)
Initializes the SD according to the specified parameters in the SD_HandleTypeDef and create the associated handle.
HAL_StatusTypeDef HAL_SD_InitCard (SD_HandleTypeDef *hsd)
Initializes the SD Card.
HAL_StatusTypeDef HAL_SD_DeInit (SD_HandleTypeDef *hsd)
De-Initializes the SD card.
__weak void HAL_SD_MspInit (SD_HandleTypeDef *hsd)
Initializes the SD MSP.
__weak void HAL_SD_MspDeInit (SD_HandleTypeDef *hsd)
De-Initialize SD MSP.
Detailed Description
Initialization and de-initialization functions.
  ==============================================================================
          ##### Initialization and de-initialization functions #####
  ==============================================================================
  [..]
    This section provides functions allowing to initialize/de-initialize the SD
    card device to be ready for use.
Function Documentation
HAL_StatusTypeDef HAL_SD_DeInit (SD_HandleTypeDef * hsd)
De-Initializes the SD card.
Parameters:
hsd,: Pointer to SD handle
Return values:
HAL status
Definition at line 463 of file stm32f1xx_hal_sd.c.
References assert_param, HAL_SD_MspDeInit(), and SD_PowerOFF().
HAL_StatusTypeDef HAL_SD_Init (SD_HandleTypeDef * hsd)
Initializes the SD according to the specified parameters in the SD_HandleTypeDef and create the associated handle.
Parameters:
hsd,: Pointer to the SD handle
Return values:
HAL status
Definition at line 335 of file stm32f1xx_hal_sd.c.
References assert_param, HAL_SD_AbortCallback(), HAL_SD_ErrorCallback(), HAL_SD_InitCard(), HAL_SD_MspInit(), HAL_SD_RxCpltCallback(), and HAL_SD_TxCpltCallback().
HAL_StatusTypeDef HAL_SD_InitCard (SD_HandleTypeDef * hsd)
Initializes the SD Card.
Parameters:
hsd,: Pointer to SD handle
Note:
This function initializes the SD card. It could be used when a card re-initialization is needed.
Return values:
HAL status
Definition at line 403 of file stm32f1xx_hal_sd.c.
References SD_InitCard(), and SD_PowerON().
Referenced by HAL_SD_Init().
__weak void HAL_SD_MspDeInit (SD_HandleTypeDef * hsd)
De-Initialize SD MSP.
Parameters:
hsd,: Pointer to SD handle
Return values:
None
Definition at line 519 of file stm32f1xx_hal_sd.c.
Referenced by HAL_SD_DeInit().
__weak void HAL_SD_MspInit (SD_HandleTypeDef * hsd)
Initializes the SD MSP.
Parameters:
hsd,: Pointer to SD handle
Return values:
None
Definition at line 504 of file stm32f1xx_hal_sd.c.
Referenced by HAL_SD_Init().