STM32F103xG HAL User Manual: Initialization/de-initialization functions
Initialization/de-initialization functions
ADC Exported Functions
Initialization and Configuration functions.
Functions
HAL_StatusTypeDef HAL_ADC_Init (ADC_HandleTypeDef *hadc)
Initializes the ADC peripheral and regular group according to parameters specified in structure "ADC_InitTypeDef".
HAL_StatusTypeDef HAL_ADC_DeInit (ADC_HandleTypeDef *hadc)
Deinitialize the ADC peripheral registers to their default reset values, with deinitialization of the ADC MSP.
__weak void HAL_ADC_MspInit (ADC_HandleTypeDef *hadc)
Initializes the ADC MSP.
__weak void HAL_ADC_MspDeInit (ADC_HandleTypeDef *hadc)
DeInitializes the ADC MSP.
Detailed Description
Initialization and Configuration functions.
 ===============================================================================
              ##### Initialization and de-initialization functions #####
 ===============================================================================
    [..]  This section provides functions allowing to:
      (+) Initialize and configure the ADC.
      (+) De-initialize the ADC.
Function Documentation
HAL_StatusTypeDef HAL_ADC_DeInit (ADC_HandleTypeDef * hadc)
Deinitialize the ADC peripheral registers to their default reset values, with deinitialization of the ADC MSP.
If needed, the example code can be copied and uncommented into function HAL_ADC_MspDeInit().
Parameters:
hadc,: ADC handle
Return values:
HAL status
Definition at line 639 of file stm32f1xx_hal_adc.c.
References __HAL_ADC_CLEAR_FLAG, ADC_CLEAR_ERRORCODE, ADC_ConversionStop_Disable(), ADC_FLAG_AWD, ADC_FLAG_EOC, ADC_FLAG_JEOC, ADC_FLAG_JSTRT, ADC_FLAG_STRT, assert_param, HAL_ADC_MspDeInit(), HAL_ADC_STATE_BUSY_INTERNAL, HAL_ADC_STATE_RESET, __ADC_HandleTypeDef::Instance, and __ADC_HandleTypeDef::State.
HAL_StatusTypeDef HAL_ADC_Init (ADC_HandleTypeDef * hadc)
Initializes the ADC peripheral and regular group according to parameters specified in structure "ADC_InitTypeDef".
Note:
As prerequisite, ADC clock must be configured at RCC top level (clock source APB2). See commented example code below that can be copied and uncommented into HAL_ADC_MspInit().
Possibility to update parameters on the fly: This function initializes the ADC MSP (HAL_ADC_MspInit()) only when coming from ADC state reset. Following calls to this function can be used to reconfigure some parameters of ADC_InitTypeDef structure on the fly, without modifying MSP configuration. If ADC MSP has to be modified again, HAL_ADC_DeInit() must be called before HAL_ADC_Init(). The setting of these parameters is conditioned to ADC state. For parameters constraints, see comments of structure "ADC_InitTypeDef".
This function configures the ADC within 2 scopes: scope of entire ADC and scope of regular group. For parameters details, see comments of structure "ADC_InitTypeDef".
Parameters:
hadc,: ADC handle
Return values:
HAL status
Definition at line 421 of file stm32f1xx_hal_adc.c.
References ADC_CFGR_EXTSEL, ADC_CLEAR_ERRORCODE, ADC_ConversionStop_Disable(), ADC_CR1_DISCONTINUOUS_NUM, ADC_CR1_SCAN_SET, ADC_CR2_CONTINUOUS, ADC_SCAN_DISABLE, ADC_SCAN_ENABLE, ADC_SQR1_L_SHIFT, ADC_STATE_CLR_SET, assert_param, ADC_InitTypeDef::ContinuousConvMode, ADC_InitTypeDef::DataAlign, ADC_InitTypeDef::DiscontinuousConvMode, __ADC_HandleTypeDef::ErrorCode, ADC_InitTypeDef::ExternalTrigConv, HAL_ADC_ConvCpltCallback(), HAL_ADC_ConvHalfCpltCallback(), HAL_ADC_ERROR_INTERNAL, HAL_ADC_ErrorCallback(), HAL_ADC_LevelOutOfWindowCallback(), HAL_ADC_MspInit(), HAL_ADC_STATE_BUSY_INTERNAL, HAL_ADC_STATE_ERROR_CONFIG, HAL_ADC_STATE_ERROR_INTERNAL, HAL_ADC_STATE_INJ_BUSY, HAL_ADC_STATE_READY, HAL_ADC_STATE_REG_BUSY, HAL_ADC_STATE_RESET, HAL_ADCEx_InjectedConvCpltCallback(), __ADC_HandleTypeDef::Init, __ADC_HandleTypeDef::Instance, IS_ADC_DATA_ALIGN, IS_ADC_EXTTRIG, IS_ADC_REGULAR_DISCONT_NUMBER, IS_ADC_REGULAR_NB_CONV, IS_ADC_SCAN_MODE, __ADC_HandleTypeDef::Lock, ADC_InitTypeDef::NbrOfConversion, ADC_InitTypeDef::NbrOfDiscConversion, ADC_InitTypeDef::ScanConvMode, and __ADC_HandleTypeDef::State.
void HAL_ADC_MspDeInit (ADC_HandleTypeDef * hadc)
DeInitializes the ADC MSP.
Parameters:
hadc,: ADC handle
Return values:
None
Definition at line 801 of file stm32f1xx_hal_adc.c.
Referenced by HAL_ADC_DeInit().
void HAL_ADC_MspInit (ADC_HandleTypeDef * hadc)
Initializes the ADC MSP.
Parameters:
hadc,: ADC handle
Return values:
None
Definition at line 787 of file stm32f1xx_hal_adc.c.
Referenced by HAL_ADC_Init().