STM32F103xG HAL User Manual: Interrupts management
Interrupts management
CAN Exported Functions
Interrupts management.
Functions
HAL_StatusTypeDef HAL_CAN_ActivateNotification (CAN_HandleTypeDef *hcan, uint32_t ActiveITs)
Enable interrupts.
HAL_StatusTypeDef HAL_CAN_DeactivateNotification (CAN_HandleTypeDef *hcan, uint32_t InactiveITs)
Disable interrupts.
void HAL_CAN_IRQHandler (CAN_HandleTypeDef *hcan)
Handles CAN interrupt request.
Detailed Description
Interrupts management.
  ==============================================================================
                       ##### Interrupts management #####
  ==============================================================================
    [..]  This section provides functions allowing to:
      (+) HAL_CAN_ActivateNotification      : Enable interrupts
      (+) HAL_CAN_DeactivateNotification    : Disable interrupts
      (+) HAL_CAN_IRQHandler                : Handles CAN interrupt request
Function Documentation
HAL_StatusTypeDef HAL_CAN_ActivateNotification (CAN_HandleTypeDef * hcan, uint32_t ActiveITs)
Enable interrupts.
Parameters:
hcan pointer to an CAN_HandleTypeDef structure that contains the configuration information for the specified CAN.
ActiveITs indicates which interrupts will be enabled. This parameter can be any combination of
CAN_Interrupts.
Return values:
HAL status
Definition at line 1631 of file stm32f1xx_hal_can.c.
References __HAL_CAN_ENABLE_IT, assert_param, __CAN_HandleTypeDef::ErrorCode, HAL_CAN_ERROR_NOT_INITIALIZED, HAL_CAN_STATE_LISTENING, HAL_CAN_STATE_READY, IS_CAN_IT, and __CAN_HandleTypeDef::State.
HAL_StatusTypeDef HAL_CAN_DeactivateNotification (CAN_HandleTypeDef * hcan, uint32_t InactiveITs)
Disable interrupts.
Parameters:
hcan pointer to an CAN_HandleTypeDef structure that contains the configuration information for the specified CAN.
InactiveITs indicates which interrupts will be disabled. This parameter can be any combination of
CAN_Interrupts.
Return values:
HAL status
Definition at line 1664 of file stm32f1xx_hal_can.c.
References __HAL_CAN_DISABLE_IT, assert_param, __CAN_HandleTypeDef::ErrorCode, HAL_CAN_ERROR_NOT_INITIALIZED, HAL_CAN_STATE_LISTENING, HAL_CAN_STATE_READY, IS_CAN_IT, and __CAN_HandleTypeDef::State.
void HAL_CAN_IRQHandler (CAN_HandleTypeDef * hcan)
Handles CAN interrupt request.
Parameters:
hcan pointer to a CAN_HandleTypeDef structure that contains the configuration information for the specified CAN.
Return values:
None
Definition at line 1695 of file stm32f1xx_hal_can.c.
References __HAL_CAN_CLEAR_FLAG, CAN_FLAG_ERRI, CAN_FLAG_FF0, CAN_FLAG_FF1, CAN_FLAG_FOV0, CAN_FLAG_FOV1, CAN_FLAG_RQCP0, CAN_FLAG_RQCP1, CAN_FLAG_RQCP2, CAN_FLAG_SLAKI, CAN_FLAG_WKU, CAN_IT_BUSOFF, CAN_IT_ERROR, CAN_IT_ERROR_PASSIVE, CAN_IT_ERROR_WARNING, CAN_IT_LAST_ERROR_CODE, CAN_IT_RX_FIFO0_FULL, CAN_IT_RX_FIFO0_MSG_PENDING, CAN_IT_RX_FIFO0_OVERRUN, CAN_IT_RX_FIFO1_FULL, CAN_IT_RX_FIFO1_MSG_PENDING, CAN_IT_RX_FIFO1_OVERRUN, CAN_IT_SLEEP_ACK, CAN_IT_TX_MAILBOX_EMPTY, CAN_IT_WAKEUP, __CAN_HandleTypeDef::ErrorCode, HAL_CAN_ERROR_ACK, HAL_CAN_ERROR_BD, HAL_CAN_ERROR_BOF, HAL_CAN_ERROR_BR, HAL_CAN_ERROR_CRC, HAL_CAN_ERROR_EPV, HAL_CAN_ERROR_EWG, HAL_CAN_ERROR_FOR, HAL_CAN_ERROR_NONE, HAL_CAN_ERROR_RX_FOV0, HAL_CAN_ERROR_RX_FOV1, HAL_CAN_ERROR_STF, HAL_CAN_ERROR_TX_ALST0, HAL_CAN_ERROR_TX_ALST1, HAL_CAN_ERROR_TX_ALST2, HAL_CAN_ERROR_TX_TERR0, HAL_CAN_ERROR_TX_TERR1, HAL_CAN_ERROR_TX_TERR2, HAL_CAN_ErrorCallback(), HAL_CAN_RxFifo0FullCallback(), HAL_CAN_RxFifo0MsgPendingCallback(), HAL_CAN_RxFifo1FullCallback(), HAL_CAN_RxFifo1MsgPendingCallback(), HAL_CAN_SleepCallback(), HAL_CAN_TxMailbox0AbortCallback(), HAL_CAN_TxMailbox0CompleteCallback(), HAL_CAN_TxMailbox1AbortCallback(), HAL_CAN_TxMailbox1CompleteCallback(), HAL_CAN_TxMailbox2AbortCallback(), HAL_CAN_TxMailbox2CompleteCallback(), HAL_CAN_WakeUpFromRxMsgCallback(), and __CAN_HandleTypeDef::Instance.