STM32F103xG HAL User Manual: Input and Output functions
Input and Output functions
NAND Exported Functions
Input Output and memory control functions.
Functions
HAL_StatusTypeDef HAL_NAND_Read_ID (NAND_HandleTypeDef *hnand, NAND_IDTypeDef *pNAND_ID)
Read the NAND memory electronic signature.
HAL_StatusTypeDef HAL_NAND_Reset (NAND_HandleTypeDef *hnand)
NAND memory reset.
HAL_StatusTypeDef HAL_NAND_ConfigDevice (NAND_HandleTypeDef *hnand, NAND_DeviceConfigTypeDef *pDeviceConfig)
Configure the device: Enter the physical parameters of the device.
HAL_StatusTypeDef HAL_NAND_Read_Page_8b (NAND_HandleTypeDef *hnand, NAND_AddressTypeDef *pAddress, uint8_t *pBuffer, uint32_t NumPageToRead)
Read Page(s) from NAND memory block (8-bits addressing)
HAL_StatusTypeDef HAL_NAND_Read_Page_16b (NAND_HandleTypeDef *hnand, NAND_AddressTypeDef *pAddress, uint16_t *pBuffer, uint32_t NumPageToRead)
Read Page(s) from NAND memory block (16-bits addressing)
HAL_StatusTypeDef HAL_NAND_Write_Page_8b (NAND_HandleTypeDef *hnand, NAND_AddressTypeDef *pAddress, uint8_t *pBuffer, uint32_t NumPageToWrite)
Write Page(s) to NAND memory block (8-bits addressing)
HAL_StatusTypeDef HAL_NAND_Write_Page_16b (NAND_HandleTypeDef *hnand, NAND_AddressTypeDef *pAddress, uint16_t *pBuffer, uint32_t NumPageToWrite)
Write Page(s) to NAND memory block (16-bits addressing)
HAL_StatusTypeDef HAL_NAND_Read_SpareArea_8b (NAND_HandleTypeDef *hnand, NAND_AddressTypeDef *pAddress, uint8_t *pBuffer, uint32_t NumSpareAreaToRead)
Read Spare area(s) from NAND memory (8-bits addressing)
HAL_StatusTypeDef HAL_NAND_Read_SpareArea_16b (NAND_HandleTypeDef *hnand, NAND_AddressTypeDef *pAddress, uint16_t *pBuffer, uint32_t NumSpareAreaToRead)
Read Spare area(s) from NAND memory (16-bits addressing)
HAL_StatusTypeDef HAL_NAND_Write_SpareArea_8b (NAND_HandleTypeDef *hnand, NAND_AddressTypeDef *pAddress, uint8_t *pBuffer, uint32_t NumSpareAreaTowrite)
Write Spare area(s) to NAND memory (8-bits addressing)
HAL_StatusTypeDef HAL_NAND_Write_SpareArea_16b (NAND_HandleTypeDef *hnand, NAND_AddressTypeDef *pAddress, uint16_t *pBuffer, uint32_t NumSpareAreaTowrite)
Write Spare area(s) to NAND memory (16-bits addressing)
HAL_StatusTypeDef HAL_NAND_Erase_Block (NAND_HandleTypeDef *hnand, NAND_AddressTypeDef *pAddress)
NAND memory Block erase.
uint32_t HAL_NAND_Address_Inc (NAND_HandleTypeDef *hnand, NAND_AddressTypeDef *pAddress)
Increment the NAND memory address.
Detailed Description
Input Output and memory control functions.
  ==============================================================================
                    ##### NAND Input and Output functions #####
  ==============================================================================
  [..]
    This section provides functions allowing to use and control the NAND
    memory
Function Documentation
uint32_t HAL_NAND_Address_Inc (NAND_HandleTypeDef * hnand, NAND_AddressTypeDef * pAddress)
Increment the NAND memory address.
Parameters:
hnand pointer to a NAND_HandleTypeDef structure that contains the configuration information for NAND module.
pAddress pointer to NAND address structure
Return values:
The new status of the increment address operation. It can be:
NAND_VALID_ADDRESS: When the new address is valid address
NAND_INVALID_ADDRESS: When the new address is invalid address
Definition at line 1889 of file stm32f1xx_hal_nand.c.
HAL_StatusTypeDef HAL_NAND_ConfigDevice (NAND_HandleTypeDef * hnand, NAND_DeviceConfigTypeDef * pDeviceConfig)
Configure the device: Enter the physical parameters of the device.
Parameters:
hnand pointer to a NAND_HandleTypeDef structure that contains the configuration information for NAND module.
pDeviceConfig pointer to NAND_DeviceConfigTypeDef structure
Return values:
HAL status
Definition at line 509 of file stm32f1xx_hal_nand.c.
HAL_StatusTypeDef HAL_NAND_Erase_Block (NAND_HandleTypeDef * hnand, NAND_AddressTypeDef * pAddress)
NAND memory Block erase.
Parameters:
hnand pointer to a NAND_HandleTypeDef structure that contains the configuration information for NAND module.
pAddress pointer to NAND address structure
Return values:
HAL status
Definition at line 1826 of file stm32f1xx_hal_nand.c.
HAL_StatusTypeDef HAL_NAND_Read_ID (NAND_HandleTypeDef * hnand, NAND_IDTypeDef * pNAND_ID)
Read the NAND memory electronic signature.
Parameters:
hnand pointer to a NAND_HandleTypeDef structure that contains the configuration information for NAND module.
pNAND_ID NAND ID structure
Return values:
HAL status
Definition at line 379 of file stm32f1xx_hal_nand.c.
HAL_StatusTypeDef HAL_NAND_Read_Page_16b (NAND_HandleTypeDef * hnand, NAND_AddressTypeDef * pAddress, uint16_t * pBuffer, uint32_t NumPageToRead)
Read Page(s) from NAND memory block (16-bits addressing)
Parameters:
hnand pointer to a NAND_HandleTypeDef structure that contains the configuration information for NAND module.
pAddress pointer to NAND address structure
pBuffer pointer to destination read buffer. pBuffer should be 16bits aligned
NumPageToRead number of pages to read from block
Return values:
HAL status
Definition at line 692 of file stm32f1xx_hal_nand.c.
References HAL_GetTick(), and HAL_NAND_Read_Status().
HAL_StatusTypeDef HAL_NAND_Read_Page_8b (NAND_HandleTypeDef * hnand, NAND_AddressTypeDef * pAddress, uint8_t * pBuffer, uint32_t NumPageToRead)
Read Page(s) from NAND memory block (8-bits addressing)
Parameters:
hnand pointer to a NAND_HandleTypeDef structure that contains the configuration information for NAND module.
pAddress pointer to NAND address structure
pBuffer pointer to destination read buffer
NumPageToRead number of pages to read from block
Return values:
HAL status
Definition at line 531 of file stm32f1xx_hal_nand.c.
References HAL_GetTick(), and HAL_NAND_Read_Status().
HAL_StatusTypeDef HAL_NAND_Read_SpareArea_16b (NAND_HandleTypeDef * hnand, NAND_AddressTypeDef * pAddress, uint16_t * pBuffer, uint32_t NumSpareAreaToRead)
Read Spare area(s) from NAND memory (16-bits addressing)
Parameters:
hnand pointer to a NAND_HandleTypeDef structure that contains the configuration information for NAND module.
pAddress pointer to NAND address structure
pBuffer pointer to source buffer to write. pBuffer should be 16bits aligned.
NumSpareAreaToRead Number of spare area to read
Return values:
HAL status
Definition at line 1331 of file stm32f1xx_hal_nand.c.
References HAL_GetTick(), and HAL_NAND_Read_Status().
HAL_StatusTypeDef HAL_NAND_Read_SpareArea_8b (NAND_HandleTypeDef * hnand, NAND_AddressTypeDef * pAddress, uint8_t * pBuffer, uint32_t NumSpareAreaToRead)
Read Spare area(s) from NAND memory (8-bits addressing)
Parameters:
hnand pointer to a NAND_HandleTypeDef structure that contains the configuration information for NAND module.
pAddress pointer to NAND address structure
pBuffer pointer to source buffer to write
NumSpareAreaToRead Number of spare area to read
Return values:
HAL status
Definition at line 1164 of file stm32f1xx_hal_nand.c.
References HAL_GetTick(), and HAL_NAND_Read_Status().
HAL_StatusTypeDef HAL_NAND_Reset (NAND_HandleTypeDef * hnand)
NAND memory reset.
Parameters:
hnand pointer to a NAND_HandleTypeDef structure that contains the configuration information for NAND module.
Return values:
HAL status
Definition at line 457 of file stm32f1xx_hal_nand.c.
HAL_StatusTypeDef HAL_NAND_Write_Page_16b (NAND_HandleTypeDef * hnand, NAND_AddressTypeDef * pAddress, uint16_t * pBuffer, uint32_t NumPageToWrite)
Write Page(s) to NAND memory block (16-bits addressing)
Parameters:
hnand pointer to a NAND_HandleTypeDef structure that contains the configuration information for NAND module.
pAddress pointer to NAND address structure
pBuffer pointer to source buffer to write. pBuffer should be 16bits aligned
NumPageToWrite number of pages to write to block
Return values:
HAL status
Definition at line 1008 of file stm32f1xx_hal_nand.c.
References HAL_GetTick(), and HAL_NAND_Read_Status().
HAL_StatusTypeDef HAL_NAND_Write_Page_8b (NAND_HandleTypeDef * hnand, NAND_AddressTypeDef * pAddress, uint8_t * pBuffer, uint32_t NumPageToWrite)
Write Page(s) to NAND memory block (8-bits addressing)
Parameters:
hnand pointer to a NAND_HandleTypeDef structure that contains the configuration information for NAND module.
pAddress pointer to NAND address structure
pBuffer pointer to source buffer to write
NumPageToWrite number of pages to write to block
Return values:
HAL status
Definition at line 852 of file stm32f1xx_hal_nand.c.
References HAL_GetTick(), and HAL_NAND_Read_Status().
HAL_StatusTypeDef HAL_NAND_Write_SpareArea_16b (NAND_HandleTypeDef * hnand, NAND_AddressTypeDef * pAddress, uint16_t * pBuffer, uint32_t NumSpareAreaTowrite)
Write Spare area(s) to NAND memory (16-bits addressing)
Parameters:
hnand pointer to a NAND_HandleTypeDef structure that contains the configuration information for NAND module.
pAddress pointer to NAND address structure
pBuffer pointer to source buffer to write. pBuffer should be 16bits aligned.
NumSpareAreaTowrite number of spare areas to write to block
Return values:
HAL status
Definition at line 1663 of file stm32f1xx_hal_nand.c.
References HAL_GetTick(), and HAL_NAND_Read_Status().
HAL_StatusTypeDef HAL_NAND_Write_SpareArea_8b (NAND_HandleTypeDef * hnand, NAND_AddressTypeDef * pAddress, uint8_t * pBuffer, uint32_t NumSpareAreaTowrite)
Write Spare area(s) to NAND memory (8-bits addressing)
Parameters:
hnand pointer to a NAND_HandleTypeDef structure that contains the configuration information for NAND module.
pAddress pointer to NAND address structure
pBuffer pointer to source buffer to write
NumSpareAreaTowrite number of spare areas to write to block
Return values:
HAL status
Definition at line 1498 of file stm32f1xx_hal_nand.c.
References HAL_GetTick(), and HAL_NAND_Read_Status().