STM32F103xG HAL User Manual: Alarm functions
Alarm functions
RTC Exported Functions
RTC Alarm functions.
Functions
HAL_StatusTypeDef HAL_RTC_SetAlarm (RTC_HandleTypeDef *hrtc, RTC_AlarmTypeDef *sAlarm, uint32_t Format)
Sets the specified RTC Alarm.
HAL_StatusTypeDef HAL_RTC_SetAlarm_IT (RTC_HandleTypeDef *hrtc, RTC_AlarmTypeDef *sAlarm, uint32_t Format)
Sets the specified RTC Alarm with Interrupt.
HAL_StatusTypeDef HAL_RTC_GetAlarm (RTC_HandleTypeDef *hrtc, RTC_AlarmTypeDef *sAlarm, uint32_t Alarm, uint32_t Format)
Gets the RTC Alarm value and masks.
HAL_StatusTypeDef HAL_RTC_DeactivateAlarm (RTC_HandleTypeDef *hrtc, uint32_t Alarm)
Deactive the specified RTC Alarm.
void HAL_RTC_AlarmIRQHandler (RTC_HandleTypeDef *hrtc)
This function handles Alarm interrupt request.
__weak void HAL_RTC_AlarmAEventCallback (RTC_HandleTypeDef *hrtc)
Alarm A callback.
HAL_StatusTypeDef HAL_RTC_PollForAlarmAEvent (RTC_HandleTypeDef *hrtc, uint32_t Timeout)
This function handles AlarmA Polling request.
Detailed Description
RTC Alarm functions.
 ===============================================================================
                 ##### RTC Alarm functions #####
 ===============================================================================
 [..] This section provides functions allowing to configure Alarm feature
Function Documentation
void HAL_RTC_AlarmAEventCallback (RTC_HandleTypeDef * hrtc)
Alarm A callback.
Parameters:
hrtc pointer to a RTC_HandleTypeDef structure that contains the configuration information for RTC.
Return values:
None
Definition at line 1433 of file stm32f1xx_hal_rtc.c.
Referenced by HAL_RTC_AlarmIRQHandler(), and HAL_RTC_Init().
void HAL_RTC_AlarmIRQHandler (RTC_HandleTypeDef * hrtc)
This function handles Alarm interrupt request.
Parameters:
hrtc pointer to a RTC_HandleTypeDef structure that contains the configuration information for RTC.
Return values:
None
Definition at line 1401 of file stm32f1xx_hal_rtc.c.
References __HAL_RTC_ALARM_CLEAR_FLAG, __HAL_RTC_ALARM_EXTI_CLEAR_FLAG, __HAL_RTC_ALARM_GET_FLAG, __HAL_RTC_ALARM_GET_IT_SOURCE, HAL_RTC_AlarmAEventCallback(), HAL_RTC_STATE_READY, RTC_FLAG_ALRAF, RTC_IT_ALRA, and RTC_HandleTypeDef::State.
HAL_StatusTypeDef HAL_RTC_DeactivateAlarm (RTC_HandleTypeDef * hrtc, uint32_t Alarm)
Deactive the specified RTC Alarm.
Parameters:
hrtc pointer to a RTC_HandleTypeDef structure that contains the configuration information for RTC.
Alarm,: Specifies the Alarm. This parameter can be one of the following values:
RTC_ALARM_A: AlarmA
Return values:
HAL status
Definition at line 1331 of file stm32f1xx_hal_rtc.c.
References __HAL_RTC_ALARM_CLEAR_FLAG, __HAL_RTC_ALARM_DISABLE_IT, __HAL_RTC_ALARM_EXTI_DISABLE_IT, assert_param, HAL_RTC_STATE_BUSY, HAL_RTC_STATE_ERROR, HAL_RTC_STATE_READY, RTC_HandleTypeDef::Instance, IS_RTC_ALARM, RTC_ALARM_RESETVALUE_REGISTER, RTC_EnterInitMode(), RTC_ExitInitMode(), RTC_FLAG_ALRAF, RTC_IT_ALRA, and RTC_HandleTypeDef::State.
HAL_StatusTypeDef HAL_RTC_GetAlarm (RTC_HandleTypeDef * hrtc, RTC_AlarmTypeDef * sAlarm, uint32_t Alarm, uint32_t Format)
Gets the RTC Alarm value and masks.
Parameters:
hrtc pointer to a RTC_HandleTypeDef structure that contains the configuration information for RTC.
sAlarm,: Pointer to Date structure
Alarm,: Specifies the Alarm. This parameter can be one of the following values:
RTC_ALARM_A: Alarm
Format,: Specifies the format of the entered parameters. This parameter can be one of the following values:
RTC_FORMAT_BIN: Binary data format
RTC_FORMAT_BCD: BCD data format
Return values:
HAL status
Definition at line 1286 of file stm32f1xx_hal_rtc.c.
References RTC_AlarmTypeDef::AlarmTime, assert_param, RTC_TimeTypeDef::Hours, IS_RTC_ALARM, IS_RTC_FORMAT, RTC_TimeTypeDef::Minutes, RTC_ByteToBcd2(), RTC_FORMAT_BIN, RTC_ReadAlarmCounter(), and RTC_TimeTypeDef::Seconds.
HAL_StatusTypeDef HAL_RTC_PollForAlarmAEvent (RTC_HandleTypeDef * hrtc, uint32_t Timeout)
This function handles AlarmA Polling request.
Parameters:
hrtc pointer to a RTC_HandleTypeDef structure that contains the configuration information for RTC.
Timeout,: Timeout duration
Return values:
HAL status
Definition at line 1449 of file stm32f1xx_hal_rtc.c.
References __HAL_RTC_ALARM_CLEAR_FLAG, __HAL_RTC_ALARM_GET_FLAG, HAL_GetTick(), HAL_RTC_STATE_READY, HAL_RTC_STATE_TIMEOUT, RTC_FLAG_ALRAF, and RTC_HandleTypeDef::State.
HAL_StatusTypeDef HAL_RTC_SetAlarm (RTC_HandleTypeDef * hrtc, RTC_AlarmTypeDef * sAlarm, uint32_t Format)
Sets the specified RTC Alarm.
Parameters:
hrtc pointer to a RTC_HandleTypeDef structure that contains the configuration information for RTC.
sAlarm,: Pointer to Alarm structure
Format,: Specifies the format of the entered parameters. This parameter can be one of the following values:
RTC_FORMAT_BIN: Binary data format
RTC_FORMAT_BCD: BCD data format
Return values:
HAL status
Definition at line 1089 of file stm32f1xx_hal_rtc.c.
References RTC_AlarmTypeDef::Alarm, RTC_AlarmTypeDef::AlarmTime, assert_param, HAL_RTC_GetTime(), HAL_RTC_STATE_BUSY, HAL_RTC_STATE_ERROR, HAL_RTC_STATE_READY, RTC_TimeTypeDef::Hours, IS_RTC_ALARM, IS_RTC_FORMAT, IS_RTC_HOUR24, IS_RTC_MINUTES, IS_RTC_SECONDS, RTC_TimeTypeDef::Minutes, RTC_Bcd2ToByte(), RTC_FORMAT_BIN, RTC_WriteAlarmCounter(), RTC_TimeTypeDef::Seconds, and RTC_HandleTypeDef::State.
HAL_StatusTypeDef HAL_RTC_SetAlarm_IT (RTC_HandleTypeDef * hrtc, RTC_AlarmTypeDef * sAlarm, uint32_t Format)
Sets the specified RTC Alarm with Interrupt.
Parameters:
hrtc pointer to a RTC_HandleTypeDef structure that contains the configuration information for RTC.
sAlarm,: Pointer to Alarm structure
Format,: Specifies the format of the entered parameters. This parameter can be one of the following values:
RTC_FORMAT_BIN: Binary data format
RTC_FORMAT_BCD: BCD data format
Note:
The HAL_RTC_SetTime() must be called before enabling the Alarm feature.
Return values:
HAL status
Definition at line 1181 of file stm32f1xx_hal_rtc.c.
References __HAL_RTC_ALARM_CLEAR_FLAG, __HAL_RTC_ALARM_ENABLE_IT, __HAL_RTC_ALARM_EXTI_ENABLE_IT, __HAL_RTC_ALARM_EXTI_ENABLE_RISING_EDGE, RTC_AlarmTypeDef::Alarm, RTC_AlarmTypeDef::AlarmTime, assert_param, HAL_RTC_GetTime(), HAL_RTC_STATE_BUSY, HAL_RTC_STATE_ERROR, HAL_RTC_STATE_READY, RTC_TimeTypeDef::Hours, IS_RTC_ALARM, IS_RTC_FORMAT, IS_RTC_HOUR24, IS_RTC_MINUTES, IS_RTC_SECONDS, RTC_TimeTypeDef::Minutes, RTC_Bcd2ToByte(), RTC_FLAG_ALRAF, RTC_FORMAT_BIN, RTC_IT_ALRA, RTC_WriteAlarmCounter(), RTC_TimeTypeDef::Seconds, and RTC_HandleTypeDef::State.