STM32F103xG HAL User Manual: Initialization and de-initialization functions
Initialization and de-initialization functions
CORTEX Exported Functions
Initialization and Configuration functions.
Functions
void HAL_NVIC_SetPriorityGrouping (uint32_t PriorityGroup)
Sets the priority grouping field (preemption priority and subpriority) using the required unlock sequence.
void HAL_NVIC_SetPriority (IRQn_Type IRQn, uint32_t PreemptPriority, uint32_t SubPriority)
Sets the priority of an interrupt.
void HAL_NVIC_EnableIRQ (IRQn_Type IRQn)
Enables a device specific interrupt in the NVIC interrupt controller.
void HAL_NVIC_DisableIRQ (IRQn_Type IRQn)
Disables a device specific interrupt in the NVIC interrupt controller.
void HAL_NVIC_SystemReset (void)
Initiates a system reset request to reset the MCU.
uint32_t HAL_SYSTICK_Config (uint32_t TicksNumb)
Initializes the System Timer and its interrupt, and starts the System Tick Timer.
Detailed Description
Initialization and Configuration functions.
  ==============================================================================
              ##### Initialization and de-initialization functions #####
  ==============================================================================
    [..]
      This section provides the CORTEX HAL driver functions allowing to configure Interrupts
      Systick functionalities
Function Documentation
void HAL_NVIC_DisableIRQ (IRQn_Type IRQn)
Disables a device specific interrupt in the NVIC interrupt controller.
Parameters:
IRQn External interrupt number. This parameter can be an enumerator of IRQn_Type enumeration (For the complete STM32 Devices IRQ Channels list, please refer to the appropriate CMSIS device file (stm32f10xxx.h))
Return values:
None
Definition at line 203 of file stm32f1xx_hal_cortex.c.
References assert_param, and IS_NVIC_DEVICE_IRQ.
void HAL_NVIC_EnableIRQ (IRQn_Type IRQn)
Enables a device specific interrupt in the NVIC interrupt controller.
Note:
To configure interrupts priority correctly, the NVIC_PriorityGroupConfig() function should be called before.
Parameters:
IRQn External interrupt number. This parameter can be an enumerator of IRQn_Type enumeration (For the complete STM32 Devices IRQ Channels list, please refer to the appropriate CMSIS device file (stm32f10xxx.h))
Return values:
None
Definition at line 187 of file stm32f1xx_hal_cortex.c.
References assert_param, and IS_NVIC_DEVICE_IRQ.
void HAL_NVIC_SetPriority (IRQn_Type IRQn, uint32_t PreemptPriority, uint32_t SubPriority)
Sets the priority of an interrupt.
Parameters:
IRQn,: External interrupt number. This parameter can be an enumerator of IRQn_Type enumeration (For the complete STM32 Devices IRQ Channels list, please refer to the appropriate CMSIS device file (stm32f10xx.h))
PreemptPriority,: The preemption priority for the IRQn channel. This parameter can be a value between 0 and 15 A lower priority value indicates a higher priority
SubPriority,: the subpriority level for the IRQ channel. This parameter can be a value between 0 and 15 A lower priority value indicates a higher priority.
Return values:
None
Definition at line 165 of file stm32f1xx_hal_cortex.c.
References assert_param, IS_NVIC_PREEMPTION_PRIORITY, and IS_NVIC_SUB_PRIORITY.
Referenced by HAL_InitTick().
void HAL_NVIC_SetPriorityGrouping (uint32_t PriorityGroup)
Sets the priority grouping field (preemption priority and subpriority) using the required unlock sequence.
Parameters:
PriorityGroup,: The priority grouping bits length. This parameter can be one of the following values:
NVIC_PRIORITYGROUP_0: 0 bits for preemption priority 4 bits for subpriority
NVIC_PRIORITYGROUP_1: 1 bits for preemption priority 3 bits for subpriority
NVIC_PRIORITYGROUP_2: 2 bits for preemption priority 2 bits for subpriority
NVIC_PRIORITYGROUP_3: 3 bits for preemption priority 1 bits for subpriority
NVIC_PRIORITYGROUP_4: 4 bits for preemption priority 0 bits for subpriority
Note:
When the NVIC_PriorityGroup_0 is selected, IRQ preemption is no more possible. The pending IRQ priority will be managed only by the subpriority.
Return values:
None
Definition at line 143 of file stm32f1xx_hal_cortex.c.
References assert_param, and IS_NVIC_PRIORITY_GROUP.
Referenced by HAL_Init().
void HAL_NVIC_SystemReset (void)
Initiates a system reset request to reset the MCU.
Return values:
None
Definition at line 216 of file stm32f1xx_hal_cortex.c.
Referenced by HAL_FLASH_OB_Launch().
uint32_t HAL_SYSTICK_Config (uint32_t TicksNumb)
Initializes the System Timer and its interrupt, and starts the System Tick Timer.
Counter is in free running mode to generate periodic interrupts.
Parameters:
TicksNumb,: Specifies the ticks Number of ticks between two interrupts.
Return values:
status,: - 0 Function succeeded.
1 Function failed.
Definition at line 229 of file stm32f1xx_hal_cortex.c.
Referenced by HAL_InitTick().