STM32F103xG HAL User Manual: Interrupt Management
Interrupt Management
I2S Exported Functions
Functions
__STATIC_INLINE void LL_I2S_EnableIT_ERR (SPI_TypeDef *SPIx)
Enable error IT.
__STATIC_INLINE void LL_I2S_EnableIT_RXNE (SPI_TypeDef *SPIx)
Enable Rx buffer not empty IT.
__STATIC_INLINE void LL_I2S_EnableIT_TXE (SPI_TypeDef *SPIx)
Enable Tx buffer empty IT.
__STATIC_INLINE void LL_I2S_DisableIT_ERR (SPI_TypeDef *SPIx)
Disable error IT.
__STATIC_INLINE void LL_I2S_DisableIT_RXNE (SPI_TypeDef *SPIx)
Disable Rx buffer not empty IT.
__STATIC_INLINE void LL_I2S_DisableIT_TXE (SPI_TypeDef *SPIx)
Disable Tx buffer empty IT.
__STATIC_INLINE uint32_t LL_I2S_IsEnabledIT_ERR (SPI_TypeDef *SPIx)
Check if ERR IT is enabled.
__STATIC_INLINE uint32_t LL_I2S_IsEnabledIT_RXNE (SPI_TypeDef *SPIx)
Check if RXNE IT is enabled.
__STATIC_INLINE uint32_t LL_I2S_IsEnabledIT_TXE (SPI_TypeDef *SPIx)
Check if TXE IT is enabled.
Function Documentation
__STATIC_INLINE void LL_I2S_DisableIT_ERR (SPI_TypeDef * SPIx)
Disable error IT.
Note:
This bit controls the generation of an interrupt when an error condition occurs (OVR, UDR and FRE in I2S mode).
Reference Manual to LL API cross reference:
CR2 ERRIE LL_I2S_DisableIT_ERR
Parameters:
SPIx SPI Instance
Return values:
None
Definition at line 1733 of file stm32f1xx_ll_spi.h.
References LL_SPI_DisableIT_ERR().
__STATIC_INLINE void LL_I2S_DisableIT_RXNE (SPI_TypeDef * SPIx)
Disable Rx buffer not empty IT.
Reference Manual to LL API cross reference:
CR2 RXNEIE LL_I2S_DisableIT_RXNE
Parameters:
SPIx SPI Instance
Return values:
None
Definition at line 1744 of file stm32f1xx_ll_spi.h.
References LL_SPI_DisableIT_RXNE().
__STATIC_INLINE void LL_I2S_DisableIT_TXE (SPI_TypeDef * SPIx)
Disable Tx buffer empty IT.
Reference Manual to LL API cross reference:
CR2 TXEIE LL_I2S_DisableIT_TXE
Parameters:
SPIx SPI Instance
Return values:
None
Definition at line 1755 of file stm32f1xx_ll_spi.h.
References LL_SPI_DisableIT_TXE().
__STATIC_INLINE void LL_I2S_EnableIT_ERR (SPI_TypeDef * SPIx)
Enable error IT.
Note:
This bit controls the generation of an interrupt when an error condition occurs (OVR, UDR and FRE in I2S mode).
Reference Manual to LL API cross reference:
CR2 ERRIE LL_I2S_EnableIT_ERR
Parameters:
SPIx SPI Instance
Return values:
None
Definition at line 1699 of file stm32f1xx_ll_spi.h.
References LL_SPI_EnableIT_ERR().
__STATIC_INLINE void LL_I2S_EnableIT_RXNE (SPI_TypeDef * SPIx)
Enable Rx buffer not empty IT.
Reference Manual to LL API cross reference:
CR2 RXNEIE LL_I2S_EnableIT_RXNE
Parameters:
SPIx SPI Instance
Return values:
None
Definition at line 1710 of file stm32f1xx_ll_spi.h.
References LL_SPI_EnableIT_RXNE().
__STATIC_INLINE void LL_I2S_EnableIT_TXE (SPI_TypeDef * SPIx)
Enable Tx buffer empty IT.
Reference Manual to LL API cross reference:
CR2 TXEIE LL_I2S_EnableIT_TXE
Parameters:
SPIx SPI Instance
Return values:
None
Definition at line 1721 of file stm32f1xx_ll_spi.h.
References LL_SPI_EnableIT_TXE().
__STATIC_INLINE uint32_t LL_I2S_IsEnabledIT_ERR (SPI_TypeDef * SPIx)
Check if ERR IT is enabled.
Reference Manual to LL API cross reference:
CR2 ERRIE LL_I2S_IsEnabledIT_ERR
Parameters:
SPIx SPI Instance
Return values:
State of bit (1 or 0).
Definition at line 1766 of file stm32f1xx_ll_spi.h.
References LL_SPI_IsEnabledIT_ERR().
__STATIC_INLINE uint32_t LL_I2S_IsEnabledIT_RXNE (SPI_TypeDef * SPIx)
Check if RXNE IT is enabled.
Reference Manual to LL API cross reference:
CR2 RXNEIE LL_I2S_IsEnabledIT_RXNE
Parameters:
SPIx SPI Instance
Return values:
State of bit (1 or 0).
Definition at line 1777 of file stm32f1xx_ll_spi.h.
References LL_SPI_IsEnabledIT_RXNE().
__STATIC_INLINE uint32_t LL_I2S_IsEnabledIT_TXE (SPI_TypeDef * SPIx)
Check if TXE IT is enabled.
Reference Manual to LL API cross reference:
CR2 TXEIE LL_I2S_IsEnabledIT_TXE
Parameters:
SPIx SPI Instance
Return values:
State of bit (1 or 0).
Definition at line 1788 of file stm32f1xx_ll_spi.h.
References LL_SPI_IsEnabledIT_TXE().