STM32F103xG HAL User Manual: DMA Management
DMA Management
I2S Exported Functions
Functions
__STATIC_INLINE void LL_I2S_EnableDMAReq_RX (SPI_TypeDef *SPIx)
Enable DMA Rx.
__STATIC_INLINE void LL_I2S_DisableDMAReq_RX (SPI_TypeDef *SPIx)
Disable DMA Rx.
__STATIC_INLINE uint32_t LL_I2S_IsEnabledDMAReq_RX (SPI_TypeDef *SPIx)
Check if DMA Rx is enabled.
__STATIC_INLINE void LL_I2S_EnableDMAReq_TX (SPI_TypeDef *SPIx)
Enable DMA Tx.
__STATIC_INLINE void LL_I2S_DisableDMAReq_TX (SPI_TypeDef *SPIx)
Disable DMA Tx.
__STATIC_INLINE uint32_t LL_I2S_IsEnabledDMAReq_TX (SPI_TypeDef *SPIx)
Check if DMA Tx is enabled.
Function Documentation
__STATIC_INLINE void LL_I2S_DisableDMAReq_RX (SPI_TypeDef * SPIx)
Disable DMA Rx.
Reference Manual to LL API cross reference:
CR2 RXDMAEN LL_I2S_DisableDMAReq_RX
Parameters:
SPIx SPI Instance
Return values:
None
Definition at line 1818 of file stm32f1xx_ll_spi.h.
References LL_SPI_DisableDMAReq_RX().
__STATIC_INLINE void LL_I2S_DisableDMAReq_TX (SPI_TypeDef * SPIx)
Disable DMA Tx.
Reference Manual to LL API cross reference:
CR2 TXDMAEN LL_I2S_DisableDMAReq_TX
Parameters:
SPIx SPI Instance
Return values:
None
Definition at line 1851 of file stm32f1xx_ll_spi.h.
References LL_SPI_DisableDMAReq_TX().
__STATIC_INLINE void LL_I2S_EnableDMAReq_RX (SPI_TypeDef * SPIx)
Enable DMA Rx.
Reference Manual to LL API cross reference:
CR2 RXDMAEN LL_I2S_EnableDMAReq_RX
Parameters:
SPIx SPI Instance
Return values:
None
Definition at line 1807 of file stm32f1xx_ll_spi.h.
References LL_SPI_EnableDMAReq_RX().
__STATIC_INLINE void LL_I2S_EnableDMAReq_TX (SPI_TypeDef * SPIx)
Enable DMA Tx.
Reference Manual to LL API cross reference:
CR2 TXDMAEN LL_I2S_EnableDMAReq_TX
Parameters:
SPIx SPI Instance
Return values:
None
Definition at line 1840 of file stm32f1xx_ll_spi.h.
References LL_SPI_EnableDMAReq_TX().
__STATIC_INLINE uint32_t LL_I2S_IsEnabledDMAReq_RX (SPI_TypeDef * SPIx)
Check if DMA Rx is enabled.
Reference Manual to LL API cross reference:
CR2 RXDMAEN LL_I2S_IsEnabledDMAReq_RX
Parameters:
SPIx SPI Instance
Return values:
State of bit (1 or 0).
Definition at line 1829 of file stm32f1xx_ll_spi.h.
References LL_SPI_IsEnabledDMAReq_RX().
__STATIC_INLINE uint32_t LL_I2S_IsEnabledDMAReq_TX (SPI_TypeDef * SPIx)
Check if DMA Tx is enabled.
Reference Manual to LL API cross reference:
CR2 TXDMAEN LL_I2S_IsEnabledDMAReq_TX
Parameters:
SPIx SPI Instance
Return values:
State of bit (1 or 0).
Definition at line 1862 of file stm32f1xx_ll_spi.h.
References LL_SPI_IsEnabledDMAReq_TX().