STM32F103xG HAL User Manual: Initialization and de-initialization functions
Initialization and de-initialization functions
EXTI Exported Functions
Functions
uint32_t LL_EXTI_DeInit (void)
De-initialize the EXTI registers to their default reset values.
uint32_t LL_EXTI_Init (LL_EXTI_InitTypeDef *EXTI_InitStruct)
Initialize the EXTI registers according to the specified parameters in EXTI_InitStruct.
void LL_EXTI_StructInit (LL_EXTI_InitTypeDef *EXTI_InitStruct)
Set each LL_EXTI_InitTypeDef field to default value.
Function Documentation
uint32_t LL_EXTI_DeInit (void)
De-initialize the EXTI registers to their default reset values.
Return values:
An ErrorStatus enumeration value:
SUCCESS: EXTI registers are de-initialized
ERROR: not applicable
Definition at line 81 of file stm32f1xx_ll_exti.c.
References LL_EXTI_WriteReg.
uint32_t LL_EXTI_Init (LL_EXTI_InitTypeDef * EXTI_InitStruct)
Initialize the EXTI registers according to the specified parameters in EXTI_InitStruct.
Parameters:
EXTI_InitStruct pointer to a LL_EXTI_InitTypeDef structure.
Return values:
An ErrorStatus enumeration value:
SUCCESS: EXTI registers are initialized
ERROR: not applicable
Definition at line 106 of file stm32f1xx_ll_exti.c.
References assert_param, IS_LL_EXTI_LINE_0_31, IS_LL_EXTI_MODE, IS_LL_EXTI_TRIGGER, LL_EXTI_InitTypeDef::Line_0_31, LL_EXTI_InitTypeDef::LineCommand, LL_EXTI_DisableEvent_0_31(), LL_EXTI_DisableFallingTrig_0_31(), LL_EXTI_DisableIT_0_31(), LL_EXTI_DisableRisingTrig_0_31(), LL_EXTI_EnableEvent_0_31(), LL_EXTI_EnableFallingTrig_0_31(), LL_EXTI_EnableIT_0_31(), LL_EXTI_EnableRisingTrig_0_31(), LL_EXTI_LINE_NONE, LL_EXTI_MODE_EVENT, LL_EXTI_MODE_IT, LL_EXTI_MODE_IT_EVENT, LL_EXTI_TRIGGER_FALLING, LL_EXTI_TRIGGER_NONE, LL_EXTI_TRIGGER_RISING, LL_EXTI_TRIGGER_RISING_FALLING, LL_EXTI_InitTypeDef::Mode, and LL_EXTI_InitTypeDef::Trigger.
void LL_EXTI_StructInit (LL_EXTI_InitTypeDef * EXTI_InitStruct)
Set each LL_EXTI_InitTypeDef field to default value.
Parameters:
EXTI_InitStruct Pointer to a LL_EXTI_InitTypeDef structure.
Return values:
None
Definition at line 187 of file stm32f1xx_ll_exti.c.
References LL_EXTI_InitTypeDef::Line_0_31, LL_EXTI_InitTypeDef::LineCommand, LL_EXTI_LINE_NONE, LL_EXTI_MODE_IT, LL_EXTI_TRIGGER_FALLING, LL_EXTI_InitTypeDef::Mode, and LL_EXTI_InitTypeDef::Trigger.