STM32F103xG HAL User Manual: IRDA Private Functions
IRDA Private Functions
IRDA
Functions
static void IRDA_SetConfig (IRDA_HandleTypeDef *hirda)
Configures the IRDA peripheral.
static HAL_StatusTypeDef IRDA_Transmit_IT (IRDA_HandleTypeDef *hirda)
Send an amount of data in non blocking mode.
static HAL_StatusTypeDef IRDA_EndTransmit_IT (IRDA_HandleTypeDef *hirda)
Wraps up transmission in non blocking mode.
static HAL_StatusTypeDef IRDA_Receive_IT (IRDA_HandleTypeDef *hirda)
Receives an amount of data in non blocking mode.
static void IRDA_DMATransmitCplt (DMA_HandleTypeDef *hdma)
DMA IRDA transmit process complete callback.
static void IRDA_DMATransmitHalfCplt (DMA_HandleTypeDef *hdma)
DMA IRDA receive process half complete callback.
static void IRDA_DMAReceiveCplt (DMA_HandleTypeDef *hdma)
DMA IRDA receive process complete callback.
static void IRDA_DMAReceiveHalfCplt (DMA_HandleTypeDef *hdma)
DMA IRDA receive process half complete callback.
static void IRDA_DMAError (DMA_HandleTypeDef *hdma)
DMA IRDA communication error callback.
static void IRDA_DMAAbortOnError (DMA_HandleTypeDef *hdma)
DMA IRDA communication abort callback, when initiated by HAL services on Error (To be called at end of DMA Abort procedure following error occurrence).
static void IRDA_DMATxAbortCallback (DMA_HandleTypeDef *hdma)
DMA IRDA Tx communication abort callback, when initiated by user (To be called at end of DMA Tx Abort procedure following user abort request).
static void IRDA_DMARxAbortCallback (DMA_HandleTypeDef *hdma)
DMA IRDA Rx communication abort callback, when initiated by user (To be called at end of DMA Rx Abort procedure following user abort request).
static void IRDA_DMATxOnlyAbortCallback (DMA_HandleTypeDef *hdma)
DMA IRDA Tx communication abort callback, when initiated by user by a call to HAL_IRDA_AbortTransmit_IT API (Abort only Tx transfer) (This callback is executed at end of DMA Tx Abort procedure following user abort request, and leads to user Tx Abort Complete callback execution).
static void IRDA_DMARxOnlyAbortCallback (DMA_HandleTypeDef *hdma)
DMA IRDA Rx communication abort callback, when initiated by user by a call to HAL_IRDA_AbortReceive_IT API (Abort only Rx transfer) (This callback is executed at end of DMA Rx Abort procedure following user abort request, and leads to user Rx Abort Complete callback execution).
static HAL_StatusTypeDef IRDA_WaitOnFlagUntilTimeout (IRDA_HandleTypeDef *hirda, uint32_t Flag, FlagStatus Status, uint32_t Tickstart, uint32_t Timeout)
This function handles IRDA Communication Timeout.
static void IRDA_EndTxTransfer (IRDA_HandleTypeDef *hirda)
End ongoing Tx transfer on IRDA peripheral (following error detection or Transmit completion).
static void IRDA_EndRxTransfer (IRDA_HandleTypeDef *hirda)
End ongoing Rx transfer on IRDA peripheral (following error detection or Reception completion).
Function Documentation
static void IRDA_DMAAbortOnError (DMA_HandleTypeDef * hdma) [static]
DMA IRDA communication abort callback, when initiated by HAL services on Error (To be called at end of DMA Abort procedure following error occurrence).
Parameters:
hdma DMA handle.
Return values:
None
Definition at line 2271 of file stm32f1xx_hal_irda.c.
References HAL_IRDA_ErrorCallback(), IRDA_HandleTypeDef::RxXferCount, and IRDA_HandleTypeDef::TxXferCount.
Referenced by HAL_IRDA_IRQHandler().
static void IRDA_DMAError (DMA_HandleTypeDef * hdma) [static]
DMA IRDA communication error callback.
Parameters:
hdma Pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA.
Return values:
None
Definition at line 2167 of file stm32f1xx_hal_irda.c.
References IRDA_HandleTypeDef::ErrorCode, IRDA_HandleTypeDef::gState, HAL_IRDA_ERROR_DMA, HAL_IRDA_ErrorCallback(), HAL_IRDA_STATE_BUSY_RX, HAL_IRDA_STATE_BUSY_TX, IRDA_HandleTypeDef::Instance, IRDA_EndRxTransfer(), IRDA_EndTxTransfer(), IRDA_HandleTypeDef::RxState, IRDA_HandleTypeDef::RxXferCount, and IRDA_HandleTypeDef::TxXferCount.
Referenced by HAL_IRDA_Receive_DMA(), and HAL_IRDA_Transmit_DMA().
static void IRDA_DMAReceiveCplt (DMA_HandleTypeDef * hdma) [static]
DMA IRDA receive process complete callback.
Parameters:
hdma Pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA.
Return values:
None
Definition at line 2112 of file stm32f1xx_hal_irda.c.
References HAL_IRDA_RxCpltCallback(), HAL_IRDA_STATE_READY, __DMA_HandleTypeDef::Instance, IRDA_HandleTypeDef::Instance, IRDA_HandleTypeDef::RxState, and IRDA_HandleTypeDef::RxXferCount.
Referenced by HAL_IRDA_Receive_DMA().
static void IRDA_DMAReceiveHalfCplt (DMA_HandleTypeDef * hdma) [static]
DMA IRDA receive process half complete callback.
Parameters:
hdma Pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA.
Return values:
None
Definition at line 2148 of file stm32f1xx_hal_irda.c.
References HAL_IRDA_RxHalfCpltCallback().
Referenced by HAL_IRDA_Receive_DMA().
static void IRDA_DMARxAbortCallback (DMA_HandleTypeDef * hdma) [static]
DMA IRDA Rx communication abort callback, when initiated by user (To be called at end of DMA Rx Abort procedure following user abort request).
Note:
When this callback is executed, User Abort complete call back is called only if no Abort still ongoing for Tx DMA Handle.
Parameters:
hdma DMA handle.
Return values:
None
Definition at line 2338 of file stm32f1xx_hal_irda.c.
References IRDA_HandleTypeDef::ErrorCode, IRDA_HandleTypeDef::gState, HAL_IRDA_AbortCpltCallback(), HAL_IRDA_ERROR_NONE, HAL_IRDA_STATE_READY, IRDA_HandleTypeDef::hdmarx, IRDA_HandleTypeDef::hdmatx, IRDA_HandleTypeDef::RxState, IRDA_HandleTypeDef::RxXferCount, IRDA_HandleTypeDef::TxXferCount, and __DMA_HandleTypeDef::XferAbortCallback.
Referenced by HAL_IRDA_Abort_IT().
static void IRDA_DMARxOnlyAbortCallback (DMA_HandleTypeDef * hdma) [static]
DMA IRDA Rx communication abort callback, when initiated by user by a call to HAL_IRDA_AbortReceive_IT API (Abort only Rx transfer) (This callback is executed at end of DMA Rx Abort procedure following user abort request, and leads to user Rx Abort Complete callback execution).
Parameters:
hdma DMA handle.
Return values:
None
Definition at line 2409 of file stm32f1xx_hal_irda.c.
References HAL_IRDA_AbortReceiveCpltCallback(), HAL_IRDA_STATE_READY, IRDA_HandleTypeDef::RxState, and IRDA_HandleTypeDef::RxXferCount.
Referenced by HAL_IRDA_AbortReceive_IT().
static void IRDA_DMATransmitCplt (DMA_HandleTypeDef * hdma) [static]
DMA IRDA transmit process complete callback.
Parameters:
hdma Pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA.
Return values:
None
Definition at line 2059 of file stm32f1xx_hal_irda.c.
References HAL_IRDA_TxCpltCallback(), __DMA_HandleTypeDef::Instance, IRDA_HandleTypeDef::Instance, and IRDA_HandleTypeDef::TxXferCount.
Referenced by HAL_IRDA_Transmit_DMA().
static void IRDA_DMATransmitHalfCplt (DMA_HandleTypeDef * hdma) [static]
DMA IRDA receive process half complete callback.
Parameters:
hdma Pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA.
Return values:
None
Definition at line 2093 of file stm32f1xx_hal_irda.c.
References HAL_IRDA_TxHalfCpltCallback().
Referenced by HAL_IRDA_Transmit_DMA().
static void IRDA_DMATxAbortCallback (DMA_HandleTypeDef * hdma) [static]
DMA IRDA Tx communication abort callback, when initiated by user (To be called at end of DMA Tx Abort procedure following user abort request).
Note:
When this callback is executed, User Abort complete call back is called only if no Abort still ongoing for Rx DMA Handle.
Parameters:
hdma DMA handle.
Return values:
None
Definition at line 2294 of file stm32f1xx_hal_irda.c.
References IRDA_HandleTypeDef::ErrorCode, IRDA_HandleTypeDef::gState, HAL_IRDA_AbortCpltCallback(), HAL_IRDA_ERROR_NONE, HAL_IRDA_STATE_READY, IRDA_HandleTypeDef::hdmarx, IRDA_HandleTypeDef::hdmatx, IRDA_HandleTypeDef::RxState, IRDA_HandleTypeDef::RxXferCount, IRDA_HandleTypeDef::TxXferCount, and __DMA_HandleTypeDef::XferAbortCallback.
Referenced by HAL_IRDA_Abort_IT().
static void IRDA_DMATxOnlyAbortCallback (DMA_HandleTypeDef * hdma) [static]
DMA IRDA Tx communication abort callback, when initiated by user by a call to HAL_IRDA_AbortTransmit_IT API (Abort only Tx transfer) (This callback is executed at end of DMA Tx Abort procedure following user abort request, and leads to user Tx Abort Complete callback execution).
Parameters:
hdma DMA handle.
Return values:
None
Definition at line 2382 of file stm32f1xx_hal_irda.c.
References IRDA_HandleTypeDef::gState, HAL_IRDA_AbortTransmitCpltCallback(), HAL_IRDA_STATE_READY, and IRDA_HandleTypeDef::TxXferCount.
Referenced by HAL_IRDA_AbortTransmit_IT().
static void IRDA_EndRxTransfer (IRDA_HandleTypeDef * hirda) [static]
End ongoing Rx transfer on IRDA peripheral (following error detection or Reception completion).
Parameters:
hirda IRDA handle.
Return values:
None
Definition at line 2255 of file stm32f1xx_hal_irda.c.
References HAL_IRDA_STATE_READY, IRDA_HandleTypeDef::Instance, and IRDA_HandleTypeDef::RxState.
Referenced by HAL_IRDA_DMAStop(), HAL_IRDA_IRQHandler(), and IRDA_DMAError().
static HAL_StatusTypeDef IRDA_EndTransmit_IT (IRDA_HandleTypeDef * hirda) [static]
Wraps up transmission in non blocking mode.
Parameters:
hirda Pointer to a IRDA_HandleTypeDef structure that contains the configuration information for the specified IRDA module.
Return values:
HAL status
Definition at line 2482 of file stm32f1xx_hal_irda.c.
References IRDA_HandleTypeDef::gState, HAL_IRDA_STATE_READY, HAL_IRDA_TxCpltCallback(), and IRDA_HandleTypeDef::Instance.
Referenced by HAL_IRDA_IRQHandler().
static void IRDA_EndTxTransfer (IRDA_HandleTypeDef * hirda) [static]
End ongoing Tx transfer on IRDA peripheral (following error detection or Transmit completion).
Parameters:
hirda IRDA handle.
Return values:
None
Definition at line 2241 of file stm32f1xx_hal_irda.c.
References IRDA_HandleTypeDef::gState, HAL_IRDA_STATE_READY, and IRDA_HandleTypeDef::Instance.
Referenced by HAL_IRDA_DMAStop(), and IRDA_DMAError().
static HAL_StatusTypeDef IRDA_Receive_IT (IRDA_HandleTypeDef * hirda) [static]
Receives an amount of data in non blocking mode.
Parameters:
hirda Pointer to a IRDA_HandleTypeDef structure that contains the configuration information for the specified IRDA module.
Return values:
HAL status
Definition at line 2510 of file stm32f1xx_hal_irda.c.
References HAL_IRDA_RxCpltCallback(), HAL_IRDA_STATE_BUSY_RX, HAL_IRDA_STATE_READY, IRDA_HandleTypeDef::Init, IRDA_HandleTypeDef::Instance, IRDA_PARITY_NONE, IRDA_WORDLENGTH_9B, IRDA_InitTypeDef::Parity, IRDA_HandleTypeDef::pRxBuffPtr, IRDA_HandleTypeDef::RxState, IRDA_HandleTypeDef::RxXferCount, and IRDA_InitTypeDef::WordLength.
Referenced by HAL_IRDA_IRQHandler().
static void IRDA_SetConfig (IRDA_HandleTypeDef * hirda) [static]
Configures the IRDA peripheral.
Parameters:
hirda Pointer to a IRDA_HandleTypeDef structure that contains the configuration information for the specified IRDA module.
Return values:
None
Definition at line 2583 of file stm32f1xx_hal_irda.c.
References assert_param, IRDA_InitTypeDef::BaudRate, HAL_RCC_GetPCLK1Freq(), HAL_RCC_GetPCLK2Freq(), IRDA_HandleTypeDef::Init, IRDA_HandleTypeDef::Instance, IRDA_BRR, IRDA_InitTypeDef::IrDAMode, IS_IRDA_BAUDRATE, IS_IRDA_MODE, IS_IRDA_PARITY, IS_IRDA_POWERMODE, IS_IRDA_WORD_LENGTH, IRDA_InitTypeDef::Mode, IRDA_InitTypeDef::Parity, and IRDA_InitTypeDef::WordLength.
Referenced by HAL_IRDA_Init().
static HAL_StatusTypeDef IRDA_Transmit_IT (IRDA_HandleTypeDef * hirda) [static]
Send an amount of data in non blocking mode.
Parameters:
hirda Pointer to a IRDA_HandleTypeDef structure that contains the configuration information for the specified IRDA module.
Return values:
HAL status
Definition at line 2434 of file stm32f1xx_hal_irda.c.
References IRDA_HandleTypeDef::gState, HAL_IRDA_STATE_BUSY_TX, IRDA_HandleTypeDef::Init, IRDA_HandleTypeDef::Instance, IRDA_PARITY_NONE, IRDA_WORDLENGTH_9B, IRDA_InitTypeDef::Parity, IRDA_HandleTypeDef::pTxBuffPtr, IRDA_HandleTypeDef::TxXferCount, and IRDA_InitTypeDef::WordLength.
Referenced by HAL_IRDA_IRQHandler().
static HAL_StatusTypeDef IRDA_WaitOnFlagUntilTimeout (IRDA_HandleTypeDef * hirda, uint32_t Flag, FlagStatus Status, uint32_t Tickstart, uint32_t Timeout) [static]
This function handles IRDA Communication Timeout.
Parameters:
hirda Pointer to a IRDA_HandleTypeDef structure that contains the configuration information for the specified IRDA.
Flag specifies the IRDA flag to check.
Status The new Flag status (SET or RESET).
Tickstart Tick start value
Timeout Timeout duration
Return values:
HAL status
Definition at line 2209 of file stm32f1xx_hal_irda.c.
References __HAL_IRDA_GET_FLAG, IRDA_HandleTypeDef::gState, HAL_GetTick(), HAL_IRDA_STATE_READY, IRDA_HandleTypeDef::Instance, and IRDA_HandleTypeDef::RxState.
Referenced by HAL_IRDA_Receive(), and HAL_IRDA_Transmit().