STM32F103xG HAL User Manual: Initialization and de-initialization functions
Initialization and de-initialization functions
DAC | DAC Exported Functions
Functions
ErrorStatus LL_DAC_DeInit (DAC_TypeDef *DACx)
De-initialize registers of the selected DAC instance to their default reset values.
ErrorStatus LL_DAC_Init (DAC_TypeDef *DACx, uint32_t DAC_Channel, LL_DAC_InitTypeDef *DAC_InitStruct)
Initialize some features of DAC channel.
void LL_DAC_StructInit (LL_DAC_InitTypeDef *DAC_InitStruct)
Set each LL_DAC_InitTypeDef field to default value.
Function Documentation
ErrorStatus LL_DAC_DeInit (DAC_TypeDef * DACx)
De-initialize registers of the selected DAC instance to their default reset values.
Parameters:
DACx DAC instance
Return values:
An ErrorStatus enumeration value:
SUCCESS: DAC registers are de-initialized
ERROR: not applicable
Definition at line 134 of file stm32f1xx_ll_dac.c.
References assert_param, LL_APB1_GRP1_ForceReset(), LL_APB1_GRP1_PERIPH_DAC1, and LL_APB1_GRP1_ReleaseReset().
ErrorStatus LL_DAC_Init (DAC_TypeDef * DACx, uint32_t DAC_Channel, LL_DAC_InitTypeDef * DAC_InitStruct)
Initialize some features of DAC channel.
Note:
LL_DAC_Init() aims to ease basic configuration of a DAC channel. Leaving it ready to be enabled and output: a level by calling one of LL_DAC_ConvertData12RightAligned LL_DAC_ConvertData12LeftAligned LL_DAC_ConvertData8RightAligned or one of the supported autogenerated wave.
This function allows configuration of:
Output mode
Trigger
Wave generation
The setting of these parameters by function LL_DAC_Init() is conditioned to DAC state: DAC channel must be disabled.
Parameters:
DACx DAC instance
DAC_Channel This parameter can be one of the following values:
LL_DAC_CHANNEL_1
LL_DAC_CHANNEL_2
DAC_InitStruct Pointer to a LL_DAC_InitTypeDef structure
Return values:
An ErrorStatus enumeration value:
SUCCESS: DAC registers are initialized
ERROR: DAC registers are not initialized
Definition at line 173 of file stm32f1xx_ll_dac.c.
References assert_param, DAC_CR_CHX_BITOFFSET_MASK, IS_LL_DAC_CHANNEL, IS_LL_DAC_OUTPUT_BUFFER, IS_LL_DAC_TRIGGER_SOURCE, IS_LL_DAC_WAVE_AUTO_GENER_CONFIG, IS_LL_DAC_WAVE_AUTO_GENER_MODE, LL_DAC_IsEnabled(), LL_DAC_WAVE_AUTO_GENERATION_NONE, LL_DAC_InitTypeDef::OutputBuffer, LL_DAC_InitTypeDef::TriggerSource, LL_DAC_InitTypeDef::WaveAutoGeneration, and LL_DAC_InitTypeDef::WaveAutoGenerationConfig.
void LL_DAC_StructInit (LL_DAC_InitTypeDef * DAC_InitStruct)
Set each LL_DAC_InitTypeDef field to default value.
Parameters:
DAC_InitStruct pointer to a LL_DAC_InitTypeDef structure whose fields will be set to default values.
Return values:
None
Definition at line 243 of file stm32f1xx_ll_dac.c.
References LL_DAC_NOISE_LFSR_UNMASK_BIT0, LL_DAC_OUTPUT_BUFFER_ENABLE, LL_DAC_TRIG_SOFTWARE, LL_DAC_WAVE_AUTO_GENERATION_NONE, LL_DAC_InitTypeDef::OutputBuffer, LL_DAC_InitTypeDef::TriggerSource, LL_DAC_InitTypeDef::WaveAutoGeneration, and LL_DAC_InitTypeDef::WaveAutoGenerationConfig.