STM32F103xG HAL User Manual: Input and Output functions
Input and Output functions
PCCARD Exported Functions
Input Output and memory control functions.
Functions
HAL_StatusTypeDef HAL_PCCARD_Read_ID (PCCARD_HandleTypeDef *hpccard, uint8_t CompactFlash_ID[], uint8_t *pStatus)
Read Compact Flash's ID.
HAL_StatusTypeDef HAL_PCCARD_Read_Sector (PCCARD_HandleTypeDef *hpccard, uint16_t *pBuffer, uint16_t SectorAddress, uint8_t *pStatus)
Read sector from PCCARD memory.
HAL_StatusTypeDef HAL_PCCARD_Write_Sector (PCCARD_HandleTypeDef *hpccard, uint16_t *pBuffer, uint16_t SectorAddress, uint8_t *pStatus)
Write sector to PCCARD memory.
HAL_StatusTypeDef HAL_PCCARD_Erase_Sector (PCCARD_HandleTypeDef *hpccard, uint16_t SectorAddress, uint8_t *pStatus)
Erase sector from PCCARD memory.
HAL_StatusTypeDef HAL_PCCARD_Reset (PCCARD_HandleTypeDef *hpccard)
Reset the PCCARD memory.
void HAL_PCCARD_IRQHandler (PCCARD_HandleTypeDef *hpccard)
This function handles PCCARD device interrupt request.
__weak void HAL_PCCARD_ITCallback (PCCARD_HandleTypeDef *hpccard)
PCCARD interrupt feature callback.
Detailed Description
Input Output and memory control functions.
  ==============================================================================
                    ##### PCCARD Input and Output functions #####
  ==============================================================================
  [..]
    This section provides functions allowing to use and control the PCCARD memory
Function Documentation
HAL_StatusTypeDef HAL_PCCARD_Erase_Sector (PCCARD_HandleTypeDef * hpccard, uint16_t SectorAddress, uint8_t * pStatus)
Erase sector from PCCARD memory.
Parameters:
hpccard pointer to a PCCARD_HandleTypeDef structure that contains the configuration information for PCCARD module.
SectorAddress Sector address to erase
pStatus pointer to PCCARD status
Return values:
HAL status
Definition at line 524 of file stm32f1xx_hal_pccard.c.
References PCCARD_STATUS_WRITE_OK, and PCCARD_TIMEOUT_ERASE_SECTOR.
void HAL_PCCARD_IRQHandler (PCCARD_HandleTypeDef * hpccard)
This function handles PCCARD device interrupt request.
Parameters:
hpccard pointer to a PCCARD_HandleTypeDef structure that contains the configuration information for PCCARD module.
Return values:
HAL status
Definition at line 619 of file stm32f1xx_hal_pccard.c.
References HAL_PCCARD_ITCallback().
__weak void HAL_PCCARD_ITCallback (PCCARD_HandleTypeDef * hpccard)
PCCARD interrupt feature callback.
Parameters:
hpccard pointer to a PCCARD_HandleTypeDef structure that contains the configuration information for PCCARD module.
Return values:
None
Definition at line 684 of file stm32f1xx_hal_pccard.c.
Referenced by HAL_PCCARD_Init(), and HAL_PCCARD_IRQHandler().
HAL_StatusTypeDef HAL_PCCARD_Read_ID (PCCARD_HandleTypeDef * hpccard, uint8_t CompactFlash_ID[], uint8_t * pStatus)
Read Compact Flash's ID.
Parameters:
hpccard pointer to a PCCARD_HandleTypeDef structure that contains the configuration information for PCCARD module.
CompactFlash_ID Compact flash ID structure.
pStatus pointer to compact flash status
Return values:
HAL status
Definition at line 307 of file stm32f1xx_hal_pccard.c.
References PCCARD_STATUS_OK, and PCCARD_TIMEOUT_READ_ID.
HAL_StatusTypeDef HAL_PCCARD_Read_Sector (PCCARD_HandleTypeDef * hpccard, uint16_t * pBuffer, uint16_t SectorAddress, uint8_t * pStatus)
Read sector from PCCARD memory.
Parameters:
hpccard pointer to a PCCARD_HandleTypeDef structure that contains the configuration information for PCCARD module.
pBuffer pointer to destination read buffer
SectorAddress Sector address to read
pStatus pointer to PCCARD status
Return values:
HAL status
Definition at line 371 of file stm32f1xx_hal_pccard.c.
References PCCARD_STATUS_OK, and PCCARD_TIMEOUT_READ_WRITE_SECTOR.
HAL_StatusTypeDef HAL_PCCARD_Reset (PCCARD_HandleTypeDef * hpccard)
Reset the PCCARD memory.
Parameters:
hpccard pointer to a PCCARD_HandleTypeDef structure that contains the configuration information for PCCARD module.
Return values:
HAL status
Definition at line 581 of file stm32f1xx_hal_pccard.c.
HAL_StatusTypeDef HAL_PCCARD_Write_Sector (PCCARD_HandleTypeDef * hpccard, uint16_t * pBuffer, uint16_t SectorAddress, uint8_t * pStatus)
Write sector to PCCARD memory.
Parameters:
hpccard pointer to a PCCARD_HandleTypeDef structure that contains the configuration information for PCCARD module.
pBuffer pointer to source write buffer
SectorAddress Sector address to write
pStatus pointer to PCCARD status
Return values:
HAL status
Definition at line 449 of file stm32f1xx_hal_pccard.c.
References PCCARD_STATUS_OK, PCCARD_STATUS_WRITE_OK, and PCCARD_TIMEOUT_READ_WRITE_SECTOR.