STM32F103xG HAL User Manual: SD Private Functions
SD Private Functions
SD
Functions
static uint32_t SD_InitCard (SD_HandleTypeDef *hsd)
Initializes the sd card.
static uint32_t SD_PowerON (SD_HandleTypeDef *hsd)
Enquires cards about their operating voltage and configures clock controls and stores SD information that will be needed in future in the SD handle.
static uint32_t SD_SendSDStatus (SD_HandleTypeDef *hsd, uint32_t *pSDstatus)
Send Status info command.
static uint32_t SD_SendStatus (SD_HandleTypeDef *hsd, uint32_t *pCardStatus)
Returns the current card's status.
static uint32_t SD_WideBus_Enable (SD_HandleTypeDef *hsd)
Enables the SDIO wide bus mode.
static uint32_t SD_WideBus_Disable (SD_HandleTypeDef *hsd)
Disables the SDIO wide bus mode.
static uint32_t SD_FindSCR (SD_HandleTypeDef *hsd, uint32_t *pSCR)
Finds the SD card SCR register value.
static void SD_PowerOFF (SD_HandleTypeDef *hsd)
Turns the SDIO output signals off.
static void SD_Write_IT (SD_HandleTypeDef *hsd)
Wrap up writing in non-blocking mode.
static void SD_Read_IT (SD_HandleTypeDef *hsd)
Wrap up reading in non-blocking mode.
static void SD_DMATransmitCplt (DMA_HandleTypeDef *hdma)
DMA SD transmit process complete callback.
static void SD_DMAReceiveCplt (DMA_HandleTypeDef *hdma)
DMA SD receive process complete callback.
static void SD_DMAError (DMA_HandleTypeDef *hdma)
DMA SD communication error callback.
static void SD_DMATxAbort (DMA_HandleTypeDef *hdma)
DMA SD Tx Abort callback.
static void SD_DMARxAbort (DMA_HandleTypeDef *hdma)
DMA SD Rx Abort callback.
Function Documentation
static void SD_DMAError (DMA_HandleTypeDef * hdma) [static]
DMA SD communication error callback.
Parameters:
hdma,: DMA handle
Return values:
None
Definition at line 2524 of file stm32f1xx_hal_sd.c.
References HAL_DMA_ERROR_TE, HAL_SD_ErrorCallback(), HAL_SD_GetCardState(), and __DMA_HandleTypeDef::Parent.
Referenced by HAL_SD_ReadBlocks_DMA(), and HAL_SD_WriteBlocks_DMA().
static void SD_DMAReceiveCplt (DMA_HandleTypeDef * hdma) [static]
DMA SD receive process complete callback.
Parameters:
hdma,: DMA handle
Return values:
None
Definition at line 2482 of file stm32f1xx_hal_sd.c.
References HAL_SD_ErrorCallback(), HAL_SD_RxCpltCallback(), and __DMA_HandleTypeDef::Parent.
Referenced by HAL_SD_ReadBlocks_DMA().
static void SD_DMARxAbort (DMA_HandleTypeDef * hdma) [static]
DMA SD Rx Abort callback.
Parameters:
hdma,: DMA handle
Return values:
None
Definition at line 2603 of file stm32f1xx_hal_sd.c.
References HAL_SD_AbortCallback(), HAL_SD_ErrorCallback(), HAL_SD_GetCardState(), and __DMA_HandleTypeDef::Parent.
Referenced by HAL_SD_Abort_IT(), and HAL_SD_IRQHandler().
static void SD_DMATransmitCplt (DMA_HandleTypeDef * hdma) [static]
DMA SD transmit process complete callback.
Parameters:
hdma,: DMA handle
Return values:
None
Definition at line 2469 of file stm32f1xx_hal_sd.c.
References __DMA_HandleTypeDef::Parent.
Referenced by HAL_SD_WriteBlocks_DMA().
static void SD_DMATxAbort (DMA_HandleTypeDef * hdma) [static]
DMA SD Tx Abort callback.
Parameters:
hdma,: DMA handle
Return values:
None
Definition at line 2564 of file stm32f1xx_hal_sd.c.
References HAL_SD_AbortCallback(), HAL_SD_ErrorCallback(), HAL_SD_GetCardState(), and __DMA_HandleTypeDef::Parent.
Referenced by HAL_SD_Abort_IT(), and HAL_SD_IRQHandler().
static uint32_t SD_FindSCR (SD_HandleTypeDef * hsd, uint32_t * pSCR) [static]
Finds the SD card SCR register value.
Parameters:
hsd,: Pointer to SD handle
pSCR,: pointer to the buffer that will contain the SCR value
Return values:
error state
Definition at line 3066 of file stm32f1xx_hal_sd.c.
References HAL_GetTick().
Referenced by SD_WideBus_Disable(), and SD_WideBus_Enable().
static uint32_t SD_InitCard (SD_HandleTypeDef * hsd) [static]
Initializes the sd card.
Parameters:
hsd,: Pointer to SD handle
Return values:
SD Card error state
Definition at line 2642 of file stm32f1xx_hal_sd.c.
References HAL_SD_GetCardCSD().
Referenced by HAL_SD_InitCard().
static void SD_PowerOFF (SD_HandleTypeDef * hsd) [static]
Turns the SDIO output signals off.
Parameters:
hsd,: Pointer to SD handle
Return values:
None
Definition at line 2824 of file stm32f1xx_hal_sd.c.
Referenced by HAL_SD_DeInit().
static uint32_t SD_PowerON (SD_HandleTypeDef * hsd) [static]
Enquires cards about their operating voltage and configures clock controls and stores SD information that will be needed in future in the SD handle.
Parameters:
hsd,: Pointer to SD handle
Return values:
error state
Definition at line 2734 of file stm32f1xx_hal_sd.c.
Referenced by HAL_SD_InitCard().
static void SD_Read_IT (SD_HandleTypeDef * hsd) [static]
Wrap up reading in non-blocking mode.
Parameters:
hsd,: pointer to a SD_HandleTypeDef structure that contains the configuration information.
Return values:
None
Definition at line 3159 of file stm32f1xx_hal_sd.c.
Referenced by HAL_SD_IRQHandler().
static uint32_t SD_SendSDStatus (SD_HandleTypeDef * hsd, uint32_t * pSDstatus) [static]
Send Status info command.
Parameters:
hsd,: pointer to SD handle
pSDstatus,: Pointer to the buffer that will contain the SD card status SD Status register)
Return values:
error state
Definition at line 2837 of file stm32f1xx_hal_sd.c.
References HAL_GetTick().
Referenced by HAL_SD_GetCardStatus().
static uint32_t SD_SendStatus (SD_HandleTypeDef * hsd, uint32_t * pCardStatus) [static]
Returns the current card's status.
Parameters:
hsd,: Pointer to SD handle
pCardStatus,: pointer to the buffer that will contain the SD card status (Card Status register)
Return values:
error state
Definition at line 2943 of file stm32f1xx_hal_sd.c.
Referenced by HAL_SD_GetCardState().
static uint32_t SD_WideBus_Disable (SD_HandleTypeDef * hsd) [static]
Disables the SDIO wide bus mode.
Parameters:
hsd,: Pointer to SD handle
Return values:
error state
Definition at line 3017 of file stm32f1xx_hal_sd.c.
References SD_FindSCR().
Referenced by HAL_SD_ConfigWideBusOperation().
static uint32_t SD_WideBus_Enable (SD_HandleTypeDef * hsd) [static]
Enables the SDIO wide bus mode.
Parameters:
hsd,: pointer to SD handle
Return values:
error state
Definition at line 2970 of file stm32f1xx_hal_sd.c.
References SD_FindSCR().
Referenced by HAL_SD_ConfigWideBusOperation().
static void SD_Write_IT (SD_HandleTypeDef * hsd) [static]
Wrap up writing in non-blocking mode.
Parameters:
hsd,: pointer to a SD_HandleTypeDef structure that contains the configuration information.
Return values:
None
Definition at line 3198 of file stm32f1xx_hal_sd.c.
Referenced by HAL_SD_IRQHandler().