STM32F103xG HAL User Manual: Initialization and de-initialization functions
Initialization and de-initialization functions
PCCARD Exported Functions
Initialization and Configuration functions.
Functions
HAL_StatusTypeDef HAL_PCCARD_Init (PCCARD_HandleTypeDef *hpccard, FSMC_NAND_PCC_TimingTypeDef *ComSpaceTiming, FSMC_NAND_PCC_TimingTypeDef *AttSpaceTiming, FSMC_NAND_PCC_TimingTypeDef *IOSpaceTiming)
Perform the PCCARD memory Initialization sequence.
HAL_StatusTypeDef HAL_PCCARD_DeInit (PCCARD_HandleTypeDef *hpccard)
Perform the PCCARD memory De-initialization sequence.
__weak void HAL_PCCARD_MspInit (PCCARD_HandleTypeDef *hpccard)
PCCARD MSP Init.
__weak void HAL_PCCARD_MspDeInit (PCCARD_HandleTypeDef *hpccard)
PCCARD MSP DeInit.
Detailed Description
Initialization and Configuration functions.
  ==============================================================================
          ##### PCCARD Initialization and de-initialization functions #####
  ==============================================================================
  [..]
    This section provides functions allowing to initialize/de-initialize
    the PCCARD memory
Function Documentation
HAL_StatusTypeDef HAL_PCCARD_DeInit (PCCARD_HandleTypeDef * hpccard)
Perform the PCCARD memory De-initialization sequence.
Parameters:
hpccard pointer to a PCCARD_HandleTypeDef structure that contains the configuration information for PCCARD module.
Return values:
HAL status
Definition at line 223 of file stm32f1xx_hal_pccard.c.
References HAL_PCCARD_MspDeInit().
HAL_StatusTypeDef HAL_PCCARD_Init (PCCARD_HandleTypeDef * hpccard, FSMC_NAND_PCC_TimingTypeDef * ComSpaceTiming, FSMC_NAND_PCC_TimingTypeDef * AttSpaceTiming, FSMC_NAND_PCC_TimingTypeDef * IOSpaceTiming)
Perform the PCCARD memory Initialization sequence.
Parameters:
hpccard pointer to a PCCARD_HandleTypeDef structure that contains the configuration information for PCCARD module.
ComSpaceTiming Common space timing structure
AttSpaceTiming Attribute space timing structure
IOSpaceTiming IO space timing structure
Return values:
HAL status
Definition at line 165 of file stm32f1xx_hal_pccard.c.
References HAL_PCCARD_ITCallback(), and HAL_PCCARD_MspInit().
__weak void HAL_PCCARD_MspDeInit (PCCARD_HandleTypeDef * hpccard)
PCCARD MSP DeInit.
Parameters:
hpccard pointer to a PCCARD_HandleTypeDef structure that contains the configuration information for PCCARD module.
Return values:
None
Definition at line 271 of file stm32f1xx_hal_pccard.c.
Referenced by HAL_PCCARD_DeInit().
__weak void HAL_PCCARD_MspInit (PCCARD_HandleTypeDef * hpccard)
PCCARD MSP Init.
Parameters:
hpccard pointer to a PCCARD_HandleTypeDef structure that contains the configuration information for PCCARD module.
Return values:
None
Definition at line 256 of file stm32f1xx_hal_pccard.c.
Referenced by HAL_PCCARD_Init().