STM32F103xG HAL User Manual: USART Private Functions
USART Private Functions
USART Exported Functions | USART
Functions
static void USART_EndTxTransfer (USART_HandleTypeDef *husart)
End ongoing Tx transfer on USART peripheral (following error detection or Transmit completion).
static void USART_EndRxTransfer (USART_HandleTypeDef *husart)
End ongoing Rx transfer on USART peripheral (following error detection or Reception completion).
static HAL_StatusTypeDef USART_Transmit_IT (USART_HandleTypeDef *husart)
Simplex Send an amount of data in non-blocking mode.
static HAL_StatusTypeDef USART_EndTransmit_IT (USART_HandleTypeDef *husart)
Wraps up transmission in non blocking mode.
static HAL_StatusTypeDef USART_Receive_IT (USART_HandleTypeDef *husart)
Simplex Receive an amount of data in non-blocking mode.
static HAL_StatusTypeDef USART_TransmitReceive_IT (USART_HandleTypeDef *husart)
Full-Duplex Send receive an amount of data in full-duplex mode (non-blocking).
static void USART_SetConfig (USART_HandleTypeDef *husart)
Configures the USART peripheral.
static void USART_DMATransmitCplt (DMA_HandleTypeDef *hdma)
Initialize the callbacks to their default values.
static void USART_DMATxHalfCplt (DMA_HandleTypeDef *hdma)
DMA USART transmit process half complete callback.
static void USART_DMAReceiveCplt (DMA_HandleTypeDef *hdma)
DMA USART receive process complete callback.
static void USART_DMARxHalfCplt (DMA_HandleTypeDef *hdma)
DMA USART receive process half complete callback.
static void USART_DMAError (DMA_HandleTypeDef *hdma)
DMA USART communication error callback.
static void USART_DMAAbortOnError (DMA_HandleTypeDef *hdma)
DMA USART communication abort callback, when initiated by HAL services on Error (To be called at end of DMA Abort procedure following error occurrence).
static void USART_DMATxAbortCallback (DMA_HandleTypeDef *hdma)
DMA USART Tx communication abort callback, when initiated by user (To be called at end of DMA Tx Abort procedure following user abort request).
static void USART_DMARxAbortCallback (DMA_HandleTypeDef *hdma)
DMA USART Rx communication abort callback, when initiated by user (To be called at end of DMA Rx Abort procedure following user abort request).
static HAL_StatusTypeDef USART_WaitOnFlagUntilTimeout (USART_HandleTypeDef *husart, uint32_t Flag, FlagStatus Status, uint32_t Tickstart, uint32_t Timeout)
This function handles USART Communication Timeout.
Function Documentation
static void USART_DMAAbortOnError (DMA_HandleTypeDef * hdma) [static]
DMA USART communication abort callback, when initiated by HAL services on Error (To be called at end of DMA Abort procedure following error occurrence).
Parameters:
hdma DMA handle.
Return values:
None
Definition at line 2318 of file stm32f1xx_hal_usart.c.
References HAL_USART_ErrorCallback(), __USART_HandleTypeDef::RxXferCount, and __USART_HandleTypeDef::TxXferCount.
Referenced by HAL_USART_IRQHandler().
static void USART_DMAError (DMA_HandleTypeDef * hdma) [static]
DMA USART communication error callback.
Parameters:
hdma Pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 2206 of file stm32f1xx_hal_usart.c.
References __USART_HandleTypeDef::ErrorCode, HAL_USART_ERROR_DMA, HAL_USART_ErrorCallback(), HAL_USART_STATE_BUSY_RX, HAL_USART_STATE_BUSY_TX, HAL_USART_STATE_READY, __USART_HandleTypeDef::Instance, __USART_HandleTypeDef::RxXferCount, __USART_HandleTypeDef::State, __USART_HandleTypeDef::TxXferCount, USART_EndRxTransfer(), and USART_EndTxTransfer().
Referenced by HAL_USART_Receive_DMA(), HAL_USART_Transmit_DMA(), and HAL_USART_TransmitReceive_DMA().
static void USART_DMAReceiveCplt (DMA_HandleTypeDef * hdma) [static]
DMA USART receive process complete callback.
Parameters:
hdma Pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 2112 of file stm32f1xx_hal_usart.c.
References HAL_USART_RxCpltCallback(), HAL_USART_STATE_BUSY_RX, HAL_USART_STATE_READY, HAL_USART_TxRxCpltCallback(), __USART_HandleTypeDef::Instance, __DMA_HandleTypeDef::Instance, __USART_HandleTypeDef::RxXferCount, and __USART_HandleTypeDef::State.
Referenced by HAL_USART_Receive_DMA(), and HAL_USART_TransmitReceive_DMA().
static void USART_DMARxAbortCallback (DMA_HandleTypeDef * hdma) [static]
DMA USART Rx communication abort callback, when initiated by user (To be called at end of DMA Rx Abort procedure following user abort request).
Note:
When this callback is executed, User Abort complete call back is called only if no Abort still ongoing for Tx DMA Handle.
Parameters:
hdma DMA handle.
Return values:
None
Definition at line 2384 of file stm32f1xx_hal_usart.c.
References __USART_HandleTypeDef::ErrorCode, HAL_USART_AbortCpltCallback(), HAL_USART_ERROR_NONE, HAL_USART_STATE_READY, __USART_HandleTypeDef::hdmarx, __USART_HandleTypeDef::hdmatx, __USART_HandleTypeDef::RxXferCount, __USART_HandleTypeDef::State, __USART_HandleTypeDef::TxXferCount, and __DMA_HandleTypeDef::XferAbortCallback.
Referenced by HAL_USART_Abort_IT().
static void USART_DMARxHalfCplt (DMA_HandleTypeDef * hdma) [static]
DMA USART receive process half complete callback.
Parameters:
hdma Pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 2187 of file stm32f1xx_hal_usart.c.
References HAL_USART_RxHalfCpltCallback().
Referenced by HAL_USART_Receive_DMA(), and HAL_USART_TransmitReceive_DMA().
static void USART_DMATransmitCplt (DMA_HandleTypeDef * hdma) [static]
Initialize the callbacks to their default values.
Parameters:
husart USART handle.
Return values:
none DMA USART transmit process complete callback.
Parameters:
hdma Pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 2054 of file stm32f1xx_hal_usart.c.
References HAL_USART_STATE_BUSY_TX, HAL_USART_TxCpltCallback(), __USART_HandleTypeDef::Instance, __DMA_HandleTypeDef::Instance, __USART_HandleTypeDef::State, and __USART_HandleTypeDef::TxXferCount.
Referenced by HAL_USART_Transmit_DMA(), and HAL_USART_TransmitReceive_DMA().
static void USART_DMATxAbortCallback (DMA_HandleTypeDef * hdma) [static]
DMA USART Tx communication abort callback, when initiated by user (To be called at end of DMA Tx Abort procedure following user abort request).
Note:
When this callback is executed, User Abort complete call back is called only if no Abort still ongoing for Rx DMA Handle.
Parameters:
hdma DMA handle.
Return values:
None
Definition at line 2341 of file stm32f1xx_hal_usart.c.
References __USART_HandleTypeDef::ErrorCode, HAL_USART_AbortCpltCallback(), HAL_USART_ERROR_NONE, HAL_USART_STATE_READY, __USART_HandleTypeDef::hdmarx, __USART_HandleTypeDef::hdmatx, __USART_HandleTypeDef::RxXferCount, __USART_HandleTypeDef::State, __USART_HandleTypeDef::TxXferCount, and __DMA_HandleTypeDef::XferAbortCallback.
Referenced by HAL_USART_Abort_IT().
static void USART_DMATxHalfCplt (DMA_HandleTypeDef * hdma) [static]
DMA USART transmit process half complete callback.
Parameters:
hdma Pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 2093 of file stm32f1xx_hal_usart.c.
References HAL_USART_TxHalfCpltCallback().
Referenced by HAL_USART_Transmit_DMA(), and HAL_USART_TransmitReceive_DMA().
static void USART_EndRxTransfer (USART_HandleTypeDef * husart) [static]
End ongoing Rx transfer on USART peripheral (following error detection or Reception completion).
Parameters:
husart USART handle.
Return values:
None
Definition at line 2302 of file stm32f1xx_hal_usart.c.
References HAL_USART_STATE_READY, __USART_HandleTypeDef::Instance, and __USART_HandleTypeDef::State.
Referenced by HAL_USART_DMAStop(), HAL_USART_IRQHandler(), and USART_DMAError().
static HAL_StatusTypeDef USART_EndTransmit_IT (USART_HandleTypeDef * husart) [static]
Wraps up transmission in non blocking mode.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
Return values:
HAL status
Definition at line 2472 of file stm32f1xx_hal_usart.c.
References HAL_USART_STATE_READY, HAL_USART_TxCpltCallback(), __USART_HandleTypeDef::Instance, and __USART_HandleTypeDef::State.
Referenced by HAL_USART_IRQHandler().
static void USART_EndTxTransfer (USART_HandleTypeDef * husart) [static]
End ongoing Tx transfer on USART peripheral (following error detection or Transmit completion).
Parameters:
husart USART handle.
Return values:
None
Definition at line 2288 of file stm32f1xx_hal_usart.c.
References HAL_USART_STATE_READY, __USART_HandleTypeDef::Instance, and __USART_HandleTypeDef::State.
Referenced by HAL_USART_DMAStop(), and USART_DMAError().
static HAL_StatusTypeDef USART_Receive_IT (USART_HandleTypeDef * husart) [static]
Simplex Receive an amount of data in non-blocking mode.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
Return values:
HAL status
Definition at line 2499 of file stm32f1xx_hal_usart.c.
References DUMMY_DATA, HAL_USART_RxCpltCallback(), HAL_USART_STATE_BUSY_RX, HAL_USART_STATE_READY, __USART_HandleTypeDef::Init, __USART_HandleTypeDef::Instance, USART_InitTypeDef::Parity, __USART_HandleTypeDef::pRxBuffPtr, __USART_HandleTypeDef::RxXferCount, __USART_HandleTypeDef::State, USART_PARITY_NONE, USART_WORDLENGTH_9B, and USART_InitTypeDef::WordLength.
Referenced by HAL_USART_IRQHandler().
static void USART_SetConfig (USART_HandleTypeDef * husart) [static]
Configures the USART peripheral.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
Return values:
None
Definition at line 2686 of file stm32f1xx_hal_usart.c.
References assert_param, USART_InitTypeDef::BaudRate, USART_InitTypeDef::CLKLastBit, USART_InitTypeDef::CLKPhase, USART_InitTypeDef::CLKPolarity, HAL_RCC_GetPCLK1Freq(), HAL_RCC_GetPCLK2Freq(), __USART_HandleTypeDef::Init, __USART_HandleTypeDef::Instance, IS_USART_BAUDRATE, IS_USART_LASTBIT, IS_USART_MODE, IS_USART_PARITY, IS_USART_PHASE, IS_USART_POLARITY, IS_USART_STOPBITS, IS_USART_WORD_LENGTH, USART_InitTypeDef::Mode, USART_InitTypeDef::Parity, USART_InitTypeDef::StopBits, USART_BRR, USART_CLOCK_ENABLE, and USART_InitTypeDef::WordLength.
Referenced by HAL_USART_Init().
static HAL_StatusTypeDef USART_Transmit_IT (USART_HandleTypeDef * husart) [static]
Simplex Send an amount of data in non-blocking mode.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
Return values:
HAL status
Note:
The USART errors are not managed to avoid the overrun error.
Definition at line 2426 of file stm32f1xx_hal_usart.c.
References HAL_USART_STATE_BUSY_TX, __USART_HandleTypeDef::Init, __USART_HandleTypeDef::Instance, USART_InitTypeDef::Parity, __USART_HandleTypeDef::pTxBuffPtr, __USART_HandleTypeDef::State, __USART_HandleTypeDef::TxXferCount, USART_PARITY_NONE, USART_WORDLENGTH_9B, and USART_InitTypeDef::WordLength.
Referenced by HAL_USART_IRQHandler().
static HAL_StatusTypeDef USART_TransmitReceive_IT (USART_HandleTypeDef * husart) [static]
Full-Duplex Send receive an amount of data in full-duplex mode (non-blocking).
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
Return values:
HAL status
Definition at line 2577 of file stm32f1xx_hal_usart.c.
References __HAL_USART_GET_FLAG, HAL_USART_STATE_BUSY_TX_RX, HAL_USART_STATE_READY, HAL_USART_TxRxCpltCallback(), __USART_HandleTypeDef::Init, __USART_HandleTypeDef::Instance, USART_InitTypeDef::Parity, __USART_HandleTypeDef::pRxBuffPtr, __USART_HandleTypeDef::pTxBuffPtr, __USART_HandleTypeDef::RxXferCount, __USART_HandleTypeDef::State, __USART_HandleTypeDef::TxXferCount, USART_FLAG_RXNE, USART_FLAG_TXE, USART_PARITY_NONE, USART_WORDLENGTH_9B, and USART_InitTypeDef::WordLength.
Referenced by HAL_USART_IRQHandler().
static HAL_StatusTypeDef USART_WaitOnFlagUntilTimeout (USART_HandleTypeDef * husart, uint32_t Flag, FlagStatus Status, uint32_t Tickstart, uint32_t Timeout) [static]
This function handles USART Communication Timeout.
Parameters:
husart Pointer to a USART_HandleTypeDef structure that contains the configuration information for the specified USART module.
Flag specifies the USART flag to check.
Status The new Flag status (SET or RESET).
Tickstart Tick start value.
Timeout Timeout duration.
Return values:
HAL status
Definition at line 2249 of file stm32f1xx_hal_usart.c.
References __HAL_USART_GET_FLAG, HAL_GetTick(), HAL_USART_STATE_READY, __USART_HandleTypeDef::Instance, and __USART_HandleTypeDef::State.
Referenced by HAL_USART_Receive(), HAL_USART_Transmit(), and HAL_USART_TransmitReceive().