STM32F103xG HAL User Manual: Initialization and de-initialization functions
Initialization and de-initialization functions
GPIO Exported Functions
Functions
ErrorStatus LL_GPIO_DeInit (GPIO_TypeDef *GPIOx)
De-initialize GPIO registers (Registers restored to their default values).
ErrorStatus LL_GPIO_Init (GPIO_TypeDef *GPIOx, LL_GPIO_InitTypeDef *GPIO_InitStruct)
Initialize GPIO registers according to the specified parameters in GPIO_InitStruct.
void LL_GPIO_StructInit (LL_GPIO_InitTypeDef *GPIO_InitStruct)
Set each LL_GPIO_InitTypeDef field to default value.
Function Documentation
ErrorStatus LL_GPIO_DeInit (GPIO_TypeDef * GPIOx)
De-initialize GPIO registers (Registers restored to their default values).
Parameters:
GPIOx GPIO Port
Return values:
An ErrorStatus enumeration value:
SUCCESS: GPIO registers are de-initialized
ERROR: Wrong GPIO Port
Definition at line 90 of file stm32f1xx_ll_gpio.c.
References assert_param, LL_APB2_GRP1_ForceReset(), LL_APB2_GRP1_PERIPH_GPIOA, LL_APB2_GRP1_PERIPH_GPIOB, LL_APB2_GRP1_PERIPH_GPIOC, LL_APB2_GRP1_PERIPH_GPIOD, LL_APB2_GRP1_PERIPH_GPIOE, LL_APB2_GRP1_PERIPH_GPIOF, LL_APB2_GRP1_PERIPH_GPIOG, and LL_APB2_GRP1_ReleaseReset().
ErrorStatus LL_GPIO_Init (GPIO_TypeDef * GPIOx, LL_GPIO_InitTypeDef * GPIO_InitStruct)
Initialize GPIO registers according to the specified parameters in GPIO_InitStruct.
Parameters:
GPIOx GPIO Port
GPIO_InitStruct,: pointer to a LL_GPIO_InitTypeDef structure that contains the configuration information for the specified GPIO peripheral.
Return values:
An ErrorStatus enumeration value:
SUCCESS: GPIO registers are initialized according to GPIO_InitStruct content
ERROR: Not applicable
Definition at line 156 of file stm32f1xx_ll_gpio.c.
References assert_param, GPIO_PIN_MASK_POS, GPIO_PIN_NB, IS_LL_GPIO_MODE, IS_LL_GPIO_OUTPUT_TYPE, IS_LL_GPIO_PIN, IS_LL_GPIO_PULL, IS_LL_GPIO_SPEED, LL_GPIO_MODE_ALTERNATE, LL_GPIO_MODE_OUTPUT, LL_GPIO_SetPinMode(), LL_GPIO_SetPinOutputType(), LL_GPIO_SetPinPull(), LL_GPIO_SetPinSpeed(), LL_GPIO_InitTypeDef::Mode, LL_GPIO_InitTypeDef::OutputType, LL_GPIO_InitTypeDef::Pin, LL_GPIO_InitTypeDef::Pull, and LL_GPIO_InitTypeDef::Speed.
void LL_GPIO_StructInit (LL_GPIO_InitTypeDef * GPIO_InitStruct)
Set each LL_GPIO_InitTypeDef field to default value.
Parameters:
GPIO_InitStruct,: pointer to a LL_GPIO_InitTypeDef structure whose fields will be set to default values.
Return values:
None
Definition at line 223 of file stm32f1xx_ll_gpio.c.
References LL_GPIO_MODE_FLOATING, LL_GPIO_OUTPUT_OPENDRAIN, LL_GPIO_PIN_ALL, LL_GPIO_PULL_DOWN, LL_GPIO_SPEED_FREQ_LOW, LL_GPIO_InitTypeDef::Mode, LL_GPIO_InitTypeDef::OutputType, LL_GPIO_InitTypeDef::Pin, LL_GPIO_InitTypeDef::Pull, and LL_GPIO_InitTypeDef::Speed.