STM32F103xG HAL User Manual: MMC Private Functions
MMC Private Functions
MMC
Functions
static uint32_t MMC_InitCard (MMC_HandleTypeDef *hmmc)
Initializes the mmc card.
static uint32_t MMC_PowerON (MMC_HandleTypeDef *hmmc)
Enquires cards about their operating voltage and configures clock controls and stores MMC information that will be needed in future in the MMC handle.
static uint32_t MMC_SendStatus (MMC_HandleTypeDef *hmmc, uint32_t *pCardStatus)
Returns the current card's status.
static void MMC_PowerOFF (MMC_HandleTypeDef *hmmc)
Turns the SDIO output signals off.
static void MMC_Write_IT (MMC_HandleTypeDef *hmmc)
Wrap up writing in non-blocking mode.
static void MMC_Read_IT (MMC_HandleTypeDef *hmmc)
Wrap up reading in non-blocking mode.
static void MMC_DMATransmitCplt (DMA_HandleTypeDef *hdma)
DMA MMC transmit process complete callback.
static void MMC_DMAReceiveCplt (DMA_HandleTypeDef *hdma)
DMA MMC receive process complete callback.
static void MMC_DMAError (DMA_HandleTypeDef *hdma)
DMA MMC communication error callback.
static void MMC_DMATxAbort (DMA_HandleTypeDef *hdma)
DMA MMC Tx Abort callback.
static void MMC_DMARxAbort (DMA_HandleTypeDef *hdma)
DMA MMC Rx Abort callback.
Function Documentation
static void MMC_DMAError (DMA_HandleTypeDef * hdma) [static]
DMA MMC communication error callback.
Parameters:
hdma,: DMA handle
Return values:
None
Definition at line 2464 of file stm32f1xx_hal_mmc.c.
References HAL_DMA_ERROR_TE, HAL_MMC_ErrorCallback(), HAL_MMC_GetCardState(), and __DMA_HandleTypeDef::Parent.
Referenced by HAL_MMC_ReadBlocks_DMA(), and HAL_MMC_WriteBlocks_DMA().
static void MMC_DMAReceiveCplt (DMA_HandleTypeDef * hdma) [static]
DMA MMC receive process complete callback.
Parameters:
hdma,: DMA handle
Return values:
None
Definition at line 2423 of file stm32f1xx_hal_mmc.c.
References HAL_MMC_ErrorCallback(), HAL_MMC_RxCpltCallback(), and __DMA_HandleTypeDef::Parent.
Referenced by HAL_MMC_ReadBlocks_DMA().
static void MMC_DMARxAbort (DMA_HandleTypeDef * hdma) [static]
DMA MMC Rx Abort callback.
Parameters:
hdma,: DMA handle
Return values:
None
Definition at line 2548 of file stm32f1xx_hal_mmc.c.
References HAL_MMC_AbortCallback(), HAL_MMC_ErrorCallback(), HAL_MMC_GetCardState(), and __DMA_HandleTypeDef::Parent.
Referenced by HAL_MMC_Abort_IT(), and HAL_MMC_IRQHandler().
static void MMC_DMATransmitCplt (DMA_HandleTypeDef * hdma) [static]
DMA MMC transmit process complete callback.
Parameters:
hdma,: DMA handle
Return values:
None
Definition at line 2410 of file stm32f1xx_hal_mmc.c.
References __DMA_HandleTypeDef::Parent.
Referenced by HAL_MMC_WriteBlocks_DMA().
static void MMC_DMATxAbort (DMA_HandleTypeDef * hdma) [static]
DMA MMC Tx Abort callback.
Parameters:
hdma,: DMA handle
Return values:
None
Definition at line 2503 of file stm32f1xx_hal_mmc.c.
References HAL_MMC_AbortCallback(), HAL_MMC_ErrorCallback(), HAL_MMC_GetCardState(), and __DMA_HandleTypeDef::Parent.
Referenced by HAL_MMC_Abort_IT(), and HAL_MMC_IRQHandler().
static uint32_t MMC_InitCard (MMC_HandleTypeDef * hmmc) [static]
Initializes the mmc card.
Parameters:
hmmc,: Pointer to MMC handle
Return values:
MMC Card error state
Definition at line 2593 of file stm32f1xx_hal_mmc.c.
References HAL_MMC_GetCardCSD().
Referenced by HAL_MMC_InitCard().
static void MMC_PowerOFF (MMC_HandleTypeDef * hmmc) [static]
Turns the SDIO output signals off.
Parameters:
hmmc,: Pointer to MMC handle
Return values:
None
Definition at line 2729 of file stm32f1xx_hal_mmc.c.
Referenced by HAL_MMC_DeInit().
static uint32_t MMC_PowerON (MMC_HandleTypeDef * hmmc) [static]
Enquires cards about their operating voltage and configures clock controls and stores MMC information that will be needed in future in the MMC handle.
Parameters:
hmmc,: Pointer to MMC handle
Return values:
error state
Definition at line 2677 of file stm32f1xx_hal_mmc.c.
Referenced by HAL_MMC_InitCard().
static void MMC_Read_IT (MMC_HandleTypeDef * hmmc) [static]
Wrap up reading in non-blocking mode.
Parameters:
hmmc,: pointer to a MMC_HandleTypeDef structure that contains the configuration information.
Return values:
None
Definition at line 2770 of file stm32f1xx_hal_mmc.c.
Referenced by HAL_MMC_IRQHandler().
static uint32_t MMC_SendStatus (MMC_HandleTypeDef * hmmc, uint32_t * pCardStatus) [static]
Returns the current card's status.
Parameters:
hmmc,: Pointer to MMC handle
pCardStatus,: pointer to the buffer that will contain the MMC card status (Card Status register)
Return values:
error state
Definition at line 2742 of file stm32f1xx_hal_mmc.c.
Referenced by HAL_MMC_GetCardState().
static void MMC_Write_IT (MMC_HandleTypeDef * hmmc) [static]
Wrap up writing in non-blocking mode.
Parameters:
hmmc,: pointer to a MMC_HandleTypeDef structure that contains the configuration information.
Return values:
None
Definition at line 2809 of file stm32f1xx_hal_mmc.c.
Referenced by HAL_MMC_IRQHandler().