STM32F103xG HAL User Manual: I2S Private Functions
I2S Private Functions
I2S
Functions
static void I2S_DMATxCplt (DMA_HandleTypeDef *hdma)
DMA I2S transmit process complete callback.
static void I2S_DMATxHalfCplt (DMA_HandleTypeDef *hdma)
DMA I2S transmit process half complete callback.
static void I2S_DMARxCplt (DMA_HandleTypeDef *hdma)
DMA I2S receive process complete callback.
static void I2S_DMARxHalfCplt (DMA_HandleTypeDef *hdma)
DMA I2S receive process half complete callback.
static void I2S_DMAError (DMA_HandleTypeDef *hdma)
DMA I2S communication error callback.
static void I2S_Transmit_IT (I2S_HandleTypeDef *hi2s)
Transmit an amount of data in non-blocking mode with Interrupt.
static void I2S_Receive_IT (I2S_HandleTypeDef *hi2s)
Receive an amount of data in non-blocking mode with Interrupt.
static HAL_StatusTypeDef I2S_WaitFlagStateUntilTimeout (I2S_HandleTypeDef *hi2s, uint32_t Flag, FlagStatus State, uint32_t Timeout)
This function handles I2S Communication Timeout.
Function Documentation
static void I2S_DMAError (DMA_HandleTypeDef * hdma) [static]
DMA I2S communication error callback.
Parameters:
hdma pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 1693 of file stm32f1xx_hal_i2s.c.
References I2S_HandleTypeDef::ErrorCode, HAL_I2S_ERROR_DMA, HAL_I2S_ErrorCallback(), HAL_I2S_STATE_READY, I2S_HandleTypeDef::Instance, I2S_HandleTypeDef::RxXferCount, I2S_HandleTypeDef::State, and I2S_HandleTypeDef::TxXferCount.
Referenced by HAL_I2S_Receive_DMA(), and HAL_I2S_Transmit_DMA().
static void I2S_DMARxCplt (DMA_HandleTypeDef * hdma) [static]
DMA I2S receive process complete callback.
Parameters:
hdma pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 1649 of file stm32f1xx_hal_i2s.c.
References DMA_NORMAL, HAL_I2S_RxCpltCallback(), HAL_I2S_STATE_READY, __DMA_HandleTypeDef::Init, I2S_HandleTypeDef::Instance, DMA_InitTypeDef::Mode, I2S_HandleTypeDef::RxXferCount, and I2S_HandleTypeDef::State.
Referenced by HAL_I2S_Receive_DMA().
static void I2S_DMARxHalfCplt (DMA_HandleTypeDef * hdma) [static]
DMA I2S receive process half complete callback.
Parameters:
hdma pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 1675 of file stm32f1xx_hal_i2s.c.
References HAL_I2S_RxHalfCpltCallback().
Referenced by HAL_I2S_Receive_DMA().
static void I2S_DMATxCplt (DMA_HandleTypeDef * hdma) [static]
DMA I2S transmit process complete callback.
Parameters:
hdma pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 1604 of file stm32f1xx_hal_i2s.c.
References DMA_NORMAL, HAL_I2S_STATE_READY, HAL_I2S_TxCpltCallback(), __DMA_HandleTypeDef::Init, I2S_HandleTypeDef::Instance, DMA_InitTypeDef::Mode, I2S_HandleTypeDef::State, and I2S_HandleTypeDef::TxXferCount.
Referenced by HAL_I2S_Transmit_DMA().
static void I2S_DMATxHalfCplt (DMA_HandleTypeDef * hdma) [static]
DMA I2S transmit process half complete callback.
Parameters:
hdma pointer to a DMA_HandleTypeDef structure that contains the configuration information for the specified DMA module.
Return values:
None
Definition at line 1631 of file stm32f1xx_hal_i2s.c.
References HAL_I2S_TxHalfCpltCallback().
Referenced by HAL_I2S_Transmit_DMA().
static void I2S_Receive_IT (I2S_HandleTypeDef * hi2s) [static]
Receive an amount of data in non-blocking mode with Interrupt.
Parameters:
hi2s pointer to a I2S_HandleTypeDef structure that contains the configuration information for I2S module
Return values:
None
Definition at line 1748 of file stm32f1xx_hal_i2s.c.
References __HAL_I2S_DISABLE_IT, HAL_I2S_RxCpltCallback(), HAL_I2S_STATE_READY, I2S_IT_ERR, I2S_IT_RXNE, I2S_HandleTypeDef::Instance, I2S_HandleTypeDef::pRxBuffPtr, I2S_HandleTypeDef::RxXferCount, and I2S_HandleTypeDef::State.
Referenced by HAL_I2S_IRQHandler().
static void I2S_Transmit_IT (I2S_HandleTypeDef * hi2s) [static]
Transmit an amount of data in non-blocking mode with Interrupt.
Parameters:
hi2s pointer to a I2S_HandleTypeDef structure that contains the configuration information for I2S module
Return values:
None
Definition at line 1720 of file stm32f1xx_hal_i2s.c.
References __HAL_I2S_DISABLE_IT, HAL_I2S_STATE_READY, HAL_I2S_TxCpltCallback(), I2S_IT_ERR, I2S_IT_TXE, I2S_HandleTypeDef::Instance, I2S_HandleTypeDef::pTxBuffPtr, I2S_HandleTypeDef::State, and I2S_HandleTypeDef::TxXferCount.
Referenced by HAL_I2S_IRQHandler().
static HAL_StatusTypeDef I2S_WaitFlagStateUntilTimeout (I2S_HandleTypeDef * hi2s, uint32_t Flag, FlagStatus State, uint32_t Timeout) [static]
This function handles I2S Communication Timeout.
Parameters:
hi2s pointer to a I2S_HandleTypeDef structure that contains the configuration information for I2S module
Flag Flag checked
State Value of the flag expected
Timeout Duration of the timeout
Return values:
HAL status
Definition at line 1779 of file stm32f1xx_hal_i2s.c.
References __HAL_I2S_GET_FLAG, HAL_GetTick(), HAL_I2S_STATE_READY, and I2S_HandleTypeDef::State.
Referenced by HAL_I2S_Receive(), and HAL_I2S_Transmit().