STM32F103xG HAL User Manual: Initialization and de-initialization functions
Initialization and de-initialization functions
I2S Exported Functions
Functions
ErrorStatus LL_I2S_DeInit (SPI_TypeDef *SPIx)
De-initialize the SPI/I2S registers to their default reset values.
ErrorStatus LL_I2S_Init (SPI_TypeDef *SPIx, LL_I2S_InitTypeDef *I2S_InitStruct)
Initializes the SPI/I2S registers according to the specified parameters in I2S_InitStruct.
void LL_I2S_StructInit (LL_I2S_InitTypeDef *I2S_InitStruct)
Set each LL_I2S_InitTypeDef field to default value.
void LL_I2S_ConfigPrescaler (SPI_TypeDef *SPIx, uint32_t PrescalerLinear, uint32_t PrescalerParity)
Set linear and parity prescaler.
Function Documentation
void LL_I2S_ConfigPrescaler (SPI_TypeDef * SPIx, uint32_t PrescalerLinear, uint32_t PrescalerParity)
Set linear and parity prescaler.
Note:
To calculate value of PrescalerLinear(I2SDIV[7:0] bits) and PrescalerParity(ODD bit)
Check Audio frequency table and formulas inside Reference Manual (SPI/I2S).
Parameters:
SPIx SPI Instance
PrescalerLinear value Min_Data=0x02 and Max_Data=0xFF.
PrescalerParity This parameter can be one of the following values:
LL_I2S_PRESCALER_PARITY_EVEN
LL_I2S_PRESCALER_PARITY_ODD
Return values:
None
Definition at line 498 of file stm32f1xx_ll_spi.c.
References assert_param, IS_LL_I2S_PRESCALER_LINEAR, and IS_LL_I2S_PRESCALER_PARITY.
ErrorStatus LL_I2S_DeInit (SPI_TypeDef * SPIx)
De-initialize the SPI/I2S registers to their default reset values.
Parameters:
SPIx SPI Instance
Return values:
An ErrorStatus enumeration value:
SUCCESS: SPI registers are de-initialized
ERROR: SPI registers are not de-initialized
Definition at line 352 of file stm32f1xx_ll_spi.c.
References LL_SPI_DeInit().
ErrorStatus LL_I2S_Init (SPI_TypeDef * SPIx, LL_I2S_InitTypeDef * I2S_InitStruct)
Initializes the SPI/I2S registers according to the specified parameters in I2S_InitStruct.
Note:
As some bits in SPI configuration registers can only be written when the SPI is disabled (SPI_CR1_SPE bit =0), SPI peripheral should be in disabled state prior calling this function. Otherwise, ERROR result will be returned.
Parameters:
SPIx SPI Instance
I2S_InitStruct pointer to a LL_I2S_InitTypeDef structure
Return values:
An ErrorStatus enumeration value:
SUCCESS: SPI registers are Initialized
ERROR: SPI registers are not Initialized
Definition at line 367 of file stm32f1xx_ll_spi.c.
References assert_param, LL_I2S_InitTypeDef::AudioFreq, LL_I2S_InitTypeDef::ClockPolarity, LL_I2S_InitTypeDef::DataFormat, I2S_I2SCFGR_CLEAR_MASK, IS_LL_I2S_AUDIO_FREQ, IS_LL_I2S_CPOL, IS_LL_I2S_DATAFORMAT, IS_LL_I2S_MCLK_OUTPUT, IS_LL_I2S_MODE, IS_LL_I2S_STANDARD, LL_I2S_AUDIOFREQ_DEFAULT, LL_I2S_DATAFORMAT_16B, LL_I2S_IsEnabled(), LL_I2S_MCLK_OUTPUT_ENABLE, LL_RCC_GetSystemClocksFreq(), LL_I2S_InitTypeDef::MCLKOutput, LL_I2S_InitTypeDef::Mode, LL_I2S_InitTypeDef::Standard, and LL_RCC_ClocksTypeDef::SYSCLK_Frequency.
void LL_I2S_StructInit (LL_I2S_InitTypeDef * I2S_InitStruct)
Set each LL_I2S_InitTypeDef field to default value.
Parameters:
I2S_InitStruct pointer to a LL_I2S_InitTypeDef structure whose fields will be set to default values.
Return values:
None
Definition at line 476 of file stm32f1xx_ll_spi.c.
References LL_I2S_InitTypeDef::AudioFreq, LL_I2S_InitTypeDef::ClockPolarity, LL_I2S_InitTypeDef::DataFormat, LL_I2S_AUDIOFREQ_DEFAULT, LL_I2S_DATAFORMAT_16B, LL_I2S_MCLK_OUTPUT_DISABLE, LL_I2S_MODE_SLAVE_TX, LL_I2S_POLARITY_LOW, LL_I2S_STANDARD_PHILIPS, LL_I2S_InitTypeDef::MCLKOutput, LL_I2S_InitTypeDef::Mode, and LL_I2S_InitTypeDef::Standard.