STM32F103xG HAL User Manual: Extended Extended IO operation functions
Extended Extended IO operation functions
ADCEx Exported Functions
Extended Extended Input and Output operation functions.
Functions
HAL_StatusTypeDef HAL_ADCEx_Calibration_Start (ADC_HandleTypeDef *hadc)
Perform an ADC automatic self-calibration Calibration prerequisite: ADC must be disabled (execute this function before HAL_ADC_Start() or after HAL_ADC_Stop()).
HAL_StatusTypeDef HAL_ADCEx_InjectedStart (ADC_HandleTypeDef *hadc)
Enables ADC, starts conversion of injected group.
HAL_StatusTypeDef HAL_ADCEx_InjectedStop (ADC_HandleTypeDef *hadc)
Stop conversion of injected channels.
HAL_StatusTypeDef HAL_ADCEx_InjectedPollForConversion (ADC_HandleTypeDef *hadc, uint32_t Timeout)
Wait for injected group conversion to be completed.
HAL_StatusTypeDef HAL_ADCEx_InjectedStart_IT (ADC_HandleTypeDef *hadc)
Enables ADC, starts conversion of injected group with interruption.
HAL_StatusTypeDef HAL_ADCEx_InjectedStop_IT (ADC_HandleTypeDef *hadc)
Stop conversion of injected channels, disable interruption of end-of-conversion.
HAL_StatusTypeDef HAL_ADCEx_MultiModeStart_DMA (ADC_HandleTypeDef *hadc, uint32_t *pData, uint32_t Length)
Enables ADC, starts conversion of regular group and transfers result through DMA.
HAL_StatusTypeDef HAL_ADCEx_MultiModeStop_DMA (ADC_HandleTypeDef *hadc)
Stop ADC conversion of regular group (and injected channels in case of auto_injection mode), disable ADC DMA transfer, disable ADC peripheral.
uint32_t HAL_ADCEx_InjectedGetValue (ADC_HandleTypeDef *hadc, uint32_t InjectedRank)
Get ADC injected group conversion result.
uint32_t HAL_ADCEx_MultiModeGetValue (ADC_HandleTypeDef *hadc)
Returns the last ADC Master&Slave regular conversions results data in the selected multi mode.
__weak void HAL_ADCEx_InjectedConvCpltCallback (ADC_HandleTypeDef *hadc)
Injected conversion complete callback in non blocking mode.
Detailed Description
Extended Extended Input and Output operation functions.
 ===============================================================================
                      ##### IO operation functions #####
 ===============================================================================
    [..]  This section provides functions allowing to:
      (+) Start conversion of injected group.
      (+) Stop conversion of injected group.
      (+) Poll for conversion complete on injected group.
      (+) Get result of injected channel conversion.
      (+) Start conversion of injected group and enable interruptions.
      (+) Stop conversion of injected group and disable interruptions.
      (+) Start multimode and enable DMA transfer.
      (+) Stop multimode and disable ADC DMA transfer.
      (+) Get result of multimode conversion.
      (+) Perform the ADC self-calibration for single or differential ending.
      (+) Get calibration factors for single or differential ending.
      (+) Set calibration factors for single or differential ending.
Function Documentation
HAL_StatusTypeDef HAL_ADCEx_Calibration_Start (ADC_HandleTypeDef * hadc)
Perform an ADC automatic self-calibration Calibration prerequisite: ADC must be disabled (execute this function before HAL_ADC_Start() or after HAL_ADC_Stop()).
During calibration process, ADC is enabled. ADC is let enabled at the completion of this function.
Parameters:
hadc,: ADC handle
Return values:
HAL status
Definition at line 126 of file stm32f1xx_hal_adc_ex.c.
References ADC_CALIBRATION_TIMEOUT, ADC_ConversionStop_Disable(), ADC_Enable(), ADC_PRECALIBRATION_DELAY_ADCCLOCKCYCLES, ADC_STATE_CLR_SET, assert_param, HAL_ADC_STATE_BUSY_INTERNAL, HAL_ADC_STATE_ERROR_INTERNAL, HAL_ADC_STATE_INJ_BUSY, HAL_ADC_STATE_READY, HAL_ADC_STATE_REG_BUSY, HAL_GetTick(), HAL_RCCEx_GetPeriphCLKFreq(), __ADC_HandleTypeDef::Instance, RCC_PERIPHCLK_ADC, and __ADC_HandleTypeDef::State.
void HAL_ADCEx_InjectedConvCpltCallback (ADC_HandleTypeDef * hadc)
Injected conversion complete callback in non blocking mode.
Parameters:
hadc,: ADC handle
Return values:
None
Definition at line 954 of file stm32f1xx_hal_adc_ex.c.
Referenced by HAL_ADC_Init(), and HAL_ADC_IRQHandler().
uint32_t HAL_ADCEx_InjectedGetValue (ADC_HandleTypeDef * hadc, uint32_t InjectedRank)
Get ADC injected group conversion result.
Note:
Reading register JDRx automatically clears ADC flag JEOC (ADC group injected end of unitary conversion).
This function does not clear ADC flag JEOS (ADC group injected end of sequence conversion) Occurrence of flag JEOS rising:
If sequencer is composed of 1 rank, flag JEOS is equivalent to flag JEOC.
If sequencer is composed of several ranks, during the scan sequence flag JEOC only is raised, at the end of the scan sequence both flags JEOC and EOS are raised. Flag JEOS must not be cleared by this function because it would not be compliant with low power features (feature low power auto-wait, not available on all STM32 families). To clear this flag, either use function: in programming model IT: HAL_ADC_IRQHandler(), in programming model polling: HAL_ADCEx_InjectedPollForConversion() or __HAL_ADC_CLEAR_FLAG(&hadc, ADC_FLAG_JEOS).
Parameters:
hadc,: ADC handle
InjectedRank,: the converted ADC injected rank. This parameter can be one of the following values:
ADC_INJECTED_RANK_1: Injected Channel1 selected
ADC_INJECTED_RANK_2: Injected Channel2 selected
ADC_INJECTED_RANK_3: Injected Channel3 selected
ADC_INJECTED_RANK_4: Injected Channel4 selected
Return values:
ADC group injected conversion data
Definition at line 885 of file stm32f1xx_hal_adc_ex.c.
References ADC_INJECTED_RANK_1, ADC_INJECTED_RANK_2, ADC_INJECTED_RANK_3, ADC_INJECTED_RANK_4, assert_param, __ADC_HandleTypeDef::Instance, and IS_ADC_INJECTED_RANK.
HAL_StatusTypeDef HAL_ADCEx_InjectedPollForConversion (ADC_HandleTypeDef * hadc, uint32_t Timeout)
Wait for injected group conversion to be completed.
Parameters:
hadc,: ADC handle
Timeout,: Timeout value in millisecond.
Return values:
HAL status
Definition at line 384 of file stm32f1xx_hal_adc_ex.c.
References __HAL_ADC_CLEAR_FLAG, ADC_CONVCYCLES_MAX_RANGE, ADC_FLAG_EOC, ADC_FLAG_JEOC, ADC_FLAG_JSTRT, ADC_IS_SOFTWARE_START_INJECTED, ADC_IS_SOFTWARE_START_REGULAR, assert_param, ADC_InitTypeDef::ContinuousConvMode, HAL_ADC_STATE_INJ_BUSY, HAL_ADC_STATE_INJ_EOC, HAL_ADC_STATE_READY, HAL_ADC_STATE_REG_BUSY, HAL_ADC_STATE_TIMEOUT, HAL_GetTick(), HAL_RCCEx_GetPeriphCLKFreq(), __ADC_HandleTypeDef::Init, __ADC_HandleTypeDef::Instance, RCC_PERIPHCLK_ADC, and __ADC_HandleTypeDef::State.
HAL_StatusTypeDef HAL_ADCEx_InjectedStart (ADC_HandleTypeDef * hadc)
Enables ADC, starts conversion of injected group.
Interruptions enabled in this function: None.
Parameters:
hadc,: ADC handle
Return values:
HAL status
Definition at line 232 of file stm32f1xx_hal_adc_ex.c.
References __HAL_ADC_CLEAR_FLAG, ADC_CLEAR_ERRORCODE, ADC_Enable(), ADC_FLAG_JEOC, ADC_IS_SOFTWARE_START_INJECTED, ADC_NONMULTIMODE_OR_MULTIMODEMASTER, ADC_STATE_CLR_SET, assert_param, HAL_ADC_STATE_INJ_BUSY, HAL_ADC_STATE_INJ_EOC, HAL_ADC_STATE_MULTIMODE_SLAVE, HAL_ADC_STATE_READY, HAL_ADC_STATE_REG_BUSY, __ADC_HandleTypeDef::Instance, and __ADC_HandleTypeDef::State.
HAL_StatusTypeDef HAL_ADCEx_InjectedStart_IT (ADC_HandleTypeDef * hadc)
Enables ADC, starts conversion of injected group with interruption.
JEOC (end of conversion of injected group) Each of these interruptions has its dedicated callback function.
Parameters:
hadc,: ADC handle
Return values:
HAL status.
Definition at line 502 of file stm32f1xx_hal_adc_ex.c.
References __HAL_ADC_CLEAR_FLAG, __HAL_ADC_ENABLE_IT, ADC_CLEAR_ERRORCODE, ADC_Enable(), ADC_FLAG_JEOC, ADC_IS_SOFTWARE_START_INJECTED, ADC_IT_JEOC, ADC_NONMULTIMODE_OR_MULTIMODEMASTER, ADC_STATE_CLR_SET, assert_param, HAL_ADC_STATE_INJ_BUSY, HAL_ADC_STATE_INJ_EOC, HAL_ADC_STATE_MULTIMODE_SLAVE, HAL_ADC_STATE_READY, HAL_ADC_STATE_REG_BUSY, __ADC_HandleTypeDef::Instance, and __ADC_HandleTypeDef::State.
HAL_StatusTypeDef HAL_ADCEx_InjectedStop (ADC_HandleTypeDef * hadc)
Stop conversion of injected channels.
Disable ADC peripheral if no regular conversion is on going.
Note:
If ADC must be disabled and if conversion is on going on regular group, function HAL_ADC_Stop must be used to stop both injected and regular groups, and disable the ADC.
If injected group mode auto-injection is enabled, function HAL_ADC_Stop must be used.
In case of auto-injection mode, HAL_ADC_Stop must be used.
Parameters:
hadc,: ADC handle
Return values:
None
Definition at line 331 of file stm32f1xx_hal_adc_ex.c.
References ADC_ConversionStop_Disable(), ADC_STATE_CLR_SET, assert_param, HAL_ADC_STATE_ERROR_CONFIG, HAL_ADC_STATE_INJ_BUSY, HAL_ADC_STATE_READY, HAL_ADC_STATE_REG_BUSY, __ADC_HandleTypeDef::Instance, and __ADC_HandleTypeDef::State.
HAL_StatusTypeDef HAL_ADCEx_InjectedStop_IT (ADC_HandleTypeDef * hadc)
Stop conversion of injected channels, disable interruption of end-of-conversion.
Disable ADC peripheral if no regular conversion is on going.
Note:
If ADC must be disabled and if conversion is on going on regular group, function HAL_ADC_Stop must be used to stop both injected and regular groups, and disable the ADC.
If injected group mode auto-injection is enabled, function HAL_ADC_Stop must be used.
Parameters:
hadc,: ADC handle
Return values:
None
Definition at line 601 of file stm32f1xx_hal_adc_ex.c.
References __HAL_ADC_DISABLE_IT, ADC_ConversionStop_Disable(), ADC_IT_JEOC, ADC_STATE_CLR_SET, assert_param, HAL_ADC_STATE_ERROR_CONFIG, HAL_ADC_STATE_INJ_BUSY, HAL_ADC_STATE_READY, HAL_ADC_STATE_REG_BUSY, __ADC_HandleTypeDef::Instance, and __ADC_HandleTypeDef::State.
uint32_t HAL_ADCEx_MultiModeGetValue (ADC_HandleTypeDef * hadc)
Returns the last ADC Master&Slave regular conversions results data in the selected multi mode.
Parameters:
hadc,: ADC handle of ADC master (handle of ADC slave must not be used)
Return values:
The converted data value.
Definition at line 922 of file stm32f1xx_hal_adc_ex.c.
References assert_param, and __ADC_HandleTypeDef::Instance.
HAL_StatusTypeDef HAL_ADCEx_MultiModeStart_DMA (ADC_HandleTypeDef * hadc, uint32_t * pData, uint32_t Length)
Enables ADC, starts conversion of regular group and transfers result through DMA.
Multimode must have been previously configured using HAL_ADCEx_MultiModeConfigChannel() function. Interruptions enabled in this function:
DMA transfer complete
DMA half transfer Each of these interruptions has its dedicated callback function.
Note:
: On STM32F1 devices, ADC slave regular group must be configured with conversion trigger ADC_SOFTWARE_START.
: ADC slave can be enabled preliminarily using single-mode HAL_ADC_Start() function.
Parameters:
hadc,: ADC handle of ADC master (handle of ADC slave must not be used)
pData,: The destination Buffer address.
Length,: The length of data to be transferred from ADC peripheral to memory.
Return values:
None
Definition at line 670 of file stm32f1xx_hal_adc_ex.c.
References __HAL_ADC_CLEAR_FLAG, ADC_CLEAR_ERRORCODE, ADC_DMAConvCplt(), ADC_DMAError(), ADC_DMAHalfConvCplt(), ADC_Enable(), ADC_FLAG_EOC, ADC_IS_SOFTWARE_START_REGULAR, ADC_MULTI_SLAVE, ADC_STATE_CLR_SET, assert_param, ADC_InitTypeDef::ContinuousConvMode, __ADC_HandleTypeDef::DMA_Handle, HAL_ADC_STATE_ERROR_CONFIG, HAL_ADC_STATE_INJ_BUSY, HAL_ADC_STATE_INJ_EOC, HAL_ADC_STATE_MULTIMODE_SLAVE, HAL_ADC_STATE_READY, HAL_ADC_STATE_REG_BUSY, HAL_ADC_STATE_REG_EOC, HAL_DMA_Start_IT(), __ADC_HandleTypeDef::Init, __ADC_HandleTypeDef::Instance, __ADC_HandleTypeDef::State, __DMA_HandleTypeDef::XferCpltCallback, __DMA_HandleTypeDef::XferErrorCallback, and __DMA_HandleTypeDef::XferHalfCpltCallback.
HAL_StatusTypeDef HAL_ADCEx_MultiModeStop_DMA (ADC_HandleTypeDef * hadc)
Stop ADC conversion of regular group (and injected channels in case of auto_injection mode), disable ADC DMA transfer, disable ADC peripheral.
Note:
Multimode is kept enabled after this function. To disable multimode (set with HAL_ADCEx_MultiModeConfigChannel(), ADC must be reinitialized using HAL_ADC_Init() or HAL_ADC_ReInit().
In case of DMA configured in circular mode, function HAL_ADC_Stop_DMA must be called after this function with handle of ADC slave, to properly disable the DMA channel.
Parameters:
hadc,: ADC handle of ADC master (handle of ADC slave must not be used)
Return values:
None
Definition at line 796 of file stm32f1xx_hal_adc_ex.c.
References ADC_ConversionStop_Disable(), ADC_MULTI_SLAVE, ADC_STATE_CLR_SET, assert_param, __ADC_HandleTypeDef::DMA_Handle, HAL_ADC_STATE_ERROR_INTERNAL, HAL_ADC_STATE_INJ_BUSY, HAL_ADC_STATE_READY, HAL_ADC_STATE_REG_BUSY, HAL_DMA_Abort(), __ADC_HandleTypeDef::Instance, and __ADC_HandleTypeDef::State.