STM32F103xG HAL User Manual: Input and Output operation functions
Input and Output operation functions
PCD Exported Functions
Data transfers functions.
Functions
HAL_StatusTypeDef HAL_PCD_Start (PCD_HandleTypeDef *hpcd)
Start the USB device.
HAL_StatusTypeDef HAL_PCD_Stop (PCD_HandleTypeDef *hpcd)
Stop the USB device.
void HAL_PCD_IRQHandler (PCD_HandleTypeDef *hpcd)
This function handles PCD interrupt request.
__weak void HAL_PCD_DataOutStageCallback (PCD_HandleTypeDef *hpcd, uint8_t epnum)
Data OUT stage callback.
__weak void HAL_PCD_DataInStageCallback (PCD_HandleTypeDef *hpcd, uint8_t epnum)
Data IN stage callback.
__weak void HAL_PCD_SetupStageCallback (PCD_HandleTypeDef *hpcd)
Setup stage callback.
__weak void HAL_PCD_SOFCallback (PCD_HandleTypeDef *hpcd)
USB Start Of Frame callback.
__weak void HAL_PCD_ResetCallback (PCD_HandleTypeDef *hpcd)
USB Reset callback.
__weak void HAL_PCD_SuspendCallback (PCD_HandleTypeDef *hpcd)
Suspend event callback.
__weak void HAL_PCD_ResumeCallback (PCD_HandleTypeDef *hpcd)
Resume event callback.
__weak void HAL_PCD_ISOOUTIncompleteCallback (PCD_HandleTypeDef *hpcd, uint8_t epnum)
Incomplete ISO OUT callback.
__weak void HAL_PCD_ISOINIncompleteCallback (PCD_HandleTypeDef *hpcd, uint8_t epnum)
Incomplete ISO IN callback.
__weak void HAL_PCD_ConnectCallback (PCD_HandleTypeDef *hpcd)
Connection event callback.
__weak void HAL_PCD_DisconnectCallback (PCD_HandleTypeDef *hpcd)
Disconnection event callback.
Detailed Description
Data transfers functions.
 ===============================================================================
                      ##### IO operation functions #####
 ===============================================================================
    [..]
    This subsection provides a set of functions allowing to manage the PCD data
    transfers.
Function Documentation
void HAL_PCD_ConnectCallback (PCD_HandleTypeDef * hpcd)
Connection event callback.
Parameters:
hpcd PCD handle
Return values:
None
Definition at line 1447 of file stm32f1xx_hal_pcd.c.
Referenced by HAL_PCD_Init().
void HAL_PCD_DataInStageCallback (PCD_HandleTypeDef * hpcd, uint8_t epnum)
Data IN stage callback.
Parameters:
hpcd PCD handle
epnum endpoint number
Return values:
None
Definition at line 1323 of file stm32f1xx_hal_pcd.c.
Referenced by HAL_PCD_Init(), and PCD_EP_ISR_Handler().
void HAL_PCD_DataOutStageCallback (PCD_HandleTypeDef * hpcd, uint8_t epnum)
Data OUT stage callback.
Parameters:
hpcd PCD handle
epnum endpoint number
Return values:
None
Definition at line 1306 of file stm32f1xx_hal_pcd.c.
Referenced by HAL_PCD_Init(), and PCD_EP_ISR_Handler().
void HAL_PCD_DisconnectCallback (PCD_HandleTypeDef * hpcd)
Disconnection event callback.
Parameters:
hpcd PCD handle
Return values:
None
Definition at line 1462 of file stm32f1xx_hal_pcd.c.
Referenced by HAL_PCD_Init().
void HAL_PCD_IRQHandler (PCD_HandleTypeDef * hpcd)
This function handles PCD interrupt request.
Parameters:
hpcd PCD handle
Return values:
HAL status
Definition at line 1215 of file stm32f1xx_hal_pcd.c.
References __HAL_PCD_CLEAR_FLAG, __HAL_PCD_GET_FLAG, HAL_PCD_ResetCallback(), HAL_PCD_ResumeCallback(), HAL_PCD_SetAddress(), HAL_PCD_SOFCallback(), HAL_PCD_SuspendCallback(), PCD_HandleTypeDef::Instance, and PCD_EP_ISR_Handler().
void HAL_PCD_ISOINIncompleteCallback (PCD_HandleTypeDef * hpcd, uint8_t epnum)
Incomplete ISO IN callback.
Parameters:
hpcd PCD handle
epnum endpoint number
Return values:
None
Definition at line 1431 of file stm32f1xx_hal_pcd.c.
Referenced by HAL_PCD_Init().
void HAL_PCD_ISOOUTIncompleteCallback (PCD_HandleTypeDef * hpcd, uint8_t epnum)
Incomplete ISO OUT callback.
Parameters:
hpcd PCD handle
epnum endpoint number
Return values:
None
Definition at line 1414 of file stm32f1xx_hal_pcd.c.
Referenced by HAL_PCD_Init().
void HAL_PCD_ResetCallback (PCD_HandleTypeDef * hpcd)
USB Reset callback.
Parameters:
hpcd PCD handle
Return values:
None
Definition at line 1368 of file stm32f1xx_hal_pcd.c.
Referenced by HAL_PCD_Init(), and HAL_PCD_IRQHandler().
void HAL_PCD_ResumeCallback (PCD_HandleTypeDef * hpcd)
Resume event callback.
Parameters:
hpcd PCD handle
Return values:
None
Definition at line 1398 of file stm32f1xx_hal_pcd.c.
Referenced by HAL_PCD_Init(), and HAL_PCD_IRQHandler().
void HAL_PCD_SetupStageCallback (PCD_HandleTypeDef * hpcd)
Setup stage callback.
Parameters:
hpcd PCD handle
Return values:
None
Definition at line 1338 of file stm32f1xx_hal_pcd.c.
Referenced by HAL_PCD_Init(), and PCD_EP_ISR_Handler().
void HAL_PCD_SOFCallback (PCD_HandleTypeDef * hpcd)
USB Start Of Frame callback.
Parameters:
hpcd PCD handle
Return values:
None
Definition at line 1353 of file stm32f1xx_hal_pcd.c.
Referenced by HAL_PCD_Init(), and HAL_PCD_IRQHandler().
HAL_StatusTypeDef HAL_PCD_Start (PCD_HandleTypeDef * hpcd)
Start the USB device.
Parameters:
hpcd PCD handle
Return values:
HAL status
Definition at line 845 of file stm32f1xx_hal_pcd.c.
References __HAL_PCD_ENABLE, HAL_PCDEx_SetConnectionState(), and PCD_HandleTypeDef::Instance.
HAL_StatusTypeDef HAL_PCD_Stop (PCD_HandleTypeDef * hpcd)
Stop the USB device.
Parameters:
hpcd PCD handle
Return values:
HAL status
Definition at line 862 of file stm32f1xx_hal_pcd.c.
References __HAL_PCD_DISABLE, and PCD_HandleTypeDef::Instance.
Referenced by HAL_PCD_DeInit().
void HAL_PCD_SuspendCallback (PCD_HandleTypeDef * hpcd)
Suspend event callback.
Parameters:
hpcd PCD handle
Return values:
None
Definition at line 1383 of file stm32f1xx_hal_pcd.c.
Referenced by HAL_PCD_Init(), and HAL_PCD_IRQHandler().