STM32F103xG HAL User Manual: MMC_Exported_Functions_Group3
MMC_Exported_Functions_Group3
MMC_Exported_Functions
management functions
Functions
HAL_StatusTypeDef HAL_MMC_GetCardCID (MMC_HandleTypeDef *hmmc, HAL_MMC_CardCIDTypeDef *pCID)
Returns information the information of the card which are stored on the CID register.
HAL_StatusTypeDef HAL_MMC_GetCardCSD (MMC_HandleTypeDef *hmmc, HAL_MMC_CardCSDTypeDef *pCSD)
Returns information the information of the card which are stored on the CSD register.
HAL_StatusTypeDef HAL_MMC_GetCardInfo (MMC_HandleTypeDef *hmmc, HAL_MMC_CardInfoTypeDef *pCardInfo)
Gets the MMC card info.
HAL_StatusTypeDef HAL_MMC_ConfigWideBusOperation (MMC_HandleTypeDef *hmmc, uint32_t WideMode)
Enables wide bus operation for the requested card if supported by card.
HAL_MMC_CardStateTypeDef HAL_MMC_GetCardState (MMC_HandleTypeDef *hmmc)
Gets the current mmc card data state.
HAL_StatusTypeDef HAL_MMC_Abort (MMC_HandleTypeDef *hmmc)
Abort the current transfer and disable the MMC.
HAL_StatusTypeDef HAL_MMC_Abort_IT (MMC_HandleTypeDef *hmmc)
Abort the current transfer and disable the MMC (IT mode).
Detailed Description
management functions
  ==============================================================================
                      ##### Peripheral Control functions #####
  ==============================================================================
  [..]
    This subsection provides a set of functions allowing to control the MMC card
    operations and get the related information
Function Documentation
HAL_StatusTypeDef HAL_MMC_Abort (MMC_HandleTypeDef * hmmc)
Abort the current transfer and disable the MMC.
Parameters:
hmmc,: pointer to a MMC_HandleTypeDef structure that contains the configuration information for MMC module.
Return values:
HAL status
Definition at line 2272 of file stm32f1xx_hal_mmc.c.
References HAL_DMA_Abort(), and HAL_MMC_GetCardState().
HAL_StatusTypeDef HAL_MMC_Abort_IT (MMC_HandleTypeDef * hmmc)
Abort the current transfer and disable the MMC (IT mode).
Parameters:
hmmc,: pointer to a MMC_HandleTypeDef structure that contains the configuration information for MMC module.
Return values:
HAL status
Definition at line 2329 of file stm32f1xx_hal_mmc.c.
References HAL_DMA_Abort_IT(), HAL_MMC_AbortCallback(), HAL_MMC_GetCardState(), MMC_DMARxAbort(), and MMC_DMATxAbort().
HAL_StatusTypeDef HAL_MMC_ConfigWideBusOperation (MMC_HandleTypeDef * hmmc, uint32_t WideMode)
Enables wide bus operation for the requested card if supported by card.
Parameters:
hmmc,: Pointer to MMC handle
WideMode,: Specifies the MMC card wide bus mode This parameter can be one of the following values:
SDIO_BUS_WIDE_8B: 8-bit data transfer
SDIO_BUS_WIDE_4B: 4-bit data transfer
SDIO_BUS_WIDE_1B: 1-bit data transfer
Return values:
HAL status
Definition at line 2118 of file stm32f1xx_hal_mmc.c.
References assert_param.
HAL_StatusTypeDef HAL_MMC_GetCardCID (MMC_HandleTypeDef * hmmc, HAL_MMC_CardCIDTypeDef * pCID)
Returns information the information of the card which are stored on the CID register.
Parameters:
hmmc,: Pointer to MMC handle
pCID,: Pointer to a HAL_MMC_CIDTypedef structure that contains all CID register parameters
Return values:
HAL status
Definition at line 1968 of file stm32f1xx_hal_mmc.c.
HAL_StatusTypeDef HAL_MMC_GetCardCSD (MMC_HandleTypeDef * hmmc, HAL_MMC_CardCSDTypeDef * pCSD)
Returns information the information of the card which are stored on the CSD register.
Parameters:
hmmc,: Pointer to MMC handle
pCSD,: Pointer to a HAL_MMC_CardCSDTypeDef structure that contains all CSD register parameters
Return values:
HAL status
< Reserved
Definition at line 2001 of file stm32f1xx_hal_mmc.c.
Referenced by MMC_InitCard().
HAL_StatusTypeDef HAL_MMC_GetCardInfo (MMC_HandleTypeDef * hmmc, HAL_MMC_CardInfoTypeDef * pCardInfo)
Gets the MMC card info.
Parameters:
hmmc,: Pointer to MMC handle
pCardInfo,: Pointer to the HAL_MMC_CardInfoTypeDef structure that will contain the MMC card status information
Return values:
HAL status
Definition at line 2094 of file stm32f1xx_hal_mmc.c.
HAL_MMC_CardStateTypeDef HAL_MMC_GetCardState (MMC_HandleTypeDef * hmmc)
Gets the current mmc card data state.
Parameters:
hmmc,: pointer to MMC handle
Return values:
Card state
Definition at line 2249 of file stm32f1xx_hal_mmc.c.
References MMC_SendStatus().
Referenced by HAL_MMC_Abort(), HAL_MMC_Abort_IT(), MMC_DMAError(), MMC_DMARxAbort(), and MMC_DMATxAbort().