STM32F103xG HAL User Manual: MMC_Exported_Functions_Group1
MMC_Exported_Functions_Group1
MMC_Exported_Functions
Initialization and de-initialization functions.
Functions
HAL_StatusTypeDef HAL_MMC_Init (MMC_HandleTypeDef *hmmc)
Initializes the MMC according to the specified parameters in the MMC_HandleTypeDef and create the associated handle.
HAL_StatusTypeDef HAL_MMC_InitCard (MMC_HandleTypeDef *hmmc)
Initializes the MMC Card.
HAL_StatusTypeDef HAL_MMC_DeInit (MMC_HandleTypeDef *hmmc)
De-Initializes the MMC card.
__weak void HAL_MMC_MspInit (MMC_HandleTypeDef *hmmc)
Initializes the MMC MSP.
__weak void HAL_MMC_MspDeInit (MMC_HandleTypeDef *hmmc)
De-Initialize MMC MSP.
Detailed Description
Initialization and de-initialization functions.
  ==============================================================================
          ##### Initialization and de-initialization functions #####
  ==============================================================================
  [..]
    This section provides functions allowing to initialize/de-initialize the MMC
    card device to be ready for use.
Function Documentation
HAL_StatusTypeDef HAL_MMC_DeInit (MMC_HandleTypeDef * hmmc)
De-Initializes the MMC card.
Parameters:
hmmc,: Pointer to MMC handle
Return values:
HAL status
Definition at line 455 of file stm32f1xx_hal_mmc.c.
References assert_param, HAL_MMC_MspDeInit(), and MMC_PowerOFF().
HAL_StatusTypeDef HAL_MMC_Init (MMC_HandleTypeDef * hmmc)
Initializes the MMC according to the specified parameters in the MMC_HandleTypeDef and create the associated handle.
Parameters:
hmmc,: Pointer to the MMC handle
Return values:
HAL status
Definition at line 327 of file stm32f1xx_hal_mmc.c.
References assert_param, HAL_DMA_ERROR_NONE, HAL_MMC_AbortCallback(), HAL_MMC_ErrorCallback(), HAL_MMC_InitCard(), HAL_MMC_MspInit(), HAL_MMC_RxCpltCallback(), and HAL_MMC_TxCpltCallback().
HAL_StatusTypeDef HAL_MMC_InitCard (MMC_HandleTypeDef * hmmc)
Initializes the MMC Card.
Parameters:
hmmc,: Pointer to MMC handle
Note:
This function initializes the MMC card. It could be used when a card re-initialization is needed.
Return values:
HAL status
Definition at line 395 of file stm32f1xx_hal_mmc.c.
References MMC_InitCard(), and MMC_PowerON().
Referenced by HAL_MMC_Init().
__weak void HAL_MMC_MspDeInit (MMC_HandleTypeDef * hmmc)
De-Initialize MMC MSP.
Parameters:
hmmc,: Pointer to MMC handle
Return values:
None
Definition at line 511 of file stm32f1xx_hal_mmc.c.
Referenced by HAL_MMC_DeInit().
__weak void HAL_MMC_MspInit (MMC_HandleTypeDef * hmmc)
Initializes the MMC MSP.
Parameters:
hmmc,: Pointer to MMC handle
Return values:
None
Definition at line 496 of file stm32f1xx_hal_mmc.c.
Referenced by HAL_MMC_Init().