STM32F103xG HAL User Manual: Peripheral State functions
Peripheral State functions
NAND Exported Functions
Peripheral State functions.
Functions
HAL_NAND_StateTypeDef HAL_NAND_GetState (NAND_HandleTypeDef *hnand)
return the NAND state
uint32_t HAL_NAND_Read_Status (NAND_HandleTypeDef *hnand)
NAND memory read status.
Detailed Description
Peripheral State functions.
  ==============================================================================
                         ##### NAND State functions #####
  ==============================================================================
  [..]
    This subsection permits to get in run-time the status of the NAND controller
    and the data flow.
Function Documentation
HAL_NAND_StateTypeDef HAL_NAND_GetState (NAND_HandleTypeDef * hnand)
return the NAND state
Parameters:
hnand pointer to a NAND_HandleTypeDef structure that contains the configuration information for NAND module.
Return values:
HAL state
Definition at line 2199 of file stm32f1xx_hal_nand.c.
uint32_t HAL_NAND_Read_Status (NAND_HandleTypeDef * hnand)
NAND memory read status.
Parameters:
hnand pointer to a NAND_HandleTypeDef structure that contains the configuration information for NAND module.
Return values:
NAND status
Definition at line 2210 of file stm32f1xx_hal_nand.c.
Referenced by HAL_NAND_Read_Page_16b(), HAL_NAND_Read_Page_8b(), HAL_NAND_Read_SpareArea_16b(), HAL_NAND_Read_SpareArea_8b(), HAL_NAND_Write_Page_16b(), HAL_NAND_Write_Page_8b(), HAL_NAND_Write_SpareArea_16b(), and HAL_NAND_Write_SpareArea_8b().